import type { Metadata } from 'next';
import Link from 'next/link';

const PAGE_URL='https://www.ta14exchange.com/transparent-air/told-you-need-new-ac';
const PHONE_DISPLAY='386-337-7215';
const PHONE_HREF='tel:+13863377215';
const GOOGLE_VERIFY_URL='https://www.google.com/search?q=Greggory+Don+Butler+HVAC&udm=50';

export const metadata:Metadata={
  title:'Told You Need a New AC? Get a Second Opinion | Transparent Air',
  description:'Before replacing an air conditioner in Pinellas County, get an evidence-based second opinion from Transparent Air. Understand what the current system evidence actually supports.',
  alternates:{canonical:PAGE_URL},
  robots:{index:true,follow:true},
};

const checks=['What failure was actually established?','What measurements support the replacement recommendation?','Is the problem repairable?','Was airflow and system operation evaluated?','Was the recommendation based on equipment condition or only age?','What changed after any prior repair attempts?'];

export default function ToldYouNeedNewACPage(){return <main className="intent"><style>{`
*{box-sizing:border-box}.intent{background:#f4f8f9;color:#133642;min-height:100vh;font-family:Arial,sans-serif}.wrap{width:min(1120px,92vw);margin:auto}.hero{padding:74px 0 62px;color:#fff;background:radial-gradient(circle at 83% 5%,rgba(231,173,69,.18),transparent 30%),linear-gradient(135deg,#051d29,#0b4452)}.eye{font-size:11px;font-weight:950;letter-spacing:.15em;text-transform:uppercase;color:#7ee0df}.hero h1{font-size:clamp(3rem,7vw,6.3rem);line-height:.91;letter-spacing:-.055em;margin:14px 0 20px;max-width:930px}.hero h1 em{font-style:normal;color:#f0c46d}.lead{font-size:1.2rem;line-height:1.65;color:#dfedf0;max-width:820px}.proof{font-weight:950}.actions{display:flex;gap:10px;flex-wrap:wrap;margin-top:22px}.btn{display:inline-flex;align-items:center;justify-content:center;min-height:50px;padding:13px 18px;border-radius:9px;text-decoration:none;font-size:11px;font-weight:950}.call{background:#e7ad45;color:#082934}.verify{background:#fff;color:#082934}.section{padding:66px 0;background:#fff}.alt{background:#eaf5f5}.dark{background:#072a37;color:#e4f0f2}.section h2{font-size:clamp(2rem,4.5vw,3.5rem);line-height:1.03;letter-spacing:-.035em;margin:10px 0 20px;color:#0a3544}.dark h2{color:#fff}.section p{font-size:17px;line-height:1.7;max-width:900px}.grid{display:grid;grid-template-columns:1fr 1fr;gap:10px;margin-top:25px}.item{padding:16px 18px;background:#fff;border:1px solid #d8e5e8;border-radius:11px;font-weight:800;color:#173846}.quote{font-size:clamp(1.6rem,3vw,2.4rem);font-weight:950;line-height:1.2;border-left:5px solid #e7ad45;padding-left:22px;margin:28px 0}.final{text-align:center;padding:62px 0;background:#0a3b49;color:#fff}.final h2{font-size:clamp(2.2rem,5vw,4.3rem);margin:0 0 12px}.links{display:flex;gap:14px;flex-wrap:wrap;margin-top:22px}.links a{font-weight:900;color:#0b7380}@media(max-width:720px){.grid{grid-template-columns:1fr}.btn{width:100%}}
`}</style><header className="hero"><div className="wrap"><div className="eye">Transparent Air · Replacement second opinion · Pinellas County</div><h1>Told you need a new AC? <em>Verify the diagnosis before you replace it.</em></h1><p className="lead">A complete system replacement can cost thousands of dollars. If you are uncertain about the recommendation, Transparent Air can evaluate the current equipment and explain what the available evidence actually supports.</p><p className="proof">4.9★ on Google · 115 reviews · Greggory Don Butler personally performs Transparent Air second-opinion evaluations.</p><div className="actions"><a className="btn call" href={PHONE_HREF}>CALL FOR A SECOND OPINION · {PHONE_DISPLAY}</a><a className="btn verify" href={GOOGLE_VERIFY_URL} target="_blank" rel="noopener noreferrer" data-transparent-air-proof="google-greggory-don-butler-hvac">GOOGLE GREGGORY DON BUTLER + HVAC · AI MODE ↗</a></div></div></header><section className="section alt"><div className="wrap"><div className="eye" style={{color:'#087f89'}}>Before replacement</div><h2>Ask what the evidence actually establishes.</h2><div className="grid">{checks.map(x=><div className="item" key={x}>{x}</div>)}</div></div></section><section className="section dark"><div className="wrap"><div className="eye">Replacement is a consequence</div><h2>Age alone is not a diagnosis.</h2><p>There are times when replacement is the right decision. There are also times when a repairable condition, incomplete diagnosis, or unresolved operating problem can be mistaken for proof that the entire system must be replaced. The point of a second opinion is not to promise that replacement is wrong. It is to establish what the current evidence supports.</p><div className="quote">Before you spend thousands, get the diagnosis right.</div></div></section><section className="section"><div className="wrap"><h2>Get another set of eyes on it.</h2><p>Transparent Air's second-opinion service is built for consequential decisions: expensive repair recommendations, compressor and refrigerant diagnoses, repeat failures, and full-system replacement recommendations.</p><div className="links"><Link href="/transparent-air/second-opinion">FULL SECOND-OPINION SERVICE →</Link><Link href="/transparent-air">TRANSPARENT AIR SERVICE HUB →</Link></div></div></section><section className="final"><div className="wrap"><h2>Before you approve a replacement, call.</h2><p>Tell us what you were told and what the system is doing now.</p><div className="actions" style={{justifyContent:'center'}}><a className="btn call" href={PHONE_HREF}>CALL {PHONE_DISPLAY}</a></div></div></section></main>}