'use client';

import Link from 'next/link';

const tiers=[
 {key:'passport',name:'Evidence Passport',price:'$19',capacity:'3 systems · 1 user',best:'Individual evidence continuity',href:'/eu-ai-act/join?plan=passport'},
 {key:'workspace',name:'Compliance Workspace',price:'$49',capacity:'10 systems · 5 users',best:'Team compliance operations',href:'/eu-ai-act/join?plan=workspace'},
 {key:'pro',name:'Governance Pro',price:'$99',capacity:'25 systems · 10 users',best:'High-risk / GPAI / FRIA readiness',href:'/eu-ai-act/join?plan=pro'},
 {key:'institution',name:'Institution',price:'$499',capacity:'50 systems · 25 users',best:'Enterprise portfolio governance',href:'/eu-ai-act/join?plan=institution'},
];

export default function Upgrade(){return <main className="page"><nav><Link href="/eu-ai-act">← WORLD 05</Link><b>TA-14 EXCHANGE · TA14EXCHANGE.COM</b><Link href="/eu-ai-act/commercial">FULL PRICING →</Link></nav><header><small>CONTINUE THE COMPLIANCE TWIN</small><h1>UPGRADE CAPACITY.<br/><em>KEEP THE RECORD.</em></h1><p>Move to the governance environment your organization needs without treating an upgrade as permission to erase chronology, overwrite earlier evidence, or convert subscription access into an independent finding.</p></header><section className="tiers">{tiers.map((t,i)=><article key={t.key} className={i===2?'featured':''}><small>{String(i+1).padStart(2,'0')} · {t.key.toUpperCase()}</small><h2>{t.name}</h2><div><b>{t.price}</b><span>/ MONTH</span></div><p>{t.capacity}</p><strong>{t.best}</strong><Link href={t.href}>SELECT {t.name.toUpperCase()} →</Link></article>)}</section><section className="preserve"><div><small>UPGRADE CONTINUITY</small><h2>The evidence history travels forward.</h2><p>A plan change should increase capacity and capability. It should not silently rewrite system identity, prior evidence state, material-change history, authority provenance, participant responses, or independent review records.</p></div><div className="chain"><span>IDENTITY</span><i>→</i><span>EVIDENCE</span><i>→</i><span>CHANGE</span><i>→</i><span>REVALIDATION</span><i>→</i><span>REVIEW</span></div></section><style jsx>{`
*{box-sizing:border-box}.page{min-height:100vh;background:radial-gradient(circle at 50% 0,#0a2a4a,#03070d 42%,#010306);color:#edf7ff;font-family:Inter,system-ui,sans-serif;padding-bottom:80px}nav{height:70px;padding:0 5vw;display:flex;justify-content:space-between;align-items:center;border-bottom:1px solid #17364d}nav :global(a){color:#70ddf9;text-decoration:none;font-size:8px;font-weight:900;letter-spacing:.1em}nav b{font-size:8px;color:#8099ab;letter-spacing:.15em}header{max-width:1050px;margin:auto;text-align:center;padding:80px 20px 45px}header small,.preserve small{font-size:8px;color:#69ddfa;letter-spacing:.2em;font-weight:900}h1{font:clamp(50px,7vw,90px)/.9 Georgia,serif;margin:18px 0}h1 em{font-style:normal;color:#75e0fa}header p{max-width:800px;margin:auto;color:#91a7b7;line-height:1.7}.tiers{width:min(1280px,calc(100% - 32px));margin:auto;display:grid;grid-template-columns:repeat(4,1fr);gap:9px}.tiers article{min-height:340px;padding:24px;border:1px solid #1c4058;background:#06111b;display:flex;flex-direction:column}.tiers article.featured{border-color:#a47a35;background:linear-gradient(180deg,#181308,#06111b)}.tiers small{font-size:7px;color:#63daf8}.tiers h2{font:23px Georgia,serif}.tiers div b{font:39px Georgia,serif}.tiers div span{font-size:7px;color:#7891a3}.tiers p{font-size:9px;color:#839bab}.tiers strong{font-size:9px;color:#efc16d}.tiers :global(a){margin-top:auto;border:1px solid #5ed9f7;padding:13px;color:#061018;background:#6ddff9;text-decoration:none;font-size:8px;font-weight:950;text-align:center}.preserve{width:min(1100px,calc(100% - 32px));margin:45px auto 0;padding:30px;border:1px solid #8a6732;background:#171107}.preserve h2{font:31px Georgia,serif;margin:8px 0}.preserve p{color:#aa9e8a;line-height:1.6}.chain{margin-top:25px;display:flex;align-items:center;justify-content:space-between;gap:8px}.chain span{border:1px solid #775e34;padding:10px;font-size:7px;color:#efc16d}.chain i{font-style:normal;color:#69dffb}@media(max-width:900px){.tiers{grid-template-columns:1fr 1fr}}@media(max-width:560px){nav b{display:none}.tiers{grid-template-columns:1fr}.chain{flex-wrap:wrap}}
`}</style></main>}
