import { NextRequest, NextResponse } from 'next/server';
import { createClient } from '@supabase/supabase-js';
import {planKeyFromPayPalPlanId} from '@/lib/billing/eu-ai-act-entitlements';
export const dynamic='force-dynamic';export const runtime='nodejs';
function cfg(){const id=process.env.PAYPAL_CLIENT_ID?.trim(),secret=process.env.PAYPAL_CLIENT_SECRET?.trim(),webhookId=process.env.PAYPAL_WEBHOOK_ID?.trim(),sandbox=process.env.PAYPAL_ENVIRONMENT?.toLowerCase()==='sandbox';if(!id||!secret||!webhookId)return null;return{id,secret,webhookId,base:sandbox?'https://api-m.sandbox.paypal.com':'https://api-m.paypal.com'}}
async function token(c:NonNullable<ReturnType<typeof cfg>>){const r=await fetch(`${c.base}/v1/oauth2/token`,{method:'POST',headers:{Authorization:`Basic ${Buffer.from(`${c.id}:${c.secret}`).toString('base64')}`,'Content-Type':'application/x-www-form-urlencoded'},body:'grant_type=client_credentials',cache:'no-store'});if(!r.ok)throw new Error('PayPal auth failed');return (await r.json()).access_token as string}
function db(){const url=process.env.NEXT_PUBLIC_SUPABASE_URL,key=process.env.SUPABASE_SERVICE_ROLE_KEY;if(!url||!key)return null;return createClient(url,key,{auth:{persistSession:false,autoRefreshToken:false}})}
function boundUser(customId:unknown){const value=typeof customId==='string'?customId:'';const match=/^ta14-user:([0-9a-f-]{36})$/i.exec(value);return match?.[1]??null}
export async function POST(req:NextRequest){const c=cfg(),supabase=db();if(!c||!supabase)return NextResponse.json({error:'WEBHOOK_CONFIGURATION_MISSING'},{status:503});let event:any;try{event=await req.json()}catch{return NextResponse.json({error:'INVALID_JSON'},{status:400})}const access=await token(c);const verification={auth_algo:req.headers.get('paypal-auth-algo'),cert_url:req.headers.get('paypal-cert-url'),transmission_id:req.headers.get('paypal-transmission-id'),transmission_sig:req.headers.get('paypal-transmission-sig'),transmission_time:req.headers.get('paypal-transmission-time'),webhook_id:c.webhookId,webhook_event:event};if(Object.values(verification).slice(0,5).some(v=>!v))return NextResponse.json({error:'PAYPAL_HEADERS_MISSING'},{status:400});const vr=await fetch(`${c.base}/v1/notifications/verify-webhook-signature`,{method:'POST',headers:{Authorization:`Bearer ${access}`,'Content-Type':'application/json'},body:JSON.stringify(verification),cache:'no-store'});const verified=await vr.json();if(!vr.ok||verified.verification_status!=='SUCCESS'){console.error('TA14_PAYPAL_WEBHOOK_VERIFICATION_FAILED',verified);return NextResponse.json({error:'INVALID_WEBHOOK_SIGNATURE'},{status:400})}const eventId=String(event.id||''),eventType=String(event.event_type||''),resource=event.resource||{},resourceId=String(resource.id||'')||null;if(!eventId||!eventType)return NextResponse.json({error:'INVALID_PAYPAL_EVENT'},{status:400});const receipt=await supabase.from('ta14_paypal_webhook_events').upsert({paypal_event_id:eventId,event_type:eventType,resource_id:resourceId,verification_status:'SUCCESS',payload:event,processed_at:new Date().toISOString()},{onConflict:'paypal_event_id',ignoreDuplicates:true});if(receipt.error){console.error('TA14_PAYPAL_WEBHOOK_RECEIPT_ERROR',receipt.error);return NextResponse.json({error:'WEBHOOK_PERSISTENCE_FAILED'},{status:500})}if(eventType.startsWith('BILLING.SUBSCRIPTION.')&&resourceId){const status=String(resource.status||eventType.replace('BILLING.SUBSCRIPTION.','')),paypalPlanId=resource.plan_id??null,planKey=planKeyFromPayPalPlanId(paypalPlanId);const row={paypal_subscription_id:resourceId,paypal_plan_id:paypalPlanId,plan_key:planKey,owner_user_id:boundUser(resource.custom_id),customer_reference:resource.custom_id??null,subscriber_email:resource.subscriber?.email_address??null,subscriber_payer_id:resource.subscriber?.payer_id??null,status,status_changed_at:resource.status_update_time??event.create_time??new Date().toISOString(),next_billing_time:resource.billing_info?.next_billing_time??null,raw_resource:resource,updated_at:new Date().toISOString()};const up=await supabase.from('ta14_billing_subscriptions').upsert(row,{onConflict:'paypal_subscription_id'});if(up.error){console.error('TA14_PAYPAL_SUBSCRIPTION_PERSISTENCE_ERROR',up.error);return NextResponse.json({error:'SUBSCRIPTION_PERSISTENCE_FAILED'},{status:500})}}return NextResponse.json({received:true,verified:true,eventId,eventType})}
