import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Anto Budiardjo | Making Connectivity Explicit | TA-14 Exchange",
  description: "A public profile showroom examining Anto Budiardjo's long arc from building integration to CNS/CP, Connection Profiles, interoperability, and governed connectivity.",
};

const sources = [
  ["Padi.io — About", "https://www.home.padi.io/about"],
  ["Padi.io — Rethinking Interoperability", "https://www.home.padi.io/"],
  ["AutomatedBuildings — Anto Budiardjo", "https://www.automatedbuildings.com/author/anto/"],
  ["The Missing Binding Layer", "https://www.automatedbuildings.com/2026/03/the-missing-binding-layer/"],
  ["Monday Live! — Members", "https://www.mondaylive.org/members"],
];

const arc = [
  ["1989 →", "Connected buildings", "Development of building connectivity and integration technologies begins decades before today's digital-twin vocabulary."],
  ["INTEGRATION", "Systems meet", "The problem starts as getting independently designed building systems to exchange useful information without bespoke integration everywhere."],
  ["INTEROPERABILITY", "Context matters", "The work moves beyond raw data transport toward shared meaning, relationships, roles, and the context surrounding a connection."],
  ["NOW", "CNS / CP", "Connection Profiles make the relationship explicit: who provides, who consumes, what crosses, and under what declared contract."],
];

export default function AntoBudiardjoShowroom() {
  return <main className="page">
    <style>{`
      *{box-sizing:border-box}.page{margin:0;background:#f2efe7;color:#152229;font-family:Arial,Helvetica,sans-serif}.shell{width:min(1180px,92vw);margin:auto}
      .nav{position:sticky;top:0;z-index:20;background:rgba(8,20,27,.97);border-bottom:1px solid #29434d;color:#fff}.nav .shell{height:62px;display:flex;align-items:center;justify-content:space-between;gap:22px}.brand{font-size:11px;font-weight:900;letter-spacing:.13em}.links{display:flex;align-items:center}.nav a{color:#c9dadd;text-decoration:none;font-size:10px;font-weight:900;letter-spacing:.1em;margin-left:18px}.nav a:first-child{color:#7adbd9}
      .hero{background:radial-gradient(circle at 82% 18%,#174653 0,transparent 28%),#0b1b22;color:#f7f3ea;padding:82px 0 72px}.heroGrid{display:grid;grid-template-columns:1.08fr .92fr;gap:64px;align-items:center}.eyebrow{font-size:10px;font-weight:950;letter-spacing:.17em;color:#79c6c2;margin:0 0 18px}.hero h1{font:clamp(56px,7vw,96px)/.9 Georgia,serif;letter-spacing:-.055em;margin:0 0 26px;max-width:760px}.hero h1 em{display:block;color:#e0bc69;font-weight:400}.lede{max-width:720px;font:20px/1.62 Georgia,serif;color:#d5e0e1}.statusRow{display:flex;flex-wrap:wrap;gap:8px;margin-top:27px}.statusRow span{padding:8px 10px;border:1px solid #51707a;color:#b9d0d4;font-size:9px;font-weight:900;letter-spacing:.12em}
      .profileSide{display:grid;grid-template-columns:120px 1fr;gap:18px;align-items:start}.profilePortrait{width:120px;height:120px;object-fit:cover;display:block;border:1px solid #51707a}.diagram{border:1px solid #31515c;background:#07131a;padding:26px;box-shadow:0 22px 70px rgba(0,0,0,.25)}.diagramTitle{display:flex;justify-content:space-between;align-items:center;border-bottom:1px solid #28434d;padding-bottom:17px}.diagramTitle b{font-size:12px;letter-spacing:.13em}.diagramTitle span{font-size:9px;color:#e1bf6d;font-weight:900}.nodes{display:grid;grid-template-columns:1fr 54px 1fr;gap:10px;align-items:center;padding:32px 0}.node{padding:22px 18px;border:1px solid #2f5662;background:#0b2028}.node small{display:block;color:#78d7d3;font-size:9px;font-weight:900;letter-spacing:.13em}.node strong{display:block;margin-top:8px;font:24px Georgia,serif}.connector{text-align:center;color:#e1bf6d;font-size:28px}.cp{border:2px solid #e1bf6d;background:#17180f;padding:20px;margin-top:4px}.cp small{display:block;color:#e1bf6d;font-size:9px;font-weight:950;letter-spacing:.14em}.cp b{display:block;margin-top:8px;font-size:18px}.cp p{margin:8px 0 0;color:#b9c7ca;font-size:12px;line-height:1.55}.diagramFoot{margin-top:20px;color:#8fa5ab;font-size:11px;line-height:1.6}
      .section{padding:78px 0}.section h2{font:clamp(40px,5vw,66px)/1.02 Georgia,serif;letter-spacing:-.04em;margin:0 0 22px;max-width:980px}.intro{max-width:900px;font:18px/1.7 Georgia,serif;color:#4e5f64}
      .flow{display:grid;grid-template-columns:repeat(5,1fr);gap:8px;margin-top:38px}.flow div{background:#fff;border-top:4px solid #34777c;padding:22px 14px;min-height:100px}.flow small{display:block;color:#698086;font-size:9px;font-weight:900;letter-spacing:.12em}.flow b{display:block;margin-top:9px;font-size:12px;letter-spacing:.06em}
      .dark{background:#132930;color:#f3f5f2}.dark .intro{color:#bdcdd0}.dark .eyebrow{color:#7fd8d3}.arc{display:grid;grid-template-columns:repeat(4,1fr);gap:1px;background:#42616a;margin-top:42px}.arc article{background:#132930;padding:28px;min-height:260px}.arc b{color:#e2bf6d;font-size:10px;letter-spacing:.13em}.arc h3{font:25px/1.12 Georgia,serif;margin:16px 0}.arc p{font-size:13px;line-height:1.65;color:#bacacc}
      .quote{background:#dce8e5;padding:70px 0}.quote blockquote{margin:0;max-width:1050px;font:clamp(34px,5vw,62px)/1.1 Georgia,serif;letter-spacing:-.03em;color:#193037}.quote p{font-size:10px;font-weight:950;letter-spacing:.13em;color:#527078;margin-top:25px}
      .seam{display:grid;grid-template-columns:1fr 72px 1fr;gap:14px;align-items:stretch;margin-top:38px}.seam article{padding:30px;border:1px solid #d6d1c5;background:#fff}.seam small{font-size:9px;font-weight:950;letter-spacing:.13em;color:#39777a}.seam h3{font:30px Georgia,serif;margin:12px 0}.seam p{font-size:13px;line-height:1.7;color:#526166}.seam .arrow{display:flex;align-items:center;justify-content:center;font-size:34px;color:#b98d31}.rule{margin-top:24px;padding:24px;border-left:5px solid #b58b34;background:#eee4c9;font-size:17px;line-height:1.6}.rule strong{color:#6e5018}
      .cards{display:grid;grid-template-columns:repeat(3,1fr);gap:16px;margin-top:38px}.card{padding:28px;background:#fff;border:1px solid #d8d3c8}.card small{font-size:9px;font-weight:950;letter-spacing:.13em;color:#39777a}.card h3{font:27px/1.15 Georgia,serif}.card p{font-size:13px;line-height:1.7;color:#536166}
      .boundary{margin-top:34px;padding:27px 30px;border-left:5px solid #e0bc69;background:#f0e6c9;color:#29362f}.boundary p{margin:0;line-height:1.7;color:#29362f}.boundary strong{color:#172820}
      .sources{display:grid;grid-template-columns:repeat(2,1fr);gap:12px;margin-top:34px}.sources a{display:block;padding:20px;background:#fff;border:1px solid #d7d2c6;color:#18323a;text-decoration:none;font-size:12px;font-weight:850;transition:.18s}.sources a:hover{transform:translateY(-2px);border-color:#477e82;box-shadow:0 8px 24px rgba(21,34,41,.08)}.sources a:focus-visible,.nav a:focus-visible{outline:2px solid #4c8b8d;outline-offset:4px}.sourceNote{font-size:12px;color:#6b797c;margin-top:16px}
      .footer{background:#08151b;color:#8ca0a5;padding:36px 0;font-size:10px;letter-spacing:.09em;line-height:1.7}
      @media(max-width:850px){.heroGrid,.arc,.cards,.sources,.seam{grid-template-columns:1fr}.heroGrid{gap:34px}.flow{grid-template-columns:1fr 1fr}.seam .arrow{transform:rotate(90deg);min-height:52px}.links{display:none}.hero{padding:56px 0}.section{padding:58px 0}}
      @media(max-width:520px){.flow{grid-template-columns:1fr}.nodes{grid-template-columns:1fr}.connector{transform:rotate(90deg)}.profileSide{grid-template-columns:88px 1fr}.profilePortrait{width:88px;height:88px}}
    `}</style>

    <nav className="nav"><div className="shell"><div className="brand">ANTO BUDIARDJO · PUBLIC PROFILE SHOWROOM</div><div className="links"><a href="/">TA-14 EXCHANGE</a><a href="#arc">ARC</a><a href="#seam">SEAM</a><a href="#record">RECORD</a></div></div></nav>

    <header className="hero"><div className="shell heroGrid">
      <div><p className="eyebrow">ANTO BUDIARDJO · PADI.IO · MONDAY LIVE! · INTEROPERABILITY</p><h1>Making connectivity <em>explicit.</em></h1><p className="lede">For decades, Anto Budiardjo has worked on the problem underneath smart buildings: independently designed systems must be able to form understandable, reusable relationships. Today that work is visible in CNS/CP and Connection Profiles — an architecture for naming and governing the connection itself.</p><div className="statusRow"><span>PUBLIC PROFILE</span><span>OPEN FOR CORRECTION</span><span>NO ENDORSEMENT IMPLIED</span></div></div>
      <aside className="diagram" aria-label="Anto Budiardjo and Connection Profile conceptual diagram"><div className="profileSide"><img className="profilePortrait" src="/anto-budiardjo.png" width="120" height="120" alt="Anto Budiardjo" /><div><div className="diagramTitle"><b>ANTO BUDIARDJO</b><span>CNS / CP</span></div><div className="diagramFoot">Padi.io · Monday Live! · building interoperability</div></div></div><div className="nodes"><div className="node"><small>PROVIDER</small><strong>System A</strong></div><div className="connector">↔</div><div className="node"><small>CONSUMER</small><strong>System B</strong></div></div><div className="cp"><small>CONNECTION PROFILE</small><b>Declare the relationship before the systems connect.</b><p>Roles · properties · context · matching · lifecycle · auditability</p></div><div className="diagramFoot">A connection can be explicit without becoming authority for every consequence that may later be proposed.</div></aside>
    </div></header>

    <section className="section"><div className="shell"><p className="eyebrow">THE WORK BEHIND THE CONNECTION</p><h2>Interoperability is not just getting the data through.</h2><p className="intro">When systems multiply, one-off integrations become expensive, brittle and hard to reason about. Anto's work has repeatedly pushed toward a different model: make the relationship between systems explicit enough that people and software can understand what is connecting, why, and under what declared conditions.</p><div className="flow">{[["01","NAME"],["02","DECLARE"],["03","MATCH"],["04","CONNECT"],["05","OBSERVE"]].map(([n,x])=><div key={x}><small>{n}</small><b>{x}</b></div>)}</div></div></section>

    <section id="arc" className="section dark"><div className="shell"><p className="eyebrow">A LONG CONNECTIVITY ARC</p><h2>This did not start with digital twins or AI agents.</h2><p className="intro">Padi.io's public biography traces Anto's connected-building work to 1989. The vocabulary has changed over time, but the recurring problem has remained recognizable: how independently governed systems form useful relationships without dissolving their boundaries.</p><div className="arc">{arc.map((item)=><article key={item[0]}><b>{item[0]}</b><h3>{item[1]}</h3><p>{item[2]}</p></article>)}</div></div></section>

    <section className="quote"><div className="shell"><blockquote>“Every connection between systems is governed by a named, immutable contract.”</blockquote><p>SUMMARY OF THE CONNECTION PROFILE MODEL DESCRIBED IN ANTO'S 2026 PUBLIC WRITING · SEE SOURCE RECORD BELOW</p></div></section>

    <section id="seam" className="section"><div className="shell"><p className="eyebrow">THE INTEROPERABILITY SEAM</p><h2>The connection layer and the consequence layer are different jobs.</h2><p className="intro">This is the point where Anto's CNS/CP work and TA-14 can be examined together without collapsing one architecture into the other.</p><div className="seam"><article><small>CNS / CP · CONNECTION LAYER</small><h3>What may connect?</h3><p>Name the provider and consumer roles. Define the Connection Profile. Establish the declared properties and context that may cross. Form and observe the relationship.</p></article><div className="arrow">→</div><article><small>TA-14 · CONSEQUENCE LAYER</small><h3>What may this connection cause?</h3><p>When a proposed real-world consequence approaches Commit, establish Admissible Evidence, Applicable Authority and Established Standing for that exact consequence NOW.</p></article></div><div className="rule"><strong>Connection ≠ execution authority.</strong> A governed crossing can carry context while the authority to make a consequential change still has to be established where that consequence becomes real.</div></div></section>

    <section className="section dark"><div className="shell"><p className="eyebrow">WHY IT MATTERS</p><h2>A named relationship can be inspected, challenged and reused.</h2><div className="cards"><article className="card"><small>01 · EXPLICITNESS</small><h3>The relationship stops being hidden glue.</h3><p>The connection becomes something that can be named, described and reasoned about instead of disappearing inside custom integration code.</p></article><article className="card"><small>02 · REUSE</small><h3>A pattern can travel.</h3><p>A Connection Profile can describe a reusable relationship rather than forcing every project to rediscover the same integration contract.</p></article><article className="card"><small>03 · BOUNDARIES</small><h3>Connectivity can remain distinct from consequence.</h3><p>Knowing what crossed a connection does not by itself settle whether a later proposed action is authorized to become reality.</p></article></div><div className="boundary"><p><strong>Important boundary:</strong> this is an independent TA-14 public profile and interoperability examination. It does not claim that Anto Budiardjo, Padi.io, CNS/CP, Monday Live!, the IBB Project or AutomatedBuildings.com adopts TA-14. CNS/CP remains independently stewarded; TA-14 remains independently governed. The seam is published so each side can be inspected and corrected without being merged by implication.</p></div></div></section>

    <section id="record" className="section"><div className="shell"><p className="eyebrow">PUBLIC WORK SURFACE</p><h2>Follow the architecture through the record.</h2><p className="intro">Anto's public work spans building integration, cloud-native systems, context-driven interoperability, Connection Profiles, the IBB Project and the governance problem created when autonomous systems begin forming relationships at scale.</p><p className="sourceNote">External links open the underlying public sources directly.</p><div className="sources">{sources.map((item)=><a key={item[1]} href={item[1]} target="_blank" rel="noreferrer">{item[0]} ↗</a>)}</div></div></section>

    <section className="section"><div className="shell"><p className="eyebrow">ANTO BUDIARDJO</p><h2>The system does not become interoperable merely because two endpoints can exchange bytes.</h2><p className="intro">The relationship itself needs structure. That is the through-line this showroom makes visible: from building integration to named, contextual, inspectable connectivity — and then to the next boundary, where connection meets consequence.</p></div></section>

    <footer className="footer"><div className="shell">PUBLIC PROFILE SHOWROOM · ASSEMBLED FROM PUBLIC SOURCES AND DIRECT COLLABORATION RECORDS · OPEN FOR CORRECTION · NO ENDORSEMENT IMPLIED</div></footer>
  </main>;
}
