"use client";
import Link from "next/link";
import {useState} from "react";
import "./showroom.css";
type Run="baseline"|"preserved"|"defeated";
const fixed=[["T₀ AUTHORITY","Facilities authority A-214 · active"],["ACTOR","Building automation controller BAC-07"],["PROPOSED CONSEQUENCE","Increase outdoor-air ventilation in Classroom 214"],["EXECUTION PATH","Controller → governed commit → AHU-2 outside-air command"]];
const data:Record<Run,{tag:string,name:string,tone:string,change:string,fact:string,source:string,evidence:string,authority:string,standing:string,decision:string,gate:string,why:string}>={baseline:{tag:"T₀",name:"FROZEN BASELINE",tone:"blue",change:"No changed-context event has been introduced. The governed proposition is frozen so both runs can be compared against the same starting state.",fact:"Baseline frozen",source:"Authority + actor + object + scope + path",evidence:"ESTABLISHED",authority:"APPLICABLE",standing:"ESTABLISHED",decision:"READY TO TEST",gate:"COMMIT NOT YET REQUESTED",why:"The baseline is the control, not the answer. Run ΔN₁ and ΔN₂ against this same frozen proposition."},preserved:{tag:"ΔN₁",name:"STANDING PRESERVED",tone:"green",change:"Occupancy increases from 21 to 27. Authoritative reality changes, but the actor, authority, governed object, scope, equipment relationship, and intervention boundary remain intact.",fact:"Occupancy: 21 → 27",source:"Room occupancy service · signed event · sequence continuous",evidence:"ESTABLISHED",authority:"APPLICABLE",standing:"ESTABLISHED",decision:"ALLOW",gate:"COMMIT MAY PROCEED",why:"TA-14 derives that the changed fact does not defeat the standing-bearing relationships. The same consequence remains eligible to cross the boundary if all remaining execution conditions are satisfied."},defeated:{tag:"ΔN₂",name:"STANDING DEFEATED",tone:"gold",change:"AHU-2 enters an active fire-smoke control override. The proposed consequence is unchanged, but the authoritative relationship governing who may command this path is not.",fact:"Fire-smoke override: INACTIVE → ACTIVE",source:"Life-safety control record · signed event · sequence continuous",evidence:"ESTABLISHED",authority:"NORMAL PATH DISPLACED",standing:"DEFEATED",decision:"HOLD",gate:"COMMIT BLOCKED",why:"TA-14 derives the refusal from authoritative changed reality and preserved provenance. It does not receive an upstream standing verdict. The consequence stops before it binds."}};
const chain=["REALITY","RECORD","CONTINUITY","ADMISSIBILITY","BINDING","COMMIT","EXECUTION","OUTCOME"];
const receiptId=(run:Run)=>`TA14-AEA-CRR-R1-${run==="preserved"?"DN1":run==="defeated"?"DN2":"T0"}`;
function downloadReceipt(run:Run){
 const r=data[run], lines=[
 "TA-14 AUTHORITY · CHANGED-REALITY RUNTIME EXAMINATION R1",
 "EXAMINATION RECEIPT",
 "",
 `Receipt ID: ${receiptId(run)}`,
 `Runtime state: ${r.tag} · ${r.name}`,
 "",
 "FROZEN CONTROL",
 ...fixed.map(([a,b])=>`${a}: ${b}`),
 "",
 "AUTHORITATIVE INPUT",
 `Changed fact: ${r.fact}`,
 `Provenance: ${r.source}`,
 "",
 "TA-14 DERIVATION",
 `Admissible Evidence: ${r.evidence}`,
 `Applicable Authority: ${r.authority}`,
 `Standing: ${r.standing}`,
 `Determination: ${r.decision}`,
 `Execution disposition: ${r.gate}`,
 `Decision point: TA-14 consequence boundary · before commit`,
 "",
 "DERIVATION NOTE",
 r.why,
 "",
 "R1 CONTROL: Same T0 authority · same actor · same proposed consequence · same execution path.",
 "ONLY TEST VARIABLE: Delta N · authoritative changed reality.",
 "This receipt records the selected public examination state. It is not an upstream standing declaration.",
 "NO ADMISSIBLE EVIDENCE. NO ADMISSIBLE EXECUTION."
 ];
 const blob=new Blob([lines.join("\n")],{type:"text/plain;charset=utf-8"});
 const url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download=`${receiptId(run)}-receipt.txt`;document.body.appendChild(a);a.click();a.remove();URL.revokeObjectURL(url);
}
export default function Page(){const[run,setRun]=useState<Run>("baseline"),[inspect,setInspect]=useState(false),[compare,setCompare]=useState(false);const r=data[run];return <main className={"crt "+r.tone}><div className="crt-mx" aria-hidden="true">{["REALITY","RECORD","CONTINUITY","ADMISSIBILITY","BINDING","COMMIT","EXECUTION","OUTCOME","REALIDAD","REGISTRO","CONTINUIDAD","AUTORIDAD","STANDING","RÉALITÉ","PREUVE","EXÉCUTION","現実","記録","実行","현실","기록","실행"].map((x,i)=><span key={i}>{x}</span>)}</div><div className="crt-w">
<nav><Link href="/registry/ta-14-admissible-execution-architecture">← TA-14 AEA</Link><Link href="/registry/ta-14-admissible-execution-architecture/showcase/cross-architecture-revalidation">FLAGSHIP FOUNDING SHOWCASE →</Link></nav>
<header className="crt-hero"><div className="crt-badges"><b>TA-14 AUTHORITY</b><b>PUBLIC TECHNICAL SHOWROOM</b><b>CONTROLLED RUNTIME TEST</b><b>R1 · FROZEN EXAMINATION RECORD</b></div><p className="crt-eye">THE CONSEQUENCE BOUNDARY · FORMAL CHANGED-REALITY EXAMINATION</p><h1>THE CHANGED-<br/><em>REALITY</em> TEST</h1><p className="crt-challenge">CAN ONE AUTHORITATIVE FACT STOP THE SAME CONSEQUENCE?</p><p className="crt-lede">R1 freezes the examination boundary: same T₀ authority, same actor, same proposed consequence, and same execution path. Only ΔN changes. Inspect whether TA-14 derives the consequence state from authoritative facts before commit.</p></header>
<section className="crt-question"><small>THE QUESTION TA-14 MUST ANSWER AT RUNTIME</small><h2>Does this proposed consequence have <i>admissible evidence</i>, <i>applicable authority</i>, and <i>established standing</i> to become reality <i>now</i>?</h2><div className="crt-dets"><b>ALLOW</b><b>HOLD</b><b>DENY</b><b>ESCALATE</b></div></section>
<section><p className="crt-eye">01 · FREEZE THE CONTROL</p><h2 className="crt-title">Four things are not allowed to move.</h2><div className="crt-fixed">{fixed.map(([a,b])=><article key={a}><small>{a}</small><strong>{b}</strong><span>LOCKED</span></article>)}</div></section>
<section><p className="crt-eye">02 · RUN THE TEST</p><h2 className="crt-title">Same consequence. Different authoritative reality.</h2><div className="crt-runs">{([["baseline","T₀","FREEZE BASELINE"],["preserved","ΔN₁","PRESERVE STANDING"],["defeated","ΔN₂","DEFEAT STANDING"]] as const).map(([k,a,b])=><button key={k} className={run===k?"active":""} onClick={()=>{setRun(k);setInspect(false)}}><small>{a}</small><strong>{b}</strong><span>{k==="baseline"?"Establish the control":k==="preserved"?"Change a non-standing-bearing fact":"Change a standing-bearing fact"}</span></button>)}</div>
<div className="crt-runtime"><div className="crt-rhead"><div><small>ACTIVE RUNTIME STATE · {r.tag}</small><h3>{r.name}</h3></div><div className="crt-decision">{r.decision}</div></div><p className="crt-change">{r.change}</p><div className="crt-pipe">{[["AUTHORITATIVE REALITY",r.fact],["PROVENANCE",r.source],["ADMISSIBLE EVIDENCE",r.evidence],["APPLICABLE AUTHORITY",r.authority],["DERIVED STANDING",r.standing],["EXECUTION STATE",r.decision]].map(([a,b],i)=><div key={a}><small>0{i+1} · {a}</small><strong>{b}</strong>{i<5&&<i>→</i>}</div>)}</div><div className="crt-gate"><small>CONSEQUENCE GATE</small><strong>{r.gate}</strong><p>{r.why}</p></div><button className="crt-action" onClick={()=>setInspect(!inspect)}>{inspect?"CLOSE DERIVATION RECORD ↑":"INSPECT WHERE THE DETERMINATION HAPPENED ↓"}</button>{inspect&&<div className="crt-record"><div><small>INPUT TYPE</small><b>Authoritative facts + preserved provenance</b></div><div><small>NOT ACCEPTED AS PROOF</small><b>Upstream standing verdict</b></div><div><small>DERIVATION LOCATION</small><b>TA-14 consequence boundary · before commit</b></div><div><small>BINDING EFFECT</small><b>{run==="defeated"?"HOLD prevents governed commit":"Determination controls whether commit may proceed"}</b></div></div>}</div></section>
<section><p className="crt-eye">03 · COMPARE THE EVIDENCE</p><h2 className="crt-title">Do not trust the result. Inspect the divergence.</h2><button className="crt-action compareBtn" onClick={()=>setCompare(!compare)}>{compare?"HIDE SIDE-BY-SIDE DIFF":"OPEN ΔN₁ ↔ ΔN₂ SIDE-BY-SIDE DIFF"}</button>{compare&&<div className="crt-cmp"><article><small>RUN A · ΔN₁</small><h3>STANDING PRESERVED</h3><p><b>Changed fact:</b> Occupancy 21 → 27</p><p><b>Evidence:</b> Established</p><p><b>Authority:</b> Applicable</p><p><b>Standing:</b> Established</p><strong>ALLOW · COMMIT MAY PROCEED</strong></article><div className="crt-only"><small>ONLY MATERIAL DIFFERENCE</small><b>AUTHORITATIVE ΔN</b><span>Everything in the frozen control remains identical.</span></div><article><small>RUN B · ΔN₂</small><h3>STANDING DEFEATED</h3><p><b>Changed fact:</b> Fire-smoke override activates</p><p><b>Evidence:</b> Established</p><p><b>Authority:</b> Normal path displaced</p><p><b>Standing:</b> Defeated</p><strong>HOLD · COMMIT BLOCKED</strong></article></div>}</section>
<section><p className="crt-eye">04 · EXAMINATION RECEIPT</p><h2 className="crt-title">Preserve what TA-14 actually determined.</h2><div className="crt-runtime"><div className="crt-rhead"><div><small>RECEIPT ID</small><h3>{receiptId(run)}</h3></div><div className="crt-decision">{r.decision}</div></div><p className="crt-change">The receipt captures the selected runtime state, frozen control, authoritative changed fact, provenance, TA-14 derivation, exact pre-commit decision point, determination, and execution disposition.</p><div className="crt-record"><div><small>ADMISSIBLE EVIDENCE</small><b>{r.evidence}</b></div><div><small>APPLICABLE AUTHORITY</small><b>{r.authority}</b></div><div><small>STANDING</small><b>{r.standing}</b></div><div><small>EXECUTION DISPOSITION</small><b>{r.gate}</b></div></div><button className="crt-action" onClick={()=>downloadReceipt(run)}>DOWNLOAD R1 EXAMINATION RECEIPT ↓</button></div></section>
<section><p className="crt-eye">05 · THE PUBLIC CHAIN</p><div className="crt-chain">{chain.map((x,i)=><div key={x}><small>0{i+1}</small><b>{x}</b></div>)}</div><div className="crt-bound"><span>PROPOSAL</span><i>→</i><strong>TA-14 CONSEQUENCE BOUNDARY</strong><i>→</i><span>REALITY</span></div></section>
<section className="crt-falsify"><p className="crt-eye">R1 · FROZEN EXAMINATION RECORD</p><h2 className="crt-title">The claim survives only if the preserved record survives its falsifier.</h2><div className="crt-record"><div><small>CONTROL VARIABLES</small><b>Same T₀ authority · same actor · same proposed consequence · same execution path</b></div><div><small>ONLY TEST VARIABLE</small><b>ΔN · authoritative changed reality</b></div><div><small>PRESERVED FOR BOTH RUNS</small><b>Authoritative inputs · provenance · derivation trace · exact decision point · determination · execution disposition</b></div><div><small>DERIVATION REQUIREMENT</small><b>TA-14 must derive standing from underlying authoritative facts before consequence binds.</b></div></div><p className="crt-eye">FALSIFICATION CONDITIONS</p><div className="crt-fgrid">{["The runs do not begin from the same frozen T₀ authority, actor, proposed consequence, and execution path.","The ΔN event cannot be traced to an authoritative source with preserved provenance.","TA-14 receives standing upstream instead of deriving it from underlying authoritative facts.","A different execution path is used between runs.","A hidden manual judgment determines the standing result.","The record cannot show where ΔN changes the derivation before consequence binds.","A HOLD or DENY can be ignored while the governed consequence still commits."].map((x,i)=><p key={x}><b>{String(i+1).padStart(2,"0")}</b>{x}</p>)}</div></section>
<footer><p>THE ARCHITECTURE DID NOT ASK WHETHER STANDING HAD BEEN DECLARED.</p><h2>It asked whether standing was established from authoritative reality <em>now.</em></h2><strong>NO ADMISSIBLE EVIDENCE. NO ADMISSIBLE EXECUTION.</strong><div className="crt-links"><Link href="/registry/ta-14-admissible-execution-architecture">OPEN AEA REGISTRY RECORD →</Link><Link href="/registry/ta-14-admissible-execution-architecture/showcase/cross-architecture-revalidation">OPEN FLAGSHIP FOUNDING SHOWCASE →</Link></div></footer>
</div></main>}