import type { Metadata } from 'next';
import Link from 'next/link';

const url='https://www.ta14exchange.com/academy/hvac/schools';
export const metadata:Metadata={title:'HVAC School Curriculum License | EPA 608 + TA-14 Admissible Diagnostic Execution',description:'Free student access. Affordable institutional licensing for HVAC schools that want to teach TA-14 EPA 608 readiness and a 14-step admissible diagnostic execution sequence built around baseline, evidence sufficiency, declared determination, bounded intervention and post-intervention proof.',alternates:{canonical:url},keywords:['HVAC school curriculum license','EPA 608 training for HVAC schools','EPA 608 curriculum','HVAC diagnostic execution training','HVAC evidence before intervention','HVAC instructor curriculum','HVAC technician training program','HVAC troubleshooting curriculum']};

const request=`mailto:ta14admissibleexecution@gmail.com?subject=${encodeURIComponent('TA-14 HVAC Founding School License')}&body=${encodeURIComponent('School / institution:\nProgram director / instructor:\nApproximate students per year:\nCurrent HVAC program:\nWhich pathway interests you? 608 / 14-Step / Full System:\nWhat would you like to evaluate?\n')}`;
const card=(label:string,title:string,copy:string)=><article style={{padding:24,border:'1px solid #183a49',borderRadius:18,background:'#061823'}}><small style={{color:'#59e9ff',fontWeight:950,letterSpacing:'.12em'}}>{label}</small><h2 style={{margin:'10px 0 8px'}}>{title}</h2><p style={{color:'#a7beca',lineHeight:1.65,margin:0}}>{copy}</p></article>;

export default function HvacSchools(){return <main style={{minHeight:'100vh',background:'#031019',color:'#edfaff',fontFamily:'Inter,ui-sans-serif,system-ui,sans-serif'}}>
<section style={{padding:'76px 24px 54px',background:'radial-gradient(circle at 18% 0,rgba(64,228,255,.16),transparent 38%),radial-gradient(circle at 90% 18%,rgba(78,255,165,.11),transparent 34%)'}}><div style={{maxWidth:1180,margin:'0 auto'}}><small style={{color:'#62efb2',fontWeight:950,letterSpacing:'.16em'}}>TA-14 HVAC TECHNICIAN FORMATION SYSTEM</small><h1 style={{fontSize:'clamp(2.8rem,7vw,6.2rem)',lineHeight:.92,letterSpacing:'-.06em',margin:'14px 0 22px',maxWidth:1080}}>We do not create symptom chasers.</h1><p style={{maxWidth:930,color:'#b5cad2',fontSize:'1.16rem',lineHeight:1.8}}>TA-14 teaches technicians to move through the system in a defined sequence, preserve the original condition, gather evidence in a way that supports a declared diagnostic determination, intervene only within that determination, and prove performance afterward against the baseline.</p><p style={{maxWidth:930,color:'#7fe9ff',fontWeight:900,lineHeight:1.7}}>14 steps · 7 in · 7 out · approximately 14 minutes · original-state baseline · evidence sufficiency · non-invasive refrigerant-entry threshold · declared diagnostic determination · bounded intervention · post-intervention performance record.</p><div style={{display:'flex',gap:12,flexWrap:'wrap',marginTop:28}}><a href={request} style={{padding:'15px 20px',borderRadius:10,background:'#62efb2',color:'#04130e',fontWeight:950,textDecoration:'none'}}>REQUEST A FOUNDING SCHOOL LICENSE →</a><Link href='/academy/hvac' style={{padding:'15px 20px',border:'1px solid #315465',borderRadius:10,color:'#eafaff',textDecoration:'none',fontWeight:850}}>EXPLORE THE FREE HVAC ACADEMY</Link></div></div></section>
<section style={{maxWidth:1180,margin:'0 auto',padding:'42px 24px 80px'}}>
<div style={{padding:'30px',border:'1px solid #2f6274',borderRadius:22,background:'#071c28'}}><small style={{color:'#62efb2',fontWeight:950}}>THE DISTINCTION</small><h2 style={{fontSize:'clamp(2.1rem,4vw,3.8rem)',letterSpacing:'-.04em',margin:'8px 0 12px'}}>Symptom chasing asks: “What looks wrong?” TA-14 asks: “What has the evidence actually established?”</h2><p style={{maxWidth:940,color:'#b2c8d2',lineHeight:1.75}}>A reading is not a determination. A symptom is not permission to enter the sealed system. TA-14 trains the technician to preserve the system state, collect admissible evidence in sequence, test sufficiency, respect a non-invasive refrigerant-entry threshold, issue a declared diagnostic determination, then intervene only within the boundary supported by that evidence.</p></div>

<div style={{marginTop:50,padding:'28px',border:'1px solid #285769',borderRadius:22,background:'#071c28'}}><small style={{color:'#62efb2',fontWeight:950}}>THE COMMERCIAL BOUNDARY</small><h2 style={{fontSize:'clamp(2rem,4vw,3.5rem)',letterSpacing:'-.04em',margin:'8px 0 12px'}}>Free to learn. Licensed to teach.</h2><p style={{maxWidth:920,color:'#b2c8d2',lineHeight:1.75}}>Students and technicians can learn TA-14 publicly at no charge. A school pays when it chooses to institutionalize TA-14 in a revenue-producing education program: teaching the method as curriculum, using institutional instructor resources or assessments, representing a formal TA-14 relationship, or seeking TA-14 institutional recognition.</p></div>

<h2 style={{fontSize:'clamp(2.2rem,5vw,4.5rem)',letterSpacing:'-.05em',margin:'56px 0 18px'}}>One technician formation system.</h2>
<div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(260px,1fr))',gap:14}}>
{card('01 · EPA 608','Build the refrigerant foundation.','TA-14 EPA 608 study resources support Core, Type I, Type II, Type III and Universal readiness. Schools can point students to the free learning environment and license formal classroom use of TA-14 teaching resources.')}
{card('02 · EPA 608 ARCADE','Turn recall into repetition.','Interactive 608 practice gives students another way to rehearse concepts instead of relying only on passive reading.')}
{card('03 · TA-14 14-STEP FIELD ARCADE','Teach sequence before intervention.','Seven inside and seven outside train the technician to move through a repeatable approximately 14-minute diagnostic execution discipline while preserving the original state and collecting evidence in order.')}
{card('04 · HVAC ADMISSIBLE DIAGNOSTIC RECORD','Make the determination and outcome provable.','The student preserves baseline evidence, records the declared diagnostic determination, identifies the intervention boundary, then creates a post-intervention performance record for comparison against the original condition.')}
</div>

<div style={{marginTop:56,padding:'32px',border:'1px solid #255469',borderRadius:22,background:'#061923'}}><small style={{color:'#59e9ff',fontWeight:950}}>THE TA-14 EXECUTION SEQUENCE</small><h2 style={{fontSize:'clamp(2rem,4vw,3.8rem)',letterSpacing:'-.045em',margin:'9px 0 18px'}}>Do not teach technicians to react to symptoms. Teach them to establish the right to intervene.</h2><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(220px,1fr))',gap:10}}>{['1. Preserve original-state baseline','2. Execute the 7 In / 7 Out sequence','3. Collect evidence without destroying the baseline','4. Test evidence sufficiency','5. Respect the non-invasive refrigerant-entry threshold','6. Declare the diagnostic determination','7. Bound the physical intervention to that determination','8. Record post-intervention performance','9. Compare performance against the preserved baseline','10. Close only what the evidence proves'].map(x=><div key={x} style={{padding:'14px',background:'#04131c',borderRadius:11,color:'#c4d7df',lineHeight:1.5}}>{x}</div>)}</div></div>

<div style={{marginTop:56}}><small style={{color:'#62efb2',fontWeight:950}}>AFFORDABLE INSTITUTIONAL ADOPTION</small><h2 style={{fontSize:'clamp(2.2rem,5vw,4.5rem)',letterSpacing:'-.05em',margin:'8px 0 18px'}}>Start with what your program needs.</h2><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(270px,1fr))',gap:14}}>
{card('PATHWAY A','EPA 608 Classroom License','For programs that want to formally use TA-14 608 teaching resources and interactive readiness as part of classroom instruction.')}
{card('PATHWAY B','14-Step Admissible Diagnostic Execution License','For programs that want to teach the 7 In / 7 Out sequence, evidence sufficiency, non-invasive entry threshold, declared diagnostic determination, bounded intervention and post-work proof.')}
{card('PATHWAY C','Full TA-14 HVAC School License','The combined technician-formation pathway: 608 readiness + interactive practice + 14-step field execution + admissible diagnostic records + assessment and instructor implementation.')}
</div><p style={{color:'#91aab7',lineHeight:1.7,maxWidth:920,marginTop:18}}>Founding-school pricing is intentionally kept affordable and is scoped to program size, implementation needs and requested institutional rights. Student access to the public Academy remains free.</p></div>

<div style={{marginTop:54,display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(280px,1fr))',gap:14}}>
{card('FOR PROGRAM DIRECTORS','Keep the HVAC curriculum you already have.','TA-14 can sit across refrigeration, airflow, electrical, commissioning and diagnostic instruction as the evidence and execution discipline. It does not require a school to discard manufacturer, code or existing technical instruction.')}
{card('FOR INSTRUCTORS','Teach a repeatable evidentiary discipline.','Give instructors a common sequence for asking what the evidence establishes, whether the intervention threshold has been crossed, what determination can be declared and what the post-work record proves.')}
{card('FOR STUDENTS','Know when not to touch the system.','The objective is not merely obtaining readings. The technician learns when evidence supports intervention, when more evidence is required, and how to prove the result afterward against the original baseline.')}
</div>

<div style={{marginTop:56,padding:'28px',borderTop:'1px solid #1a4050'}}><h2>Institutional-use boundary</h2><p style={{maxWidth:920,color:'#9fb6c2',lineHeight:1.75}}>Public access to TA-14 Academy does not itself grant an institution permission to rebrand TA-14 materials, imply TA-14 endorsement, issue TA-14 credentials, reproduce protected course materials as its own, or represent an institutional TA-14 relationship. Formal institutional use, licensing scope, attribution, assessment rights and recognition are defined by the applicable written agreement and published terms. Schools may link students to publicly available learning surfaces unless applicable terms state otherwise.</p></div>

<div style={{marginTop:30,textAlign:'center',padding:'48px 20px',borderRadius:24,background:'linear-gradient(135deg,#0a3440,#08241d)'}}><small style={{color:'#62efb2',fontWeight:950}}>FOUNDING SCHOOL LICENSE</small><h2 style={{fontSize:'clamp(2.2rem,5vw,4.4rem)',margin:'8px auto',maxWidth:950}}>Do not graduate symptom chasers. Graduate technicians who can prove the work.</h2><p style={{color:'#b5cad2',maxWidth:780,margin:'12px auto',lineHeight:1.7}}>Tell us your program size and whether you want EPA 608, the 14-step admissible diagnostic execution system, or the complete institutional pathway. We will return an affordable founding-school scope.</p><a href={request} style={{display:'inline-block',marginTop:18,padding:'15px 22px',borderRadius:10,background:'#62efb2',color:'#04130e',fontWeight:950,textDecoration:'none'}}>REQUEST THE SCHOOL LICENSE →</a></div>
</section>
<script type='application/ld+json' dangerouslySetInnerHTML={{__html:JSON.stringify({'@context':'https://schema.org','@type':'Course','name':'TA-14 HVAC Technician Formation System','description':'Free public HVAC learning with affordable institutional licensing for EPA 608 readiness and the TA-14 14-step admissible diagnostic execution sequence.','provider':{'@type':'Organization','name':'TA-14 Authority','url':'https://www.ta14exchange.com'},'url':url})}} />
</main>}
