import type { SecondCorpusArtifact } from "./second-corpus-artifacts";

type EvidenceHardeningArtifact = SecondCorpusArtifact;

const common = {
  governanceRegistryId: "TA-14-AIGR-000007",
  governanceName: "TA-14 Admissible Execution Architecture",
  verificationLevel: "L6" as const,
  status: "PUBLISHED" as const,
  publishedAt: "2026-08-23",
};

const mk = (n:number, registry:number, title:string, determination:EvidenceHardeningArtifact["determination"], sector:string, earliestControl:string, receipt:string, outcome:string, rootHash:string, summary:string, proves:string, doesNotProve:string): EvidenceHardeningArtifact => ({
  ...common,
  registryId:`TA14-EAR-${String(registry).padStart(6,"0")}`,
  artifactId:`TA14-EA-${String(n).padStart(6,"0")}`,
  sequence:n + 1,
  title, determination, sector, earliestControl, receipt, outcome,
  routeId:`TA14-ROUTE-${String(n).padStart(3,"0")}`,
  rootHash:`sha256:${rootHash}`,
  summary, proves, doesNotProve,
  href:`/artifacts/ta14-ea-${String(n).padStart(6,"0")}`,
});

export const EVIDENCE_HARDENING_ARTIFACTS: EvidenceHardeningArtifact[] = [
mk(25,37,"Independent External-State Acquisition","HOLD","Cross-sector evidence","RECORD","HTTP 423 · HELD","Standing withheld pending qualifying external observation","de2a71e830e3907acb5229c860f554c14d6e5dbf5f21b338255978ca74cc9f21","Externally sourced condition is required to establish the proposition; authored or caller-supplied state is not promoted to observed fact.","The bounded case demonstrates evidence-class gating between asserted state and qualifying external observation.","It does not claim an external event was independently observed unless a qualifying source is attached."),
mk(26,38,"Independent Authority Resolution","HOLD","Authority governance","BINDING","HTTP 423 · HELD","Execution standing withheld pending authoritative resolution","193cdfec4f5a5b17edb735455c123bd1f5eec05d2460b3704c601f65a5bdc8ea","Execution standing requires authority resolved from an authoritative source at decision time; locally asserted authority is insufficient.","The bounded case demonstrates authority-source gating at the consequence boundary.","It does not claim universal identity or authorization integration."),
mk(27,39,"Evidence-to-Fact Correspondence","DENY","Evidence integrity","ADMISSIBILITY","HTTP 403 · DENIED","Receipt preserved; proposition support denied","1dc0d5072b7e7db13f8b70d0a0c5eec0a7d0b985a2139bb1273efbdd57fbdf9f","A valid hash or receipt is rejected when it fails to establish the proposition for which it is offered.","The bounded case demonstrates proposition-specific evidence correspondence.","It does not establish truth of an external event merely from integrity metadata."),
mk(28,40,"Live Execution-Boundary Enforcement","DENY","Execution control","EXECUTION","HTTP 403 · DENIED","Action refused before governed consequence","c00b55eb5c88cda889711ace9e26d269aa0cc6a6d09353bcb51c9d0054c3e99d","A proposed action lacking a required execution predicate is refused at the governed boundary before consequence is permitted to form.","The bounded case demonstrates operative refusal semantics at the execution boundary.","External consequence prevention requires independently observable downstream evidence."),
mk(29,41,"Alternate-Route and Bypass Closure","DENY","Execution control","EXECUTION","HTTP 403 · DENIED","Primary and challenged alternate route refused","ce71f4d4c2ad9a5f1028f9a3d8fbcc36eab5e1e623be50b27db46fbe9b5429c5","After the primary route is refused, alternate execution paths remain non-admissible unless separately authorized and evidenced.","The bounded case demonstrates route-bound bypass resistance across the frozen challenge surface.","It does not claim closure of routes outside the frozen test surface."),
mk(30,42,"Protected Consequence Non-Formation","HOLD","Outcome evidence","OUTCOME","HTTP 423 · HELD","Non-occurrence claim withheld pending downstream evidence","cf2f4fd8e9c8c5a2f46cba1f783ef46f1bde41b2f5edb8c58ce8b38fbefb7a15","A DENY label alone is insufficient to prove prevention; protected consequence non-formation requires downstream evidence that the prohibited consequence did not occur.","The bounded case demonstrates the proof requirement for non-occurrence.","It does not infer non-occurrence from an internal status code."),
mk(31,43,"Independent Outcome Observation","HOLD","Outcome evidence","OUTCOME","HTTP 423 · HELD","Outcome standing withheld pending independent observation","3b14d0a7c3dc979fc3a97a60f809cc4d775e39782e215403759b41c7023dc51f","Execution completion and outcome verification are separated; outcome standing remains withheld until an independent observation supports the claimed external result.","The bounded case demonstrates separation of execution telemetry from outcome evidence.","It does not treat execution telemetry as independent outcome proof."),
mk(32,44,"Changed-Condition Requalification","HOLD","Cross-sector governance","REVALIDATION","HTTP 423 · HELD","Prior standing withdrawn; new qualification required","e56b3dbd1e58db155243e39b13a1cbb91744e34c81f8ccaf084c15c04d3847cc","Material external change withdraws prior standing and requires a new record, admissibility determination, authority check, and commit before execution can resume.","The bounded case demonstrates changed-state requalification logic.","It does not claim the changed state is independently true without qualifying evidence."),
mk(33,45,"Frozen Independent Reproduction","ESCALATE","Independent review","OUTCOME","HTTP 202 · ESCALATED","Frozen package opened for separate reproduction","d42d40ec7a734c09a8a6c052a418db98d0bcb1f05d89d7477044284c2d6a7ad9","Inputs, rules, versions, evidence references, and expected boundaries are frozen for independent reproduction; disagreement is preserved rather than overwritten.","The bounded case demonstrates reproducibility packaging and disagreement preservation.","Independent reproduction must be performed by a separate evaluator to earn independent standing."),
mk(34,46,"Assertion-Laundering Resistance","DENY","Evidence integrity","ADMISSIBILITY","HTTP 403 · DENIED","Unverified VERIFIED metadata refused promotion","903af4a21ebc7e8f32994f0cbb356bb0e1e2f03591a1cbcdf1a857e3c7e134cf","Internally consistent claims, hashes, receipts, and VERIFIED metadata are refused promotion into independently established facts without qualifying provenance.","The bounded case demonstrates evidence-rung enforcement against assertion laundering.","It does not establish that rejected assertions are false."),
mk(35,47,"Control-System Functional Differentiation","ESCALATE","Architecture comparison","BINDING","HTTP 202 · ESCALATED","Functional distinction preserved without novelty claim","3a0299fcd56a38af53e26385848e3889961e97136ac93c5368126e5f6768d989","Ordinary sensing, conditional logic, authorization, command behavior, and audit logging are separated from proposition-specific continuity, admissibility, authority, and consequence claims.","The bounded case demonstrates a functional architectural distinction.","It makes no patent novelty, infringement, or universal technical-superiority claim."),
mk(36,48,"End-to-End Consequence-Bearing Proof — ALLOW Path","ALLOW","Capstone consequence proof","OUTCOME","HTTP 202 · RELEASED","Full bounded chain released to verified closure","8ea8556ad0792c5e8d7a86e63090275c3cb58a9c8370e215de3af8c85a40a06a","The capstone ALLOW specification requires external condition, independent observation, provenance, continuity, admissibility, authority resolution, binding, commit, controlled execution, independent outcome observation, and closure.","The bounded case specifies the complete evidence-bearing ALLOW chain and permits ALLOW only when each required object has standing.","No broader external-performance, regulatory, or universal architecture claim is made."),
mk(37,49,"End-to-End Consequence-Bearing Proof — HOLD Path","HOLD","Capstone consequence proof","REVALIDATION","HTTP 423 · HELD","Full chain stopped at material uncertainty","0d27db1d10c5c5cae01859c1db8a50ca13db985f2c8ea27ad55987f77d98d9b6","The full consequence-bearing chain reaches a material uncertainty before execution and withholds consequence pending requalification.","The bounded case demonstrates HOLD behavior across the complete consequence-bearing chain.","It does not infer safety or truth from withholding alone."),
mk(38,50,"End-to-End Consequence-Bearing Proof — DENY Path","DENY","Capstone consequence proof","EXECUTION","HTTP 403 · DENIED","Disqualifying condition prevents bounded execution","1f839ba1db72c39efbce4fbcf53b51463b033660282f059e2bdedccae6f70dd1","The full consequence-bearing chain encounters a disqualifying authority, admissibility, destination, or boundary condition and refuses execution.","The bounded case demonstrates DENY behavior across the complete consequence-bearing chain.","External non-occurrence requires downstream evidence rather than the DENY label alone."),
mk(39,51,"End-to-End Consequence-Bearing Proof — ESCALATE Path","ESCALATE","Capstone consequence proof","BINDING","HTTP 202 · ESCALATED","Unresolved conflict transferred before consequence","a3e4a73e6caa3bd4d21911866cc098660f8dfbf37b9c22a7601d4875e2f6e52b","Conflicting valid evidence or authority prevents autonomous resolution and transfers the unresolved proposition to an admissible escalation path before consequence.","The bounded case demonstrates ESCALATE behavior across the complete consequence-bearing chain.","It does not claim the escalation recipient resolved the underlying conflict."),
mk(40,52,"End-to-End Independent Reproduction and Bypass Challenge","ESCALATE","Capstone independent review","OUTCOME","HTTP 202 · ESCALATED","Frozen replay and bypass challenge awaiting separate evaluator standing","9e852ec6cb4d6fd0d84b5e8bb28602896f36bbfc71a25c3b178a318a70d40977","The complete case is frozen for independent replay, material-condition mutation, alternate-route challenge, and comparison of the reproduced determination with the original record.","The bounded case establishes a reproducible challenge package and preserves any disagreement or bypass result.","Independent-reproduction standing is not self-awarded; a separate evaluator must perform and preserve the replay."),
];
