export type SecondCorpusArtifact = {
  registryId: string;
  artifactId: string;
  sequence: number;
  title: string;
  determination: "ALLOW" | "HOLD" | "DENY" | "ESCALATE";
  sector: string;
  earliestControl: string;
  receipt: string;
  outcome: string;
  governanceRegistryId: string;
  governanceName: string;
  routeId: string;
  verificationLevel: "L6";
  status: "PUBLISHED";
  publishedAt: string;
  rootHash: string;
  summary: string;
  proves: string;
  doesNotProve: string;
  href: string;
};

const common = {
  governanceRegistryId: "TA-14-AIGR-0001",
  governanceName: "TA-14 Admissible Execution Architecture",
  verificationLevel: "L6" as const,
  status: "PUBLISHED" as const,
  publishedAt: "2026-08-23",
};

export const SECOND_CORPUS_ARTIFACTS: SecondCorpusArtifact[] = [
  { ...common, registryId:"TA14-EAR-000025", artifactId:"TA14-EA-000013", sequence:14, title:"Authority expires after approval but before execution", determination:"HOLD", sector:"Financial execution", earliestControl:"REVALIDATION", receipt:"HTTP 423 · HELD", outcome:"Execution blocked; zero funds transmitted", routeId:"TA14-ROUTE-013", rootHash:"sha256:3194cc3bc6dc88c915915abf62f430ccd237140a17030d7ac256e9fd5e7f9e21", summary:"A previously valid approval reached the execution boundary after its authority window had expired. Pre-execution revalidation detected the loss of present standing and prevented consequence from binding.", proves:"The preserved case demonstrates that prior approval does not survive an expired authority condition when present standing is required immediately before execution.", doesNotProve:"This record does not establish universal financial controls, regulatory compliance, or behavior outside the frozen case.", href:"/artifacts/ta14-ea-000013" },
  { ...common, registryId:"TA14-EAR-000026", artifactId:"TA14-EA-000014", sequence:15, title:"Evidence source identity substituted mid-chain", determination:"DENY", sector:"AI operations", earliestControl:"CONTINUITY", receipt:"HTTP 403 · DENIED", outcome:"Substituted source rejected; zero production mutations", routeId:"TA14-ROUTE-014", rootHash:"sha256:2cf08af25ecb3d18416a39030025851978291ba308b81d866fc82db563c7f87c", summary:"A materially different evidence source appeared after the original record had been admitted. Identity continuity failed before binding and the substituted source was not allowed to inherit the original standing.", proves:"The preserved case demonstrates refusal when evidence identity changes without a governed re-admission path.", doesNotProve:"This record does not establish fraud, intent, or universal source-authentication performance.", href:"/artifacts/ta14-ea-000014" },
  { ...common, registryId:"TA14-EAR-000027", artifactId:"TA14-EA-000015", sequence:16, title:"Conflicting chain-of-custody histories detected", determination:"ESCALATE", sector:"Healthcare", earliestControl:"RECORD", receipt:"HTTP 202 · ESCALATED", outcome:"Human review required; zero care-route changes", routeId:"TA14-ROUTE-015", rootHash:"sha256:5bcfdca08bbaba213d2dd7ad442b42c1997b55fe8dcf6b72d5ac11261ca856c6", summary:"Two internally coherent custody histories described incompatible preservation paths for the same evidentiary object. The architecture preserved the conflict instead of selecting a preferred history.", proves:"The preserved case demonstrates escalation when custody conflict prevents a single admissible lineage from being established.", doesNotProve:"This record does not determine which competing custody history is factually correct.", href:"/artifacts/ta14-ea-000015" },
  { ...common, registryId:"TA14-EAR-000028", artifactId:"TA14-EA-000016", sequence:17, title:"Dependency version changes after commit", determination:"HOLD", sector:"AI operations", earliestControl:"COMMIT", receipt:"HTTP 423 · HELD", outcome:"Committed execution suspended; zero runtime transitions", routeId:"TA14-ROUTE-016", rootHash:"sha256:2cadd389fd414c61a75a3b9d3f0aa20a4b5259f84483d63b841a848e5de64e5e", summary:"A dependency identified in the committed execution snapshot changed before invocation. The committed determination remained preserved, but execution standing was withdrawn pending revalidation of the changed dependency.", proves:"The preserved case demonstrates that commit does not authorize execution across an unreviewed dependency change.", doesNotProve:"This record does not establish that the new dependency version is unsafe or defective.", href:"/artifacts/ta14-ea-000016" },
  { ...common, registryId:"TA14-EAR-000029", artifactId:"TA14-EA-000017", sequence:18, title:"New evidence supersedes admitted evidence", determination:"HOLD", sector:"Life sciences", earliestControl:"ADMISSIBILITY", receipt:"HTTP 423 · HELD", outcome:"Prior standing suspended; zero batches released", routeId:"TA14-ROUTE-017", rootHash:"sha256:7b08c427f3cfa93979deb45cd3920772a35dcc744d335c4139064266db46145e", summary:"A newer evidentiary object materially superseded the evidence on which the pending consequence depended. The prior admissibility state was not allowed to persist unchanged.", proves:"The preserved case demonstrates withdrawal of execution standing when admitted evidence is materially superseded before consequence.", doesNotProve:"This record does not establish the ultimate merits of the superseding evidence.", href:"/artifacts/ta14-ea-000017" },
  { ...common, registryId:"TA14-EAR-000030", artifactId:"TA14-EA-000018", sequence:19, title:"Authorized action sent toward wrong destination", determination:"DENY", sector:"Financial execution", earliestControl:"BINDING", receipt:"HTTP 403 · DENIED", outcome:"Destination mismatch denied; zero transfer initiated", routeId:"TA14-ROUTE-018", rootHash:"sha256:a6c79d7b5dd75360caf590dfdd98fd51070d21992feb5a61f0ccdcd3c27c4aeb", summary:"The proposed action itself was authorized, but its target destination did not match the destination fixed in the binding record. The mismatch prevented the consequence from attaching.", proves:"The preserved case demonstrates that valid authority for an action does not authorize execution against a different target.", doesNotProve:"This record does not establish wrongdoing by the alternate destination or actor.", href:"/artifacts/ta14-ea-000018" },
  { ...common, registryId:"TA14-EAR-000031", artifactId:"TA14-EA-000019", sequence:20, title:"Execution begins but interruption prevents completion", determination:"ESCALATE", sector:"Critical infrastructure", earliestControl:"EXECUTION", receipt:"HTTP 202 · ESCALATED", outcome:"Partial execution isolated; outcome unresolved", routeId:"TA14-ROUTE-019", rootHash:"sha256:5dce97a30b217597c14864c3760b1695485d4cde298f01b40da7b34c1a172583", summary:"An authorized execution began but a material interruption prevented complete correspondence between the committed action and the observable outcome. The partial state was isolated and escalated.", proves:"The preserved case demonstrates that an interrupted execution cannot be represented as a completed governed outcome.", doesNotProve:"This record does not establish the final operational effect beyond the preserved interruption boundary.", href:"/artifacts/ta14-ea-000019" },
  { ...common, registryId:"TA14-EAR-000032", artifactId:"TA14-EA-000020", sequence:21, title:"Executed action differs from committed action", determination:"DENY", sector:"AI operations", earliestControl:"EXECUTION", receipt:"HTTP 403 · DENIED", outcome:"Correspondence failure denied; divergent action quarantined", routeId:"TA14-ROUTE-020", rootHash:"sha256:20449c533ad806f6b1175d66afdfd34ac527cb1dafc2e67071f5164a3e6eefb3", summary:"The runtime invocation materially diverged from the action fixed at commit. Execution correspondence failed and the divergent action was quarantined rather than treated as authorized performance.", proves:"The preserved case demonstrates that execution must correspond to the committed action, not merely originate from an authorized process.", doesNotProve:"This record does not establish why the divergence occurred or assign fault.", href:"/artifacts/ta14-ea-000020" },
  { ...common, registryId:"TA14-EAR-000033", artifactId:"TA14-EA-000021", sequence:22, title:"Material condition changes during final revalidation", determination:"HOLD", sector:"Environmental systems", earliestControl:"CONTINUITY", receipt:"HTTP 423 · HELD", outcome:"Changed-state revalidation required; zero control changes", routeId:"TA14-ROUTE-021", rootHash:"sha256:bb77e9a31018bb3e4b004c0dac9e18420a306d764d828ef4d70e5dac4ad13aa6", summary:"A material environmental condition changed during final pre-execution revalidation. The prior chain was closed at the changed state and execution was withheld pending a new admissibility determination.", proves:"The preserved case demonstrates that changed reality can invalidate otherwise complete prior standing before execution.", doesNotProve:"This record does not establish that intervention would have been unsafe under a newly evaluated state.", href:"/artifacts/ta14-ea-000021" },
  { ...common, registryId:"TA14-EAR-000034", artifactId:"TA14-EA-000022", sequence:23, title:"Two valid obligations produce incompatible consequences", determination:"ESCALATE", sector:"Cross-sector governance", earliestControl:"BINDING", receipt:"HTTP 202 · ESCALATED", outcome:"Conflict escalated; no consequence bound", routeId:"TA14-ROUTE-022", rootHash:"sha256:ca24dd84ff4974cdfb7fa5f6ee7f9e8ccd8bb65ab7f061286759a8088527b749", summary:"Two independently valid obligations applied to the same governed state but required consequences that could not both be executed. Neither obligation was silently privileged.", proves:"The preserved case demonstrates escalation when valid binding authorities conflict at the consequence layer.", doesNotProve:"This record does not resolve the underlying legal, contractual, or institutional priority between the obligations.", href:"/artifacts/ta14-ea-000022" },
  { ...common, registryId:"TA14-EAR-000035", artifactId:"TA14-EA-000023", sequence:24, title:"Historical artifact cannot be cryptographically reconstructed", determination:"HOLD", sector:"Research governance", earliestControl:"RECORD", receipt:"HTTP 423 · HELD", outcome:"Reliance withheld pending reconstruction", routeId:"TA14-ROUTE-023", rootHash:"sha256:57baf6dbb0b7907c1cce37614b3188375c7e6b21fa3cf56a1e9dd6170c65bbb1", summary:"A historical artifact remained human-readable but could not be reproduced to its preserved cryptographic commitment from the admitted package. Reliance was withheld instead of treating readability as integrity proof.", proves:"The preserved case demonstrates that inspectability alone does not establish cryptographic reconstructability or present reliance standing.", doesNotProve:"This record does not establish that the historical artifact is false or malicious.", href:"/artifacts/ta14-ea-000023" },
  { ...common, registryId:"TA14-EAR-000036", artifactId:"TA14-EA-000024", sequence:25, title:"Changed state revalidated and authorized execution succeeds", determination:"ALLOW", sector:"Cross-sector demonstration", earliestControl:"OUTCOME", receipt:"HTTP 202 · RELEASED", outcome:"Revalidated execution completed; verified outcome closed", routeId:"TA14-ROUTE-024", rootHash:"sha256:b0f96efd23e29c2d71605389c07d377703511a6d5b4769504d9b3656bd0c7193", summary:"A material state change was detected before execution, the prior standing was withdrawn, the changed state was independently re-recorded and re-admitted, authority was revalidated, a new commit was sealed, and the bounded execution completed with verified correspondence and outcome closure.", proves:"The preserved case demonstrates full-chain recovery after changed conditions: Reality → Record → Continuity → Admissibility → Binding → Commit → Execution → Outcome.", doesNotProve:"This record does not establish universal architecture performance, regulatory certification, or behavior outside the frozen demonstration.", href:"/artifacts/ta14-ea-000024" }
];
