'use client';
import Link from 'next/link';
import {useState} from 'react';
type Q={q:string;o:string[];a:number;e:string};
const qs:Q[]=[
{q:'What is the purpose of electrical fault isolation?',o:['Narrow the unsupported transition using sequence and discriminating evidence','Replace the most likely failed component first','Collect as many unrelated measurements as possible','Restore operation before preserving the original state'],a:0,e:'Fault isolation narrows where the expected sequence stops being supported.'},
{q:'Why begin with the expected sequence of operation?',o:['Sequence proves every component is healthy','It provides an ordered set of expected state transitions to test','Sequence eliminates the need for measurements','It identifies the replacement part before testing'],a:1,e:'Expected sequence gives measurements a proposition and location.'},
{q:'What makes a measurement discriminating?',o:['It is taken with the most expensive meter','It produces a value close to nameplate','It separates plausible fault locations or competing explanations','It is repeated several times at the same point'],a:2,e:'A useful next measurement should reduce uncertainty.'},
{q:'What should happen when evidence establishes the sequence through one boundary?',o:['Replace the next component automatically','Restart the examination from the source','Ignore earlier measurements','Move to the next unresolved transition while preserving established evidence'],a:3,e:'Supported transitions become the basis for examining the next boundary.'},
{q:'What is the strongest first move when a load does not operate?',o:['Define the expected command-to-load sequence and identify the first unestablished state','Replace the load because it did not respond','Bypass the control path to force operation','Increase the protective-device rating'],a:0,e:'Locate the first unsupported transition before assigning a failed part.'},
{q:'Why is “parts cannon” troubleshooting weak?',o:['Replacement parts cannot be tested','It substitutes probability/assumption for evidence locating the fault','New parts always change circuit voltage','It is useful only on low-voltage circuits'],a:1,e:'Component replacement without isolation can obscure the original fault and waste parts.'},
{q:'A command is present and coil voltage is correct, but the contact does not deliver power. Where is the boundary?',o:['At the thermostat setpoint','At the refrigeration circuit','At the switching/contact transition','At the blower duct system'],a:2,e:'Upstream command and coil state are supported; switching delivery is unresolved.'},
{q:'What does a successful upstream measurement allow you to conclude?',o:['Every downstream component is healthy','The fault is definitely mechanical','The equipment is authorized for repair','That measured upstream proposition is supported; downstream states still require evidence'],a:3,e:'Evidence has scope; do not extend it beyond the measured boundary.'},
{q:'Why preserve the original equipment state before intervention?',o:['Changes can destroy or alter evidence needed to locate the fault','Original state is never relevant after a complaint','Intervention always improves diagnostic accuracy','Only photographs are valid evidence'],a:0,e:'Changing wiring, controls or components can erase the condition being examined.'},
{q:'What is the value of measuring on both sides of a suspected boundary?',o:['It guarantees the suspected component is failed','It can show whether the expected electrical condition crossed that boundary','It replaces the need to understand the circuit','It determines refrigerant charge'],a:1,e:'Input/output evidence tests the transition itself.'},
{q:'What should a technician do when two fault explanations remain plausible?',o:['Choose the cheaper repair','Choose the more common failure','Select a safe measurement that best distinguishes between them','Replace both possible components'],a:2,e:'Use the next test to discriminate between remaining explanations.'},
{q:'What is wrong with collecting measurements that do not answer a defined question?',o:['All measurements are equally useful','They always damage the circuit','They automatically invalidate prior evidence','They can add data without reducing diagnostic uncertainty'],a:3,e:'Measurement should be proposition-driven rather than accumulation-driven.'},
{q:'What does a voltage measurement at a load need for useful interpretation?',o:['Defined test points, circuit state and expected relationship','Only the numeric voltage value','Only the equipment model number','A replacement component on hand'],a:0,e:'Context makes the measurement attributable and comparable.'},
{q:'Why can a fault move or disappear after wires are disturbed?',o:['Electrical faults cannot be intermittent','The intervention may alter a loose/intermittent condition and change the evidence state','Wire movement proves the control board failed','Disturbing wiring always repairs the fault permanently'],a:1,e:'Intervention can change the very condition being investigated.'},
{q:'What is the proper conclusion when evidence stops before a cause is established?',o:['The most likely component is failed','The customer complaint is invalid','The cause is not yet established and further bounded evidence is required','The entire circuit should be replaced'],a:2,e:'Uncertainty should be preserved rather than converted into a false verdict.'},
{q:'Why should protection operation be included in a fault-isolation chain?',o:['Protection is unrelated to faults','A trip proves the protective device is defective','Protection should be bypassed during diagnosis','Its state can identify where/when circuit conditions crossed a protective threshold'],a:3,e:'Protective response is part of the event sequence and can narrow examination.'},
{q:'What is a useful divide-and-narrow strategy?',o:['Choose safe test points that split the remaining circuit uncertainty into meaningful regions','Disconnect random components until the equipment runs','Replace half the circuit components at once','Measure only at the electrical source'],a:0,e:'Strategic test points can efficiently narrow the unresolved region.'},
{q:'Why must the technician re-establish standing after a repair or wiring change?',o:['Repairs never affect electrical evidence','The circuit state changed, so earlier measurements may no longer represent the present condition','Only current measurements expire after repair','The service ticket number changed'],a:1,e:'Material intervention creates a new state requiring relevant revalidation.'},
{q:'A fuse opens only when one branch is connected. What is the best next move?',o:['Upsize the fuse','Replace the transformer','Safely isolate and discriminate within that branch while preserving protection','Bypass the branch protection'],a:2,e:'The branch association narrows the region; continue isolation without defeating protection.'},
{q:'What is the role of a hypothesis in fault isolation?',o:['It authorizes component replacement','It becomes true when written in the service record','It replaces the need for circuit sequence','It proposes an explanation that must survive discriminating evidence'],a:3,e:'A hypothesis guides testing but does not become a fact without support.'},
{q:'What should a fault-isolation record show?',o:['Expected sequence, tested transitions, measurements, state changes and bounded conclusion','Only the final replaced component','Only the customer complaint and invoice','A list of every tool used'],a:0,e:'The record should make the diagnostic chain reconstructable.'},
{q:'Why is repeating the same non-discriminating test usually weak?',o:['Repeated measurements are prohibited','It may confirm repeatability without narrowing the unresolved fault location','Meters cannot repeat values accurately','The second reading automatically replaces the first'],a:1,e:'Repeatability can matter, but isolation requires tests that reduce uncertainty.'},
{q:'When should a technician stop and escalate rather than continue testing?',o:['Whenever the first measurement is abnormal','Only after replacing all likely parts','When required safety, qualification, authority or evidence conditions are not established','Never during an electrical diagnosis'],a:2,e:'Diagnostic objectives do not override safety, qualification or authority boundaries.'},
{q:'What does successful fault isolation establish before repair?',o:['That every component in the system is healthy','That the repair will never fail later','That no revalidation is required','A supported fault location/condition within the evidence collected'],a:3,e:'Isolation supports a bounded condition; repair and outcome still require execution and revalidation.'},
{q:'What is the core habit of Lesson 2.14?',o:['Follow sequence, test transitions, reduce uncertainty and stop where the evidence stops','Replace the statistically most common failed part before measurement','Collect voltage readings everywhere and decide afterward','Bypass controls until the failed load becomes obvious'],a:0,e:'Disciplined isolation converts electrical troubleshooting into an evidence chain.'}
];
const chain=[['PRESERVE','Capture the original state before changing the system.'],['MAP','State the expected electrical sequence and the observed failure point.'],['BOUND','Mark the last established state and the first unsupported state.'],['DISCRIMINATE','Choose the safest next measurement that best separates remaining explanations.'],['NARROW','Repeat only as evidence reduces the unresolved region.'],['ESTABLISH','Name a fault condition only when the evidence supports it.'],['REVALIDATE','After intervention, treat the changed circuit as a new state and prove outcome again.']];
export default function Lesson214(){const [tab,setTab]=useState('learn'),[ans,setAns]=useState<Record<number,number>>({}),[sub,setSub]=useState(false),[pick,setPick]=useState('');const score=qs.reduce((n,q,i)=>n+(ans[i]===q.a?1:0),0),pct=Math.round(score/25*100),card={padding:26,border:'1px solid #245878',borderRadius:18,background:'linear-gradient(145deg,#062945,#041e35)'};return <main style={{minHeight:'100vh',background:'#001326',color:'#f7fbff',fontFamily:'Arial,sans-serif',padding:'0 20px'}}><div style={{maxWidth:1120,margin:'auto'}}><nav style={{padding:'22px 0',display:'flex',justifyContent:'space-between',borderBottom:'1px solid #285b78'}}><Link href="/eight24-hvacdr/curriculum/02" style={{color:'#7BAFD4'}}>← MODULE 02</Link><b>LESSON 2.14 · 30 MIN</b></nav><header style={{padding:'58px 0 28px'}}><small style={{color:'#7BAFD4',fontWeight:900}}>TA-14 × EIGHT24 · ELECTRICAL DIAGNOSIS</small><h1 style={{fontFamily:'Georgia,serif',fontSize:'clamp(43px,7vw,72px)',lineHeight:1}}>Electrical<br/><i>Fault Isolation.</i></h1><p style={{maxWidth:900,color:'#C9E0EF',fontSize:19,lineHeight:1.75}}>Do not ask, “What part usually fails?” Ask, “Where does the expected sequence stop being established?” Then choose the safest measurement that reduces the remaining uncertainty the most.</p></header><div style={{display:'flex',gap:8,flexWrap:'wrap',paddingBottom:28}}>{[['learn','DEEP LESSON'],['chain','ISOLATION CHAIN'],['cases','FIELD CASES'],['interact','INTERACT'],['exam','25-Q EXAM'],['record','RECORD']].map(t=><button key={t[0]} onClick={()=>setTab(t[0])} style={{padding:'10px 15px',borderRadius:999,border:'1px solid #316987',background:tab===t[0]?'#7BAFD4':'#06243B',color:tab===t[0]?'#001426':'#C9E0EF',fontWeight:900}}>{t[1]}</button>)}</div>
{tab==='learn'&&<section style={{display:'grid',gap:14,paddingBottom:50}}><article style={card}><h2>Find the transition, not the favorite part.</h2><p style={{color:'#C9E0EF',lineHeight:1.8}}>Start from the intended sequence. Establish each handoff until you reach the first transition that does not have sufficient evidence. That boundary defines the next question.</p></article><article style={card}><h2>Every measurement should reduce uncertainty.</h2><p style={{color:'#C9E0EF',lineHeight:1.8}}>A discriminating measurement separates plausible explanations. Random meter readings create data; a test tied to a proposition creates evidence.</p></article><article style={card}><h2>Intervention creates a new state.</h2><p style={{color:'#C9E0EF',lineHeight:1.8}}>Moving a wire, resetting protection, replacing a component or changing a control can alter the evidence. Preserve Reality₀ first. After intervention, re-establish the relevant conditions before declaring outcome.</p></article></section>}
{tab==='chain'&&<section style={{display:'grid',gap:10,paddingBottom:50}}>{chain.map((x,i)=><article key={x[0]} style={{...card,display:'grid',gridTemplateColumns:'175px 1fr',gap:18}}><b style={{color:'#7BAFD4'}}>{i+1} · {x[0]}</b><span>{x[1]}</span></article>)}</section>}
{tab==='cases'&&<section style={{display:'grid',gap:12,paddingBottom:50}}><article style={card}><b>CASE A · CONTACTOR COMMAND PRESENT, LOAD POWER ABSENT</b><p style={{color:'#C9E0EF'}}>Command and actuation evidence move the boundary downstream. Compare input and output at the switching path instead of replacing the load.</p></article><article style={card}><b>CASE B · CONTROL FUSE OPENS WITH ONE BRANCH</b><p style={{color:'#C9E0EF'}}>The branch association narrows the unresolved region. Continue safe discrimination inside that branch without upsizing or bypassing protection.</p></article><article style={card}><b>CASE C · FAULT DISAPPEARS WHEN WIRING MOVES</b><p style={{color:'#C9E0EF'}}>The intervention changed the state. Preserve that temporal fact; do not rewrite the original complaint as “no fault found.”</p></article></section>}
{tab==='interact'&&<section style={{paddingBottom:50}}><article style={card}><h2>You have correct line voltage into a closed contactor, but no voltage on one load-side pole. Best next conclusion?</h2>{[['a','The compressor has failed.'],['b','The switching boundary for that pole is unsupported; examine that path before moving downstream.'],['c','The refrigerant charge is low.']].map(x=><button key={x[0]} onClick={()=>setPick(x[0])} style={{display:'block',width:'100%',padding:14,marginTop:8,textAlign:'left',background:pick===x[0]?'#123e58':'#031a2e',color:'white',border:'1px solid #316987',borderRadius:9}}>{x[1]}</button>)}{pick&&<p style={{color:pick==='b'?'#9fe0bd':'#efc86c'}}>{pick==='b'?'SUPPORTED — the discriminating evidence has located the unsupported transition.':'TOO FAR — the evidence has not crossed the switching boundary yet.'}</p>}</article></section>}
{tab==='exam'&&<section style={{paddingBottom:50}}>{qs.map((q,i)=><article key={q.q} style={{...card,marginBottom:9}}><b>{i+1}. {q.q}</b>{q.o.map((o,j)=><button key={o} onClick={()=>!sub&&setAns({...ans,[i]:j})} style={{display:'block',width:'100%',padding:11,marginTop:7,textAlign:'left',background:ans[i]===j?'#123e58':'#031a2e',color:'white',border:'1px solid #316987',borderRadius:8}}>{String.fromCharCode(65+j)}. {o}</button>)}{sub&&<p style={{color:ans[i]===q.a?'#9fe0bd':'#efc86c'}}>{ans[i]===q.a?'CORRECT — ':'REVIEW — '}{q.e}</p>}</article>)}<button onClick={()=>setSub(true)} style={{padding:'14px 22px',borderRadius:999,fontWeight:900}}>SUBMIT 25-Q EXAM</button>{sub&&<h2>{score}/25 · {pct}% · {pct>=80?'PASS':'REVIEW REQUIRED'}</h2>}</section>}
{tab==='record'&&<section style={{paddingBottom:50}}><article style={card}><h2>Fault-Isolation Evidence Chain</h2>{['Reality₀ / original condition preserved','Expected sequence documented','Last established state identified','First unsupported transition identified','Next test chosen for discrimination, not convenience','Measurements tied to exact points and circuit state','Competing explanations narrowed by evidence','Safety / qualification / authority boundaries preserved','Post-intervention state revalidated before outcome'].map(x=><p key={x}>✓ {x}</p>)}<b style={{color:'#7BAFD4'}}>HANDOFF → 2.15 ELECTRICAL WALKTHROUGH VR</b></article></section>}</div></main>}
