import Link from 'next/link';

export const dynamic='force-dynamic';
export const metadata={title:'TA14-EA-000043 | TA-14 x Elias Reciprocal Provenance Reconciliation',description:'TA-14 AEA Governance Showcase record of the reciprocal provenance reconciliation between TA-14 and Elias Systems.'};

const gold='#efc66e'; const muted='#a8bfd3';
const panel:React.CSSProperties={border:'1px solid rgba(148,163,184,.20)',borderRadius:22,padding:24,background:'linear-gradient(145deg,rgba(7,22,37,.88),rgba(3,12,22,.93))',boxShadow:'0 24px 70px rgba(0,0,0,.22)'};
const classifications=[
 ['TA-14 antecedent','Earlier TA-14 evidence establishes the proposition before substantive Elias exposure.'],
 ['Elias antecedent','Earlier Elias evidence establishes the proposition independently before relevant TA-14 exposure.'],
 ['Independent convergence','Comparable principles or controls are independently evidenced without a sufficient causal bridge.'],
 ['TA-14 → Elias influence','A TA-14 requirement or gap is communicated, earlier Elias evidence does not establish it at that level, a successor Elias state materially changes, and the documentary record links the change.'],
 ['Elias → TA-14 influence','The same rule applies in reverse where later TA-14 work is demonstrably sharpened by Elias examination or contribution.'],
 ['Unresolved','Chronology or similarity exists, but the evidence does not close the directional causal chain.'],
];
export default function Page(){return <main style={{minHeight:'100vh',color:'#f5f8fc',background:'radial-gradient(circle at 10% 4%,rgba(35,104,173,.27),transparent 28%),radial-gradient(circle at 88% 7%,rgba(227,177,76,.16),transparent 25%),linear-gradient(180deg,#01050b 0%,#04111f 46%,#02070d 100%)'}}><div style={{width:'min(1160px,calc(100% - 40px))',margin:'0 auto',padding:'42px 0 90px'}}>
<nav style={{fontSize:12,color:'#7892a8',marginBottom:50}}><Link href="/workspace/ai-governance/registry/showcase/TA-14-AIGR-0001" style={{color:'#c4d9ea',textDecoration:'none'}}>TA-14 Admissible Execution Architecture Showcase</Link><span> / </span><Link href="/workspace/ai-governance/registry/showcase/TA-14-AIGR-0001/provenance-series" style={{color:gold,textDecoration:'none'}}>Connected Provenance Series</Link><span> / </span><strong style={{color:gold}}>TA14-EA-000043</strong></nav>
<section style={{display:'grid',gridTemplateColumns:'minmax(0,1.45fr) minmax(300px,.55fr)',gap:34,alignItems:'start'}}><div><p style={{color:gold,fontSize:11,fontWeight:900,letterSpacing:'.15em'}}>TA-14 AEA GOVERNANCE SHOWCASE · RECIPROCAL PROVENANCE</p><h1 style={{fontSize:'clamp(42px,6.5vw,80px)',lineHeight:.94,letterSpacing:'-.055em',margin:'18px 0 0'}}>When Two Governance Architectures Let the Evidence Correct Both of Them</h1><p style={{color:muted,fontSize:20,lineHeight:1.72,maxWidth:860,marginTop:25}}>A reciprocal provenance examination between TA-14 Authority and Elias Systems showing what happens when one governance architecture challenges the other's history, earlier evidence changes the initial understanding, and the same evidentiary rule is then applied back in the opposite direction.</p></div><aside style={{...panel,borderColor:'rgba(239,198,110,.32)'}}><p style={{color:'#71899e',fontSize:10,fontWeight:900,letterSpacing:'.12em'}}>ARTIFACT IDENTITY</p><div style={{color:gold,fontWeight:950,fontSize:20}}>TA14-EA-000043</div><div style={{display:'grid',gap:13,marginTop:18}}><div><small style={{color:'#70879b'}}>Parent governance</small><br/><strong>TA-14-AIGR-0001</strong></div><div><small style={{color:'#70879b'}}>Artifact class</small><br/><strong>Governance Showcase / Reciprocal Provenance</strong></div><div><small style={{color:'#70879b'}}>Finding</small><br/><strong style={{color:gold}}>SUPPORTED - RECIPROCAL PROVENANCE RECONCILIATION</strong></div><div><small style={{color:'#70879b'}}>Series position</small><br/><strong>Artifact 03 of 04</strong></div></div></aside></section>
<section style={{...panel,marginTop:36,borderColor:'rgba(239,198,110,.32)'}}><p style={{color:gold,fontSize:10,fontWeight:900,letterSpacing:'.13em'}}>THE GOVERNANCE EVENT</p><h2 style={{fontSize:31,margin:'9px 0 12px'}}>Gary challenged TA-14's provenance. TA-14 answered with chronology. The record changed.</h2><p style={{color:muted,lineHeight:1.75,fontSize:17}}>Gary Williams raised a serious concern that later TA-14 work may have absorbed Elias concepts and explicitly asked TA-14 to apply the same provenance standard it had required of others. TA-14 reconstructed its earlier public record rather than resolving the dispute by institutional assertion. Gary reviewed that earlier evidence and accepted that the foundational TA-14 doctrines at issue were already present before the later substantive Elias interaction.</p></section>
<section style={{...panel,marginTop:18}}><h2 style={{fontSize:26,marginTop:0}}>What Gary's review changed</h2><p style={{color:muted,lineHeight:1.75}}>The broader implication that TA-14's foundational present-tense admissibility, current-state execution governance, evidence continuity, authority-loss logic, non-bypass doctrine, and Reality→Outcome parent sequence may have originated through later Elias work was withdrawn. The remaining provenance question became narrower and more defensible: what was pre-existing TA-14, what was pre-existing Elias, where independent convergence occurred, and what later bidirectional influence can actually be proven.</p><div style={{marginTop:15,padding:17,borderLeft:`3px solid ${gold}`,background:'rgba(239,198,110,.07)',color:'#f1d998',fontWeight:900}}>The evidence did not erase Elias. It corrected the starting point of the dispute.</div></section>
<section style={{marginTop:40}}><p style={{color:gold,fontSize:10,fontWeight:900,letterSpacing:'.13em'}}>THE AGREED CLASSIFICATION MODEL</p><div style={{display:'grid',gridTemplateColumns:'repeat(2,minmax(0,1fr))',gap:14,marginTop:15}}>{classifications.map(([a,b])=><article key={a} style={panel}><h3 style={{margin:'0 0 8px',fontSize:19,color:gold}}>{a}</h3><p style={{margin:0,color:muted,lineHeight:1.65}}>{b}</p></article>)}</div></section>
<section style={{...panel,marginTop:18}}><h2 style={{fontSize:26,marginTop:0}}>Elias antecedence remained Elias</h2><p style={{color:muted,lineHeight:1.75}}>TA-14 did not turn its earlier antecedence into a whole-architecture claim over Elias. Independent Elias material remained attributable to Elias wherever the preserved record supported it. Later Elias architectures were required to be reconciled version by version and control by control rather than flattened into a single origin story.</p></section>
<section style={{...panel,marginTop:18}}><h2 style={{fontSize:26,marginTop:0}}>Later maturity could not be projected backward</h2><p style={{color:muted,lineHeight:1.75}}>The reciprocal rule applied to successor Elias records as well. A later mature Elias control could not be backdated to establish earlier priority merely because it existed in a later registered state. At the same time, close timing after TA-14 review could not by itself establish TA-14 influence. Influence required a documentary bridge from communicated requirement or gap, to missing earlier control at the relevant level, to successor change, to evidence connecting the change to the interaction.</p></section>
<section style={{...panel,marginTop:18,borderColor:'rgba(239,198,110,.34)',background:'linear-gradient(135deg,rgba(22,52,73,.86),rgba(16,26,34,.92))'}}><p style={{color:gold,fontSize:10,fontWeight:900,letterSpacing:'.13em'}}>THE PROSPECTIVE FIX</p><h2 style={{fontSize:30,margin:'8px 0 10px'}}>Clean causation by design</h2><p style={{color:'#b6c8d6',lineHeight:1.75}}>TA-14 and Elias agreed not to repeat the retrospective ambiguity. TA-14 will not enter the current Elias/Tim internal adversarial-hardening lineage. Elias and Tim complete that cycle first, reach their internal stopping condition, and freeze one exact candidate with version, hashes, claims, evidence model, limitations, predecessor history and provenance schedule. Only then does TA-14 begin its independent examination.</p><p style={{color:'#b6c8d6',lineHeight:1.75}}>Gary expressly accepted that sequencing and recorded TA-14 as HOLD pending delivery of the exact frozen examination object. Any later remediation remains Elias engineering in a separately identified successor, with review influence recorded prospectively where the causal chain establishes it.</p></section>
<section style={{...panel,marginTop:18}}><p style={{color:gold,fontSize:10,fontWeight:900,letterSpacing:'.13em'}}>WHAT THIS DOES NOT CLAIM</p><p style={{color:muted,lineHeight:1.75}}>This artifact does not certify Elias, does not claim TA-14 authored Elias, does not claim every later Elias control was influenced by TA-14, does not erase independent Elias antecedence, does not convert timing or similarity into causation, and does not predetermine the outcome of the future frozen-object examination.</p></section>
<section style={{...panel,marginTop:18,borderColor:'rgba(239,198,110,.34)'}}><p style={{color:gold,fontSize:10,fontWeight:900,letterSpacing:'.13em'}}>CONTROLLED SOURCE RECORD</p><p style={{color:muted,lineHeight:1.75}}><strong>Source filename:</strong> TA14_AEA_Governance_Showcase_Elias_Reciprocal_Provenance_Reconciliation_Artifact_v1.0.pdf<br/><strong>Source SHA-256:</strong> 04de4c6451f7e6bf7829e063a081483c8a872dfee84ce282ef905f5b977a238d<br/><strong>Source size:</strong> 58,340 bytes<br/><strong>Publication posture:</strong> Public showcase record; controlled PDF retained as the source artifact.</p></section>
<section style={{...panel,marginTop:18,borderColor:'rgba(239,198,110,.36)',background:'linear-gradient(135deg,rgba(25,52,73,.85),rgba(20,28,33,.9))'}}><p style={{color:gold,fontSize:10,fontWeight:900,letterSpacing:'.13em'}}>CONNECTED PROVENANCE SERIES</p><h2 style={{fontSize:29,margin:'7px 0'}}>Artifact 03 of 04</h2><p style={{color:'#b5c7d5',lineHeight:1.7,maxWidth:850}}>Move between the AB / BIGMAE record, Tim / Harmonic reconciliation, this Gary / Elias reciprocal record, and the eventual combined multi-party chronology. The investigation is connected; the evidentiary boundaries remain separate.</p><Link href="/workspace/ai-governance/registry/showcase/TA-14-AIGR-0001/provenance-series" style={{display:'inline-flex',marginTop:10,padding:'13px 18px',borderRadius:11,background:'linear-gradient(135deg,#f1cd7d,#d3a347)',color:'#07111b',fontWeight:950,textDecoration:'none'}}>Open the connected provenance record →</Link></section>
<section style={{...panel,marginTop:18,textAlign:'center'}}><p style={{color:'#f2d28b',fontSize:18,fontWeight:950,lineHeight:1.6,margin:0}}>Challenge without hostility. Correction without loss of identity.<br/>Attribution without absorption. Evidence above either side.</p></section>
<p style={{marginTop:28}}><Link href="/workspace/ai-governance/registry/showcase/TA-14-AIGR-0001" style={{color:gold,fontWeight:900,textDecoration:'none'}}>← Return to TA-14 Admissible Execution Architecture Governance Showcase</Link></p>
</div></main>}
