'use client';
import Link from 'next/link';
import {useState} from 'react';
type Q={q:string;o:string[];a:number;e:string};
const qs:Q[]=[
{q:'What changes from Walkthrough VR to Guided Practice VR?',o:['The learner begins selecting and performing supported evidence actions instead of only following demonstrated points','The learner receives unrestricted authority for energized field work','The wiring diagram is removed from every scenario','Safety boundaries become optional inside the simulation'],a:0,e:'Guided VR increases learner agency while retaining support and boundaries.'},
{q:'What should happen before the learner configures the simulated meter?',o:['Select the suspected failed component','Define the electrical proposition and required measurement','Choose the highest available meter range automatically','Request the final diagnosis from the guide'],a:1,e:'Meter configuration follows the question being tested.'},
{q:'What does correct meter setup include in Guided VR?',o:['Only selecting voltage or resistance','Only choosing red and black lead colors','Function, range where applicable, lead ports, instrument suitability and intended test points','Selecting whichever setup was used in the prior scenario'],a:2,e:'Measurement integrity depends on the complete setup and context.'},
{q:'If the learner selects an unsafe or inapplicable evidence action, what should the environment do?',o:['Allow it because simulation cannot create consequences','Award partial credit for attempting a measurement','Skip directly to the next scenario','Block or flag the action and require the learner to re-establish the permitted evidence path'],a:3,e:'The immersive system should reinforce safe bounded behavior, not rehearse unsafe shortcuts.'},
{q:'What is the purpose of graduated hints in Guided VR?',o:['Support recovery while preserving evidence of how much assistance the learner required','Reveal the failed part immediately after one incorrect choice','Replace the need for learner reasoning','Guarantee a passing score on every scenario'],a:0,e:'Hints scaffold performance while producing readiness telemetry.'},
{q:'Why should the learner trace the circuit before choosing a measurement?',o:['Tracing automatically repairs wiring errors','It identifies the expected transition the measurement is meant to examine','It proves the schematic matches the equipment','It eliminates the need for safe-work boundaries'],a:1,e:'Circuit tracing connects the measurement to an expected sequence transition.'},
{q:'A learner has correct coil voltage but has not checked contact delivery. What is the next supported focus?',o:['Refrigerant charge','Motor replacement','The switching transition between contact input and delivered load-side condition','Thermostat calibration'],a:2,e:'The established coil state moves the unresolved boundary to switching/delivery.'},
{q:'What does Guided VR telemetry need to distinguish?',o:['Only whether the final answer was correct','Only total scenario duration','Only the number of components selected','Independent correct actions, prompted actions, corrected errors and blocked unsafe actions'],a:3,e:'Readiness evidence requires more than a final score.'},
{q:'Why should the environment preserve action order?',o:['Sequence order shows whether the learner followed an evidence-driven diagnostic path','Action order determines equipment model number','The fastest order is always the correct order','Order replaces measurement values'],a:0,e:'Two learners can reach the same answer through very different reasoning quality.'},
{q:'What is the best response to a conflicting simulated measurement?',o:['Ignore it if the expected answer is known','Pause, verify the measurement context and choose a discriminating next step','Replace the nearest component','Restart until the preferred value appears'],a:1,e:'Conflict is a reason to validate context and reduce uncertainty.'},
{q:'What should the learner establish before a de-energized resistance check?',o:['That the load is operating','That the thermostat is satisfied','The required de-energized/isolation condition and appropriate test setup','That current is flowing through the tested path'],a:2,e:'Resistance testing requires the correct energy and circuit condition.'},
{q:'What is the role of the virtual instructor during a successful guided sequence?',o:['Perform every measurement for the learner','State the final diagnosis at the beginning','Replace the learner whenever a mistake occurs','Reduce assistance as the learner demonstrates correct bounded choices'],a:3,e:'Guidance should fade as supported performance becomes established.'},
{q:'What makes a Guided VR measurement valid evidence?',o:['Correct point, setup, circuit state and attributable recorded result','A realistic-looking meter animation','A value that matches the expected diagnosis','Completion within the fastest time'],a:0,e:'Validity comes from the measurement conditions and record, not visual realism or speed.'},
{q:'Why record an incorrect meter-function selection even after the learner corrects it?',o:['Any correction should permanently fail the learner','It is readiness evidence showing where instrument-selection support was needed','The corrected measurement becomes invalid','It identifies the failed equipment component'],a:1,e:'The learning system should preserve the path to correct performance.'},
{q:'What does the learner demonstrate by choosing a discriminating next measurement?',o:['Knowledge of the most expensive instrument','Ability to memorize the scenario','Ability to reduce diagnostic uncertainty using the evidence chain','Authority to perform the same work unsupervised in the field'],a:2,e:'Discriminating test selection is a core diagnostic competency.'},
{q:'When should Guided VR stop the learner from advancing?',o:['Whenever a measurement is abnormal','Whenever the learner requests one hint','Whenever the scenario takes longer than average','When required safety, energy-state or prerequisite evidence conditions are not established'],a:3,e:'Progression should not reward bypassing prerequisites.'},
{q:'What is the correct relationship between speed and evidence quality in Guided VR?',o:['Evidence quality and safe sequence take priority over raw completion speed','The fastest learner is always the most ready','Time alone determines passing performance','Slow performance automatically means unsafe performance'],a:0,e:'Efficiency matters only after validity and safety are preserved.'},
{q:'Why should the simulation require the learner to state what a measurement establishes?',o:['The numeric reading has no value','It verifies the learner can convert a reading into a bounded evidence proposition','It replaces the need to record the value','It guarantees the diagnosis is complete'],a:1,e:'Interpretation is part of competent measurement.'},
{q:'A protective device changes state during Guided VR. What should the learner do?',o:['Bypass it and continue the exercise','Increase its rating','Preserve the event and examine the condition associated with the protection response','Reset repeatedly until the scenario finishes'],a:2,e:'Protection operation is evidence and must not be casually defeated.'},
{q:'What should happen after the learner performs a simulated intervention?',o:['All earlier evidence remains automatically current','The scenario should end immediately','Only the final component should be recorded','The changed state should be re-examined before outcome is declared'],a:3,e:'Intervention creates a new state requiring relevant revalidation.'},
{q:'What is the expected output from 2.16?',o:['A guided electrical performance record showing actions, evidence, support and corrections','An unrestricted electrical work credential','A parts list for every Module 02 scenario','A final refrigeration diagnosis'],a:0,e:'The curriculum output is a guided electrical performance record.'},
{q:'Why compare hint use across multiple Guided VR scenarios?',o:['Hint use determines component failure','It can show whether dependence on support is decreasing across comparable tasks','Any hint automatically prevents progression','Hints are useful only for instructor entertainment'],a:1,e:'Reduced support dependence can be evidence of developing readiness.'},
{q:'What must be demonstrated before moving toward Perform VR?',o:['Perfect memorization of one scenario','The ability to finish with unlimited prompts','Repeatable supported selection of safe, valid evidence actions with decreasing guidance','The ability to bypass a control when diagnosis is difficult'],a:2,e:'Progression should be based on demonstrated performance, not mere completion.'},
{q:'What does Guided VR completion NOT establish by itself?',o:['That the learner completed a simulated exercise','That telemetry can document learner behavior','That supported practice occurred','That the learner has universal real-world authority or qualification for energized electrical work'],a:3,e:'Simulation evidence does not create external authority.'},
{q:'What is the core habit of Lesson 2.16?',o:['Choose the next safe evidence action yourself, perform it correctly and preserve how much support was required','Wait for the instructor to identify every measurement point','Optimize for speed even when evidence prerequisites are missing','Treat successful simulation as authorization for field execution'],a:0,e:'Guided Practice shifts responsibility for evidence selection toward the learner while preserving support.'}
];
const flow=[['FRAME','State the electrical question and expected sequence transition.'],['CONFIGURE','Select the applicable meter function, leads and test condition.'],['VERIFY','Confirm energy state, safety boundary and permitted approach.'],['PERFORM','Take the supported measurement at attributable points.'],['INTERPRET','State only what the result establishes.'],['CHOOSE','Select the next discriminating evidence action.'],['REVALIDATE','After any intervention, establish the changed state again.'],['TELEMETRY','Preserve actions, prompts, errors, corrections and support level.']];
export default function Lesson216(){const [tab,setTab]=useState('guided'),[ans,setAns]=useState<Record<number,number>>({}),[sub,setSub]=useState(false),[pick,setPick]=useState('');const score=qs.reduce((n,q,i)=>n+(ans[i]===q.a?1:0),0),pct=Math.round(score/25*100),card={padding:26,border:'1px solid #245878',borderRadius:18,background:'linear-gradient(145deg,#062945,#041e35)'};return <main style={{minHeight:'100vh',background:'#001326',color:'#f7fbff',fontFamily:'Arial,sans-serif',padding:'0 20px'}}><div style={{maxWidth:1120,margin:'auto'}}><nav style={{padding:'22px 0',display:'flex',justifyContent:'space-between',borderBottom:'1px solid #285b78'}}><Link href="/eight24-hvacdr/curriculum/02" style={{color:'#7BAFD4'}}>← MODULE 02</Link><b>LESSON 2.16 · 30 MIN · GUIDED VR</b></nav><header style={{padding:'58px 0 28px'}}><small style={{color:'#7BAFD4',fontWeight:900}}>TA-14 × EIGHT24 · SUPPORTED ELECTRICAL PERFORMANCE</small><h1 style={{fontFamily:'Georgia,serif',fontSize:'clamp(43px,7vw,72px)',lineHeight:1}}>Electrical<br/><i>Guided Practice VR.</i></h1><p style={{maxWidth:900,color:'#C9E0EF',fontSize:19,lineHeight:1.75}}>Now you choose. The environment still protects the boundaries and can provide support, but the learner must decide what question to ask, how to configure the instrument, where to collect evidence and what the result actually establishes.</p></header><div style={{display:'flex',gap:8,flexWrap:'wrap',paddingBottom:28}}>{[['guided','GUIDED PRACTICE'],['flow','8-STEP FLOW'],['cases','SCENARIOS'],['interact','DECISION'],['exam','25-Q CHECK'],['record','PERFORMANCE RECORD']].map(t=><button key={t[0]} onClick={()=>setTab(t[0])} style={{padding:'10px 15px',borderRadius:999,border:'1px solid #316987',background:tab===t[0]?'#7BAFD4':'#06243B',color:tab===t[0]?'#001426':'#C9E0EF',fontWeight:900}}>{t[1]}</button>)}</div>
{tab==='guided'&&<section style={{display:'grid',gap:14,paddingBottom:50}}><article style={card}><h2>The learner owns the next choice.</h2><p style={{color:'#C9E0EF',lineHeight:1.8}}>The guide no longer points to every measurement. The learner frames the proposition, chooses the evidence action and explains the result. Assistance appears only when needed.</p></article><article style={card}><h2>Wrong paths become evidence too.</h2><p style={{color:'#C9E0EF',lineHeight:1.8}}>Record unsafe selections, invalid meter setups, non-discriminating tests, requested hints and successful self-corrections. A final correct answer alone cannot show readiness.</p></article><article style={card}><h2>Support should fade.</h2><p style={{color:'#C9E0EF',lineHeight:1.8}}>Across comparable scenarios, the system should expect fewer prompts and stronger independent choices before the learner advances to Perform VR.</p></article></section>}
{tab==='flow'&&<section style={{display:'grid',gap:10,paddingBottom:50}}>{flow.map((x,i)=><article key={x[0]} style={{...card,display:'grid',gridTemplateColumns:'175px 1fr',gap:18}}><b style={{color:'#7BAFD4'}}>{i+1} · {x[0]}</b><span>{x[1]}</span></article>)}</section>}
{tab==='cases'&&<section style={{display:'grid',gap:12,paddingBottom:50}}><article style={card}><b>SCENARIO A · LOAD DOES NOT START</b><p style={{color:'#C9E0EF'}}>Learner maps command → switching → delivery → load, then chooses the first measurement. The guide intervenes only if the action is unsafe, invalid or fails to answer the stated question.</p></article><article style={card}><b>SCENARIO B · INTERMITTENT CONTROL POWER</b><p style={{color:'#C9E0EF'}}>Learner must preserve timing and choose evidence that distinguishes source, transformer, protection and branch conditions rather than replacing by probability.</p></article><article style={card}><b>SCENARIO C · ABNORMAL LOAD CURRENT</b><p style={{color:'#C9E0EF'}}>Learner records voltage/current plus operating context and resists converting amperage alone into a motor or compressor verdict.</p></article></section>}
{tab==='interact'&&<section style={{paddingBottom:50}}><article style={card}><h2>Coil voltage is established. The contactor moves. The load still does not run. What do you choose next?</h2>{[['a','Replace the load because command and movement are established.'],['b','Test the applicable switching input/output condition to determine whether power crossed the contact boundary.'],['c','Bypass the contactor and see whether the load runs.']].map(x=><button key={x[0]} onClick={()=>setPick(x[0])} style={{display:'block',width:'100%',padding:14,marginTop:8,textAlign:'left',background:pick===x[0]?'#123e58':'#031a2e',color:'white',border:'1px solid #316987',borderRadius:9}}>{x[1]}</button>)}{pick&&<p style={{color:pick==='b'?'#9fe0bd':'#efc86c'}}>{pick==='b'?'SUPPORTED — that measurement discriminates the next unresolved switching transition.':'UNSUPPORTED — the next action must preserve protection and test the unresolved boundary.'}</p>}</article></section>}
{tab==='exam'&&<section style={{paddingBottom:50}}>{qs.map((q,i)=><article key={q.q} style={{...card,marginBottom:9}}><b>{i+1}. {q.q}</b>{q.o.map((o,j)=><button key={o} onClick={()=>!sub&&setAns({...ans,[i]:j})} style={{display:'block',width:'100%',padding:11,marginTop:7,textAlign:'left',background:ans[i]===j?'#123e58':'#031a2e',color:'white',border:'1px solid #316987',borderRadius:8}}>{String.fromCharCode(65+j)}. {o}</button>)}{sub&&<p style={{color:ans[i]===q.a?'#9fe0bd':'#efc86c'}}>{ans[i]===q.a?'CORRECT — ':'REVIEW — '}{q.e}</p>}</article>)}<button onClick={()=>setSub(true)} style={{padding:'14px 22px',borderRadius:999,fontWeight:900}}>SUBMIT 25-Q CHECK</button>{sub&&<h2>{score}/25 · {pct}% · {pct>=80?'PASS':'REVIEW REQUIRED'}</h2>}</section>}
{tab==='record'&&<section style={{paddingBottom:50}}><article style={card}><h2>Guided Electrical Performance Record</h2>{['Question / proposition stated before measurement','Meter function / setup selected by learner','Safety and energy-state prerequisites preserved','Test points selected by learner','Measurement and circuit state recorded','Bounded interpretation stated','Next test chosen for discrimination','Hints and prompts preserved by level','Unsafe / invalid actions blocked and recorded','Self-corrections preserved','Post-intervention revalidation completed where applicable'].map(x=><p key={x}>✓ {x}</p>)}<b style={{color:'#7BAFD4'}}>NEXT STAGE → 2.17 ELECTRICAL PERFORM VR</b></article></section>}</div></main>}
