'use client';
import Link from 'next/link';
import {useState} from 'react';

type Q={q:string;o:string[];a:number;e:string};
const qs:Q[]=[
{q:'Before measuring voltage, what should be confirmed first?',o:['Meter function, lead ports, lead condition and expected circuit domain','The suspected component has failed on similar equipment before','The display is set to show the maximum number of digits','The customer agrees that electrical testing is necessary'],a:0,e:'The instrument must be suitable, intact and correctly configured for the proposed measurement.'},
{q:'Why does the lead port matter?',o:['It changes the sequence the equipment is commanded to follow','Incorrect jack placement can invalidate the test or create a hazard','It determines whether the equipment remains within its warranty period','Every meter function uses an identical internal electrical measurement path'],a:1,e:'Lead placement is part of meter configuration; the wrong port can invalidate the test or create danger.'},
{q:'A meter lead has cracked insulation. What is the correct response?',o:['Use it only below the expected line voltage','Keep fingers behind the crack while measuring','Remove the damaged lead from service','Wrap it temporarily for one diagnostic reading'],a:2,e:'Damaged insulation compromises the measurement system and should not remain in service.'},
{q:'Why should the expected electrical quantity be known before selecting a meter function?',o:['It proves the suspected component is energized','It determines the equipment mechanical condition','It guarantees the reading will match the nameplate','The function must match what the technician intends to measure'],a:3,e:'Voltage, current and resistance require different configurations and measurement methods.'},
{q:'What does a CAT rating describe?',o:['A meter system suitability characteristic for specified electrical environments/transients','The maximum resistance a meter can display within the stated operating context','The accuracy of every reading on the instrument under the defined test condition','The technician qualification required to use the meter for the condition being examined'],a:0,e:'Measurement category relates to transient environment and instrument suitability; it is not a universal safety guarantee.'},
{q:'Why verify a meter on a known source when the applicable procedure requires it?',o:['To calculate the circuit resistance automatically','To establish that the instrument can indicate the expected condition','To prove every test point in the cabinet is de-energized','To eliminate the need to inspect leads and ports'],a:1,e:'Instrument verification helps establish that a zero or other critical indication is not merely an instrument failure.'},
{q:'A meter displays OL during a resistance test. What should the technician do?',o:['Interpret it immediately as proof the component has failed open','Replace the suspected component and repeat the same resistance test','Interpret it using the selected function, range and circuit context','Change to energized voltage testing without examining the present setup'],a:2,e:'Display indications have meaning only in the selected function and measurement context.'},
{q:'What is wrong with measuring resistance on an energized circuit?',o:['Energization makes resistance readings more precise under normal operating load','Low expected voltage makes energized resistance testing an acceptable field method','The meter establishes current and resistance together during an energized test','Resistance mode requires appropriate de-energization and may be hazardous when energized'],a:3,e:'Resistance/continuity testing requires the appropriate de-energized condition and circuit preparation.'},
{q:'What is part of measurement integrity?',o:['Recording the instrument configuration with the value and test points','Selecting the result that best matches the expected diagnosis','Repeating a reading until it reaches the expected number','Using the same meter setting for every circuit'],a:0,e:'A reading is stronger when its instrument setup and measurement points are preserved.'},
{q:'Why can auto-ranging still require technician judgment?',o:['Auto-ranging identifies the most likely failed component from the displayed value','The technician must still choose the function and interpret the displayed unit','Auto-ranging removes electrical transient exposure from the proposed measurement task','The instrument automatically chooses the proper lead ports for each measurement'],a:1,e:'Automatic range selection does not choose the measurement question, function, ports or interpretation.'},
{q:'Which meter setup is appropriate for measuring AC voltage?',o:['Resistance function with leads across the load for the condition being examined','Current function with probes placed across line and common within the stated operating context','An appropriate AC-voltage function with leads in the specified voltage/common ports','Continuity mode with the circuit energized for the condition being examined'],a:2,e:'The instrument must be configured according to its instructions for the electrical quantity being measured.'},
{q:'What should happen if the meter rating is not established for the proposed environment?',o:['Proceed if the display range is high enough','Proceed only if the technician wears gloves','Use the meter briefly to reduce exposure time','Do not use it until suitability for the task is established'],a:3,e:'Unknown instrument suitability is an unresolved measurement condition.'},
{q:'Why are probe tips part of the safety system?',o:['Their exposure and insulation affect contact control and accidental bridging risk','They determine the rated current of the equipment load for the condition being examined','They eliminate the need for electrical boundaries within the stated operating context','They prove a conductor is de-energized before contact under the defined test condition'],a:0,e:'Probe construction and exposed conductive length affect how safely the intended test point can be contacted.'},
{q:'A reading changes when a loose lead is moved. What does that indicate?',o:['The component has been established as an intermittent electrical failure','The measurement system may be unstable and should be examined first','The circuit voltage has been established as outside its specification','The equipment should be replaced before any additional electrical examination'],a:1,e:'Instrument and connection integrity must be resolved before treating the value as equipment evidence.'},
{q:'What does meter accuracy specification help describe?',o:['The authority to perform the electrical task within the stated operating context','The mechanical performance of the connected load under the defined test condition','Expected uncertainty/performance of the instrument under specified conditions','Whether a circuit is safe to touch within the stated operating context'],a:2,e:'Accuracy specifications characterize instrument performance, not task authorization or downstream system performance.'},
{q:'A clamp meter surrounds two conductors carrying equal opposite current. Why can the result mislead?',o:['Clamp meters are limited to measuring direct-current electrical circuits only','The instrument changes automatically into resistance mode around multiple conductors','Two enclosed conductors always cause the indicated current value to double','Opposing magnetic fields can cancel, making conductor selection part of measurement'],a:3,e:'Clamp-current measurements depend on enclosing the intended current path correctly.'},
{q:'What should be recorded with a critical meter reading?',o:['Value, unit, test points/conductor, state and relevant instrument configuration','Only the numeric value shown on the display within the stated operating context','The technician’s suspected failed part under the defined test condition','The replacement component selected afterward for the condition being examined'],a:0,e:'Context makes the reading attributable and interpretable.'},
{q:'Why is continuity not the same as proof of a healthy loaded circuit?',o:['Continuity is primarily a temperature-based test of the complete electrical path','It indicates a test path but does not prove performance under operating load','Continuity automatically measures the full operating current flowing through the circuit','A continuity tone establishes that every connection in the path has zero resistance'],a:1,e:'Continuity can establish a path under test conditions, not full circuit performance under load.'},
{q:'Which action protects the original evidence state?',o:['Changing meter functions while probes remain connected','Moving wires until the reading becomes stable','Planning the test points before manipulating the circuit','Resetting controls before recording the initial condition'],a:2,e:'Planning reduces unnecessary manipulation that can alter the condition being examined.'},
{q:'The meter shows 0.00 V where voltage was expected. What is the strongest immediate conclusion?',o:['The transformer has failed under the present operating and command condition','The circuit fuse is open and preventing voltage from reaching the load','The control board is defective and is not delivering its required output','0.00 V was indicated at the defined points under the recorded setup and state'],a:3,e:'First preserve the actual measurement; diagnosis requires discriminating evidence and instrument validity.'},
{q:'Why inspect meter fuses when relevant to the selected function?',o:['An internal protective fuse can affect certain measurement paths and instrument safety','Meter fuses determine the HVAC equipment breaker size under the defined test condition','A blown meter fuse proves the field circuit is shorted for the condition being examined','The fuse changes voltage into resistance within the stated operating context'],a:0,e:'The meter itself contains components that can affect function and safe operation.'},
{q:'What is the purpose of a meter’s common terminal?',o:['It automatically grounds the HVAC equipment during every electrical measurement','It provides a reference connection used by the applicable meter functions','It measures circuit current without requiring another instrument connection point','It identifies the component that should be replaced after the measurement'],a:1,e:'COM is part of the instrument measurement connection; its exact use depends on the selected function.'},
{q:'What is wrong with leaving a lead in a high-current jack before attempting a voltage measurement?',o:['It reduces the meter display resolution only','It prevents the circuit from being energized','It can create a dangerous incorrect measurement configuration','It makes voltage appear as resistance'],a:2,e:'Lead-port configuration must be checked whenever the measurement function changes.'},
{q:'When should meter configuration be reconsidered?',o:['Only when changing to a different equipment brand within the stated operating context','Only after an unexpected diagnosis under the defined test condition','Only at the end of the service call for the condition being examined','Whenever the measurement quantity, points, domain or task changes'],a:3,e:'A changed measurement can require a different instrument setup and safety basis.'},
{q:'What is the core habit of Lesson 2.03?',o:['Treat the complete measurement system as part of the electrical evidence chain','Trust the displayed value whenever the instrument powers on and responds','Keep the same meter configuration throughout the complete service call','Interpret the displayed reading before preserving its exact electrical test points'],a:0,e:'Measurement integrity begins before the displayed value and includes the complete instrument system.'}
];

const integrity=[
['INSTRUMENT','Suitable meter','Correct category/rating, condition and known limitations for the task.'],
['LEADS','Intact connection system','Insulation, probes, accessories and exposed conductive surfaces are appropriate and undamaged.'],
['CONFIGURATION','Correct function + ports','The selected quantity, jack placement, range/mode and units match the intended test.'],
['POINTS','Defined electrical relationship','The exact conductors/terminals being compared are known before contact.'],
['STATE','Known operating condition','Commanded and observed equipment state is preserved with the reading.'],
['VERIFY','Trust but establish','Where required, verify instrument response so a critical indication is not mistaken for meter failure.']
];

export default function Lesson203(){
 const [tab,setTab]=useState('learn'),[answers,setAnswers]=useState<Record<number,number>>({}),[submitted,setSubmitted]=useState(false),[pick,setPick]=useState('');
 const score=qs.reduce((n,q,i)=>n+(answers[i]===q.a?1:0),0),pct=Math.round(score/qs.length*100),passed=submitted&&pct>=80;
 const card={padding:26,border:'1px solid #245878',borderRadius:18,background:'linear-gradient(145deg,#062945,#041e35)',boxShadow:'0 18px 44px rgba(0,0,0,.22)'};
 const tabs=[['learn','DEEP LESSON'],['integrity','INTEGRITY CHAIN'],['cases','FIELD CASES'],['interact','INTERACT'],['exam','25-Q EXAM'],['record','RECORD']];
 return <main style={{minHeight:'100vh',background:'radial-gradient(circle at 80% 0%,#0b4163 0%,#001d36 32%,#001326 70%,#000b18 100%)',color:'#f7fbff',fontFamily:'Arial,sans-serif',padding:'0 20px'}}><div style={{maxWidth:1120,margin:'auto'}}>
 <nav style={{padding:'22px 0',display:'flex',justifyContent:'space-between',borderBottom:'1px solid #285b78',fontSize:11,fontWeight:900}}><Link href="/eight24-hvacdr/curriculum/02" style={{color:'#7BAFD4',textDecoration:'none'}}>← MODULE 02</Link><span style={{color:'#B9D9EB'}}>LESSON 2.03 · 20 MIN</span></nav>
 <header style={{padding:'64px 0 30px'}}><small style={{color:'#7BAFD4',fontWeight:900,letterSpacing:2}}>TA-14 × EIGHT24 · ELECTRICAL MEASUREMENT</small><h1 style={{fontFamily:'Georgia,serif',fontSize:'clamp(44px,7vw,72px)',lineHeight:1,margin:'16px 0'}}>Meters, Leads &<br/><i>Measurement Integrity.</i></h1><p style={{maxWidth:900,color:'#C9E0EF',fontSize:19,lineHeight:1.75}}>The number on the screen is only the end of the measurement chain. Instrument suitability, lead condition, port placement, function, test points and operating state determine whether that number can become trustworthy evidence.</p></header>
 <div style={{display:'flex',gap:8,flexWrap:'wrap',paddingBottom:28}}>{tabs.map(t=><button key={t[0]} onClick={()=>setTab(t[0])} style={{padding:'10px 15px',borderRadius:999,border:'1px solid #316987',background:tab===t[0]?'#7BAFD4':'#06243B',color:tab===t[0]?'#001426':'#C9E0EF',fontWeight:900,cursor:'pointer'}}>{t[1]}</button>)}</div>
 {tab==='learn'&&<section style={{display:'grid',gap:14,paddingBottom:55}}><article style={card}><small style={{color:'#B9D9EB',fontWeight:900}}>THE METER IS PART OF THE EVIDENCE</small><h2 style={{fontFamily:'Georgia,serif',fontSize:34}}>A display is not independent reality.</h2><p style={{color:'#C9E0EF',lineHeight:1.9}}>A meter transforms an electrical condition into an indication. If the instrument is unsuitable, damaged, misconfigured or connected to the wrong points, the display can be misleading even when the digits look precise.</p></article><article style={card}><h2 style={{fontFamily:'Georgia,serif',fontSize:30}}>Function and ports travel together.</h2><p style={{color:'#C9E0EF',lineHeight:1.9}}>Changing from current to voltage or resistance is not just turning a dial. Lead ports, circuit state, connection method and safety controls may also change. Build the habit of rechecking the entire configuration whenever the measurement changes.</p></article><article style={card}><h2 style={{fontFamily:'Georgia,serif',fontSize:30}}>Zero can be evidence—or instrument failure.</h2><p style={{color:'#C9E0EF',lineHeight:1.9}}>Critical absence-of-voltage decisions require the applicable verification procedure. A zero indication is meaningful only when the measurement system itself has been established as functioning for the task.</p></article></section>}
 {tab==='integrity'&&<section style={{display:'grid',gap:12,paddingBottom:55}}>{integrity.map((x,i)=><article key={x[0]} style={{...card,display:'grid',gridTemplateColumns:'120px 210px 1fr',gap:18,alignItems:'center'}}><b style={{color:'#7BAFD4'}}>{String(i+1).padStart(2,'0')} · {x[0]}</b><b>{x[1]}</b><span style={{color:'#C9E0EF',lineHeight:1.7}}>{x[2]}</span></article>)}<article style={{...card,borderColor:'#8b6d27'}}><b style={{color:'#efc86c'}}>CHAIN RULE</b><p style={{fontFamily:'Georgia,serif',fontSize:25,lineHeight:1.55}}>A precise display does not repair a broken measurement chain.</p></article></section>}
 {tab==='cases'&&<section style={{display:'grid',gap:14,paddingBottom:55}}><article style={card}><b style={{color:'#B9D9EB'}}>CASE A · WRONG JACK</b><p style={{color:'#C9E0EF',lineHeight:1.8}}>The technician previously measured current and left a lead in the high-current input. Before the next voltage test, the complete configuration is re-established. Habit prevents a hazardous connection.</p></article><article style={card}><b style={{color:'#B9D9EB'}}>CASE B · ZERO VOLTS</b><p style={{color:'#C9E0EF',lineHeight:1.8}}>A meter indicates 0.00 V at the intended points. Before that indication supports a critical electrical-state conclusion, follow the applicable instrument-verification procedure and preserve exactly where and how the measurement was made.</p></article><article style={card}><b style={{color:'#B9D9EB'}}>CASE C · CLAMP AROUND THE CABLE</b><p style={{color:'#C9E0EF',lineHeight:1.8}}>A clamp is placed around both current-carrying conductors and indicates nearly zero. The problem may not be the load—the magnetic fields can cancel. Conductor selection is part of the measurement.</p></article></section>}
 {tab==='interact'&&<section style={{paddingBottom:55}}><div style={card}><small style={{color:'#B9D9EB',fontWeight:900}}>CONFIGURATION CHECK</small><h2 style={{fontFamily:'Georgia,serif',fontSize:32}}>You just finished a current measurement. Next you need AC voltage. What comes first?</h2>{[['probe','Put the probes on the circuit and then change the dial'],['same','Leave the meter exactly as configured because both are electrical'],['reset','Remove from the circuit and re-establish function, ports, leads, rating and intended test points']].map(x=><button key={x[0]} onClick={()=>setPick(x[0])} style={{display:'block',width:'100%',marginTop:9,padding:15,textAlign:'left',borderRadius:12,border:'1px solid #316987',background:pick===x[0]?'#123e58':'#031a2e',color:'#f7fbff',cursor:'pointer'}}>{x[1]}</button>)}{pick&&<div style={{marginTop:16,padding:18,border:'1px solid '+(pick==='reset'?'#4f8f72':'#8b6d27'),borderRadius:12}}><b>{pick==='reset'?'SUPPORTED':'STOP'}</b><p style={{color:'#C9E0EF'}}>{pick==='reset'?'A new electrical quantity means a new measurement configuration. Establish it before contact.':'Do not carry a previous meter configuration blindly into a different measurement.'}</p></div>}</div></section>}
 {tab==='exam'&&<section style={{paddingBottom:55}}>{qs.map((q,i)=><article key={q.q} style={{...card,marginBottom:10}}><b>{i+1}. {q.q}</b><div style={{display:'grid',gap:8,marginTop:13}}>{q.o.map((o,j)=><button key={o} onClick={()=>!submitted&&setAnswers({...answers,[i]:j})} style={{textAlign:'left',padding:13,borderRadius:10,border:'1px solid #316987',background:answers[i]===j?'#123e58':'#031a2e',color:'#f7fbff',cursor:'pointer'}}>{String.fromCharCode(65+j)}. {o}</button>)}</div>{submitted&&<p style={{color:answers[i]===q.a?'#9fe0bd':'#efc86c'}}>{answers[i]===q.a?'CORRECT — ':'REVIEW — '}{q.e}</p>}</article>)}<button onClick={()=>setSubmitted(true)} style={{padding:'15px 22px',border:0,borderRadius:999,background:'#7BAFD4',color:'#001426',fontWeight:900}}>SUBMIT 25-Q EXAM</button>{submitted&&<div style={{...card,marginTop:14}}><h2>{score}/25 · {pct}%</h2><b style={{color:passed?'#9fe0bd':'#efc86c'}}>{passed?'PASS':'REVIEW REQUIRED — 80% MINIMUM'}</b></div>}</section>}
 {tab==='record'&&<section style={{paddingBottom:55}}><div style={card}><small style={{color:'#B9D9EB',fontWeight:900}}>LESSON EVIDENCE OBJECT</small><h2 style={{fontFamily:'Georgia,serif',fontSize:34}}>Meter Configuration Record</h2>{['Instrument identified and suitable for environment','Leads / probes / accessories inspected','Function and lead ports verified','Expected quantity / domain established','Exact measurement points or conductor identified','Operating / energy state preserved','Displayed value and unit recorded','Instrument verification preserved where required'].map(x=><p key={x} style={{borderTop:'1px solid #316987',paddingTop:12,color:'#C9E0EF'}}>✓ {x}</p>)}<p style={{marginTop:24,color:'#7BAFD4',fontWeight:900}}>HANDOFF → 2.04 READING HVACD/R WIRING DIAGRAMS</p></div></section>}
 </div></main>;
}
