'use client';
import Link from 'next/link';
import {useState} from 'react';

const visuals=[
{n:'01',k:'THE FEDERATION',title:'Four entities. Three governed connections. One federation.',img:'/nist-four-entity-federation-v1.png',alt:'Four-entity federation with three Connection Profiles, Authority Passport and AFA',script:`NIST, begin with the architecture as a whole. This visual deliberately reduces the federation to four entities and three connection profiles so the governing distinction is easy to inspect. Entity One, the owner or operator, originates the need, identity, authority context, constraints and scope. CP1 governs what may cross to Entity Two, design and engineering. Entity Two can add technical and design context, but it does not inherit unlimited execution authority. CP2 governs the connection to Entity Three, controls and systems. CP3 governs the final connection to Entity Four, the responder or facility domain. Across these connections, the Authority Passport, or AVP, carries authority context: identity, role, scope, constraints, conditions, validity and integrity information. Surrounding the complete journey is AFA, the Admissible Federation Architecture. AFA governs the federation across all four entities and all three connections. The rule we want NIST to inspect is simple: authority context may cross the federation. Execution authority does not. When the journey reaches the receiving domain, the fact that every connection worked still does not establish permission to create a physical consequence.`},
{n:'02',k:'THE CONNECTION',title:'The CP governs the doorway. The AVP carries authority context.',img:'/%20nist-connection-profile-avp-v1.png',alt:'Connection Profile and Authority Passport close-up',script:`NIST, this visual isolates the connection itself. Think of the Connection Profile as the rules of the doorway, and the Authority Passport as the authority context presented at that doorway. A Connection Profile determines what may cross a particular connection: permitted information, structure, policy, security requirements, constraints, evidence requirements and auditability. The CP does not manufacture authority, and it does not grant execution authority. The AVP carries authority context associated with the actor or request: issuer, subject, role, scope, constraints, conditions, validity and integrity information. At each connection, the receiving side admits only what that Connection Profile permits. Context may also be narrowed as it moves through the federation. Broader upstream authority does not automatically become broader downstream permission. The distinction is explicit: connection is not authority. The CP governs what may cross. The AVP carries authority context. Neither one, by itself, authorizes the receiving building to execute a real-world consequence.`},
{n:'03',k:'THE EXECUTION BOUNDARY',title:'Federation ends. Local execution authority must be established.',img:'/nist-execution-boundary-eaba-aea-v1.png',alt:'EABA and AEA execution boundary leading to reality',script:`NIST, this is the point where federation ends and physical consequence becomes possible. Entity Four has received authority context through the federation and now proposes a specific action in the real building. Notice the hard boundary. EABA, the Execution Authority Boundary Architecture, begins at the proposed consequence. Its job is not to assume that upstream authority traveled here. Its job is to establish execution authority locally for this target, this consequence and these conditions. That includes valid authority context, local policy, local conditions, local standing and binding to the actual physical target. When local execution authority is established, EABA has completed its role. AEA then begins. The Admissible Execution Architecture examines the proposed consequence through Reality, Record, Continuity, Admissibility, Binding, Commit, Execution and Outcome. At the consequential decision, TA-14 asks: Does this proposed consequence have sufficient Admissible Evidence, Applicable Authority, and Established Standing to become reality NOW? AEA ends at the admission-to-reality decision. Only an admitted consequence proceeds toward physical reality.`},
{n:'04',k:'THE PROOF',title:'Same authority context. Different proposed consequence. Different result.',img:'/%20nist-same-authority-different-governed-outcomes-v1.png',alt:'Same authority context producing different governed outcomes',script:`NIST, this visual demonstrates why valid information and valid authority context are not enough by themselves. Both sides begin from the same measured reality and the same Authority Passport. Identity can be valid. Role can be valid. Scope, constraints, conditions, validity and integrity can all be valid. Yet two proposed consequences can require two different governance determinations. On the left, the proposed consequence is to increase ventilation. If admissible evidence, applicable authority and established standing are sufficient for that action now, the disposition can be ALLOW. On the right, the proposed consequence is to shut down Electrical Panel A. The measurement may still be correct and the authority context may still be legitimate, but if applicable authority or established standing for that specific high-impact action has not been established, the disposition is HOLD. Nothing upstream has to be broken. The sensor did not have to fail. The connection did not have to fail. The Passport did not have to be fraudulent. Governance is determining whether this particular consequence is admissible now.`},
{n:'05',k:'FROM CONNECTION TO CONSEQUENCE',title:'The complete architecture in one view.',img:'/nist-connection-to-consequence-summary-v1.png',alt:'Summary from four entities through CP AVP AFA EABA and AEA to reality',script:`NIST, this final visual recombines the architecture into one end-to-end view. Four entities participate in the federation. CP1, CP2 and CP3 govern the three individual connections. The Authority Passport carries authority context across those permitted connections. AFA governs the federation as a whole and preserves the rule that authority context may cross while execution authority does not. Then we reach the execution boundary. At this point, upstream success is no longer the question. EABA establishes local execution authority for the specific physical target, consequence and present conditions. After EABA, AEA examines the proposed consequence itself. The governing question is: Does this proposed consequence have sufficient Admissible Evidence, Applicable Authority, and Established Standing to become reality NOW? The disposition can be ALLOW, HOLD, DENY or ESCALATE. Only an admitted consequence proceeds toward reality. CP governs the connection. AVP carries authority context. AFA governs the federation. EABA establishes execution authority locally. AEA governs the consequence. Everything before the boundary can be correct, and the answer at the boundary can still be HOLD.`}
];

export default function NistPresentation(){
 const [open,setOpen]=useState<number|null>(null);
 return <main>
 <nav><Link href="/">TA-14 EXCHANGE</Link><span>NIST · STOP THE CYBER ATTACK · CONSEQUENCE-BOUNDARY SHOWROOM</span></nav>
 <header><p className="eyebrow">TA-14 WORKING CONTRIBUTION · NIST-FACING TECHNICAL SHOWROOM</p><h1>FROM CONNECTION<br/><em>TO CONSEQUENCE.</em></h1><p className="lead">Five visuals. One governed journey. Follow authority context across a federation, stop at the execution boundary, and examine what must be established before a proposed building consequence becomes reality.</p><div className="status">WORKING PRESENTATION · OPEN FOR CORRECTION · NOT A NIST ENDORSEMENT · NO CLAIM OF NIST ADOPTION</div></header>
 <section className="orientation"><small>THE TEACHING SEQUENCE</small><div className="sequence"><b>CP</b><i>→</i><b>AVP</b><i>→</i><b>AFA</b><i>→</i><b>EABA</b><i>→</i><b>AEA</b><i>→</i><b>REALITY</b></div><p><strong>Core rule:</strong> Authority context can travel. Execution authority does not travel. It must be established locally before the proposed consequence can be admitted to reality.</p></section>
 {visuals.map((v,i)=><section className="visual" key={v.n}><p className="eyebrow">{v.n} · {v.k}</p><h2>{v.title}</h2><img src={v.img} alt={v.alt}/><div className="explain"><button onClick={()=>setOpen(open===i?null:i)}>{open===i?'CLOSE WALKTHROUGH':'▶ EXPLAIN THIS VISUAL'}</button><span>NIST GUIDED WALKTHROUGH · SCRIPT LOCKED FOR PRERECORDED AUDIO</span></div>{open===i&&<div className="transcript"><small>GUIDED WALKTHROUGH · TRANSCRIPT</small><p>{v.script}</p><div className="audioState">PRERECORDED AUDIO SLOT · narration script frozen · audio asset pending</div></div>}</section>)}
 <section className="question"><small>THE CONSEQUENCE QUESTION</small><h2>Does this proposed consequence have sufficient <em>Admissible Evidence, Applicable Authority, and Established Standing</em> to become reality NOW?</h2><div className="outcomes"><b>ALLOW</b><b>HOLD</b><b>DENY</b><b>ESCALATE</b></div></section>
 <section className="challenge"><small>NIST CHALLENGE</small><h2>Challenge the boundary, not the diagram.</h2><p>Show where an existing mechanism already establishes the same present-tense evidence, local authority, exact target binding and standing immediately before Commit — and can withhold the consequence when one fails. Where that function already exists, record overlap or equivalence.</p><div className="rule">NO ADMISSIBLE EVIDENCE. NO ADMISSIBLE EXECUTION.</div></section>
 <section className="cta"><Link href="/examinations/stop-the-cyber-attack">OPEN PRESERVED WORKING EXAMINATION →</Link></section>
 <footer><b>TA-14 AUTHORITY · WORKING NIST PRESENTATION</b><span>TA-14 owns the consequence-governance proposition shown here. CNS/CP remains Anto Budiardjo's domain to define and correct. NIST participation, endorsement, adoption or validation is not implied.</span></footer>
 <style jsx>{`
 :global(*){box-sizing:border-box}:global(body){margin:0;background:#02070a;color:#eefcff;font-family:Arial,Helvetica,sans-serif}main{max-width:1580px;margin:auto;padding:24px}nav{display:flex;justify-content:space-between;border-bottom:1px solid #24464d;padding:14px 0;font-size:12px;letter-spacing:.12em}nav a{color:#72e6df;text-decoration:none}header,section{padding:64px 0;border-bottom:1px solid #17343b}.eyebrow,small{color:#72e6df;font-size:11px;letter-spacing:.16em;font-weight:900}h1{font-size:clamp(50px,8vw,116px);line-height:.88;margin:24px 0;max-width:1300px}h1 em,h2 em{font-style:normal;color:#e7c76e}h2{font-size:clamp(30px,4.5vw,62px);line-height:1.05;max-width:1150px;margin:16px 0 28px}.lead,p{color:#b9cdd1;line-height:1.65;max-width:1050px}.lead{font-size:clamp(18px,2vw,26px)}.status{border:1px solid #e7c76e;color:#e7c76e;padding:14px;margin-top:30px;font-size:11px;letter-spacing:.11em}.orientation{background:#041117}.sequence{display:flex;gap:14px;align-items:center;flex-wrap:wrap;margin:22px 0;font-size:clamp(18px,3vw,32px)}.sequence b{border:1px solid #31555d;padding:12px 16px}.sequence i{color:#e7c76e;font-style:normal}.orientation strong{color:#eefcff}.visual img{width:100%;height:auto;display:block;border:1px solid #31555d;box-shadow:0 24px 80px rgba(0,0,0,.45)}.explain{display:flex;align-items:center;gap:16px;flex-wrap:wrap;margin-top:18px}.explain button{cursor:pointer;background:#0b2930;border:1px solid #72e6df;color:#eefcff;padding:15px 20px;font-weight:900;letter-spacing:.06em}.explain span{font-size:10px;color:#78969c;letter-spacing:.12em}.transcript{margin-top:12px;border:1px solid #31555d;background:#041117;padding:24px}.transcript p{font-size:17px}.audioState{border-top:1px solid #24464d;padding-top:14px;color:#e7c76e;font-size:10px;letter-spacing:.12em}.question{background:#06151c;border:1px solid #e7c76e!important;padding-left:30px;padding-right:30px}.question h2{max-width:1350px}.outcomes{display:grid;grid-template-columns:repeat(4,1fr);gap:8px;margin-top:28px}.outcomes b{border:1px solid #31555d;padding:18px;text-align:center}.challenge{background:#041117}.rule{font-size:clamp(24px,4vw,48px);font-weight:900;color:#e7c76e;margin-top:32px}.cta{text-align:center}.cta a{display:inline-block;border:1px solid #72e6df;color:#eefcff;padding:16px 22px;text-decoration:none;font-weight:900}footer{padding:36px 0;display:flex;justify-content:space-between;gap:30px;color:#91a9ae;font-size:12px}footer span{max-width:850px}@media(max-width:800px){nav,footer{flex-direction:column}.outcomes{grid-template-columns:1fr 1fr}}
 `}</style></main>
}