import Link from 'next/link';
import { cookies } from 'next/headers';
import { createServerClient } from '@supabase/ssr';
import { listPublishedGovernedArtifacts } from '../../../../../lib/governed-artifacts/public-repository';
type R={registry_identifier:string;governance_name:string;version?:string|null;category?:string|null;status:string};
function isDemo(t:string){const x=t.toLowerCase();return x.includes('demonstration')||x.includes('founding')}
export const dynamic='force-dynamic';
export const metadata={title:'Institutional Continuation | TA-14 Exchange'};
export default async function Page(){
 const store=await cookies(),url=process.env.NEXT_PUBLIC_SUPABASE_URL,key=process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY;
 if(!url||!key)throw new Error('Supabase environment variables are not configured.');
 const db=createServerClient(url,key,{cookies:{getAll(){return store.getAll()},setAll(v){try{v.forEach(({name,value,options})=>store.set(name,value,options))}catch{}}}});
 const [rr,artifacts]=await Promise.all([db.rpc('ta14_registry_public_directory_v1'),listPublishedGovernedArtifacts()]);
 const records=(Array.isArray(rr.data)?rr.data:[] as R[]).filter((r:R)=>r.status?.toLowerCase()==='registered');
 const rows=records.map((r:R)=>{const id=r.registry_identifier.toUpperCase(),a=artifacts.filter(x=>x.governance_registry_identifier?.toUpperCase()===id);return{id,name:r.governance_name,version:r.version??r.category??'—',artifacts:a.length,demos:a.filter(x=>isDemo(x.artifact_type)).length,evidence:new Set(a.flatMap(x=>x.evidence_object_identifiers??[])).size,latest:a[0]?.registered_at??null}}).sort((a,b)=>b.artifacts-a.artifacts||a.name.localeCompare(b.name));
 const active=rows.filter(r=>r.artifacts>0).length;
 return <main className="p"><style>{`*{box-sizing:border-box}body{margin:0;background:#02070c;color:#eef5fa}.p{min-height:100vh;background:radial-gradient(circle at 14% 0%,rgba(42,112,165,.24),transparent 28%),radial-gradient(circle at 88% 3%,rgba(224,174,74,.13),transparent 25%),linear-gradient(180deg,#02070c,#06121e 52%,#02070c);font-family:Inter,system-ui,sans-serif}.w{width:min(1380px,calc(100% - 36px));margin:auto;padding:32px 0 90px}nav{display:flex;gap:10px;flex-wrap:wrap;font-size:13px}nav a{color:#a9c7dd;text-decoration:none}.hero{padding:64px 0 42px;border-bottom:1px solid #ffffff12}.eye{color:#efc66f;font-size:11px;font-weight:950;letter-spacing:.15em}.hero h1{font-size:clamp(48px,7vw,90px);line-height:.94;letter-spacing:-.05em;margin:15px 0}.lead{max-width:900px;color:#a9bdcb;font-size:19px;line-height:1.7}.rule{margin-top:26px;padding:20px;border:1px solid #efc66f44;border-radius:16px;background:#efc66f0d;color:#d9c38e;line-height:1.65}.m{display:grid;grid-template-columns:repeat(3,1fr);gap:12px;margin:28px 0}.m div{padding:20px;border:1px solid #6faad31f;border-radius:15px;background:#071624cc}.m b{display:block;color:#efc66f;font-size:30px}.m span{color:#71899b;font-size:10px;font-weight:900;letter-spacing:.11em}.tw{overflow:auto;border:1px solid #6faad329;border-radius:18px;background:#040f19c7}table{width:100%;border-collapse:collapse;min-width:1120px}th{text-align:left;color:#7891a4;font-size:10px;letter-spacing:.1em;padding:15px;border-bottom:1px solid #ffffff14}td{padding:16px 15px;border-bottom:1px solid #ffffff0e;vertical-align:top;color:#b7c8d4;font-size:13px;line-height:1.5}.id{color:#efc66f;font-weight:900}.name{color:#f1f5f8;font-weight:850;font-size:15px}.pill{display:inline-block;padding:6px 8px;border-radius:8px;border:1px solid #74b1dc33;color:#a9d6f4;font-size:10px;font-weight:900}.next{max-width:360px;color:#9db0bd}.open{color:#efc66f;text-decoration:none;font-weight:900}.boundary{margin-top:28px;color:#6f8596;font-size:12px;line-height:1.7}@media(max-width:700px){.m{grid-template-columns:1fr}}`}</style><div className="w">
 <nav><Link href="/workspace/ai-governance/registry/showcase">Governance Showcase</Link><span>•</span><Link href="/workspace/ai-governance/registry">Authoritative Registry</Link><span>•</span><b>Institutional Continuation</b></nav>
 <header className="hero"><div className="eye">TA-14 EXCHANGE · DERIVED INSTITUTIONAL VIEW</div><h1>INSTITUTIONAL<br/>CONTINUATION</h1><p className="lead">Registered governance identities and the public governed work presently linked to them. This view shows record depth without converting record absence into a finding or a sales qualification.</p><div className="rule"><b>GOVERNING BOUNDARY:</b> Commercial continuation remains subordinate to the governance record. A missing public artifact, demonstration, or evidence object is not proof that none exists, not a deficiency, and not authority to proceed.</div></header>
 <div className="m"><div><b>{rows.length}</b><span>REGISTERED GOVERNANCES</span></div><div><b>{active}</b><span>WITH PUBLISHED GOVERNED ARTIFACTS</span></div><div><b>{rows.length-active}</b><span>NO PUBLISHED ARTIFACT LINK IN THIS LAYER</span></div></div>
 <div className="tw"><table><thead><tr><th>GOVERNANCE</th><th>PRESENT PUBLIC DEPTH</th><th>ARTIFACTS</th><th>DEMOS</th><th>EVIDENCE</th><th>RECORD-BOUND NEXT STEP</th><th></th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td><div className="id">{r.id}</div><div className="name">{r.name}</div><div>{r.version}</div></td><td><span className="pill">{r.artifacts? 'GOVERNED WORK PUBLISHED':'REGISTERED FOUNDATION'}</span></td><td>{r.artifacts}</td><td>{r.demos}</td><td>{r.evidence}</td><td className="next">{r.artifacts?'Inspect chronology, open conditions, and current standing before proposing continuation.':'Inspect the governance record before proposing continuation; public artifact absence establishes nothing beyond this layer.'}</td><td><Link className="open" href={`/workspace/ai-governance/registry/showcase/${encodeURIComponent(r.id)}`}>INSPECT →</Link></td></tr>)}</tbody></table></div>
 <div className="boundary">Derived operational surface only. Authoritative registry records, preserved artifacts, examination records, frozen baselines, dispositions, and current standing remain controlling. Counts describe the linked public layer and do not establish certification, endorsement, technical validity, commercial readiness, or execution authority.</div>
 </div></main>
}