'use client';
import Link from 'next/link';
import {useState} from 'react';
type Q={q:string;o:string[];a:number;e:string};
const qs:Q[]=[
{q:'What is the primary purpose of the Electrical Walkthrough VR?',o:['Practice recognizing electrical sequence, boundaries and safe evidence points before independent performance','Complete an unsupervised energized repair inside the simulated equipment','Memorize replacement part numbers for common electrical failures','Demonstrate maximum speed using every available meter function'],a:0,e:'Walkthrough VR is guided recognition and evidence sequencing, not independent authorization.'},
{q:'What should the learner establish before selecting a measurement point?',o:['The likely replacement part','The proposition the measurement is intended to test','The fastest path through the simulation','The final diagnosis expected by the instructor'],a:1,e:'A measurement point should answer a defined electrical question.'},
{q:'The VR highlights a disconnect, contactor and motor. What should guide the learner through them?',o:['Component price','Physical distance between parts','The expected electrical sequence and energy boundaries','Alphabetical equipment labels'],a:2,e:'The sequence gives each component and measurement point diagnostic meaning.'},
{q:'What does the walkthrough teach when a highlighted point is not safe or applicable for the learner to access?',o:['Proceed because VR eliminates all safety rules','Skip all remaining electrical evidence','Use any nearby point instead','Recognize the boundary and select only the permitted evidence path'],a:3,e:'Training reinforces qualification, safety and authorization boundaries even in simulation.'},
{q:'Why should the learner identify source, control and load regions before measuring?',o:['It creates a circuit map for interpreting where each observation belongs','It proves all three regions are operating correctly','It removes the need to read a wiring diagram','It identifies which component should be replaced'],a:0,e:'Circuit regions orient the learner to the evidence chain.'},
{q:'What is the role of the instructor prompts in Walkthrough VR?',o:['Provide the final diagnosis before evidence is collected','Direct attention to sequence, hazards and evidence questions without replacing reasoning','Authorize live field work after the simulation','Reward selecting the most common failed part'],a:1,e:'Guidance scaffolds disciplined observation and reasoning.'},
{q:'What should a learner do when the VR shows correct command but missing delivered load power?',o:['Conclude the load has failed','Adjust the simulated refrigerant charge','Locate the unresolved switching/delivery transition in the sequence','Restart the scenario without recording the state'],a:2,e:'The learner follows the established chain to the first unsupported transition.'},
{q:'What does a highlighted meter location in the VR NOT mean?',o:['The point has instructional relevance','The point belongs to the scenario','The point may answer a defined question','The learner is universally authorized to perform that measurement in real equipment'],a:3,e:'Simulation instruction does not grant field qualification or authority.'},
{q:'Why does the walkthrough preserve the original scenario state?',o:['So the learner can see Reality₀ before diagnostic actions change the evidence','So every scenario ends with the same component replacement','So the learner can ignore temporal changes','So meter readings never need context'],a:0,e:'Original-state preservation supports evidence integrity.'},
{q:'What does identifying a safe measurement point require?',o:['Only visual access to exposed conductors','Understanding the question, energy state, instrument requirements and permitted approach','A prediction that the component is failed','Prior replacement of the protective device'],a:1,e:'Measurement selection includes proposition, energy, instrument and safety context.'},
{q:'A VR prompt asks what exists on the line side of a contactor. What type of evidence is being targeted?',o:['Mechanical airflow evidence','Refrigeration capacity evidence','Electrical input evidence at the switching boundary','Motor bearing evidence'],a:2,e:'The line side establishes the input condition to the switch.'},
{q:'Why does the learner compare line side and load side in the walkthrough?',o:['To calculate refrigerant superheat','To determine blower wheel diameter','To prove the thermostat is calibrated','To examine whether the expected electrical condition crossed the switching boundary'],a:3,e:'Input/output comparison tests the switching transition.'},
{q:'What should happen after the walkthrough establishes one electrical transition?',o:['Preserve it and move to the next unresolved transition in sequence','Erase the earlier result to avoid bias','Replace the downstream component immediately','Jump to the final system outcome'],a:0,e:'Established evidence remains part of the chain.'},
{q:'Why are meter-function choices shown explicitly in VR?',o:['All meter functions answer the same question','Function selection is part of measurement validity and safety','The most complex function produces stronger evidence','Function choice determines component authority'],a:1,e:'Correct instrument configuration is part of valid measurement.'},
{q:'What is the learner practicing when the VR asks “What do you know now?” after each observation?',o:['Guessing the final failed part','Reciting the component name','Bounding the conclusion to the evidence just established','Choosing the next repair action'],a:2,e:'The prompt trains evidence-bounded reasoning.'},
{q:'Why does the walkthrough distinguish de-energized and energized evidence?',o:['The two states always produce identical information','Only energized evidence is useful','Only de-energized evidence is safe in every situation','They answer different questions and require different safety/test conditions'],a:3,e:'Energy state is part of both safety and interpretation.'},
{q:'What should a learner do if the simulated evidence conflicts with the expected sequence?',o:['Stop at the discrepancy and identify the next discriminating question','Force the scenario to match the diagram','Ignore the conflicting measurement','Select the most common failure from memory'],a:0,e:'Conflict defines a boundary for further examination.'},
{q:'What is the value of seeing the wiring diagram alongside the simulated equipment?',o:['It makes physical equipment unnecessary','It connects schematic relationships to actual components and measurement points','It proves the installed wiring matches the drawing','It authorizes changing circuit connections'],a:1,e:'The learner practices translating diagram logic into physical evidence locations.'},
{q:'The VR shows an open fuse. What should the learner infer first?',o:['The transformer failed','The fuse should be upsized','The protective path is open; the cause of operation remains unresolved','The thermostat must be replaced'],a:2,e:'Protection state and cause remain separate propositions.'},
{q:'Why should the walkthrough show temporal changes when a command occurs?',o:['Timing is irrelevant to electrical diagnosis','It makes the simulation visually entertaining','It replaces electrical measurements','Sequence timing helps attribute state transitions to the same operating event'],a:3,e:'Temporal continuity helps connect command, switching and response.'},
{q:'What is the expected learner output from 2.15?',o:['A VR electrical observation and telemetry record tied to the guided sequence','A completed field repair authorization','A list of components to replace in every scenario','An unrestricted energized-work qualification'],a:0,e:'The module outline defines the output as VR electrical observation plus telemetry.'},
{q:'Why record which prompts or hints the learner needed?',o:['Hints prove the learner failed the module','They provide evidence of where guided support was required during the sequence','Hints replace the final assessment','They determine the equipment fault'],a:1,e:'Guidance usage is useful readiness telemetry for later Guided and Perform stages.'},
{q:'What transition does 2.15 prepare the learner for?',o:['Directly to unrestricted field service','Back to basic electrical formulas','From guided observation into supported hands-on electrical practice in 2.16','Skipping to the final quiz'],a:2,e:'Walkthrough precedes Guided VR in the WALKTHROUGH → GUIDED → PERFORM progression.'},
{q:'What should remain true even when the VR makes the correct answer visually obvious?',o:['The learner may ignore evidence because the environment is simulated','The scenario can bypass protection for speed','The learner should memorize the visual cue only','The reasoning must still connect observation, sequence and bounded conclusion'],a:3,e:'The goal is transferable reasoning, not recognition of a game cue.'},
{q:'What is the core habit of Lesson 2.15?',o:['Observe the electrical sequence, identify permitted evidence points and stop conclusions at the supported boundary','Use the VR to practice rapid component replacement','Treat highlighted components as confirmed failures','Assume simulation completion grants field authority'],a:0,e:'Walkthrough VR rehearses disciplined electrical observation before guided performance.'}
];
const stations=[['ORIENT','Identify source, control, switching, protection and load regions.'],['READ','Connect the wiring diagram to the physical simulated equipment.'],['BOUND','Recognize energy state, hazards and permitted measurement points.'],['FOLLOW','Trace command → switching → delivery → load response.'],['OBSERVE','Record what the simulated evidence actually establishes.'],['STOP','Mark the first unsupported transition instead of guessing beyond it.'],['PRESERVE','Store observations, sequence and guidance telemetry for the next stage.']];
export default function Lesson215(){const [tab,setTab]=useState('walk'),[ans,setAns]=useState<Record<number,number>>({}),[sub,setSub]=useState(false),[pick,setPick]=useState('');const score=qs.reduce((n,q,i)=>n+(ans[i]===q.a?1:0),0),pct=Math.round(score/25*100),card={padding:26,border:'1px solid #245878',borderRadius:18,background:'linear-gradient(145deg,#062945,#041e35)'};return <main style={{minHeight:'100vh',background:'#001326',color:'#f7fbff',fontFamily:'Arial,sans-serif',padding:'0 20px'}}><div style={{maxWidth:1120,margin:'auto'}}><nav style={{padding:'22px 0',display:'flex',justifyContent:'space-between',borderBottom:'1px solid #285b78'}}><Link href="/eight24-hvacdr/curriculum/02" style={{color:'#7BAFD4'}}>← MODULE 02</Link><b>LESSON 2.15 · 25 MIN · WALKTHROUGH VR</b></nav><header style={{padding:'58px 0 28px'}}><small style={{color:'#7BAFD4',fontWeight:900}}>TA-14 × EIGHT24 · IMMERSIVE ELECTRICAL PRACTICE</small><h1 style={{fontFamily:'Georgia,serif',fontSize:'clamp(43px,7vw,72px)',lineHeight:1}}>Electrical<br/><i>Walkthrough VR.</i></h1><p style={{maxWidth:900,color:'#C9E0EF',fontSize:19,lineHeight:1.75}}>Enter the electrical examination without rushing to touch anything. Read the room. Read the diagram. Follow the sequence. The environment shows where evidence can be collected; your job is to understand why each point matters.</p></header><div style={{display:'flex',gap:8,flexWrap:'wrap',paddingBottom:28}}>{[['walk','VR WALKTHROUGH'],['stations','7 STATIONS'],['cases','SCENARIOS'],['interact','INTERACT'],['exam','25-Q CHECK'],['record','TELEMETRY']].map(t=><button key={t[0]} onClick={()=>setTab(t[0])} style={{padding:'10px 15px',borderRadius:999,border:'1px solid #316987',background:tab===t[0]?'#7BAFD4':'#06243B',color:tab===t[0]?'#001426':'#C9E0EF',fontWeight:900}}>{t[1]}</button>)}</div>
{tab==='walk'&&<section style={{display:'grid',gap:14,paddingBottom:50}}><article style={card}><h2>WALKTHROUGH — instructor beside you.</h2><p style={{color:'#C9E0EF',lineHeight:1.8}}>The environment identifies components, diagram relationships, energy boundaries and candidate evidence points. Prompts ask what each observation could establish before the learner advances.</p></article><article style={card}><h2>Highlight ≠ permission.</h2><p style={{color:'#C9E0EF',lineHeight:1.8}}>A simulated measurement point is an instructional object. Real-world electrical work still requires applicable qualification, safe-work procedure, PPE, instrument suitability and authority.</p></article><article style={card}><h2>Telemetry records reasoning, not just clicks.</h2><p style={{color:'#C9E0EF',lineHeight:1.8}}>Preserve route, observation order, selected points, incorrect jumps, requested hints and the boundary the learner identified. That becomes evidence for readiness progression.</p></article></section>}
{tab==='stations'&&<section style={{display:'grid',gap:10,paddingBottom:50}}>{stations.map((x,i)=><article key={x[0]} style={{...card,display:'grid',gridTemplateColumns:'175px 1fr',gap:18}}><b style={{color:'#7BAFD4'}}>{i+1} · {x[0]}</b><span>{x[1]}</span></article>)}</section>}
{tab==='cases'&&<section style={{display:'grid',gap:12,paddingBottom:50}}><article style={card}><b>SCENARIO A · COMMAND PRESENT, LOAD SILENT</b><p style={{color:'#C9E0EF'}}>Trace command, coil, contact state, input power and delivered power. Do not leap from “not running” to “bad motor.”</p></article><article style={card}><b>SCENARIO B · CONTROL POWER MISSING</b><p style={{color:'#C9E0EF'}}>Orient from source through transformer, protection and distribution. The walkthrough highlights evidence points; the learner explains the proposition each would test.</p></article><article style={card}><b>SCENARIO C · PROTECTION CHANGES STATE</b><p style={{color:'#C9E0EF'}}>Preserve the event and identify what changed immediately before it. Do not defeat the protective boundary to keep the simulation moving.</p></article></section>}
{tab==='interact'&&<section style={{paddingBottom:50}}><article style={card}><h2>The VR highlights a load-side contactor terminal. Why measure there?</h2>{[['a','Because every highlighted point must be measured.'],['b','To test whether the expected electrical condition crossed the switching boundary to that load-side point.'],['c','To prove the connected motor is mechanically healthy.']].map(x=><button key={x[0]} onClick={()=>setPick(x[0])} style={{display:'block',width:'100%',padding:14,marginTop:8,textAlign:'left',background:pick===x[0]?'#123e58':'#031a2e',color:'white',border:'1px solid #316987',borderRadius:9}}>{x[1]}</button>)}{pick&&<p style={{color:pick==='b'?'#9fe0bd':'#efc86c'}}>{pick==='b'?'SUPPORTED — the point exists because it answers a defined switching proposition.':'TOO FAR — a measurement point needs a proposition and cannot prove an unrelated downstream outcome.'}</p>}</article></section>}
{tab==='exam'&&<section style={{paddingBottom:50}}>{qs.map((q,i)=><article key={q.q} style={{...card,marginBottom:9}}><b>{i+1}. {q.q}</b>{q.o.map((o,j)=><button key={o} onClick={()=>!sub&&setAns({...ans,[i]:j})} style={{display:'block',width:'100%',padding:11,marginTop:7,textAlign:'left',background:ans[i]===j?'#123e58':'#031a2e',color:'white',border:'1px solid #316987',borderRadius:8}}>{String.fromCharCode(65+j)}. {o}</button>)}{sub&&<p style={{color:ans[i]===q.a?'#9fe0bd':'#efc86c'}}>{ans[i]===q.a?'CORRECT — ':'REVIEW — '}{q.e}</p>}</article>)}<button onClick={()=>setSub(true)} style={{padding:'14px 22px',borderRadius:999,fontWeight:900}}>SUBMIT 25-Q CHECK</button>{sub&&<h2>{score}/25 · {pct}% · {pct>=80?'PASS':'REVIEW REQUIRED'}</h2>}</section>}
{tab==='record'&&<section style={{paddingBottom:50}}><article style={card}><h2>VR Electrical Observation + Telemetry</h2>{['Original scenario state observed before intervention','Diagram-to-equipment mapping completed','Energy / safety boundaries identified','Measurement propositions identified before points','Sequence followed in evidence order','First unsupported transition identified','Hints / prompts used recorded','Unsupported diagnostic jumps recorded','Walkthrough conclusion bounded to observed evidence'].map(x=><p key={x}>✓ {x}</p>)}<b style={{color:'#7BAFD4'}}>NEXT STAGE → 2.16 ELECTRICAL GUIDED PRACTICE VR</b></article></section>}</div></main>}
