'use client';

import Link from 'next/link';

const stages = [
  ['01','LIVE INTEROPERABILITY','ONUMA / RE1','A live information environment exposed the practical problem: machine-readable identity can be technically available while the selected identity or context can still be wrong.'],
  ['02','CONTRADICTION','Identity mismatch surfaced','The workflow did not become evidence of perfection. It became evidence of why consequential execution needs cross-checking, provenance, and correction.'],
  ['03','RECONSTRUCTION','Records before narrative','The event chronology was reconstructed against the API and records rather than silently rewritten after the mismatch was discovered.'],
  ['04','REVALIDATION','Changed context matters','A prior determination cannot simply ride forward when identity, evidence, authority, or material context has changed.'],
  ['05','PATENT PROVENANCE','U.S. Application 19/794,767','On September 2, 2026, USPTO electronically acknowledged receipt of the non-provisional filing directed to cross-architecture evidence-bound admissible execution and changed-context revalidation.'],
  ['06','NEXT REALITY','PAE operating-building boundary','The next proposed test moves from a corrected RE1 identity event toward unresolved equipment and incomplete information in an operating-building context. The examination is now framed explicitly at the TA-14 consequence boundary: does a proposed consequence have admissible evidence, applicable authority, and established standing to become reality now? Access and permission remain prerequisites.'],
];
const boundaries = [
  'The USPTO acknowledgement establishes receipt of the identified filing package; it does not establish allowance, issuance, patentability, validity, enforceability, novelty, or exclusivity.',
  'The ONUMA / RE1 interoperability activity and the patent filing are separate evidence streams. Their proximity and architectural relationship are shown as chronology, not as proof that one legally caused or validates the other.',
  'TA-14 does not represent that ONUMA, PAE, Kimon Onuma, or any participant has adopted, certified, or transferred governance authority to TA-14 unless separately documented.',
  'PAE operating-building work remains prospective until the required access, scope, authority, confidentiality, and publication boundaries are established.',
  'Unexpected failures and unresolved conditions remain part of the record; they are not converted into successful findings by narrative.',
];
const facts = [['ARCHITECTURE','Cross-Architecture'],['CONDITION','Evidence-Bound'],['CHANGE','Δ Context'],['CONTROL','Revalidate'],['BOUNDARY','Proposal → Reality']];

export default function CrossArchitectureShowcase(){return <main style={{minHeight:'100vh',padding:'54px 22px 100px',background:'radial-gradient(circle at 88% 2%,rgba(66,211,255,.18),transparent 30%),radial-gradient(circle at 7% 35%,rgba(72,235,176,.09),transparent 28%),linear-gradient(180deg,#030811 0%,#06101b 48%,#030811 100%)',color:'#eef7fb',fontFamily:'Inter,system-ui,sans-serif'}}>
<div style={{maxWidth:1220,margin:'0 auto'}}>
  <nav style={{display:'flex',justifyContent:'space-between',gap:14,flexWrap:'wrap',alignItems:'center',paddingBottom:20,borderBottom:'1px solid rgba(113,231,255,.12)'}}><Link href="/registry/ta-14-admissible-execution-architecture" style={{color:'#9edff0',textDecoration:'none',fontWeight:800}}>← TA-14 Admissible Execution Architecture</Link><Link href="/registry/ta-14-admissible-execution-architecture/patents" style={{color:'#91a8b7',textDecoration:'none'}}>Patent provenance registry →</Link></nav>

  <section style={{position:'relative',overflow:'hidden',marginTop:26,padding:'clamp(34px,6vw,70px)',border:'1px solid rgba(113,231,255,.22)',borderRadius:30,background:'linear-gradient(145deg,rgba(8,35,52,.96),rgba(5,14,24,.98) 55%,rgba(19,24,54,.92))',boxShadow:'0 36px 110px rgba(0,0,0,.42)'}}>
    <div style={{position:'absolute',right:-90,top:-120,width:380,height:380,borderRadius:'50%',background:'rgba(68,211,255,.10)',filter:'blur(65px)'}} />
    <div style={{position:'relative'}}><div style={{fontSize:11,fontWeight:950,letterSpacing:'.22em',color:'#78e8ff'}}>TA-14 · FLAGSHIP FOUNDING INTEROPERABILITY SHOWCASE</div><h1 style={{fontSize:'clamp(46px,7.8vw,94px)',lineHeight:.93,letterSpacing:'-.055em',margin:'22px 0 24px',maxWidth:1050}}>CROSS-ARCHITECTURE<br/><span style={{color:'#7ff0bd'}}>ADMISSIBLE EXECUTION</span></h1><p style={{fontSize:'clamp(18px,2.2vw,27px)',lineHeight:1.45,maxWidth:940,color:'#b7c9d5',margin:0}}>A provenance-first record connecting live interoperability, identity contradiction, reconstruction, changed-context revalidation, patent provenance, and the next operating-building boundary.</p>
    <div style={{display:'flex',gap:9,flexWrap:'wrap',marginTop:30}}>{['ONUMA / RE1','U.S. 19/794,767','NON-PROVISIONAL §111(a)','USPTO RECEIPT · 2026-09-02','PAE · PROSPECTIVE'].map((x,i)=><b key={x} style={{padding:'9px 12px',borderRadius:999,border:`1px solid ${i===3?'rgba(127,240,189,.32)':'rgba(113,231,255,.22)'}`,background:i===3?'rgba(127,240,189,.07)':'rgba(113,231,255,.035)',color:i===3?'#7ff0bd':'#c8edf6',fontSize:10,letterSpacing:'.07em'}}>{x}</b>)}</div></div>
  </section>

  <section style={{margin:'22px 0',padding:'clamp(28px,5vw,48px)',border:'1px solid rgba(127,240,189,.24)',borderRadius:26,background:'linear-gradient(135deg,rgba(17,68,55,.28),rgba(5,17,28,.92))'}}>
    <div style={{color:'#7ff0bd',fontSize:11,fontWeight:950,letterSpacing:'.18em'}}>THE TA-14 CONSEQUENCE BOUNDARY</div>
    <h2 style={{fontSize:'clamp(31px,5vw,58px)',lineHeight:1.02,letterSpacing:'-.04em',margin:'12px 0 16px'}}>TA-14 governs the boundary between proposal and reality.</h2>
    <p style={{fontSize:'clamp(17px,2vw,23px)',lineHeight:1.55,maxWidth:980,color:'#b7c9d5',margin:'0 0 26px'}}>Before a proposed consequence becomes real, TA-14 asks: does it have <b style={{color:'#eef7fb'}}>ADMISSIBLE EVIDENCE</b>, <b style={{color:'#eef7fb'}}>APPLICABLE AUTHORITY</b>, and <b style={{color:'#eef7fb'}}>ESTABLISHED STANDING</b> to become reality <b style={{color:'#7ff0bd'}}>NOW</b>?</p>
    <div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(190px,1fr))',gap:10}}>{[['ADMISSIBLE EVIDENCE','Attributable · current · sufficient'],['APPLICABLE AUTHORITY','Valid here · for this consequence'],['ESTABLISHED STANDING','Authoritatively related · not inherited'],['NOW','Revalidated against current reality']].map(([k,v])=><div key={k} style={{padding:'17px 14px',textAlign:'center',borderRadius:13,border:'1px solid rgba(127,240,189,.18)',background:'rgba(2,10,17,.52)'}}><div style={{fontSize:13,fontWeight:950,letterSpacing:'.07em',color:'#dff7ec'}}>{k}</div><div style={{marginTop:7,fontSize:12,color:'#91a7b5',lineHeight:1.45}}>{v}</div></div>)}</div>
    <div style={{marginTop:18,textAlign:'center',fontSize:'clamp(18px,2.5vw,27px)',fontWeight:950,letterSpacing:'.05em',color:'#7ff0bd'}}>ALLOW · HOLD · DENY · ESCALATE</div>
    <p style={{maxWidth:920,margin:'20px auto 0',textAlign:'center',color:'#91a7b5',lineHeight:1.7}}>For the prospective PAE operating-building work, this is the examination boundary. PAE retains control of access and its own operational authority. TA-14 does not treat access, data availability, a recommendation, or a prior approval as automatic permission for a consequence to become reality.</p>
  </section>

  <section style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(190px,1fr))',gap:12,margin:'22px 0 42px'}}>{facts.map(([k,v])=><div key={k} style={{padding:'19px 20px',border:'1px solid rgba(113,231,255,.12)',borderRadius:15,background:'rgba(7,18,30,.78)'}}><small style={{color:'#71899a',letterSpacing:1.3,fontWeight:800}}>{k}</small><div style={{marginTop:7,fontSize:18,fontWeight:900,color:k==='BOUNDARY'?'#7ff0bd':'#eef7fb'}}>{v}</div></div>)}</section>

  <section style={{margin:'0 0 42px',padding:'clamp(28px,5vw,48px)',border:'1px solid rgba(242,204,104,.3)',borderRadius:26,background:'linear-gradient(135deg,rgba(72,52,12,.28),rgba(5,17,28,.94))'}}>
    <div style={{color:'#f2cc68',fontSize:11,fontWeight:950,letterSpacing:'.18em'}}>LIVE TECHNICAL EXAMINATION · HVAC CONTROL</div>
    <h2 style={{fontSize:'clamp(32px,5vw,58px)',lineHeight:1.02,letterSpacing:'-.04em',margin:'12px 0 16px'}}>CAN THIS CONSEQUENCE BECOME REALITY NOW?</h2>
    <p style={{maxWidth:980,color:'#c4d1d8',lineHeight:1.7,fontSize:18}}>Classroom 214 has elevated CO₂. The control sequence proposes increasing outdoor-air ventilation. The actuator is available and the sequence is technically valid. Outdoor PM2.5 then rises materially. A previous approval exists. The system can act. The consequence boundary asks a different question.</p>
    <div style={{margin:'24px 0',padding:'24px',borderRadius:18,border:'1px solid rgba(127,240,189,.28)',background:'rgba(2,10,17,.62)',fontSize:'clamp(21px,3vw,32px)',fontWeight:950,lineHeight:1.3}}>Does this proposed consequence have <span style={{color:'#7ff0bd'}}>ADMISSIBLE EVIDENCE, APPLICABLE AUTHORITY, and ESTABLISHED STANDING</span> to become reality <span style={{color:'#f2cc68'}}>NOW</span>?</div>
    <div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(160px,1fr))',gap:10}}>{['ALLOW','HOLD','DENY','ESCALATE'].map((x,i)=><button key={x} type="button" onClick={()=>{const el=document.getElementById('examination-result');if(el)el.textContent=i===1?'HOLD — The proposed consequence cannot inherit permission from the earlier state. Material context changed. Revalidate the current admissible evidence, applicable authority, established standing, and competing environmental conditions before execution.':'You selected '+x+'. Now establish the current admissible record. A technically valid command, actuator availability, or previous approval does not by itself establish present permission to execute.'}} style={{cursor:'pointer',padding:'17px 14px',borderRadius:13,border:i===1?'1px solid rgba(242,204,104,.42)':'1px solid rgba(113,231,255,.2)',background:i===1?'rgba(242,204,104,.08)':'rgba(113,231,255,.04)',color:i===1?'#f2cc68':'#dff7fb',fontSize:13,fontWeight:950,letterSpacing:'.09em'}}>{x}</button>)}</div>
    <div id="examination-result" aria-live="polite" style={{marginTop:18,minHeight:58,padding:'17px 20px',borderLeft:'3px solid #f2cc68',background:'rgba(242,204,104,.04)',color:'#d9e2e6',lineHeight:1.65}}>Choose a determination. The examination will expose what must be established at the consequence boundary.</div>
  </section>

  <section style={{margin:'0 0 42px',padding:'clamp(28px,5vw,46px)',border:'1px solid rgba(113,231,255,.22)',borderRadius:26,background:'linear-gradient(135deg,rgba(8,39,58,.82),rgba(5,17,28,.94))'}}>
    <div style={{color:'#78e8ff',fontSize:11,fontWeight:950,letterSpacing:'.18em'}}>CONTROL CORRECTNESS IS NOT THE SAME QUESTION</div>
    <h2 style={{fontSize:'clamp(30px,4.5vw,52px)',lineHeight:1.04,letterSpacing:'-.04em',margin:'12px 0 20px'}}>Capability can be established while execution remains unresolved.</h2>
    <div style={{display:'grid',gridTemplateColumns:'repeat(2,minmax(0,1fr))',border:'1px solid rgba(113,231,255,.14)',borderRadius:16,overflow:'hidden'}}>
      {[['CONTROL QUESTION','TA-14 CONSEQUENCE-BOUNDARY QUESTION'],['Is the sequence correct?','Is the proposed consequence admissible now?'],['Can the actuator execute?','Is execution authorized now?'],['Is the sensor input valid?','Is the evidence sufficient for this consequence?'],['Was this previously allowed?','Is that authority still applicable and is standing still established now?'],['Can the system act?','Should this proposed consequence become reality now?']].flatMap((row,ri)=>row.map((cell,ci)=><div key={ri+'-'+ci} style={{padding:'15px 17px',borderTop:ri?'1px solid rgba(113,231,255,.09)':'none',borderLeft:ci?'1px solid rgba(113,231,255,.09)':'none',background:ri===0?'rgba(113,231,255,.06)':'rgba(2,10,17,.42)',color:ri===0?'#78e8ff':'#c7d6de',fontWeight:ri===0?950:750,fontSize:ri===0?11:15,letterSpacing:ri===0?'.08em':'normal'}}>{cell}</div>))}
    </div>
  </section>

  <section style={{margin:'0 0 42px',padding:'clamp(28px,5vw,46px)',border:'1px solid rgba(127,240,189,.22)',borderRadius:26,background:'linear-gradient(135deg,rgba(17,68,55,.2),rgba(5,17,28,.94))'}}>
    <div style={{color:'#7ff0bd',fontSize:11,fontWeight:950,letterSpacing:'.18em'}}>ASHRAE TC 1.4 · TECHNICAL DISCUSSION PATH</div>
    <h2 style={{fontSize:'clamp(30px,4.5vw,52px)',lineHeight:1.04,letterSpacing:'-.04em',margin:'12px 0 16px'}}>Put the boundary in front of established control theory.</h2>
    <p style={{maxWidth:1000,color:'#b7c9d5',lineHeight:1.72,fontSize:17}}>ASHRAE TC 1.4 has invited TA-14 into an informal brainstorming discussion at the Winter Conference. The committee has not reviewed, validated, certified, or endorsed TA-14. The purpose is technical scrutiny: whether the distinction between control capability and present consequence authority is already fully addressed by established control approaches or represents a meaningful technical gap worthy of further discussion.</p>
    <div style={{marginTop:22,padding:'20px 22px',border:'1px solid rgba(127,240,189,.18)',borderRadius:15,background:'rgba(2,10,17,.5)',fontSize:'clamp(18px,2.3vw,25px)',fontWeight:900,lineHeight:1.45}}>If established control theory already fully resolves this boundary, identify where.</div>
    <div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(230px,1fr))',gap:10,marginTop:16}}>{['Where is present execution authority established?','What requires prior authority to be revalidated?','What happens when technically valid inputs create competing consequences?','What record establishes why a command was permitted to become reality?'].map((x,i)=><div key={x} style={{padding:'18px',borderRadius:14,border:'1px solid rgba(127,240,189,.12)',background:'rgba(127,240,189,.035)',color:'#c7d9d1',lineHeight:1.55}}><b style={{color:'#7ff0bd'}}>0{i+1}</b><div style={{marginTop:8}}>{x}</div></div>)}</div>
  </section>

  <section style={{margin:'0 0 42px',padding:'clamp(28px,5vw,46px)',border:'1px solid rgba(113,231,255,.22)',borderRadius:26,background:'linear-gradient(135deg,rgba(8,39,58,.82),rgba(5,17,28,.94))'}}>
    <div style={{color:'#78e8ff',fontSize:11,fontWeight:950,letterSpacing:'.18em'}}>OWNER-LED GOVERNED PROCESS · REFERENCE IMPLEMENTATION PATTERN</div>
    <h2 style={{fontSize:'clamp(30px,4.5vw,52px)',lineHeight:1.04,letterSpacing:'-.04em',margin:'12px 0 16px'}}>The owner need starts the process. Independent systems carry it toward consequence.</h2>
    <p style={{maxWidth:980,color:'#b7c9d5',lineHeight:1.72,fontSize:17}}>The interoperability demonstration was not a closed TA-14 / ONUMA integration and it does not begin with a particular technology. It begins with an owner need: the outcome, condition, obligation, or operating requirement that gives the technical work a governed purpose. From there, independent systems can exchange shared meaning, reference the same objects, interact through defined interfaces, and preserve their own roles and boundaries.</p>
    <div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(170px,1fr))',gap:10,marginTop:24}}>{[
      ['OWNER NEED','Governed purpose + required outcome'],
      ['RDF / TURTLE','Shared meaning + relationships'],
      ['PERSISTENT IDs','Shared reference'],
      ['API','Two-way interaction'],
      ['TA-14','Governance at the consequence boundary'],
    ].map(([k,v],i)=><div key={k} style={{padding:'20px 17px',borderRadius:15,border:i===4?'1px solid rgba(127,240,189,.3)':i===0?'1px solid rgba(242,204,104,.28)':'1px solid rgba(113,231,255,.16)',background:i===4?'rgba(127,240,189,.06)':i===0?'rgba(242,204,104,.055)':'rgba(2,10,17,.52)'}}><div style={{fontSize:12,fontWeight:950,letterSpacing:'.08em',color:i===4?'#7ff0bd':i===0?'#f2cc68':'#78e8ff'}}>{k}</div><div style={{marginTop:9,color:'#d8e7ed',lineHeight:1.5,fontWeight:800}}>{v}</div></div>)}</div>
    <div style={{marginTop:22,padding:'18px 20px',borderLeft:'3px solid #7ff0bd',background:'rgba(127,240,189,.04)',color:'#b9cbc6',lineHeight:1.72}}>The owner need establishes why the process exists and what outcome must be governed. RDF/Turtle supplies shared semantic structure and relationships. Persistent IDs keep independent systems pointed at the same objects. The API enables two-way interaction with the live information environment. TA-14 then operates at a different layer: determining whether a proposed consequence has ADMISSIBLE EVIDENCE, APPLICABLE AUTHORITY, and ESTABLISHED STANDING to become reality NOW.</div>
    <div style={{marginTop:18,padding:'17px 20px',border:'1px solid rgba(113,231,255,.16)',borderRadius:14,background:'rgba(2,10,17,.42)',fontSize:'clamp(17px,2vw,22px)',fontWeight:950,letterSpacing:'-.015em',color:'#eef7fb'}}>The technologies may change. The governed process does not.</div>
    <p style={{maxWidth:980,margin:'20px 0 0',color:'#91a7b5',lineHeight:1.7}}>The products used in the demonstration matter as evidence of a working implementation, but the architectural pattern is not dependent on a particular product. Owners can require the general governed steps while technical teams use appropriate standards, products, and tools inside those steps. Other systems can participate when they can preserve shared meaning, identity, interaction, and the required governance boundaries.</p>
  </section>

  <section style={{marginTop:46}}><div style={{color:'#7ff0bd',fontSize:11,fontWeight:900,letterSpacing:'.17em'}}>FOUNDING CHRONOLOGY · REALITY BEFORE NARRATIVE</div><h2 style={{fontSize:'clamp(30px,4vw,48px)',letterSpacing:'-.035em',margin:'10px 0 24px'}}>From live contradiction to governed continuation.</h2><div style={{display:'grid',gap:12}}>{stages.map(([n,label,title,text],i)=><article key={n} style={{display:'grid',gridTemplateColumns:'70px minmax(0,1fr)',gap:18,padding:'24px clamp(20px,4vw,34px)',border:`1px solid ${i===4?'rgba(127,240,189,.25)':'rgba(113,231,255,.12)'}`,borderRadius:18,background:i===4?'linear-gradient(120deg,rgba(34,93,72,.18),rgba(7,18,30,.82))':'rgba(7,18,30,.72)'}}><div style={{fontSize:32,fontWeight:950,color:i===4?'#7ff0bd':'#58cfe8'}}>{n}</div><div><div style={{fontSize:10,fontWeight:900,letterSpacing:'.16em',color:'#7893a4'}}>{label}</div><h3 style={{fontSize:22,margin:'5px 0 8px'}}>{title}</h3><p style={{margin:0,maxWidth:930,color:'#afc1cd',lineHeight:1.72}}>{text}</p></div></article>)}</div></section>

  <section style={{marginTop:42,padding:'clamp(28px,5vw,46px)',border:'1px solid rgba(127,240,189,.22)',borderRadius:26,background:'linear-gradient(135deg,rgba(21,70,55,.24),rgba(5,17,28,.9))'}}><div style={{color:'#7ff0bd',fontSize:11,fontWeight:900,letterSpacing:'.17em'}}>PATENT PROVENANCE MOMENT · RECEIPT, NOT ADJUDICATION</div><h2 style={{fontSize:'clamp(30px,4.5vw,50px)',lineHeight:1.04,letterSpacing:'-.035em',maxWidth:1000,margin:'13px 0 25px'}}>Systems and Methods for Cross-Architecture Evidence-Bound Admissible Execution and Changed-Context Revalidation</h2><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(190px,1fr))',gap:11}}>{[['APPLICATION','19/794,767'],['RECEIVED','SEP 2, 2026'],['TIME','08:27:08 AM ET'],['SPECIFICATION','23 PAGES · DIGEST RECORDED']].map(([k,v])=><div key={k} style={{padding:18,borderRadius:13,background:'rgba(2,10,17,.58)',border:'1px solid rgba(127,240,189,.1)'}}><small style={{color:'#6f8c80',letterSpacing:1.1}}>{k}</small><div style={{marginTop:7,fontWeight:900,color:k==='APPLICATION'?'#7ff0bd':'#eaf5ef'}}>{v}</div></div>)}</div><p style={{margin:'24px 0 0',maxWidth:1000,color:'#b5c8c0',lineHeight:1.8}}>The filing record and live interoperability work remain separate evidence streams. This showcase preserves their chronological convergence around identity, evidence, changed context, revalidation, authority, and consequence before execution.</p></section>

  <section style={{marginTop:28,padding:'clamp(26px,4vw,38px)',border:'1px solid rgba(242,204,104,.22)',borderRadius:24,background:'linear-gradient(135deg,rgba(61,46,11,.25),rgba(7,18,30,.84))'}}><div style={{color:'#f2cc68',fontSize:11,fontWeight:900,letterSpacing:'.16em'}}>EVIDENCE BOUNDARIES · WHAT THIS RECORD DOES NOT CLAIM</div><div style={{display:'grid',gap:10,marginTop:20}}>{boundaries.map((b,i)=><div key={b} style={{display:'grid',gridTemplateColumns:'30px 1fr',gap:10,padding:'13px 15px',borderLeft:'3px solid rgba(242,204,104,.75)',background:'rgba(242,204,104,.035)',color:'#b9c3c9',lineHeight:1.62}}><b style={{color:'#f2cc68'}}>{String(i+1).padStart(2,'0')}</b><span>{b}</span></div>)}</div></section>

  <section style={{marginTop:28,padding:'38px 28px',textAlign:'center',border:'1px solid rgba(113,231,255,.15)',borderRadius:24,background:'rgba(7,18,30,.72)'}}><div style={{color:'#71899a',fontSize:10,fontWeight:900,letterSpacing:'.18em'}}>FORWARD PATH · OUTCOME NOT PRE-DECLARED</div><div style={{marginTop:13,fontSize:'clamp(20px,3vw,31px)',fontWeight:950,color:'#dff7fb'}}>RE1 → Cross-check → Reconstruction → Revalidation → Patent Provenance → PAE</div><p style={{maxWidth:800,margin:'14px auto 0',color:'#91a7b5',lineHeight:1.7}}>The next stage is not pre-declared as a success. The building, evidence, authority, standing, and current conditions determine whether a proposed consequence reaches ALLOW, HOLD, DENY, or ESCALATE. PAE operating-building work remains prospective until its required boundaries are established.</p></section>
</div></main>;}