export type CorpusCategory =
  | 'BOOK'
  | 'ARTICLE'
  | 'ZENODO'
  | 'PATENT'
  | 'STANDARD'
  | 'REPOSITORY'
  | 'SITE'
  | 'IMPLEMENTATION'
  | 'CHRONOLOGY';

export type CorpusStatus =
  | 'PUBLISHED'
  | 'PUBLIC_RECORD'
  | 'FILED'
  | 'ACTIVE'
  | 'REFERENCE_IMPLEMENTATION'
  | 'LINK_PENDING'
  | 'INVENTORY_PENDING';

export type CorpusRecord = {
  id: string;
  category: CorpusCategory;
  title: string;
  date?: string;
  year: number;
  author?: string;
  platform?: string;
  status: CorpusStatus;
  identifier?: string;
  href?: string;
  description?: string;
  relationship?: string;
  sourceClass?: string;
  tags?: string[];
};

export const CORPUS_CATEGORY_LABELS: Record<CorpusCategory, string> = {
  BOOK: 'Books & Long-Form Publications',
  ARTICLE: 'Articles & Public Essays',
  ZENODO: 'Zenodo & DOI Records',
  PATENT: 'Patent Applications & Filing Lineage',
  STANDARD: 'Standards & Protocols',
  REPOSITORY: 'GitHub Repositories',
  SITE: 'Public Architecture Sites',
  IMPLEMENTATION: 'Reference Implementations',
  CHRONOLOGY: 'Chronology & Milestones',
};

export const TA14_PUBLIC_CORPUS: CorpusRecord[] = [
  {
    id: 'book-transparent-air-sop',
    category: 'BOOK',
    title: "Transparent Air's S.O.P. of Residential Air Conditioning",
    date: '2025-05-01',
    year: 2025,
    author: 'Greggory Don Butler',
    platform: 'Amazon Kindle',
    status: 'PUBLISHED',
    identifier: 'ASIN B0F74RTKTT',
    href: 'https://www.amazon.com/dp/B0F74RTKTT',
    relationship: 'Public field-origin chronology anchor for TA-14 Admissible Execution Architecture.',
    tags: ['HVAC', 'field origin', 'TA-14', 'admissible execution'],
  },
  {
    id: 'book-admissible-reality',
    category: 'BOOK',
    title: 'Admissible Reality: Why AI Governance Fails Before Execution',
    date: '2026-06-03',
    year: 2026,
    author: 'Greggory Don Butler',
    platform: 'Amazon Kindle',
    status: 'PUBLISHED',
    identifier: 'ASIN B0H3RDC8M9',
    href: 'https://www.amazon.com/dp/B0H3RDC8M9',
    relationship: 'Connects governed reality to AI execution governance.',
    tags: ['AI governance', 'admissible reality', 'execution'],
  },
  {
    id: 'book-governing-air',
    category: 'BOOK',
    title: 'Governing Air: How HVACDR Evidence Discipline Became Environmental Integrity Governance, Atmospheric Integrity Records, and the Future of Governed Air',
    date: '2026-06-04',
    year: 2026,
    author: 'Greggory Don Butler',
    platform: 'Amazon Kindle',
    status: 'PUBLISHED',
    identifier: 'ASIN B0H42DT89H',
    href: 'https://www.amazon.com/dp/B0H42DT89H',
    relationship: 'Connects HVACDR evidence discipline to Environmental Integrity Governance and Atmospheric Integrity Records.',
    tags: ['Environmental Integrity Governance', 'AIR', 'HVACDR'],
  },
  {
    id: 'book-evidence-before-intervention',
    category: 'BOOK',
    title: 'Evidence Before Intervention: The TA-14 Academy Standard for HVACDR: Sequence, Original-State Baselines, Refrigerant Entry Thresholds, Declared Determinations, and Post-Intervention Proof',
    date: '2026-06-05',
    year: 2026,
    author: 'Greggory Don Butler',
    platform: 'Amazon Kindle',
    status: 'PUBLISHED',
    identifier: 'ASIN B0H445H41R',
    href: 'https://www.amazon.com/dp/B0H445H41R',
    relationship: 'Educational field standard for evidence-before-intervention discipline.',
    tags: ['TA-14 Academy', 'HVACDR', 'determinations'],
  },
  {
    id: 'book-eig-admissible-records',
    category: 'BOOK',
    title: 'Environmental Integrity Governance: Admissible Environmental Records, Atmospheric Evidence, and the Future of Governed Environmental Reliance',
    date: '2026-06-07',
    year: 2026,
    author: 'Greggory Don Butler',
    platform: 'Amazon Kindle',
    status: 'PUBLISHED',
    identifier: 'ASIN B0H4CTZZN8',
    href: 'https://www.amazon.com/dp/B0H4CTZZN8',
    relationship: 'Long-form environmental evidence and governed-reliance record.',
    tags: ['Environmental Integrity Governance', 'evidence', 'reliance'],
  },
  {
    id: 'book-eig-air-reality',
    category: 'BOOK',
    title: 'Environmental Integrity Governance: Atmospheric Integrity Records and the Governance of Air Reality',
    date: '2026-06-10',
    year: 2026,
    author: 'Greggory Don Butler',
    platform: 'Amazon Kindle',
    status: 'PUBLISHED',
    identifier: 'ASIN B0H4RLLM5Y',
    href: 'https://www.amazon.com/dp/B0H4RLLM5Y',
    relationship: 'Long-form record for Atmospheric Integrity Records and governed air reality.',
    tags: ['AIR', 'air reality', 'environmental governance'],
  },
  {
    id: 'book-lettered-van',
    category: 'BOOK',
    title: 'The Lettered Van Illusion: What Homeowners Are Not Told About HVAC Licensing, Diagnosis, Refrigerant, and Proof',
    date: '2026-06-10',
    year: 2026,
    author: 'Greggory Don Butler',
    platform: 'Amazon Kindle',
    status: 'PUBLISHED',
    identifier: 'ASIN B0GZ26FS5S',
    href: 'https://www.amazon.com/dp/B0GZ26FS5S',
    relationship: 'Public explanation of licensing, diagnostic authority, refrigerant work, and proof.',
    tags: ['HVAC', 'licensing', 'proof'],
  },
  {
    id: 'book-hvacdr-evidence-before-intervention',
    category: 'BOOK',
    title: 'HVACDR Evidence Before Intervention: The TA-14 Academy Field Standard for Sequence, Baseline, Refrigerant Thresholds, Diagnostic Determination, and Post-Intervention Proof',
    date: '2026-06-10',
    year: 2026,
    author: 'Greggory Don Butler',
    platform: 'Amazon Kindle',
    status: 'PUBLISHED',
    identifier: 'ASIN B0H4S7MNZR',
    href: 'https://www.amazon.com/dp/B0H4S7MNZR',
    relationship: 'Formalizes the field sequence that preceded the broader admissibility architecture.',
    tags: ['TA-14 Academy', 'HVACDR', 'post-intervention proof'],
  },
  {
    id: 'book-proof-before-action',
    category: 'BOOK',
    title: 'Proof Before Action: TA-14, the EU AI Act, and the First Full-Chain Architecture for Admissible AI Execution',
    date: '2026-06-16',
    year: 2026,
    author: 'Greggory Don Butler',
    platform: 'Amazon Kindle',
    status: 'PUBLISHED',
    identifier: 'ASIN B0H5G44623',
    href: 'https://www.amazon.com/dp/B0H5G44623',
    relationship: 'Connects TA-14 full-chain governance to EU AI Act implementation questions.',
    tags: ['EU AI Act', 'AI governance', 'proof before action'],
  },
  {
    id: 'book-hvacdr-why-d',
    category: 'BOOK',
    title: 'HVACDR: Why the D Is There: Dehumidification, Seven Psychrometrics, and the Structural Correction of Environmental Control',
    date: '2026-06-20',
    year: 2026,
    author: 'Greggory Don Butler',
    platform: 'Amazon Kindle',
    status: 'PUBLISHED',
    identifier: 'ASIN B0H66DBHZB',
    href: 'https://www.amazon.com/dp/B0H66DBHZB',
    relationship: 'Technical HVACDR and environmental-control lineage focused on dehumidification and psychrometrics.',
    tags: ['HVACDR', 'dehumidification', 'psychrometrics'],
  },
  {
    id: 'book-epa-608-quick-memory',
    category: 'BOOK',
    title: 'TA-14 Academy EPA 608 Universal Quick Memory Workbook: Plain-English Review, Flashcards, Drill Questions, Scoring Sheets, and Last-Week Study Plan',
    date: '2026-06-22',
    year: 2026,
    author: 'Greggory Don Butler',
    platform: 'Amazon Kindle',
    status: 'PUBLISHED',
    identifier: 'ASIN B0H6BHJPL6',
    href: 'https://www.amazon.com/dp/B0H6BHJPL6',
    relationship: 'TA-14 Academy EPA 608 memory, drilling, scoring, and readiness workbook.',
    tags: ['TA-14 Academy', 'EPA 608', 'workbook'],
  },
  {
    id: 'book-children-schools-atmospheric-truth',
    category: 'BOOK',
    title: 'Children in Schools Need Atmospheric Truth: TA-14 Environmental Integrity Governance for Indoor Air Quality, Evidence, and Child Health',
    date: '2026-06-25',
    year: 2026,
    author: 'Greggory Don Butler',
    platform: 'Amazon Kindle',
    status: 'PUBLISHED',
    identifier: 'ASIN B0H6M38BC9',
    href: 'https://www.amazon.com/dp/B0H6M38BC9',
    relationship: 'Applies Environmental Integrity Governance to schools, indoor air quality, evidence, and child-health protection.',
    tags: ['schools', 'indoor air quality', 'Environmental Integrity Governance'],
  },
  {
    id: 'book-lungs-missing-record',
    category: 'BOOK',
    title: 'The Lung’s Missing Record: Personal Atmospheric Integrity Records and the Next Medical-Record Layer for the Human Body',
    date: '2026-06-25',
    year: 2026,
    author: 'Greggory Don Butler',
    platform: 'Amazon Kindle',
    status: 'PUBLISHED',
    identifier: 'ASIN B0H6L6R187',
    href: 'https://www.amazon.com/dp/B0H6L6R187',
    relationship: 'Defines the Personal Atmospheric Integrity Record as a governed exposure-record layer.',
    tags: ['PAIR', 'personal atmospheric integrity', 'health records'],
  },
  {
    id: 'book-air-conditioning-ta14-academy',
    category: 'BOOK',
    title: 'Air Conditioning Made Simple: The TA-14 Academy Student Textbook and Field Workbook for Learning HVACDR Without Guesswork',
    date: '2026-06-25',
    year: 2026,
    author: 'Greggory Don Butler',
    platform: 'Amazon Kindle',
    status: 'PUBLISHED',
    identifier: 'ASIN B0H6LH4S33',
    href: 'https://www.amazon.com/dp/B0H6LH4S33',
    relationship: 'TA-14 Academy student textbook and field workbook for evidence-based HVACDR learning.',
    tags: ['TA-14 Academy', 'HVACDR', 'student textbook'],
  },
  {
    id: 'book-every-gauge-touches-sky',
    category: 'BOOK',
    title: 'Every Gauge Touches the Sky: Refrigerant Loss, Time-Based HVAC Maintenance, and the Case for Evidence-Based Refrigerant Governance',
    date: '2026-06-25',
    year: 2026,
    author: 'Greggory Don Butler',
    platform: 'Amazon Kindle',
    status: 'PUBLISHED',
    identifier: 'ASIN B0H6M2VLXG',
    href: 'https://www.amazon.com/dp/B0H6M2VLXG',
    relationship: 'Connects refrigerant loss and time-based maintenance to evidence-based refrigerant governance.',
    tags: ['refrigerant', 'environmental governance', 'HVAC'],
  },
  {
    id: 'book-ta14-admissible-execution',
    category: 'BOOK',
    title: 'TA-14 Admissible Execution: The TA-14 Architecture for Governing AI, Evidence, Reality, Environment, and Consequence Before Execution',
    date: '2026-06-27',
    year: 2026,
    author: 'Greggory Don Butler',
    platform: 'Amazon Kindle',
    status: 'PUBLISHED',
    identifier: 'ASIN B0H6TF88B7',
    href: 'https://www.amazon.com/dp/B0H6TF88B7',
    relationship: 'Long-form parent-architecture publication spanning AI, evidence, reality, environment, and consequence.',
    tags: ['TA-14', 'AI governance', 'admissible execution'],
  },
  {
    id: 'book-airflow-made-simple',
    category: 'BOOK',
    title: 'Airflow Made Simple for HVAC Techs: The Practical HVAC Guide to Ducts, Pressure, Volume, Velocity, and Comfort',
    date: '2026-06-27',
    year: 2026,
    author: 'Greggory Don Butler',
    platform: 'Amazon Kindle',
    status: 'PUBLISHED',
    identifier: 'ASIN B0H6T5WJTC',
    href: 'https://www.amazon.com/dp/B0H6T5WJTC',
    relationship: 'Practical HVAC airflow guide to ducts, pressure, volume, velocity, and comfort.',
    tags: ['TA-14 Academy', 'airflow', 'HVAC'],
  },
  {
    id: 'book-electricity-made-simple',
    category: 'BOOK',
    title: 'Electricity Made Simple for HVAC Techs: The Practical HVAC Guide to Voltage, Current, Resistance, Power, Circuits, Components, Controls, and Diagnostics',
    date: '2026-06-28',
    year: 2026,
    author: 'Greggory Don Butler',
    platform: 'Amazon Kindle',
    status: 'PUBLISHED',
    identifier: 'ASIN B0H6TCB8BT',
    href: 'https://www.amazon.com/dp/B0H6TCB8BT',
    relationship: 'Practical HVAC electrical guide covering circuits, controls, components, power, and diagnostics.',
    tags: ['TA-14 Academy', 'electricity', 'HVAC'],
  },
  {
    id: 'book-air-conditioning-made-simple-techs',
    category: 'BOOK',
    title: 'Air Conditioning Made Simple for HVAC Techs: A Hands-On HVAC Workbook for Diagnostics, Airflow, Refrigeration, Charging, and Field Performance Proof',
    date: '2026-06-28',
    year: 2026,
    author: 'Greggory Don Butler',
    platform: 'Amazon Paperback',
    status: 'PUBLISHED',
    identifier: 'ASIN B0H6VN7XFN',
    href: 'https://www.amazon.com/dp/B0H6VN7XFN',
    relationship: 'Hands-on HVAC workbook covering diagnostics, airflow, refrigeration, charging, and performance proof.',
    tags: ['TA-14 Academy', 'air conditioning', 'field workbook'],
  },
  {
    id: 'book-refrigeration-made-simple',
    category: 'BOOK',
    title: 'Refrigeration Made Simple for HVAC Techs: The Practical HVAC Guide to Pressure, Temperature, Saturation, Superheat, Subcooling, Metering Devices, and Charging Discipline',
    date: '2026-06-28',
    year: 2026,
    author: 'Greggory Don Butler',
    platform: 'Amazon Kindle',
    status: 'PUBLISHED',
    identifier: 'ASIN B0GX312MW3',
    href: 'https://www.amazon.com/dp/B0GX312MW3',
    relationship: 'Practical refrigeration guide to pressure-temperature relationships, superheat, subcooling, metering devices, and charging discipline.',
    tags: ['TA-14 Academy', 'refrigeration', 'charging discipline'],
  },
  {
    id: 'book-epa-608-500',
    category: 'BOOK',
    title: 'TA-14 Academy EPA 608 Universal 500-Question Practice Exam Book: Five Full-Length Readiness Exams with Plain-English Answer Explanations, Bucket Scoring, and Critical-Miss Control',
    date: '2026-06-28',
    year: 2026,
    author: 'Greggory Don Butler',
    platform: 'Amazon Kindle',
    status: 'PUBLISHED',
    identifier: 'ASIN B0H6VBJXZV',
    href: 'https://www.amazon.com/dp/B0H6VBJXZV',
    relationship: 'Five full-length EPA 608 Universal readiness exams with explanations and scoring controls.',
    tags: ['TA-14 Academy', 'EPA 608', 'practice exams'],
  },
  {
    id: 'book-evidence-integrity-governance',
    category: 'BOOK',
    title: 'Evidence Integrity Governance: From Reality to Record to Evidence to Admissible Execution',
    date: '2026-06-28',
    year: 2026,
    author: 'Greggory Don Butler',
    platform: 'Amazon Kindle',
    status: 'PUBLISHED',
    identifier: 'ASIN B0H6V21NM8',
    href: 'https://www.amazon.com/dp/B0H6V21NM8',
    relationship: 'Long-form Evidence Integrity Governance record connecting reality, record, evidence, and admissible execution.',
    tags: ['Evidence Integrity Governance', 'reality', 'admissible execution'],
  },
  {
    id: 'book-refrigeration-student-workbook',
    category: 'BOOK',
    title: 'Refrigeration Made Simple for HVAC Techs: Student Workbook: Guided Notes, Evidence Records, Diagnostic Scenarios, Calculation Labs, Field Logs, and Capstone Proof Sheets',
    date: '2026-06-29',
    year: 2026,
    author: 'Greggory Don Butler',
    platform: 'Amazon Paperback',
    status: 'PUBLISHED',
    identifier: 'ASIN B0H6VVQJJT',
    href: 'https://www.amazon.com/dp/B0H6VVQJJT',
    relationship: 'TA-14 Academy refrigeration workbook combining technical learning with evidence records and field proof.',
    tags: ['TA-14 Academy', 'refrigeration', 'student workbook'],
  },
  {
    id: 'book-atmospheric-integrity-network',
    category: 'BOOK',
    title: 'The Atmospheric Integrity Network: How the World Can Build a Governed Memory System for the Air We Breathe',
    date: '2026-06-29',
    year: 2026,
    author: 'Greggory Don Butler',
    platform: 'Amazon Kindle',
    status: 'PUBLISHED',
    identifier: 'ASIN B0H6XJX78Q',
    href: 'https://www.amazon.com/dp/B0H6XJX78Q',
    relationship: 'Defines a governed memory system for atmospheric reality across places and time.',
    tags: ['Atmospheric Integrity Network', 'AIR', 'governed memory'],
  },
  {
    id: 'book-admissible-before-execution',
    category: 'BOOK',
    title: 'Admissible Before Execution: The TA-14 Review Manual: AI Governance, Evidence, Authority, Binding, Commit, Execution, Outcome, and New Reality Before Consequence',
    date: '2026-07-01',
    year: 2026,
    author: 'Greggory Don Butler',
    platform: 'Amazon Kindle',
    status: 'PUBLISHED',
    identifier: 'ASIN B0H78B79WB',
    href: 'https://www.amazon.com/dp/B0H78B79WB',
    relationship: 'Review-manual layer for full-chain admissibility before consequence.',
    tags: ['TA-14', 'review manual', 'admissible execution'],
  },
  {
    id: 'book-human-performance-stack',
    category: 'BOOK',
    title: 'The Human Performance Stack: Governing Human Action Before Consequence',
    date: '2026-07-01',
    year: 2026,
    author: 'Greggory Don Butler',
    platform: 'Amazon Kindle',
    status: 'PUBLISHED',
    identifier: 'ASIN B0H732NR2F',
    href: 'https://www.amazon.com/dp/B0H732NR2F',
    relationship: 'Human-action branch of consequence governance.',
    tags: ['human performance', 'consequence', 'governance'],
  },
  {
    id: 'book-air-pollution-made-admissible',
    category: 'BOOK',
    title: 'Air Pollution Made Admissible: How the Atmospheric Integrity Network Turns Pollution Reality Into Governed Evidence, Action, Execution, and Outcome',
    date: '2026-07-02',
    year: 2026,
    author: 'Greggory Don Butler',
    platform: 'Amazon Kindle',
    status: 'PUBLISHED',
    identifier: 'ASIN B0H7CQCTKT',
    href: 'https://www.amazon.com/dp/B0H7CQCTKT',
    relationship: 'Applies atmospheric integrity architecture to pollution evidence, action, execution, and outcome.',
    tags: ['air pollution', 'Atmospheric Integrity Network', 'admissible evidence'],
  },
  {
    id: 'book-america-at-250',
    category: 'BOOK',
    title: 'America at 250: The Republic for Which It Stands',
    date: '2026-07-05',
    year: 2026,
    author: 'Greggory Don Butler',
    platform: 'Amazon Kindle',
    status: 'PUBLISHED',
    identifier: 'ASIN B0H7Q16627',
    href: 'https://www.amazon.com/dp/B0H7Q16627',
    relationship: 'Public-law and civic-governance publication within the broader TA-14 institutional corpus.',
    tags: ['public law', 'civic governance', 'America at 250'],
  },
  {
    id: 'book-epa-608-pass-readiness',
    category: 'BOOK',
    title: 'TA-14 Academy EPA 608 Universal Pass-Readiness Course: A Technician-Facing Manual for Core, Type I, Type II, Type III, and Universal EPA Section 608 Readiness',
    date: '2026-06-03',
    year: 2026,
    author: 'Greggory Don Butler',
    platform: 'Amazon Kindle',
    status: 'PUBLISHED',
    identifier: 'ASIN B0GX2WLLF9',
    href: 'https://www.amazon.com/dp/B0GX2WLLF9',
    relationship: 'Technician-facing TA-14 Academy readiness manual for EPA Section 608 Universal.',
    tags: ['TA-14 Academy', 'EPA 608', 'course'],
  },

  {
    id: 'article-medium-hvac-standard',
    category: 'ARTICLE',
    title: 'HVAC Diagnostics Need a Standard',
    date: '2025-12-26',
    year: 2025,
    author: 'Greggory Don Butler',
    platform: 'Medium',
    status: 'PUBLISHED',
    href: 'https://medium.com/@greggbutlerac/hvac-diagnostics-need-a-standard-038be84916f9',
    relationship: 'Early public proof-before-action chronology anchor.',
    tags: ['HVAC', 'diagnostics', 'standard'],
  },
  {
    id: 'article-medium-hvac-proof',
    category: 'ARTICLE',
    title: "The Problem With HVAC Diagnostics Isn’t Skill. It’s Proof.",
    date: '2026-01-04',
    year: 2026,
    author: 'Greggory Don Butler',
    platform: 'Medium',
    status: 'PUBLISHED',
    href: 'https://medium.com/@greggbutlerac/the-problem-with-hvac-diagnostics-isnt-skill-it-s-proof-0395ab3345e5',
    relationship: 'Establishes proof over opinion in the public HVAC chronology.',
    tags: ['proof', 'HVAC', 'diagnostics'],
  },
  {
    id: 'article-medium-atmospheric-integrity-records',
    category: 'ARTICLE',
    title: 'Atmospheric Integrity Records: The Missing Infrastructure of Intelligent Buildings',
    date: '2026-02-25',
    year: 2026,
    author: 'Greggory Don Butler',
    platform: 'Medium',
    status: 'PUBLISHED',
    href: 'https://medium.com/@greggbutlerac/atmospheric-integrity-records-the-missing-infrastructure-of-intelligent-buildings-7e13a925f929',
    relationship: 'Public Atmospheric Integrity Records architecture record.',
    tags: ['AIR', 'intelligent buildings', 'environmental evidence'],
  },
  {
    id: 'article-medium-admissible-execution-aea',
    category: 'ARTICLE',
    title: 'Admissible Execution Architecture (AEA): The Missing Condition for Valid Action',
    date: '2026-03-31',
    year: 2026,
    author: 'Greggory Don Butler',
    platform: 'Medium',
    status: 'PUBLISHED',
    href: 'https://medium.com/@greggbutlerac/admissible-execution-architecture-aea-the-missing-condition-for-valid-action-c468714ee6ac',
    relationship: 'Explicit public naming of Admissible Execution Architecture.',
    tags: ['AEA', 'admissible execution', 'governance'],
  },
  {
    id: 'article-medium-ai-governance-route',
    category: 'ARTICLE',
    title: 'AI Governance Is Discovering the Pieces. TA-14 Governs the Route.',
    date: '2026-07-15',
    year: 2026,
    author: 'Greggory Don Butler',
    platform: 'Medium',
    status: 'PUBLISHED',
    href: 'https://medium.com/@greggbutlerac/ai-governance-is-discovering-the-pieces-ta-14-governs-the-route-159ab15a7d03',
    relationship: 'Public explanation of TA-14 as the route-complete parent architecture.',
    tags: ['AI governance', 'route', 'TA-14'],
  },
  {
    id: 'article-medium-exchange-open',
    category: 'ARTICLE',
    title: 'The TA-14 AI Governance Exchange Is Now Open: A Free Public Proving Ground for Governed AI…',
    date: '2026-07-19',
    year: 2026,
    author: 'Greggory Don Butler',
    platform: 'Medium',
    status: 'PUBLISHED',
    href: 'https://medium.com/@greggbutlerac/the-ta-14-ai-governance-exchange-is-now-open-a-free-public-proving-ground-for-governed-ai-ab23659710f5',
    relationship: 'Public launch record for the TA-14 AI Governance Exchange.',
    tags: ['TA-14 AI Governance Exchange', 'launch', 'AI governance'],
  },
  {
    id: 'article-medium-mission-control',
    category: 'ARTICLE',
    title: 'AI Governance Does Not Need Another Dashboard. It Needs Mission Control.',
    date: '2026-08-05',
    year: 2026,
    author: 'Greggory Don Butler',
    platform: 'Medium',
    status: 'PUBLISHED',
    href: 'https://medium.com/@greggbutlerac/ai-governance-does-not-need-another-dashboard-it-needs-mission-control-f8c4bbf2c0ff',
    relationship: 'Public mission-control positioning for TA-14 AI governance.',
    tags: ['AI governance', 'mission control', 'TA-14'],
  },
  {
    id: 'article-medium-human-loop',
    category: 'ARTICLE',
    title: 'Human in the Loop Is Not Governance',
    date: '2026-08-10',
    year: 2026,
    author: 'Greggory Don Butler',
    platform: 'Medium',
    status: 'PUBLISHED',
    href: 'https://medium.com/@greggbutlerac/human-in-the-loop-is-not-governance-1b51c8baa965',
    relationship: 'Introduces the TA-14 Admissible Human Intervention Architecture.',
    tags: ['human intervention', 'AI governance', 'admissible execution'],
  },

  {
    id: 'article-ab-environmental-integrity-governance',
    category: 'ARTICLE',
    title: 'Environmental Integrity Governance',
    date: '2026-02-21',
    year: 2026,
    author: 'Greggory Don Butler',
    platform: 'AutomatedBuildings.com',
    status: 'PUBLISHED',
    href: 'https://www.automatedbuildings.com/2026/02/environmental-integrity-governance/',
    relationship: 'Industry publication record for Environmental Integrity Governance.',
    tags: ['Environmental Integrity Governance', 'AutomatedBuildings'],
  },
  {
    id: 'article-ab-atmospheric-integrity-records',
    category: 'ARTICLE',
    title: 'Atmospheric Integrity Records',
    date: '2026-02-25',
    year: 2026,
    author: 'Greggory Don Butler',
    platform: 'AutomatedBuildings.com',
    status: 'PUBLISHED',
    href: 'https://www.automatedbuildings.com/2026/02/atmospheric-integrity-records/',
    relationship: 'Industry publication record for Atmospheric Integrity Records.',
    tags: ['AIR', 'AutomatedBuildings', 'atmospheric evidence'],
  },
  {
    id: 'article-ab-atmospheric-records-infrastructure',
    category: 'ARTICLE',
    title: 'Atmospheric Records as Infrastructure',
    date: '2026-02-27',
    year: 2026,
    author: 'Greggory Don Butler',
    platform: 'AutomatedBuildings.com',
    status: 'PUBLISHED',
    href: 'https://www.automatedbuildings.com/2026/02/atmospheric-records-as-infrastructure/',
    relationship: 'Industry publication on atmospheric records as infrastructure.',
    tags: ['AIR', 'infrastructure', 'AutomatedBuildings'],
  },
  {
    id: 'article-ab-interior-boundary-governance',
    category: 'ARTICLE',
    title: 'From Interior Monitoring to Boundary Governance: Why Buildings Need Exterior Atmospheric Records',
    date: '2026-03-01',
    year: 2026,
    author: 'Greggory Don Butler',
    platform: 'AutomatedBuildings.com',
    status: 'PUBLISHED',
    href: 'https://www.automatedbuildings.com/2026/03/from-interior-monitoring-to-boundary-governance-why-buildings-need-exterior-atmospheric-records/',
    relationship: 'Boundary-governance and exterior atmospheric-record chronology.',
    tags: ['boundary governance', 'atmospheric records', 'buildings'],
  },
  {
    id: 'article-ab-engineering-proof-performance',
    category: 'ARTICLE',
    title: 'Engineering Proof of Performance',
    date: '2026-03-02',
    year: 2026,
    author: 'Greggory Don Butler',
    platform: 'AutomatedBuildings.com',
    status: 'PUBLISHED',
    href: 'https://www.automatedbuildings.com/2026/03/engineering-proof-of-performance/',
    relationship: 'Industry publication on proof-based performance evidence.',
    tags: ['proof of performance', 'engineering', 'buildings'],
  },
  {
    id: 'article-ab-atmosphere-infrastructure',
    category: 'ARTICLE',
    title: 'The Atmosphere Is Infrastructure',
    date: '2026-03-12',
    year: 2026,
    author: 'Greggory Don Butler',
    platform: 'AutomatedBuildings.com',
    status: 'PUBLISHED',
    href: 'https://www.automatedbuildings.com/2026/03/the-atmosphere-is-infrastructure/',
    relationship: 'Public environmental-infrastructure doctrine record.',
    tags: ['atmosphere', 'infrastructure', 'Environmental Integrity Governance'],
  },
  {
    id: 'article-ab-era-environmental-evidence',
    category: 'ARTICLE',
    title: 'The Era of Environmental Evidence: Why Buildings Are Becoming Measurable Infrastructure',
    date: '2026-03-12',
    year: 2026,
    author: 'Greggory Don Butler',
    platform: 'AutomatedBuildings.com',
    status: 'PUBLISHED',
    href: 'https://www.automatedbuildings.com/2026/03/the-era-of-environmental-evidence-why-buildings-are-becoming-measurable-infrastructure/',
    relationship: 'Public doctrine connecting buildings to measurable environmental evidence infrastructure.',
    tags: ['environmental evidence', 'buildings', 'measurable infrastructure'],
  },
  {
    id: 'article-ab-atmospheric-memory',
    category: 'ARTICLE',
    title: 'Atmospheric Memory: The Infrastructure Humanity Didn’t Know It Was Missing',
    date: '2026-03-14',
    year: 2026,
    author: 'Greggory Don Butler',
    platform: 'AutomatedBuildings.com',
    status: 'PUBLISHED',
    href: 'https://www.automatedbuildings.com/2026/03/atmospheric-memory-the-infrastructure-humanity-didnt-know-it-was-missing/',
    relationship: 'Industry publication on atmospheric memory as missing infrastructure.',
    tags: ['atmospheric memory', 'AIR', 'infrastructure'],
  },
  {
    id: 'article-ab-standards-to-admissibility',
    category: 'ARTICLE',
    title: 'From Standards to Admissibility',
    date: '2026-03-28',
    year: 2026,
    author: 'Greggory Don Butler',
    platform: 'AutomatedBuildings.com',
    status: 'PUBLISHED',
    href: 'https://www.automatedbuildings.com/2026/03/from-standards-to-admissibility/',
    relationship: 'Public distinction between standards compliance and admissibility.',
    tags: ['standards', 'admissibility', 'governance'],
  },
  {
    id: 'article-ab-hvac-admissible-execution',
    category: 'ARTICLE',
    title: 'From Technician Burden to System-Governed Truth: Why HVACD/R Must Transition from Interpretation to Admissible Execution',
    date: '2026-03-28',
    year: 2026,
    author: 'Greggory Don Butler',
    platform: 'AutomatedBuildings.com',
    status: 'PUBLISHED',
    href: 'https://www.automatedbuildings.com/2026/03/from-technician-burden-to-system-governed-truth-why-hvacd-r-must-transition-from-interpretation-to-admissible-execution/',
    relationship: 'Industry publication explicitly connecting HVACD/R to admissible execution.',
    tags: ['HVACDR', 'admissible execution', 'system-governed truth'],
  },
  {
    id: 'article-ab-smart-building-evidence-problem',
    category: 'ARTICLE',
    title: 'The Smart Building’s Evidence Problem',
    date: '2026-05-03',
    year: 2026,
    author: 'Greggory Don Butler',
    platform: 'AutomatedBuildings.com',
    status: 'PUBLISHED',
    href: 'https://www.automatedbuildings.com/2026/05/the-smart-buildings-evidence-problem/',
    relationship: 'Industry publication on the missing governed-evidence layer in smart buildings.',
    tags: ['smart buildings', 'evidence', 'governance'],
  },
  {
    id: 'article-ab-buildings-intelligent-admissible',
    category: 'ARTICLE',
    title: 'Buildings Are Becoming Intelligent Before They Are Admissible',
    date: '2026-05-10',
    year: 2026,
    author: 'Greggory Don Butler',
    platform: 'AutomatedBuildings.com',
    status: 'PUBLISHED',
    href: 'https://www.automatedbuildings.com/2026/05/buildings-are-becoming-intelligent-before-they-are-admissible/',
    relationship: 'Industry publication applying admissibility-before-execution to intelligent buildings.',
    tags: ['intelligent buildings', 'admissibility', 'execution'],
  },
  {
    id: 'article-ab-building-health-infrastructure',
    category: 'ARTICLE',
    title: 'The Building Is Now Health Infrastructure. Continuous Monitoring Is Not Enough.',
    date: '2026-06-14',
    year: 2026,
    author: 'Greggory Don Butler',
    platform: 'AutomatedBuildings.com',
    status: 'PUBLISHED',
    href: 'https://www.automatedbuildings.com/2026/06/the-building-is-now-health-infrastructure-continuous-monitoring-is-not-enough/',
    relationship: 'Industry publication distinguishing continuous monitoring from governed health-infrastructure evidence.',
    tags: ['health infrastructure', 'continuous monitoring', 'evidence'],
  },
  {
    id: 'article-ab-filters-dashboards-not-enough',
    category: 'ARTICLE',
    title: 'When Filters, Coatings, and Dashboards Are Not Enough',
    date: '2026-06-21',
    year: 2026,
    author: 'Greggory Don Butler',
    platform: 'AutomatedBuildings.com',
    status: 'PUBLISHED',
    href: 'https://www.automatedbuildings.com/2026/06/when-filters-coatings-and-dashboards-are-not-enough/',
    relationship: 'Industry publication distinguishing products and dashboards from governed atmospheric evidence.',
    tags: ['indoor air quality', 'governance', 'atmospheric evidence'],
  },
  {
    id: 'article-ab-buildings-ai-infrastructure',
    category: 'ARTICLE',
    title: 'When Buildings Become AI Infrastructure: The EU AI Act and the End of Ungoverned Automation',
    date: '2026-06-28',
    year: 2026,
    author: 'Greggory Don Butler',
    platform: 'AutomatedBuildings.com',
    status: 'PUBLISHED',
    href: 'https://www.automatedbuildings.com/2026/06/when-buildings-become-ai-infrastructure-the-eu-ai-act-and-the-end-of-ungoverned-automation/',
    relationship: 'Connects building automation, AI infrastructure, and EU AI Act governance.',
    tags: ['EU AI Act', 'buildings', 'AI infrastructure'],
  },
  {
    id: 'article-ab-america-250',
    category: 'ARTICLE',
    title: 'Happy 250th Birthday, America: The Republic for Which It Stands',
    date: '2026-07-04',
    year: 2026,
    author: 'Greggory Don Butler',
    platform: 'AutomatedBuildings.com',
    status: 'PUBLISHED',
    href: 'https://www.automatedbuildings.com/2026/07/happy-250th-birthday-america-the-republic-for-which-it-stands/',
    relationship: 'Public civic-governance companion record to America at 250.',
    tags: ['America at 250', 'civic governance', 'public record'],
  },
  {
    id: 'article-ab-governance-exchange-arrived',
    category: 'ARTICLE',
    title: 'The Governance Exchange Has Arrived',
    date: '2026-07-19',
    year: 2026,
    author: 'Greggory Don Butler',
    platform: 'AutomatedBuildings.com',
    status: 'PUBLISHED',
    href: 'https://www.automatedbuildings.com/2026/07/the-governance-exchange-has-arrived/',
    relationship: 'Industry publication announcing the TA-14 AI Governance Exchange.',
    tags: ['TA-14 AI Governance Exchange', 'launch', 'governance'],
  },
  {
    id: 'article-ab-answer-published',
    category: 'ARTICLE',
    title: 'The Answer Was Published',
    date: '2026-07-26',
    year: 2026,
    author: 'Greggory Don Butler',
    platform: 'AutomatedBuildings.com',
    status: 'PUBLISHED',
    href: 'https://www.automatedbuildings.com/2026/07/the-answer-was-published/',
    relationship: 'Public chronology and publication-position record.',
    tags: ['public chronology', 'publication', 'TA-14'],
  },
  {
    id: 'article-ab-agent-verified-execution',
    category: 'ARTICLE',
    title: 'The Agent Has Been Verified. Now Prove the Execution.',
    date: '2026-08-01',
    year: 2026,
    author: 'Greggory Don Butler',
    platform: 'AutomatedBuildings.com',
    status: 'PUBLISHED',
    href: 'https://www.automatedbuildings.com/2026/08/the-agent-has-been-verified-now-prove-the-execution/',
    relationship: 'Public AI-governance record separating agent verification from admissible execution proof.',
    tags: ['AI governance', 'agent verification', 'execution proof'],
  },
  {
    id: 'article-ab-eu-ai-operational-boundary',
    category: 'ARTICLE',
    title: 'THE EU AI ACT CROSSES A NEW OPERATIONAL BOUNDARY',
    date: '2026-08-02',
    year: 2026,
    author: 'Greggory Don Butler',
    platform: 'AutomatedBuildings.com',
    status: 'PUBLISHED',
    href: 'https://www.automatedbuildings.com/2026/08/the-eu-ai-act-crosses-a-new-operational-boundary/',
    relationship: 'Public record connecting EU AI Act implementation to operational execution governance.',
    tags: ['EU AI Act', 'operational boundary', 'AI governance'],
  },
  {
    id: 'article-ab-building-think-act',
    category: 'ARTICLE',
    title: 'The Building Can Think. The Next Question Is Whether It Should Act.',
    date: '2026-08-09',
    year: 2026,
    author: 'Greggory Don Butler',
    platform: 'AutomatedBuildings.com',
    status: 'PUBLISHED',
    href: 'https://www.automatedbuildings.com/2026/08/the-building-can-think-the-next-question-is-whether-it-should-act/',
    relationship: 'Public record on agentic physical control and admissible action in buildings.',
    tags: ['agentic physical control', 'buildings', 'admissible execution'],
  },

  {
    id: 'patent-position-public-record',
    category: 'PATENT',
    title: 'TA-14 Patent Position and Patent Portfolio',
    year: 2026,
    author: 'Greggory Don Butler',
    platform: 'TA-14 Public Record',
    status: 'PUBLIC_RECORD',
    relationship: 'Public patent-position record preserving the filing families and protected architecture.',
    tags: ['patents', 'priority', 'architecture'],
  },
  {
    id: 'patent-63940392',
    category: 'PATENT',
    title: 'System and Method for Standardized HVAC Diagnostic Evaluation and Electrical Integrity Assessment',
    year: 2025,
    author: 'Greggory Don Butler',
    platform: 'USPTO filing record',
    status: 'FILED',
    identifier: 'US 63/940,392',
    relationship: 'Foundational proof-before-action filing.',
    tags: ['HVAC', 'diagnostics', 'proof before action'],
  },
  {
    id: 'patent-64030461',
    category: 'PATENT',
    title: 'Systems and Methods for Execution Control Based on Admissible State Validation',
    year: 2026,
    author: 'Greggory Don Butler',
    platform: 'USPTO filing record',
    status: 'FILED',
    identifier: 'US 64/030,461',
    relationship: 'Direct filing anchor for execution control based on admissible state validation.',
    tags: ['admissible state', 'execution control', 'TA-14'],
  },

  {
    id: 'repo-ta14-admissible-execution-gate',
    category: 'REPOSITORY',
    title: 'TA-14 Admissible Execution Gate',
    year: 2026,
    author: 'Greggory Don Butler',
    platform: 'GitHub',
    status: 'ACTIVE',
    href: 'https://github.com/greggbutlerac-debug/ta14-admissible-execution-gate',
    relationship: 'Primary architecture, doctrine, provenance, standards, and reference-material repository.',
    tags: ['GitHub', 'TA-14', 'architecture'],
  },
  {
    id: 'repo-ta14-exchange-platform',
    category: 'REPOSITORY',
    title: 'TA-14 Exchange Platform',
    year: 2026,
    author: 'Greggory Don Butler',
    platform: 'GitHub',
    status: 'ACTIVE',
    href: 'https://github.com/greggbutlerac-debug/ta14-exchange-platform',
    relationship: 'Application repository for the TA-14 AI Governance Exchange and Authority Governance Institution public platform.',
    tags: ['GitHub', 'TA-14 AI Governance Exchange', 'platform'],
  },

  {
    id: 'site-exchange',
    category: 'SITE',
    title: 'TA-14 AI Governance Exchange',
    year: 2026,
    platform: 'TA-14 Authority Governance Institution',
    status: 'ACTIVE',
    href: 'https://ta14authority.org',
    relationship: 'Canonical public Exchange and institutional entry point.',
    tags: ['Exchange', 'AI governance', 'institution'],
  },
  {
    id: 'site-eig',
    category: 'SITE',
    title: 'Environmental Integrity Governance',
    year: 2026,
    platform: 'Google Sites',
    status: 'PUBLIC_RECORD',
    href: 'https://sites.google.com/view/environmental-integrity-gover/home',
    relationship: 'Canonical public Environmental Integrity Governance site.',
    tags: ['Environmental Integrity Governance', 'AIR', 'environmental evidence'],
  },
  {
    id: 'site-pair',
    category: 'SITE',
    title: 'Personal Atmospheric Integrity Record',
    year: 2026,
    platform: 'Google Sites',
    status: 'PUBLIC_RECORD',
    href: 'https://sites.google.com/view/personal-atmospheric-integrity/home',
    relationship: 'Public PAIR architecture site.',
    tags: ['PAIR', 'atmospheric exposure', 'personal record'],
  },

  {
    id: 'chronology-ta14-public-doctrine',
    category: 'CHRONOLOGY',
    title: 'TA-14 Public Doctrine & Architecture Chronology',
    year: 2026,
    author: 'Greggory Don Butler',
    platform: 'TA-14 Public Record',
    status: 'PUBLIC_RECORD',
    relationship: 'Chronology from Transparent Air field origin through the parent TA-14 Admissible Execution Architecture and its applied domains.',
    tags: ['chronology', 'origin', 'TA-14'],
  },
  {
    id: 'chronology-origin-may-2025',
    category: 'CHRONOLOGY',
    title: 'May 1, 2025 Public Book Anchor — Transparent Air’s S.O.P. of Residential Air Conditioning',
    date: '2025-05-01',
    year: 2025,
    author: 'Greggory Don Butler',
    platform: 'Public publication record',
    status: 'PUBLIC_RECORD',
    relationship: 'Public origin anchor for the Chain of Eight and admissibility-before-execution architecture.',
    tags: ['May 1 2025', 'origin', 'Chain of Eight'],
  },
];

export const CORPUS_COUNTS = TA14_PUBLIC_CORPUS.reduce(
  (acc, record) => {
    acc[record.category] += 1;
    return acc;
  },
  {
    BOOK: 0,
    ARTICLE: 0,
    ZENODO: 0,
    PATENT: 0,
    STANDARD: 0,
    REPOSITORY: 0,
    SITE: 0,
    IMPLEMENTATION: 0,
    CHRONOLOGY: 0,
  } as Record<CorpusCategory, number>,
);

export const CORPUS_TOTAL = TA14_PUBLIC_CORPUS.length;

export function getCorpusRecord(id: string) {
  return TA14_PUBLIC_CORPUS.find((record) => record.id === id);
}
