import type { CorpusRecord } from './corpus';

export const TA14_REFERENCE_IMPLEMENTATIONS: CorpusRecord[] = [
  {
    id: 'implementation-ai-governance-exchange',
    category: 'IMPLEMENTATION',
    title: 'TA-14 AI Governance Exchange',
    year: 2026,
    author: 'Greggory Don Butler',
    platform: 'TA-14 Authority Governance Institution',
    status: 'REFERENCE_IMPLEMENTATION',
    href: 'https://www.ta14authority.org/workspace/ai-governance',
    description: 'Operational public workspace implementing governance registration, review, evidence, artifact, verification, Academy, and institutional participation pathways.',
    relationship: 'Reference institutional implementation of the TA-14 admissible-execution governance model.',
    sourceClass: 'Operational web implementation',
    tags: ['TA-14 AI Governance Exchange', 'AI governance', 'institution', 'reference implementation'],
  },
  {
    id: 'implementation-execution-artifact-registry',
    category: 'IMPLEMENTATION',
    title: 'TA-14 Execution Artifact Registry',
    year: 2026,
    author: 'Greggory Don Butler',
    platform: 'TA-14 AI Governance Exchange',
    status: 'REFERENCE_IMPLEMENTATION',
    href: 'https://www.ta14authority.org/artifacts/registry',
    description: 'Operational registry for governance-linked execution artifacts with registration gating, canonical record validation, integrity preservation, verification support, correction/challenge handling, disclosure controls, signing, and portfolio export.',
    relationship: 'Implements governed artifact preservation and publication inside the TA-14 Exchange.',
    sourceClass: 'Operational registry implementation',
    tags: ['Execution Artifact Registry', 'artifact governance', 'integrity', 'verification', 'reference implementation'],
  },
  {
    id: 'implementation-route-replay',
    category: 'IMPLEMENTATION',
    title: 'TA-14 Route Replay & Verification Workspace',
    year: 2026,
    author: 'Greggory Don Butler',
    platform: 'TA-14 AI Governance Exchange',
    status: 'REFERENCE_IMPLEMENTATION',
    href: 'https://www.ta14authority.org/workspace/replay',
    description: 'Operational replay surface for reconstructing and inspecting governed execution routes from preserved evidence and route state.',
    relationship: 'Reference implementation supporting TA-14 replay, verification, route reconstruction, and outcome correspondence concepts.',
    sourceClass: 'Operational verification implementation',
    tags: ['replay', 'verification', 'route reconstruction', 'TA-14 RVS', 'TA-14 IRRS'],
  },
  {
    id: 'implementation-verification-engine',
    category: 'IMPLEMENTATION',
    title: 'TA-14 Execution Artifact Verification Engine',
    year: 2026,
    author: 'Greggory Don Butler',
    platform: 'TA-14 AI Governance Exchange',
    status: 'REFERENCE_IMPLEMENTATION',
    href: 'https://www.ta14authority.org/workspace/verify',
    description: 'Operational verification pathway for inspecting execution artifacts and preserved governance evidence against declared record and verification conditions.',
    relationship: 'Implements artifact verification as a distinct governed function rather than treating publication as automatic validation.',
    sourceClass: 'Operational verification implementation',
    tags: ['verification engine', 'execution artifacts', 'evidence', 'reference implementation'],
  },
  {
    id: 'implementation-governance-registry',
    category: 'IMPLEMENTATION',
    title: 'TA-14 Governance Registry',
    year: 2026,
    author: 'Greggory Don Butler',
    platform: 'TA-14 Authority Governance Institution',
    status: 'REFERENCE_IMPLEMENTATION',
    href: 'https://www.ta14authority.org/registry',
    description: 'Operational public registry preserving governance identities, declared scope, claims and non-claims, evidence, status, version history, and governed public records.',
    relationship: 'Reference implementation of governed identity and public governance registration inside the TA-14 institution.',
    sourceClass: 'Operational registry implementation',
    tags: ['governance registry', 'governance identity', 'public record', 'reference implementation'],
  },
  {
    id: 'implementation-corpus-integrity',
    category: 'IMPLEMENTATION',
    title: 'TA-14 Public Corpus Integrity Monitor',
    year: 2026,
    author: 'Greggory Don Butler',
    platform: 'TA-14 Authority Governance Institution',
    status: 'REFERENCE_IMPLEMENTATION',
    href: 'https://www.ta14authority.org/foundation/public-corpus/integrity',
    description: 'Operational integrity surface for inspecting the completeness and structural health of the institutional public corpus.',
    relationship: 'Self-governance implementation applying corpus-integrity review to TA-14’s own institutional memory.',
    sourceClass: 'Institutional self-audit implementation',
    tags: ['corpus integrity', 'self-governance', 'institutional memory', 'reference implementation'],
  },
];
