"use client";
import {useMemo,useState} from "react";

type Props={step:number;world:"inside"|"outside";onScore:(delta:number,message:string)=>void};
type Target={id:string;label:string;icon:string;from:number;instruction:string;good:string;x:string;y:string};
const TARGETS:Target[]=[
 {id:"arrival",label:"START HERE",icon:"▶",from:1,instruction:"Meet the homeowner. Listen to the complaint. Establish the starting condition before making a determination.",good:"ARRIVAL PROTOCOL COMPLETE",x:"50%",y:"48%"},
 {id:"heat-type",label:"IDENTIFY HEAT TYPE",icon:"♨",from:2,instruction:"Identify what equipment you are actually servicing: electric heat / air handler or gas furnace. Equipment reality comes before the next service action.",good:"HEATING EQUIPMENT TYPE IDENTIFIED",x:"50%",y:"52%"},
 {id:"step3",label:"STEP 3",icon:"03",from:3,instruction:"Continue only with the canonical TA-14-Step sequence. This node is being held from invented detail until its Academy wording is verified.",good:"STEP 3 NODE ACKNOWLEDGED",x:"50%",y:"52%"},
 {id:"step4",label:"STEP 4",icon:"04",from:4,instruction:"Continue only with the canonical TA-14-Step sequence. No substitute sequence will be invented for this arcade.",good:"STEP 4 NODE ACKNOWLEDGED",x:"50%",y:"52%"},
 {id:"step5",label:"STEP 5",icon:"05",from:5,instruction:"Continue only with the canonical TA-14-Step sequence. Academy source controls the game logic.",good:"STEP 5 NODE ACKNOWLEDGED",x:"50%",y:"52%"},
 {id:"step6",label:"STEP 6",icon:"06",from:6,instruction:"Continue only with the canonical TA-14-Step sequence. Academy source controls the game logic.",good:"STEP 6 NODE ACKNOWLEDGED",x:"50%",y:"52%"},
 {id:"step7",label:"STEP 7",icon:"07",from:7,instruction:"Continue only with the canonical TA-14-Step sequence. Academy source controls the game logic.",good:"STEP 7 NODE ACKNOWLEDGED",x:"50%",y:"52%"},
 {id:"step8",label:"STEP 8",icon:"08",from:8,instruction:"Continue only with the canonical TA-14-Step sequence. Academy source controls the game logic.",good:"STEP 8 NODE ACKNOWLEDGED",x:"50%",y:"52%"},
 {id:"step9",label:"STEP 9",icon:"09",from:9,instruction:"Continue only with the canonical TA-14-Step sequence. Academy source controls the game logic.",good:"STEP 9 NODE ACKNOWLEDGED",x:"50%",y:"52%"},
 {id:"step10",label:"STEP 10",icon:"10",from:10,instruction:"Continue only with the canonical TA-14-Step sequence. Academy source controls the game logic.",good:"STEP 10 NODE ACKNOWLEDGED",x:"50%",y:"52%"},
 {id:"step11",label:"STEP 11",icon:"11",from:11,instruction:"Continue only with the canonical TA-14-Step sequence. Academy source controls the game logic.",good:"STEP 11 NODE ACKNOWLEDGED",x:"50%",y:"52%"},
 {id:"step12",label:"STEP 12",icon:"12",from:12,instruction:"Continue only with the canonical TA-14-Step sequence. Academy source controls the game logic.",good:"STEP 12 NODE ACKNOWLEDGED",x:"50%",y:"52%"},
 {id:"step13",label:"STEP 13",icon:"13",from:13,instruction:"Continue only with the canonical TA-14-Step sequence. Refrigerant-side contact must remain governed by the established evidence threshold.",good:"STEP 13 NODE ACKNOWLEDGED",x:"50%",y:"52%"},
 {id:"step14",label:"STEP TA-14",icon:"✓",from:14,instruction:"Complete the canonical TA-14-Step sequence and preserve the post-intervention performance record.",good:"TA-14-STEP RUN COMPLETE",x:"50%",y:"52%"},
];
export default function EquipmentArcade({step,onScore}:Props){const[hit,setHit]=useState(false);const target=useMemo(()=>TARGETS.find(t=>t.from===step)!,[step]);function fire(){onScore(300,`CORRECT ACTION // ${target.good}`);setHit(true);setTimeout(()=>setHit(false),450)}return <div className="equipmentArcade"><div className="guidedMission"><small>WHAT DO I DO?</small><strong>STEP {step===14?"TA-14":String(step).padStart(2,"0")}</strong><p>{target.instruction}</p><span>CLICK THE GLOWING {target.label}</span></div><button onClick={fire} className={`equipmentTarget live ${hit?"hit":""}`} style={{left:target.x,top:target.y}}><span>{target.icon}</span><b>{target.label}</b><em>CLICK ME</em></button><div className="equipmentHint">ONE ACTIVE TASK AT A TIME // EQUIPMENT REALITY BEFORE ACTION</div><style jsx>{`.equipmentArcade{position:absolute;inset:0;z-index:12}.guidedMission{position:absolute;z-index:6;left:50%;top:16px;transform:translateX(-50%);width:min(560px,72%);padding:12px 16px;border:1px solid #5ceaff88;border-radius:8px;background:linear-gradient(180deg,#06182ff2,#03101ef2);box-shadow:0 0 34px #40dfff22;text-align:center}.guidedMission small{display:block;color:#65eaff;font:1000 7px ui-monospace;letter-spacing:.18em}.guidedMission strong{display:block;margin-top:3px;color:#75ffb3;font:1000 14px ui-monospace}.guidedMission p{margin:6px auto;color:#d5e6ed;font-size:11px;line-height:1.45}.guidedMission span{display:inline-block;padding:5px 9px;border:1px solid #63ffad55;background:#092519;color:#7affb6;font:1000 7px ui-monospace;letter-spacing:.12em}.equipmentTarget{position:absolute;transform:translate(-50%,-50%);width:124px;height:124px;border-radius:50%;border:3px solid #6affae;background:radial-gradient(circle,#103c35,#071d29 55%,#020914);color:#8affbf;cursor:pointer;box-shadow:0 0 0 8px #06140faa,0 0 34px #54ff9b88,0 0 70px #38dfff44;animation:targetLive .75s ease-in-out infinite alternate}.equipmentTarget span{display:block;font:1000 30px ui-monospace}.equipmentTarget b{display:block;margin-top:4px;font:1000 8px ui-monospace}.equipmentTarget em{display:block;margin-top:6px;color:#fff;font:1000 7px ui-monospace;font-style:normal}.equipmentTarget.hit{animation:targetHit .45s ease-out}.equipmentHint{position:absolute;left:50%;bottom:34px;transform:translateX(-50%);padding:7px 11px;border:1px solid #5aeaff33;background:#020b15e8;color:#88b8c7;font:900 7px ui-monospace;letter-spacing:.12em;white-space:nowrap}@keyframes targetLive{to{box-shadow:0 0 0 12px #07170faa,0 0 48px #54ff9baa,0 0 90px #38dfff66}}@keyframes targetHit{35%{transform:translate(-50%,-50%) scale(1.3);filter:brightness(2)}}`}</style></div>}
