'use client';
import Link from 'next/link';
import {useMemo,useState} from 'react';

import {showroomCollections as collections, showroomRooms as rooms} from './showroomRegistry';
export default function Showrooms(){
 const [q,setQ]=useState(''); const [cat,setCat]=useState('ALL');
 const visible=useMemo(()=>rooms.filter(r=>(cat==='ALL'||r[2]===cat)&&(!q||r.join(' ').toLowerCase().includes(q.toLowerCase()))),[q,cat]);
 return <main className="page"><div className="shell">
  <nav><Link href="/">← TA14 EXCHANGE</Link><b>SHOWROOM LIBRARY · INVENTORY V1</b></nav>
  <header><p>PUBLIC TECHNICAL LIBRARY</p><h1>FIND YOUR<br/><em>SHOWROOM.</em></h1><p className="lead">One searchable door into TA14 public teaching, examination and presentation surfaces. A showroom teaches or examines. Artifacts prove or preserve. Indexes organize. Registry records establish identity or status.</p></header>
  <section className="search"><label>SEARCH ALL SHOWROOMS<input value={q} onChange={e=>setQ(e.target.value)} placeholder="Try: Aaron Hastings, Palestine, radon, ONUMA, HVAC, BACnet, AI, authority, mold…"/></label><div className="filters"><button onClick={()=>setCat('ALL')} className={cat==='ALL'?'on':''}>ALL</button>{collections.map(c=><button key={c[0]} onClick={()=>setCat(c[0])} className={cat===c[0]?'on':''}>{c[0]}</button>)}</div><b>{visible.length} MATCH{visible.length===1?'':'ES'}</b></section>
  <section className="grid">{visible.map(r=><Link href={r[1]} key={r[1]} className="card"><small>{r[2]}</small><h2>{r[0]}</h2><p>{r[3].split(' ').slice(0,8).join(' · ')}</p><b>ENTER SHOWROOM →</b></Link>)}</section>
  <section className="collections"><p>PRIMARY COLLECTIONS</p>{collections.map(c=><button key={c[0]} onClick={()=>{setCat(c[0]);setQ('');scrollTo({top:0,behavior:'smooth'})}}><b>{c[0]}</b><span>{c[1]}</span></button>)}</section>
  <footer>TA14 AUTHORITY GOVERNANCE INSTITUTION · SHOWROOM LIBRARY · INVENTORY V1<br/><span>One substantive public room = one showroom. Language variants and continuation surfaces do not multiply the count.</span></footer>
 </div><style jsx>{`
 .page{min-height:100vh;background:#03090e;color:#eaf5f7;font-family:Arial,sans-serif}.shell{max-width:1320px;margin:auto;padding:28px}nav{display:flex;justify-content:space-between;border-bottom:1px solid #17313b;padding-bottom:18px;font-size:12px;letter-spacing:.12em}nav a{color:#91e8f5;text-decoration:none}header{padding:70px 0 38px}header>p:first-child,.collections>p{color:#64dceb;font-weight:900;letter-spacing:.2em;font-size:11px}h1{font-size:clamp(58px,10vw,128px);line-height:.82;letter-spacing:-.07em;margin:18px 0}h1 em{color:#75efba;font-style:normal}.lead{max-width:850px;color:#9db3bc;font-size:19px;line-height:1.65}.search{position:sticky;top:0;background:#03090ef2;backdrop-filter:blur(14px);z-index:5;padding:18px 0;border-block:1px solid #17313b}.search label{font-size:10px;letter-spacing:.16em;font-weight:900}.search input{display:block;width:100%;box-sizing:border-box;margin:9px 0 13px;padding:17px;border-radius:12px;border:1px solid #244a57;background:#07141b;color:white;font-size:16px}.filters{display:flex;gap:7px;overflow:auto;padding-bottom:8px}.filters button{white-space:nowrap;background:#07141b;color:#86a2ad;border:1px solid #17313b;border-radius:999px;padding:8px 11px;font-size:9px;font-weight:900}.filters button.on{color:#03100c;background:#75efba;border-color:#75efba}.search>b{font-size:10px;color:#75efba}.grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(270px,1fr));gap:14px;padding:28px 0 70px}.card{min-height:190px;padding:22px;border:1px solid #17313b;border-radius:16px;background:#061117;text-decoration:none;color:inherit;display:flex;flex-direction:column}.card:hover{border-color:#64dceb;transform:translateY(-2px)}.card small{color:#64dceb;font-weight:900;letter-spacing:.12em;font-size:9px}.card h2{font-size:24px;line-height:1.05;margin:18px 0 10px}.card p{color:#718c97;font-size:11px;line-height:1.6;text-transform:uppercase}.card>b{margin-top:auto;color:#75efba;font-size:11px}.collections{border-top:1px solid #17313b;padding:55px 0}.collections button{width:100%;display:grid;grid-template-columns:minmax(240px,1fr) 2fr;text-align:left;padding:18px 0;border:0;border-bottom:1px solid #122832;background:none;color:inherit}.collections b{font-size:13px;color:#eaf5f7}.collections span{color:#78919b}footer{border-top:1px solid #17313b;padding:30px 0 50px;color:#6f8993;font-size:10px;letter-spacing:.1em;line-height:1.8}footer span{letter-spacing:0}@media(max-width:700px){.collections button{grid-template-columns:1fr;gap:7px}nav{gap:20px}h1{font-size:60px}}
 `}</style></main>
}