"use client";

import Link from "next/link";
import { useEffect, useState } from "react";

type Item={name:string;count:number};
type Stage={stage:string;visitors:number};
type Journey={visitId:string;firstSeen:string;entryPage:string|null;source:string;commercialEntryPage:string|null;lastStage:string|null;nextDestination:string|null;timeToNextActionSeconds:number|null;revenueEvidence:string};
type Data={generatedAt:string;windowDays:number;boundary:string;summary:{commercialJourneys:number;attributedPaidJourneys:number};stageCounts:Stage[];entryPages:Item[];sources:Item[];dropoffs:Item[];journeys:Journey[]};

function Panel({title,items}:{title:string;items:Item[]}){return <section className="rounded-2xl border border-white/10 bg-white/[.035] p-5"><h2 className="mb-4 text-sm font-semibold uppercase tracking-[.18em] text-cyan-300">{title}</h2><div className="space-y-2">{items.length?items.slice(0,12).map(x=><div key={x.name} className="flex justify-between gap-4 border-b border-white/5 pb-2 text-sm"><span className="truncate text-slate-300">{x.name}</span><strong>{x.count}</strong></div>):<p className="text-sm text-slate-500">No observed signal yet.</p>}</div></section>}

export default function CommercialIntelligencePage(){
 const[data,setData]=useState<Data|null>(null);const[error,setError]=useState("");
 useEffect(()=>{fetch("/api/mission-control/commercial-intelligence",{cache:"no-store"}).then(async r=>{if(!r.ok)throw new Error(r.status===401?"Sign in to view this private surface.":r.status===403?"Owner access required.":"Commercial intelligence unavailable.");return r.json()}).then(setData).catch(e=>setError(e.message))},[]);
 return <main className="min-h-screen bg-[#02060c] px-5 py-8 text-white">
  <div className="mx-auto max-w-7xl">
   <header className="mb-8 flex flex-wrap items-center justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-[.24em] text-cyan-300">TA-14 Mission Control</p><h1 className="mt-2 text-3xl font-semibold">Commercial Intelligence</h1><p className="mt-2 max-w-3xl text-sm text-slate-400">Visitor → source → entry page → commercial stage → next action → attributed revenue evidence.</p></div><nav className="flex gap-2"><Link className="rounded-xl border border-white/10 px-4 py-2 text-sm" href="/workspace/mission-control/seo-intelligence">SEO Intelligence</Link><Link className="rounded-xl border border-cyan-400/30 px-4 py-2 text-sm" href="/workspace/mission-control">Mission Control</Link></nav></header>
   {error?<div className="rounded-2xl border border-amber-400/20 bg-amber-400/5 p-5 text-sm text-amber-100">{error}</div>:null}
   {data?<><section className="mb-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><article className="rounded-2xl border border-white/10 bg-white/[.035] p-5"><span className="text-3xl font-semibold">{data.summary.commercialJourneys}</span><p className="mt-2 text-xs uppercase tracking-wider text-slate-400">Commercial journeys</p></article><article className="rounded-2xl border border-white/10 bg-white/[.035] p-5"><span className="text-3xl font-semibold">{data.summary.attributedPaidJourneys}</span><p className="mt-2 text-xs uppercase tracking-wider text-slate-400">Attributed paid journeys</p></article>{data.stageCounts.slice(0,2).map(s=><article key={s.stage} className="rounded-2xl border border-white/10 bg-white/[.035] p-5"><span className="text-3xl font-semibold">{s.visitors}</span><p className="mt-2 text-xs uppercase tracking-wider text-slate-400">{s.stage.replaceAll("_"," ")}</p></article>)}</section>
   <section className="mb-6 grid gap-4 lg:grid-cols-3"><Panel title="Entry pages" items={data.entryPages}/><Panel title="Acquisition sources" items={data.sources}/><Panel title="Last observed stage" items={data.dropoffs}/></section>
   <section className="rounded-2xl border border-white/10 bg-white/[.035] p-5"><div className="mb-4"><p className="text-xs font-semibold uppercase tracking-[.18em] text-cyan-300">Journey receipts</p><h2 className="mt-1 text-xl font-semibold">Observed commercial paths</h2></div><div className="overflow-x-auto"><table className="w-full min-w-[900px] text-left text-sm"><thead className="text-xs uppercase tracking-wider text-slate-500"><tr><th className="pb-3">First seen</th><th>Entry page</th><th>Source</th><th>Commercial entry</th><th>Last stage</th><th>Next</th><th>Time</th><th>Revenue</th></tr></thead><tbody>{data.journeys.map(j=><tr key={j.visitId} className="border-t border-white/5"><td className="py-3 pr-4 text-slate-400">{new Date(j.firstSeen).toLocaleString()}</td><td className="pr-4">{j.entryPage||"—"}</td><td className="pr-4">{j.source}</td><td className="pr-4">{j.commercialEntryPage||"—"}</td><td className="pr-4">{j.lastStage?.replaceAll("_"," ")||"—"}</td><td className="max-w-[220px] truncate pr-4">{j.nextDestination||"—"}</td><td className="pr-4">{j.timeToNextActionSeconds==null?"—":j.timeToNextActionSeconds+"s"}</td><td>{j.revenueEvidence}</td></tr>)}</tbody></table>{!data.journeys.length?<p className="py-6 text-sm text-slate-500">No qualifying commercial journey has been observed yet.</p>:null}</div></section>
   <section className="mt-6 rounded-2xl border border-cyan-400/15 bg-cyan-400/[.035] p-5 text-sm text-slate-300"><strong className="text-white">Evidence boundary</strong><p className="mt-2">{data.boundary}</p></section></>:<p className="text-sm text-slate-500">{error?"":"Loading commercial intelligence…"}</p>}
  </div>
 </main>
}