import Link from "next/link";
import { notFound } from "next/navigation";

const STEPS = [
  {title:"Approaching & Opening the Air Handler",phase:"7 IN",purpose:"Preserve the equipment's starting reality before disturbance.",do:["Confirm the service call and operating condition before opening the cabinet.","Capture equipment identity, thermostat state, visible condition, and baseline evidence.","Open the air handler deliberately and preserve what is found before changing it."],dont:["Do not diagnose from the complaint alone.","Do not disturb the equipment before the baseline exists.","Do not turn an early observation into a final cause statement."],proof:"A preserved, attributable pre-disturbance record showing what the technician actually encountered."},
  {title:"Heat Kit & Furnace Operation Check",phase:"7 IN",purpose:"Verify the indoor heat-producing and furnace-related operating path without allowing one normal observation to clear the whole system.",do:["Identify the installed heat configuration and applicable components.","Verify relevant operation and electrical condition within the service scope.","Record material readings and abnormal conditions before intervention."],dont:["Do not assume installed components are healthy because the system energizes.","Do not bypass safety controls to accelerate the call.","Do not claim complete electrical integrity from one reading."],proof:"A bounded operating record tied to the components and conditions actually tested."},
  {title:"Blower Motor & Airflow Integrity",phase:"7 IN",purpose:"Establish whether the indoor air-moving system can support reliable downstream conclusions.",do:["Inspect blower condition and configuration.","Measure airflow-related conditions appropriate to the equipment and call.","Preserve restrictions, settings, and readings that affect system interpretation."],dont:["Do not use refrigerant-side evidence as if airflow were already proven acceptable.","Do not replace a motor merely because airflow is low.","Do not erase the original condition before documenting it."],proof:"Evidence showing whether the indoor airflow condition is sufficiently known to support the next decision."},
  {title:"Evaporator Coil Inspection",phase:"7 IN",purpose:"Observe the evaporator as evidence, not as an invitation to overclaim.",do:["Inspect coil condition, temperature pattern, cleanliness, and visible restrictions.","Photograph material findings before cleaning or disturbance.","Keep IAQ or biological identification claims inside actual qualification and evidence."],dont:["Do not call unidentified material mold.","Do not infer refrigerant charge from appearance alone.","Do not clean away evidence before preserving the original state."],proof:"A preserved evaporator-condition record that can be compared with the rest of the service evidence."},
  {title:"Metering Device Identification",phase:"7 IN",purpose:"Know what refrigerant-control architecture is actually present before interpreting refrigeration behavior.",do:["Identify the metering-device type where reasonably accessible and supportable.","Confirm equipment/application information relevant to interpretation.","Carry uncertainty forward when identification cannot be established."],dont:["Do not assume TXV, piston, or another device from habit.","Do not apply a charging interpretation that depends on an unverified device type.","Do not manufacture certainty when the configuration remains unknown."],proof:"A supported equipment/configuration fact or an explicit unresolved state."},
  {title:"Filter & Return Airflow Check",phase:"7 IN",purpose:"Preserve and evaluate the return-air path before changing a condition that may govern performance.",do:["Inspect filter condition, return restrictions, grilles, and accessible return path.","Capture the original condition before replacement or correction.","Relate the observation to measured airflow evidence before assigning cause."],dont:["Do not replace the filter first and call the improved state the baseline.","Do not claim a dirty filter caused the complaint from appearance alone.","Do not turn the observation into an automatic upgrade sale."],proof:"A before-intervention return-air record connected to the measured operating condition."},
  {title:"Air Handler Reassembly Check",phase:"7 IN",purpose:"Close the indoor sequence without creating a new fault or losing evidence continuity.",do:["Confirm panels, fasteners, wiring, drains, and disturbed components are returned to the intended state.","Verify that required indoor evidence has been captured.","Carry unresolved questions forward rather than silently closing them."],dont:["Do not leave the indoor unit mechanically incomplete.","Do not let reassembly overwrite what was observed before intervention.","Do not convert completion of the indoor sequence into a final system diagnosis."],proof:"A documented indoor closure state and a clean handoff into the 7 OUT sequence."},
  {title:"Condenser Visual Inspection & Controlled Panel Opening",phase:"7 OUT",purpose:"Establish outdoor reality before cleaning, opening, adjusting, or recommending work.",do:["Record ambient condition, equipment identity, operating state, and visible condenser condition.","Capture the undisturbed coil and cabinet before intervention.","Open panels in a controlled manner consistent with electrical and mechanical safety."],dont:["Do not clean first.","Do not diagnose from debris alone.","Do not use appearance as automatic replacement authority."],proof:"A preserved outdoor baseline showing the condenser as encountered."},
  {title:"Start Components, Capacitors & Compressor Insulation Verification",phase:"7 OUT",purpose:"Verify the electrical start path and material component condition before attributing load or starting behavior to a failed major component.",do:["Inspect and test applicable start components and capacitors.","Evaluate compressor insulation condition with appropriate methods and safety controls.","Record nameplate/component identity and material readings."],dont:["Do not condemn a compressor from a single symptom.","Do not treat a capacitor's appearance as a complete test.","Do not bypass protective controls to force an outcome."],proof:"A component-specific electrical evidence record supporting or limiting the next determination."},
  {title:"Compressor & Fan Motor Amp Draw Verification",phase:"7 OUT",purpose:"Interpret electrical load in the operating context that produced it.",do:["Measure compressor and fan-motor current under documented conditions.","Compare readings to equipment information and the known airflow/heat-rejection state.","Preserve abnormal load as evidence to be retested after any authorized correction."],dont:["Do not equate elevated current with compressor failure by itself.","Do not discard a reading merely because it remains below a maximum rating.","Do not ignore the conditions under which the reading was produced."],proof:"Context-bound electrical load evidence that can survive comparison after intervention."},
  {title:"Condenser Panel Reassembly & Mechanical Integrity Check",phase:"7 OUT",purpose:"Restore the equipment's mechanical and electrical enclosure integrity before proceeding.",do:["Return panels, fasteners, wiring placement, and guards to their intended state.","Confirm nothing introduced during testing creates a new hazard or performance condition.","Preserve evidence of any material defect that cannot be corrected within scope."],dont:["Do not leave panels loose for convenience.","Do not normalize missing hardware or damaged enclosure conditions.","Do not allow test access to become the final operating configuration."],proof:"A documented, mechanically complete condenser state following controlled access."},
  {title:"Condenser Coil Cleaning & Airflow Restoration",phase:"7 OUT",purpose:"Intervene only where the pre-intervention record supports the correction, then establish a new testable condition.",do:["Preserve the restricted condition before cleaning.","Perform the bounded cleaning/restoration authorized by the evidence and scope.","Allow operation to stabilize before drawing post-intervention conclusions."],dont:["Do not clean before baseline capture.","Do not bundle unsupported refrigerant or component work into the intervention.","Do not claim success before comparable post-state evidence exists."],proof:"A traceable before/intervention/after chain for the condenser airflow correction."},
  {title:"Refrigerant Charge Approximation",phase:"7 OUT",purpose:"Use refrigerant evidence only after governing conditions are sufficiently controlled and without pretending an approximation is more precise than it is.",do:["Confirm that airflow and heat-rejection conditions permit meaningful interpretation.","Use the applicable equipment data, metering-device context, temperatures, pressures, and operating conditions.","State the conclusion at the level the evidence supports and preserve uncertainty."],dont:["Do not add refrigerant because a symptom resembles low charge.","Do not treat one pressure or temperature as a complete charge determination.","Do not let an approximation become an unsupported exact claim."],proof:"A bounded refrigerant-condition determination tied to known operating conditions and measurement context."},
  {title:"Condensate Management Verification & System Closure",phase:"7 OUT",purpose:"Close the service call by proving the system's post-intervention condition against the preserved starting record.",do:["Verify condensate management and the final operating condition within scope.","Collect comparable post-intervention readings and images.","Explain what improved, what did not, and what remains unresolved."],dont:["Do not call the system completely fixed because selected readings improved.","Do not erase unresolved conditions from the final record.","Do not close without a post-performance comparison."],proof:"A post-intervention performance record that supports the final outcome claim without exceeding it."},
] as const;

export function generateStaticParams(){return STEPS.map((_,i)=>({step:String(i+1)}));}

export default async function StepPage({params}:{params:Promise<{step:string}>}){
  const {step}=await params; const n=Number(step); if(!Number.isInteger(n)||n<1||n>14)notFound(); const item=STEPS[n-1];
  const prev=n>1?`/exchange/hvac/14-step/${n-1}`:null; const next=n<14?`/exchange/hvac/14-step/${n+1}`:"/atlas-14-step-field-ops-lab";
  return <main className="page"><div className="glow"/><div className="shell">
    <nav><Link href="/academy/hvac">TA-14 ACADEMY // HVAC</Link><Link href="/atlas-14-step-field-ops-lab">FIELD OPS LAB</Link></nav>
    <header><div className="phase">{item.phase} // STEP {String(n).padStart(2,"0")} OF 14</div><div className="number">{String(n).padStart(2,"0")}</div><h1>{item.title}</h1><p>{item.purpose}</p></header>
    <section className="doctrine"><small>GOVERNING IDEA</small><strong>Know what to do. Know what not to do. Preserve enough evidence to prove why.</strong></section>
    <div className="grid"><section><span className="tag green">DO</span><h2>Required field discipline</h2>{item.do.map((x,i)=><article key={x}><b>{String(i+1).padStart(2,"0")}</b><p>{x}</p></article>)}</section><section><span className="tag gold">DO NOT</span><h2>Boundary conditions</h2>{item.dont.map((x,i)=><article key={x}><b>{String(i+1).padStart(2,"0")}</b><p>{x}</p></article>)}</section></div>
    <section className="proof"><small>EVIDENCE EXIT CONDITION</small><h2>What must survive this step?</h2><p>{item.proof}</p></section>
    <section className="why"><small>WHY THIS EXISTS</small><p>The TA-14 sequence is not a checklist for moving faster. It is a governed evidence path. A technically possible action can still be wrong when the record has not yet earned the authority to take it.</p></section>
    <footer>{prev?<Link href={prev}>← STEP {String(n-1).padStart(2,"0")}</Link>:<span/>}<Link className="lab" href="/atlas-14-step-field-ops-lab">RUN FIELD OPS</Link><Link href={next}>{n<14?`STEP ${String(n+1).padStart(2,"0")} →`:"RETURN TO LAB →"}</Link></footer>
  </div><style>{`
  :root{color-scheme:dark}.page{min-height:100vh;position:relative;overflow:hidden;background:#020810;color:#effaff;font-family:Inter,system-ui,sans-serif}.page *{box-sizing:border-box}.glow{position:fixed;inset:0;pointer-events:none;background:radial-gradient(circle at 12% 5%,rgba(50,225,255,.14),transparent 30%),radial-gradient(circle at 90% 60%,rgba(63,241,167,.1),transparent 28%),linear-gradient(rgba(255,255,255,.018) 1px,transparent 1px),linear-gradient(90deg,rgba(255,255,255,.018) 1px,transparent 1px);background-size:auto,auto,48px 48px,48px 48px}.shell{position:relative;width:min(1120px,calc(100% - 36px));margin:auto;padding:24px 0 60px}nav{display:flex;justify-content:space-between;padding-bottom:20px;border-bottom:1px solid rgba(99,210,238,.18)}nav a,footer a{color:#62eaff;text-decoration:none;font-size:.7rem;font-weight:950;letter-spacing:.1em}header{padding:68px 0 42px;max-width:980px}.phase{color:#58efae;font-size:.72rem;font-weight:950;letter-spacing:.16em}.number{font-size:clamp(5rem,16vw,10rem);line-height:.8;font-weight:1000;letter-spacing:-.08em;color:rgba(94,233,255,.16);margin-top:22px}h1{font-size:clamp(2.8rem,7vw,5.8rem);line-height:.94;letter-spacing:-.055em;margin:-20px 0 18px}header p{max-width:800px;color:#9fb5c3;font-size:1.15rem;line-height:1.7}.doctrine,.proof,.why{padding:25px;border:1px solid rgba(80,225,255,.25);border-radius:20px;background:rgba(5,20,31,.82)}small{display:block;color:#62eaff;font-size:.65rem;font-weight:950;letter-spacing:.14em}.doctrine strong{display:block;margin-top:9px;font-size:1.35rem}.grid{display:grid;grid-template-columns:1fr 1fr;gap:16px;margin:16px 0}.grid>section{padding:25px;border:1px solid rgba(106,196,222,.18);border-radius:20px;background:rgba(4,16,27,.88)}.tag{display:inline-block;padding:7px 9px;border-radius:999px;font-size:.62rem;font-weight:1000;letter-spacing:.12em}.green{color:#68f0b4;border:1px solid rgba(104,240,180,.35)}.gold{color:#ffd36b;border:1px solid rgba(255,211,107,.35)}h2{margin:14px 0 20px;font-size:1.45rem}.grid article{display:grid;grid-template-columns:34px 1fr;gap:12px;padding:14px 0;border-top:1px solid rgba(255,255,255,.07)}.grid article b{color:#62eaff;font-size:.72rem}.grid article p,.proof p,.why p{margin:0;color:#a8bdc9;line-height:1.65}.proof{border-color:rgba(104,240,180,.3);background:radial-gradient(circle at 0 0,rgba(104,240,180,.07),transparent 35%),rgba(4,18,27,.9)}.proof small{color:#68f0b4}.proof h2{font-size:1.8rem}.proof p{font-size:1.08rem}.why{margin-top:16px}.why p{margin-top:10px}footer{display:grid;grid-template-columns:1fr auto 1fr;align-items:center;margin-top:28px;padding-top:22px;border-top:1px solid rgba(99,210,238,.18)}footer a:last-child{text-align:right}.lab{padding:11px 14px;border:1px solid rgba(98,234,255,.3);border-radius:10px}@media(max-width:720px){.grid{grid-template-columns:1fr}nav{gap:16px;flex-direction:column}footer{grid-template-columns:1fr;gap:16px}.lab{justify-self:start}footer a:last-child{text-align:left}}
  `}</style></main>;
}
