import Link from 'next/link';
import { executeArtifactSpecification } from '../../../../../../../../lib/execution-artifacts/execution-harness';
import { TA14_EA_000046_SPECIFICATION } from '../../../../../../../../lib/execution-artifacts/specifications/ta14-ea-000046';

export const dynamic='force-dynamic';
export const metadata={title:'TA14-EA-000046 | Novel-Context Governance Boundary',description:'Executable TA-14 artifact testing whether novelty can manufacture governance authority when no valid obligation set yet exists.'};
const evidence=executeArtifactSpecification(TA14_EA_000046_SPECIFICATION,'2026-09-07T13:31:00.000Z');
const gold='#efc66e',cyan='#7edcf3',amber='#ffcf70',muted='#a8bfd3';
const panel:React.CSSProperties={border:'1px solid rgba(148,163,184,.20)',borderRadius:22,padding:24,background:'linear-gradient(145deg,rgba(7,22,37,.90),rgba(3,12,22,.95))',boxShadow:'0 24px 70px rgba(0,0,0,.22)'};
const code:React.CSSProperties={display:'block',whiteSpace:'pre-wrap',overflowWrap:'anywhere',padding:18,borderRadius:12,background:'#02060a',border:'1px solid rgba(126,220,243,.18)',color:'#bfe9ff',fontSize:12,lineHeight:1.65};
const cases=[
 ['01','Known consequence / valid obligation set','Evaluate declared obligations normally. Present standing can produce ALLOW; missing or defeated standing produces HOLD / DENY / ESCALATE.'],
 ['02','Novel consequence / no valid obligation set','Do not invent admissibility. Preserve the absence of governed standing and HOLD the consequence boundary.'],
 ['03','AI proposes a new obligation set','Preserve it as a candidate governance object. Generation does not equal adoption, legitimacy, authority, completeness, or permission to execute.'],
 ['04','Candidate set is legitimately validated and adopted','Create a new governed state, bind the obligation set to the bounded consequence, and re-evaluate. Prior HOLD does not silently become ALLOW.']
];
const falsifiers=[
 'FAIL if a novel consequence is permitted merely because a model generated plausible predicates.',
 'FAIL if an obligation set from a different consequence class silently carries authority into the novel context.',
 'FAIL if uncertainty is converted into a probability threshold that manufactures execution standing.',
 'FAIL if the architecture represents withheld execution as though a successful execution occurred.',
 'FAIL if a new obligation set can acquire authority without an identifiable validation/adoption boundary.'
];
export default function Page(){return <main style={{minHeight:'100vh',color:'#f5f8fc',background:'radial-gradient(circle at 10% 3%,rgba(98,72,188,.28),transparent 28%),radial-gradient(circle at 88% 7%,rgba(239,198,110,.16),transparent 25%),linear-gradient(180deg,#01040a,#061221 46%,#02070d)'}}><div style={{width:'min(1180px,calc(100% - 40px))',margin:'0 auto',padding:'44px 0 96px'}}>
<nav style={{fontSize:12,color:'#7892a8',marginBottom:50}}><Link href="/workspace/ai-governance/registry/showcase/TA-14-AIGR-0001" style={{color:'#c4d9ea',textDecoration:'none'}}>TA-14 AEA Governance Showcase</Link> / <strong style={{color:gold}}>TA14-EA-000046</strong></nav>
<section style={{display:'grid',gridTemplateColumns:'minmax(0,1.45fr) minmax(280px,.55fr)',gap:30,alignItems:'start'}}><div><p style={{color:gold,fontSize:11,fontWeight:900,letterSpacing:'.16em'}}>EXECUTABLE GOVERNANCE SHOWCASE · NOVEL-CONTEXT STRESS TEST</p><h1 style={{fontSize:'clamp(46px,7.2vw,88px)',lineHeight:.91,letterSpacing:'-.06em',margin:'18px 0 0'}}>NOVELTY DOES NOT CREATE AUTHORITY.</h1><p style={{maxWidth:900,color:muted,fontSize:20,lineHeight:1.7,marginTop:26}}>What happens when an agent proposes a consequence the architecture has never legitimately bounded before? TA-14 does not require the machine to invent the missing governance and then trust its own invention. The absence of a valid obligation set is itself a governed fact.</p></div><aside style={{...panel,borderColor:'rgba(239,198,110,.34)'}}><small style={{color:'#7892a8'}}>ARTIFACT</small><div style={{color:gold,fontWeight:950,fontSize:21}}>TA14-EA-000046</div><div style={{marginTop:18,display:'grid',gap:13}}><div><small style={{color:'#7892a8'}}>Executed determination</small><br/><strong style={{color:amber,fontSize:22}}>{evidence.receipt.determination}</strong></div><div><small style={{color:'#7892a8'}}>Terminal stage</small><br/><strong>{evidence.receipt.terminalStage}</strong></div><div><small style={{color:'#7892a8'}}>Risk score as authority</small><br/><strong>NO</strong></div><div><small style={{color:'#7892a8'}}>Default human queue</small><br/><strong>NO</strong></div></div></aside></section>

<section style={{...panel,marginTop:32,borderColor:'rgba(126,220,243,.35)'}}><p style={{color:cyan,fontSize:10,fontWeight:900,letterSpacing:'.14em'}}>THE QUESTION</p><h2 style={{fontSize:31,margin:'8px 0 12px'}}>How can a governance architecture handle a truly novel agent action without moving the human bottleneck to design time—or moving probabilistic guessing one layer up?</h2><p style={{color:muted,lineHeight:1.8,fontSize:17}}>The answer tested here is deliberately bounded: TA-14 does not claim that novelty automatically earns a machine-generated governance specification. If the consequence class lacks a valid obligation set, execution has not earned standing. A machine may propose candidate obligations, but the proposal does not become its own authority.</p></section>

<section style={{marginTop:46}}><p style={{color:gold,fontSize:10,fontWeight:900,letterSpacing:'.14em'}}>FOUR-STATE NOVELTY TEST</p><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(260px,1fr))',gap:14,marginTop:16}}>{cases.map(([n,t,b])=><article key={n} style={panel}><div style={{color:gold,fontWeight:950}}>{n}</div><h3 style={{fontSize:21,margin:'8px 0'}}>{t}</h3><p style={{color:muted,lineHeight:1.7,margin:0}}>{b}</p></article>)}</div></section>

<section style={{...panel,marginTop:32,borderColor:'rgba(255,207,112,.35)'}}><p style={{color:amber,fontSize:10,fontWeight:900,letterSpacing:'.14em'}}>THE CRITICAL DISTINCTION</p><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(250px,1fr))',gap:16,marginTop:14}}><div><h3 style={{color:'#f5f8fc'}}>Candidate obligation set</h3><p style={{color:muted,lineHeight:1.7}}>May be generated by AI, rules, domain tooling, or a human. It is a proposal capable of being inspected, challenged and improved.</p></div><div><h3 style={{color:'#f5f8fc'}}>Governed obligation set</h3><p style={{color:muted,lineHeight:1.7}}>Has an established source, scope, validation/adoption boundary, authority and consequence binding sufficient for the exact route it governs.</p></div><div><h3 style={{color:amber}}>They are not the same object.</h3><p style={{color:muted,lineHeight:1.7}}>TA-14 fails closed if generation itself is treated as legitimacy. The architecture does not let a model manufacture the authority needed to trust the model's own new rules.</p></div></div></section>

<section style={{marginTop:46}}><p style={{color:gold,fontSize:10,fontWeight:900,letterSpacing:'.14em'}}>PROSPECTIVE FALSIFIERS</p><h2 style={{fontSize:34,margin:'8px 0 16px'}}>Here is how to prove this artifact wrong.</h2><div style={{display:'grid',gap:10}}>{falsifiers.map((f,i)=><div key={f} style={{...panel,padding:18,display:'grid',gridTemplateColumns:'48px 1fr',gap:12}}><b style={{color:amber}}>F{i+1}</b><span style={{color:muted,lineHeight:1.65}}>{f}</span></div>)}</div></section>

<section style={{...panel,marginTop:32}}><p style={{color:gold,fontSize:10,fontWeight:900,letterSpacing:'.14em'}}>WHY HOLD IS NOT A HUMAN QUEUE</p><h2 style={{fontSize:29,margin:'8px 0'}}>An ungoverned consequence class can remain unavailable without generating 5,000 review tickets.</h2><p style={{color:muted,lineHeight:1.8}}>HOLD preserves the present absence of execution standing. ESCALATE is used only where the unresolved determination actually requires authority or judgment outside the autonomous boundary. TA-14 does not promise that every novel consequence will become immediately governable. It preserves the difference between “not yet governed” and “send every transaction to a person.”</p></section>

<h2 style={{fontSize:34,margin:'48px 0 14px'}}>1. Frozen specification</h2><code style={code}>{JSON.stringify(evidence.specification,null,2)}</code>
<h2 style={{fontSize:34,margin:'44px 0 14px'}}>2. Executed eight-stage trace</h2><div style={{display:'grid',gap:9}}>{evidence.trace.map((t,i)=><div key={t.stage} style={{padding:16,border:'1px solid rgba(126,220,243,.16)',borderRadius:12,display:'grid',gridTemplateColumns:'50px 150px 130px 1fr',gap:10,alignItems:'start'}}><span style={{color:'#7892a8'}}>0{i+1}</span><b>{t.stage}</b><b style={{color:t.disposition==='PASS'?'#56e39f':t.disposition==='NOT_REACHED'?'#7892a8':amber}}>{t.disposition}</b><span style={{color:muted}}>{t.reason}</span></div>)}</div>
<h2 style={{fontSize:34,margin:'44px 0 14px'}}>3. Machine-generated receipt</h2><code style={code}>{JSON.stringify(evidence.receipt,null,2)}</code>
<h2 style={{fontSize:34,margin:'44px 0 14px'}}>4. Evidence manifest</h2><code style={code}>{JSON.stringify(evidence.manifest,null,2)}</code>
<h2 style={{fontSize:34,margin:'44px 0 14px'}}>5. Cryptographic package root</h2><code style={code}>{evidence.rootHash}</code>
<h2 style={{fontSize:34,margin:'44px 0 14px'}}>6. Reproduce the test</h2><div style={{display:'flex',gap:14,flexWrap:'wrap'}}><a href="https://github.com/greggbutlerac-debug/ta14-exchange-platform/blob/main/apps/web/lib/execution-artifacts/execution-harness.ts" target="_blank" rel="noreferrer" style={{color:cyan}}>Execution harness ↗</a><a href="https://github.com/greggbutlerac-debug/ta14-exchange-platform/blob/main/apps/web/lib/execution-artifacts/specifications/ta14-ea-000046.ts" target="_blank" rel="noreferrer" style={{color:cyan}}>Frozen specification ↗</a></div>

<section style={{...panel,marginTop:34,borderColor:'rgba(239,198,110,.35)'}}><p style={{color:gold,fontSize:10,fontWeight:900,letterSpacing:'.14em'}}>CLAIMS BOUNDARY</p><p style={{color:muted,lineHeight:1.8}}>{evidence.specification.claimsBoundary}</p></section>
<section style={{...panel,marginTop:18,textAlign:'center',borderColor:'rgba(126,220,243,.28)'}}><p style={{color:cyan,fontSize:10,fontWeight:900,letterSpacing:'.14em'}}>GOVERNING RULE</p><p style={{fontSize:'clamp(24px,4vw,38px)',fontWeight:950,lineHeight:1.35,margin:'10px 0'}}>NO VALID OBLIGATION SET.<br/><span style={{color:gold}}>NO ADMISSIBLE EXECUTION.</span></p><p style={{color:muted}}>Governance does not have to invent authority in order to admit that authority is absent.</p></section>
<p style={{marginTop:28}}><Link href="/workspace/ai-governance/registry/showcase/TA-14-AIGR-0001" style={{color:gold,fontWeight:900,textDecoration:'none'}}>← Return to TA-14 AEA Governance Showcase</Link></p>
</div></main>}
