"use client";

import { useEffect, useMemo, useState } from "react";
import { EXAM1, type ArcadeQuestion } from "./exam1-bank";

type WorldKey = "core"|"type1"|"type2"|"type3"|"transition"|"universal";
type World = { key:WorldKey; title:string; sub:string; icon:string; target:number };
type WorldInfo = { headline:string; scope:string; examples:string[]; boundary:string; visual:string };

const WORLDS:World[]=[
 {key:"core",title:"CORE ORBIT",sub:"Core • Three Rs • Safety",icon:"🌎",target:100},
 {key:"type1",title:"TYPE I MOON",sub:"Small appliances",icon:"🌙",target:100},
 {key:"type2",title:"TYPE II GIANT",sub:"High / very-high pressure",icon:"🪐",target:100},
 {key:"type3",title:"TYPE III VOID",sub:"Low-pressure appliances",icon:"🌌",target:100},
 {key:"transition",title:"A2L FRONTIER",sub:"2026 refrigerant transition",icon:"🔥",target:100},
 {key:"universal",title:"UNIVERSE GATE",sub:"All loaded worlds combined",icon:"🏆",target:500},
];

const WORLD_INFO:Record<WorldKey,WorldInfo>={
 core:{headline:"FOUNDATION FOR EVERY SECTION 608 PATH",scope:"Core is not a separate equipment category. It supplies the environmental, safety, recovery, regulatory and refrigerant-handling foundation used across Type I, II and III.",examples:["Ozone / climate concepts","Recovery • recycle • reclaim","Cylinders • safety • records","Certification boundaries"],boundary:"Master Core before treating equipment-specific answers as isolated facts.",visual:"🌎"},
 type1:{headline:"SMALL APPLIANCE WORLD",scope:"Type I covers servicing small appliances: equipment fully manufactured, charged and hermetically sealed in a factory with 5 lb or less of refrigerant.",examples:["Household refrigerators / freezers","Window & room air conditioners","PTAC / packaged terminal heat pumps","Dehumidifiers • water coolers • vending machines • under-counter ice makers"],boundary:"Small charge does not mean no recovery responsibility.",visual:"🌙"},
 type2:{headline:"HIGH / VERY-HIGH PRESSURE WORLD",scope:"Type II covers servicing or disposing of high- and very-high-pressure appliances, except small appliances and motor vehicle air conditioners.",examples:["Stationary comfort-cooling systems","Split systems and packaged systems","Heat pumps within applicable Section 608 scope","Other high / very-high-pressure stationary appliances"],boundary:"Classify the appliance and refrigerant before applying Type II service logic.",visual:"🪐"},
 type3:{headline:"LOW-PRESSURE WORLD",scope:"Type III covers servicing or disposing of low-pressure appliances. Large low-pressure chillers are the classic equipment family.",examples:["Low-pressure chillers","Purge-equipped systems","Systems operating below atmospheric pressure","Low-pressure evacuation / leak scenarios"],boundary:"Low pressure is not proof that the refrigerant circuit is empty.",visual:"🌌"},
 transition:{headline:"MODERN REFRIGERANT TRANSITION WORLD",scope:"A2L Frontier is TA-14 Academy transition training, not a separate EPA certification type. It adds modern refrigerant identity, equipment labeling, use-condition, tool and procedure decisions across applicable equipment.",examples:["R-32 equipment","R-454B equipment","A2L labels / nameplates","Tool compatibility • ignition / ventilation controls • approved procedures"],boundary:"Physical compatibility never substitutes for equipment-specific authorization and governing conditions.",visual:"🔥"},
 universal:{headline:"ALL EQUIPMENT WORLDS CONVERGE",scope:"Universe Gate combines the loaded Core, Type I, Type II, Type III and transition challenge banks. Official EPA Universal certification covers all Section 608 equipment types after the required approved testing path is completed.",examples:["Core foundation","Type I small appliances","Type II high / very-high pressure","Type III low pressure + transition readiness"],boundary:"Arcade mastery is readiness training; it is not EPA certification.",visual:"🏆"},
};

const LESSONS:Record<WorldKey,{kicker:string;body:string[];memory:string}>={
 core:{kicker:"Learn the rule before you spend the attempt.",body:["Core Orbit combines atmosphere/certification boundaries, the Three Rs, cylinders/records, and safety-critical stop conditions.","Do not memorize a letter. Identify the bucket, the tested rule, the trap, and what proof is missing.","If identity, cylinder suitability, recovery status, or authorization is missing, stopping is controlled practice—not failure."],memory:"LEARN THE RULE → IDENTIFY THE CATEGORY → CHOOSE THE SAFE LEGAL ANSWER → EXPLAIN EVERY MISS"},
 type1:{kicker:"Small appliance does not mean small responsibility.",body:["Type I centers on small appliances and their recovery/service/disposal logic.","Watch for factory-sealed equipment, five pounds or less, compressor condition, recovery before opening, and safe-disposal proof.","Empty-looking is an observation, not proof that refrigerant is absent."],memory:"FACTORY-SEALED + ≤5 LB → TYPE I CLUE • VERIFY RECOVERY / DISPOSAL PROOF"},
 type2:{kicker:"High-pressure readings only mean what governing conditions allow them to mean.",body:["Type II covers high- and very-high-pressure appliances with important exclusions such as small appliances and MVACs.","R-410A service context must be separated from new-equipment transition rules.","A2L-labeled heat pumps add proof requirements; physical fit does not prove authorization."],memory:"CLASSIFY → VERIFY REFRIGERANT → RECOVER BEFORE OPENING WHEN REQUIRED → PROVE A2L CONDITIONS"},
 type3:{kicker:"Low pressure is not the same thing as empty.",body:["Type III focuses on low-pressure appliances, commonly chillers.","Purge behavior, noncondensables, evacuation, recovery, leak location and freeze-risk controls require their own logic.","Never treat a low gauge reading as automatic permission to open a circuit."],memory:"LOW PRESSURE IS EVIDENCE — NOT PROOF OF EMPTY"},
 transition:{kicker:"The refrigerant world changed. The proof requirement did not disappear.",body:["Modern transition decisions add refrigerant identity, equipment design/listing, SNAP end-use/use conditions, A2L-compatible tools, ventilation, ignition control, manufacturer procedure, cylinder path and records.","R-32 and R-454B are not automatic drop-in replacements for R-410A equipment.","Numbers and thresholds must be sorted inside the correct framework before they control an answer."],memory:"IDENTIFY → LABEL → USE CONDITIONS → A2L → THRESHOLD → RECOVERY/RECLAIM → RECORD → PROCEED OR STOP"},
 universal:{kicker:"Everything comes together here.",body:["Universe Gate pulls from every loaded bucket and difficulty level.","The highest-scoring learner is not simply the fastest. The goal is to recognize the rule, resist trap wording, identify missing proof and clear critical misses.","A correct refusal can be more valuable than a technically plausible intervention made before governing facts exist."],memory:"NO PROOF → NO REFRIGERANT ACTION"},
};

function tone(ok:boolean){if(typeof window==="undefined")return;const AC=window.AudioContext||(window as typeof window&{webkitAudioContext?:typeof AudioContext}).webkitAudioContext;if(!AC)return;const c=new AC(),now=c.currentTime;const notes=ok?[523,659,784]:[196,165,147];notes.forEach((f,i)=>{const o=c.createOscillator(),g=c.createGain();o.type=ok?"sine":"triangle";o.frequency.value=f;g.gain.setValueAtTime(.0001,now+i*.07);g.gain.exponentialRampToValueAtTime(.09,now+i*.07+.01);g.gain.exponentialRampToValueAtTime(.0001,now+i*.07+.2);o.connect(g).connect(c.destination);o.start(now+i*.07);o.stop(now+i*.07+.22)});setTimeout(()=>void c.close(),700)}

export default function RefrigerantOps(){
 const [world,setWorld]=useState<WorldKey>("core");
 const [idx,setIdx]=useState(0),[score,setScore]=useState(0),[streak,setStreak]=useState(0),[miss,setMiss]=useState(0),[seconds,setSeconds]=useState(30*60);
 const [msg,setMsg]=useState("Read the evidence. Choose the most defensible answer.");
 const [flash,setFlash]=useState<"good"|"bad"|null>(null),[studying,setStudying]=useState(false),[sound,setSound]=useState(true);
 const pool=useMemo(()=>world==="universal"?EXAM1:EXAM1.filter(x=>x.world===world),[world]);
 const q=pool[idx%pool.length];
 const currentWorld=WORLDS.find(w=>w.key===world)!;
 const lesson=LESSONS[world];
 const dossier=WORLD_INFO[world];
 const loaded=(key:WorldKey)=>key==="universal"?EXAM1.length:EXAM1.filter(x=>x.world===key).length;
 useEffect(()=>{const t=setInterval(()=>setSeconds(s=>Math.max(0,s-1)),1000);return()=>clearInterval(t)},[]);
 const time=`${String(Math.floor(seconds/60)).padStart(2,"0")}:${String(seconds%60).padStart(2,"0")}`;
 function choose(i:number){if(studying)return;if(i===q.correct){const pts=(q.critical?1200:650)*(streak>=4?2:streak>=2?1.5:1);setScore(s=>s+pts);setStreak(s=>s+1);setMsg(`${q.critical?"CRITICAL GATE CLEARED":"RULE LOCKED"} +${pts} XP — ${q.why}`);setFlash("good");if(sound)tone(true);setTimeout(()=>{setIdx(n=>n+1);setFlash(null);setMsg("Next decision loaded. Read before acting.")},1250)}else{setMiss(m=>m+1);setStreak(0);setScore(s=>Math.max(0,s-(q.critical?500:150)));setMsg(`${q.critical?"CRITICAL MISS — ACTION BLOCKED":"NOT QUITE"}. ${q.why}`);setFlash("bad");if(sound)tone(false);setTimeout(()=>setFlash(null),520)}}
 function select(k:WorldKey){setWorld(k);setIdx(0);setMsg("World loaded. Read the evidence before acting.")}
 return <main className={`ops world-${world} ${flash||""}`}><style>{`*{box-sizing:border-box}body{margin:0;background:#02030a}.ops{min-height:100vh;color:#eefcff;font-family:Inter,system-ui,sans-serif;overflow:hidden;position:relative}.badge{display:inline-block;padding:7px 10px;border:1px solid #2b6575;border-radius:999px;color:#66eaff;font-size:10px;font-weight:900;letter-spacing:.12em}.bucket{margin-left:8px;color:#ffd36b;border-color:#6d5d25}.evidence{padding:15px;border:1px solid #256452;border-radius:14px;background:#06221c99;color:#c9f6e6;line-height:1.55}.evidence b{color:#60efb0;font-size:10px;letter-spacing:.13em}.studyBar{display:flex;justify-content:space-between;align-items:center;gap:12px;margin-top:12px;padding:12px 14px;border:1px solid #554d25;border-radius:13px;background:#191606}.studyBar div{font-size:12px;color:#cabf8a}.studyBtn{cursor:pointer;border:1px solid #ffd36b;background:#352c08;color:#ffe59d;padding:11px 14px;border-radius:10px;font-weight:900}.msg{margin-top:16px;min-height:62px;padding:14px;border-radius:13px;background:#050c14;color:#a7c8d5;line-height:1.5}.sideCard{margin:12px;padding:15px;border-radius:13px;background:#061520;border:1px solid #153748;color:#8fabb8;font-size:12px;line-height:1.55}.sideCard b{color:#ffd66d;font-size:11px;letter-spacing:.1em}.formula{font-size:24px!important;color:#63eaff!important;display:block;margin:7px 0}.progress{height:8px;background:#020810;border-radius:99px;overflow:hidden;margin-top:8px}.progress i{display:block;height:100%;background:linear-gradient(90deg,#54e8ff,#64efae)}.dossierVisual{font-size:64px;display:block;filter:drop-shadow(0 0 18px #65eaff66);margin:4px 0}.equipList{margin:10px 0 0;padding:0;list-style:none}.equipList li{padding:5px 0;border-bottom:1px solid #173343;color:#c0d8e3}.equipList li:before{content:"◆";color:#5deaff;margin-right:7px}.worldBoundary{margin-top:11px;padding:10px;border:1px solid #5c4b1d;background:#1a1505;border-radius:10px;color:#ffe29a}.modal{position:fixed;z-index:50;inset:0}.lesson{width:min(900px,100%)}.foot{text-align:center;color:#4f6d7b;font-size:10px;padding:5px 20px 24px;letter-spacing:.1em}`}</style><div className="circuit"/><div className="planet p1"/><div className="planet p2"/>
 {studying&&<div className="modal"><section className="lesson"><div className="lessonTop"><div><small>FIELD GUIDE // CLOCK CONTINUES • {time}</small><h3>{q.lesson}</h3><div style={{color:"#71eaff"}}>{lesson.kicker}</div></div><button className="close" onClick={()=>{setStudying(false);setMsg("Back on mission. The clock kept running while you studied.")}}>RETURN TO MISSION ▶</button></div>{lesson.body.map((p,i)=><p key={i}>{p}</p>)}<div className="memory">MEMORY LOCK // {lesson.memory}</div><p><b>Current question rule:</b> {q.why}</p><div className="pause">⏱ FIELD GUIDE RULE // Study as deeply as you need, but mission time continues to run.</div></section></div>}
 <header className="top"><div className="brand"><b>TA-14 ACADEMY // HVACDR TRAINING UNIVERSE</b><h1>EPA 608 REFRIGERANT OPS</h1></div><div className="stats"><div className="stat"><small>SCORE</small><strong>{score.toLocaleString()}</strong></div><div className="stat"><small>STREAK</small><strong>{streak}x</strong></div><div className="stat"><small>TIME</small><strong>{time}</strong></div><button className="sound" onClick={()=>setSound(s=>!s)}>{sound?"🔊":"🔇"}</button></div></header>
 <div className="layout"><aside className="panel left"><div className="title">SELECT TRAINING WORLD</div><div className="worlds">{WORLDS.map(w=><button key={w.key} onClick={()=>select(w.key)} className={`world ${world===w.key?"active":""}`}><span>{w.icon}</span><div><b>{w.title}</b><small>{w.sub}</small><small className="load">{loaded(w.key)} / {w.target} loaded</small></div></button>)}</div></aside>
 <section className="panel stage"><span className="badge">{currentWorld.title} // QUESTION {idx%pool.length+1} OF {pool.length}</span><span className="badge bucket">{q.bucket} • LEVEL {q.level}{q.critical?" • CRITICAL":""}</span><h2>{q.prompt}</h2><div className="evidence"><b>TESTED RULE / EVIDENCE BOUNDARY</b><div>{q.lesson}. Read every word; plausible does not automatically mean correct.</div></div><div className="studyBar"><div><b>Need the governing rule?</b><br/>Open the Field Guide. Mission time keeps running.</div><button className="studyBtn" onClick={()=>{setStudying(true);setMsg("FIELD GUIDE OPEN — mission clock continues.")}}>📘 OPEN FIELD GUIDE — CLOCK RUNS</button></div><div className="answers">{q.choices.map((a,i)=><button className="answer" onClick={()=>choose(i)} key={`${q.id}-${i}`}><b>{String.fromCharCode(65+i)}.</b> {a}</button>)}</div><div className="msg">{msg}</div></section>
 <aside className="panel right"><div className="title">WORLD EQUIPMENT DOSSIER</div><div className="sideCard dossier"><b>{dossier.headline}</b><span className="dossierVisual">{dossier.visual}</span><p>{dossier.scope}</p><ul className="equipList">{dossier.examples.map(x=><li key={x}>{x}</li>)}</ul><div className="worldBoundary">{dossier.boundary}</div></div><div className="sideCard"><b>WORLD BUILD</b><div className="progress"><i style={{width:`${Math.min(100,loaded(world)/currentWorld.target*100)}%`}}/></div><p>{loaded(world)} unique loaded questions toward this world's {currentWorld.target}+ target.</p></div><div className="sideCard"><b>RUN STATUS</b><p>{miss} misses • {streak} current streak • {time} remaining</p></div></aside></div>
 <footer className="foot">TA-14 Academy HVACDR readiness training • Not EPA certification • Original published readiness questions • Official certification remains with EPA-approved certifying organizations</footer></main>
}
