"use client";
import {useEffect,useRef} from "react";
type Props={flash:"good"|"bad"|null;streak:number};
export default function PhaserEffectsLayer({flash,streak}:Props){
 const host=useRef<HTMLDivElement>(null),sceneRef=useRef<any>(null);
 useEffect(()=>{let game:any,cancelled=false;(async()=>{const Phaser=(await import("phaser")).default;if(cancelled||!host.current)return;
 class EffectsScene extends Phaser.Scene{
  stars:any[]=[];arcs:any[]=[];
  create(){sceneRef.current=this;const w=innerWidth,h=innerHeight;
   for(let i=0;i<190;i++){const s=this.add.circle(Phaser.Math.Between(0,w),Phaser.Math.Between(0,h),Phaser.Math.Between(1,3),i%8===0?0x62ffae:0xbefaff,Phaser.Math.FloatBetween(.1,.62));this.stars.push(s);this.tweens.add({targets:s,alpha:Phaser.Math.FloatBetween(.04,.22),duration:Phaser.Math.Between(700,2600),yoyo:true,repeat:-1})}
   this.makePlanet(w*.91,h*.2,48,0x116a91,0x55eaff,9000);this.makePlanet(w*.07,h*.72,28,0x16694f,0x63ffad,6500);
   for(let i=0;i<12;i++){const o=this.add.circle(Phaser.Math.Between(0,w),Phaser.Math.Between(0,h),Phaser.Math.Between(2,7),i%2?0x5affab:0x48ddff,.3);this.tweens.add({targets:o,x:o.x+Phaser.Math.Between(-280,280),y:o.y+Phaser.Math.Between(-180,180),duration:Phaser.Math.Between(4200,9000),yoyo:true,repeat:-1,ease:"Sine.easeInOut"})}
   this.time.addEvent({delay:1800,loop:true,callback:()=>this.comet()});this.time.addEvent({delay:2600,loop:true,callback:()=>this.edgeArc()});this.time.addEvent({delay:4100,loop:true,callback:()=>{if(Math.random()>.45)this.lightning(0,false,.32)}});
  }
  makePlanet(x:number,y:number,r:number,fill:number,glow:number,duration:number){const p=this.add.circle(x,y,r,fill,.32).setStrokeStyle(2,glow,.42),ring=this.add.ellipse(x,y,r*2.7,r*.55).setStrokeStyle(2,glow,.36);this.tweens.add({targets:ring,angle:360,duration,repeat:-1});this.tweens.add({targets:p,scale:1.1,alpha:.48,duration:1800,yoyo:true,repeat:-1})}
  comet(){const fromLeft=Math.random()>.5,x=fromLeft?-80:this.scale.width+80,y=Phaser.Math.Between(80,this.scale.height*.65),g=this.add.graphics();g.lineStyle(3,Math.random()>.5?0x58eaff:0x63ffad,.65);g.lineBetween(0,0,90,22);const head=this.add.circle(x,y,4,0xffffff,.85),tail=this.add.container(x,y,[g]);tail.setScale(fromLeft?1:-1,1);const tx=fromLeft?this.scale.width+120:-120,ty=y+Phaser.Math.Between(80,220);this.tweens.add({targets:[head,tail],x:tx,y:ty,alpha:0,duration:Phaser.Math.Between(1200,2200),ease:"Linear",onComplete:()=>{head.destroy();tail.destroy()}})}
  edgeArc(){const side=Math.random()>.5?24:this.scale.width-24,g=this.add.graphics(),c=Math.random()>.5?0x63ffad:0x58eaff;g.lineStyle(2,c,.42);let x=side,y=Phaser.Math.Between(50,this.scale.height*.45);g.beginPath();g.moveTo(x,y);for(let i=0;i<9;i++){x+=Phaser.Math.Between(-18,18);y+=Phaser.Math.Between(18,38);g.lineTo(x,y)}g.strokePath();this.tweens.add({targets:g,alpha:0,duration:420,onComplete:()=>g.destroy()})}
  correctBurst(level=1){const w=this.scale.width,h=this.scale.height,intensity=Math.min(6,1+Math.floor(level/2)),bursts=5+intensity*2,strikes=5+intensity*2;this.wave(w/2,h/2,0x63ffad);this.wave(w/2,h/2,0x54e8ff,80);if(level>=5)this.wave(w/2,h/2,0xffffff,150);for(let j=0;j<bursts;j++){const x=Phaser.Math.Between(w*.08,w*.92),y=Phaser.Math.Between(h*.1,h*.82);this.time.delayedCall(j*42,()=>{for(let i=0;i<24+intensity*9;i++){const p=this.add.circle(x,y,Phaser.Math.Between(2,7+intensity),i%2?0x64ffab:0x54e8ff,.95);this.tweens.add({targets:p,x:x+Phaser.Math.Between(-190-intensity*28,190+intensity*28),y:y+Phaser.Math.Between(-160-intensity*22,160+intensity*22),alpha:0,scale:0,duration:Phaser.Math.Between(340,850),ease:"Cubic.easeOut",onComplete:()=>p.destroy()})}})}for(let i=0;i<strikes;i++)this.lightning(i*48,false);this.planetPulse(intensity);if(level>=3)this.banner(`POWER STREAK // ${level}x`,0x63ffad);if(level>=5){this.cameras.main.shake(150,.003);this.banner("UNIVERSE CHARGED",0x54e8ff,150)}if(level>=10){for(let i=0;i<5;i++)this.comet();this.cameras.main.shake(240,.005);this.banner("COSMIC MASTERY",0xffffff,300)}}
  wrongHit(){this.cameras.main.shake(420,.014);const v=this.add.rectangle(this.scale.width/2,this.scale.height/2,this.scale.width,this.scale.height,0xff174f,.16);this.tweens.add({targets:v,alpha:0,duration:520,onComplete:()=>v.destroy()});this.wave(this.scale.width/2,this.scale.height/2,0xff315f);for(let i=0;i<5;i++)this.lightning(i*75,true);this.banner("SYSTEM HIT // STREAK LOST",0xff315f)}
  banner(text:string,color:number,delay=0){this.time.delayedCall(delay,()=>{const t=this.add.text(this.scale.width/2,this.scale.height*.18,text,{fontFamily:"monospace",fontSize:"30px",fontStyle:"bold",color:"#ffffff",stroke:"#001018",strokeThickness:8}).setOrigin(.5).setAlpha(0).setTint(color);this.tweens.add({targets:t,alpha:1,scale:1.2,duration:160,yoyo:true,hold:330,onComplete:()=>t.destroy()})})}
  wave(x:number,y:number,color:number,delay=0){this.time.delayedCall(delay,()=>{const r=this.add.circle(x,y,20).setStrokeStyle(6,color,.9);this.tweens.add({targets:r,scale:34,alpha:0,duration:820,ease:"Quad.easeOut",onComplete:()=>r.destroy()})})}
  planetPulse(n=1){const x=this.scale.width*.88,y=this.scale.height*.24,p=this.add.circle(x,y,14,0x43dfff,.16).setStrokeStyle(5,0x62ffad,.85),r=this.add.ellipse(x,y,48,16).setStrokeStyle(4,0x55eaff,.8);this.tweens.add({targets:[p,r],scale:9+n*2,angle:n*45,alpha:0,duration:920,onComplete:()=>{p.destroy();r.destroy()}})}
  lightning(delay:number,bad:boolean,alpha=.9){this.time.delayedCall(delay,()=>{const g=this.add.graphics(),c=bad?0xff3569:(Math.random()>.5?0x63ffad:0x58eaff);g.lineStyle(Phaser.Math.Between(2,6),c,alpha);let x=Phaser.Math.Between(30,this.scale.width-30),y=-20;g.beginPath();g.moveTo(x,y);while(y<this.scale.height*.85){x+=Phaser.Math.Between(-52,52);y+=Phaser.Math.Between(22,55);g.lineTo(x,y)}g.strokePath();this.tweens.add({targets:g,alpha:0,duration:230,onComplete:()=>g.destroy()})})}
 }
 game=new Phaser.Game({type:Phaser.AUTO,parent:host.current,transparent:true,width:innerWidth,height:innerHeight,scene:[EffectsScene],scale:{mode:Phaser.Scale.RESIZE,width:"100%",height:"100%"},render:{antialias:true,pixelArt:false}})})();const resize=()=>game?.scale?.resize(innerWidth,innerHeight);addEventListener("resize",resize);return()=>{cancelled=true;removeEventListener("resize",resize);sceneRef.current=null;game?.destroy(true)}},[]);
 useEffect(()=>{const s=sceneRef.current;if(!s||!flash)return;flash==="good"?s.correctBurst(streak):s.wrongHit()},[flash,streak]);
 return <div ref={host} aria-hidden="true" style={{position:"fixed",inset:0,zIndex:35,pointerEvents:"none",overflow:"hidden"}}/>;
}
