"use client";

import Link from "next/link";
import { useEffect, useState } from "react";

type Item={name:string;count:number};
type Data={generatedAt:string;windowDays:number;summary:{pageViews:number;uniqueVisitors:number;clicks:number;searchArrivals:number};pages:Item[];searchEngines:Item[];searchQueries:Item[];referrers:Item[];campaigns:Item[];sources:Item[];terms:Item[];devices:Item[];locations:Item[];clickTargets:Item[]};

function Panel({title,items,empty="No data recorded yet."}:{title:string;items:Item[];empty?:string}){return <section className="rounded-2xl border border-white/10 bg-white/[0.035] p-5"><h2 className="mb-4 text-sm font-semibold uppercase tracking-[.18em] text-cyan-200">{title}</h2>{items?.length?<div className="space-y-2">{items.slice(0,15).map((x,i)=><div key={`${x.name}-${i}`} className="flex items-start justify-between gap-4 border-b border-white/5 pb-2 text-sm"><span className="break-all text-slate-300">{x.name}</span><strong className="shrink-0 text-white">{x.count.toLocaleString()}</strong></div>)}</div>:<p className="text-sm text-slate-500">{empty}</p>}</section>}

export default function SeoIntelligencePage(){const[data,setData]=useState<Data|null>(null);const[status,setStatus]=useState("Loading private telemetry…");useEffect(()=>{fetch("/api/admin/seo-intelligence",{cache:"no-store"}).then(async r=>{if(r.status===401)throw new Error("Sign in to view this private engine.");if(r.status===403)throw new Error("This engine is restricted to the TA-14 owner account.");if(!r.ok)throw new Error("SEO Intelligence is not available yet.");return r.json();}).then(d=>{setData(d);setStatus("");}).catch(e=>setStatus(e.message));},[]);return <main className="min-h-screen bg-[#03060b] px-5 py-10 text-white"><div className="mx-auto max-w-7xl"><div className="mb-8 flex flex-wrap items-end justify-between gap-5"><div><div className="mb-2 text-xs font-semibold uppercase tracking-[.28em] text-cyan-300">TA-14 Private Institutional Engine</div><h1 className="text-3xl font-semibold md:text-5xl">SEO Intelligence</h1><p className="mt-3 max-w-3xl text-slate-400">See which Exchange pages are being discovered, what visitors click, where traffic originates, approximate geographic demand, campaign attribution, devices, and the search terms that referrers make available.</p></div><Link href="/workspace/mission-control" className="rounded-full border border-white/15 px-4 py-2 text-sm text-slate-300 hover:bg-white/5">← Mission Control</Link></div>{status&&<div className="rounded-2xl border border-white/10 bg-white/[0.035] p-6 text-slate-300">{status}</div>}{data&&<><div className="mb-7 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[["Page views",data.summary.pageViews],["Unique visitors",data.summary.uniqueVisitors],["Tracked clicks",data.summary.clicks],["Search arrivals",data.summary.searchArrivals]].map(([k,v])=><div key={String(k)} className="rounded-2xl border border-white/10 bg-white/[0.035] p-5"><div className="text-3xl font-semibold">{Number(v).toLocaleString()}</div><div className="mt-1 text-xs uppercase tracking-[.16em] text-slate-500">{k}</div></div>)}</div><div className="mb-6 rounded-xl border border-cyan-400/15 bg-cyan-400/[0.04] px-4 py-3 text-sm text-slate-400">Private owner view · rolling {data.windowDays}-day window · no raw IP address is stored by this engine. Search-query visibility depends on what the referring service actually provides.</div><div className="grid gap-5 lg:grid-cols-2"><Panel title="Top Exchange pages" items={data.pages}/><Panel title="What people click" items={data.clickTargets}/><Panel title="Search engines & AI referrers" items={data.searchEngines}/><Panel title="Search terms observed" items={data.searchQueries}/><Panel title="Traffic sources" items={data.referrers}/><Panel title="Approximate geographic demand" items={data.locations}/><Panel title="Campaign names" items={data.campaigns}/><Panel title="UTM sources" items={data.sources}/><Panel title="UTM terms / keyword campaigns" items={data.terms}/><Panel title="Devices" items={data.devices}/></div></>}</div></main>}
