'use client';
import Link from 'next/link';
import {useState} from 'react';

type Q={q:string;o:string[];a:number;e:string};
const qs:Q[]=[
{q:'A customer says, “It needs refrigerant.” What is that?',o:['A diagnosis','A reported statement','A measurement','Permission to attach gauges'],a:1,e:'It is information from the customer. Record it, but verify present reality yourself.'},
{q:'Which is a direct observation?',o:['The compressor is weak','The outdoor fan is not turning','The system is undercharged','The TXV is restricted'],a:1,e:'You can directly observe a fan not turning. The other choices interpret a cause.'},
{q:'Which is a measurement?',o:['Indoor RH is 68%','The room feels sticky','The system is bad','The coil is starving'],a:0,e:'68% RH is a quantified reading. Its source and context still matter.'},
{q:'Why identify the exact equipment before testing?',o:['For decoration','So evidence is tied to the correct asset','Only for warranty','To avoid measuring anything'],a:1,e:'Good evidence attached to the wrong unit can create a bad record.'},
{q:'What does “operating state” mean?',o:['How old the unit is','What the system is commanded to do and what it is actually doing','The customer’s mood','The brand name'],a:1,e:'Cooling, heating, fan-only, satisfied, compressor on/off and similar states change how readings are interpreted.'},
{q:'A thermostat says 74°F. What should you also know?',o:['Nothing else','Where the reading came from and the system state','The homeowner’s favorite setting','The price of the thermostat'],a:1,e:'Source, location, time and operating state give the number meaning.'},
{q:'72°F and 68% RH are recorded. What is safest to say?',o:['Low charge','Temperature is 72°F and moisture is elevated; cause is unresolved','Bad compressor','Too much airflow'],a:1,e:'State the conditions you actually have. Do not invent the cause.'},
{q:'If the blower has electrical power, what is proven?',o:['Correct airflow','That electrical condition only','Correct humidity control','Correct refrigerant charge'],a:1,e:'Power at a component does not automatically prove the mechanical result.'},
{q:'Which comes first?',o:['Diagnosis','Reality','Repair','Invoice'],a:1,e:'Start with what is actually happening now.'},
{q:'A number from a meter is automatically a diagnosis.',o:['True','False'],a:1,e:'A reading is evidence. Diagnosis requires interpretation and enough supporting evidence.'},
{q:'Which statement is an inference?',o:['RH is 68%','The fan is not turning','Airflow may be contributing to the condition','The thermostat displays 72°F'],a:2,e:'“May be contributing” is a reasoned possibility, not a direct observation.'},
{q:'When evidence is not enough, what should a technician do?',o:['Guess','Replace the cheapest part','Keep examining or clearly preserve the limitation','Copy the last technician'],a:2,e:'Not knowing yet is acceptable. Pretending to know is not.'},
{q:'Why can the same pressure or temperature number mean different things?',o:['Numbers change their spelling','Operating conditions and measurement location change the context','They never do','Brand names change physics'],a:1,e:'A reading must be interpreted in the conditions under which it was collected.'},
{q:'Which is a diagnosis?',o:['24 VAC measured across a coil','Outdoor temperature is 91°F','A failed component is established as the cause','Customer reports noise'],a:2,e:'A diagnosis is a supported determination, not merely a reading or report.'},
{q:'What is a proposed consequence?',o:['A measurement','An action intended to change reality','A complaint','A serial number'],a:1,e:'Replacing, adjusting, recovering or repairing are examples of actions intended to change the system.'},
{q:'Does a correct diagnosis automatically give permission to perform any repair?',o:['Yes','No'],a:1,e:'Knowing what is wrong and having authority to execute a consequence are different questions.'},
{q:'What is Dehumidification concerned with?',o:['Only temperature','Moisture performance','Only voltage','Only compressor sound'],a:1,e:'The D in HVACD/R keeps moisture performance visible as its own discipline.'},
{q:'If a room reaches setpoint, is moisture performance automatically proven?',o:['Yes','No'],a:1,e:'Sensible temperature and moisture performance are related but distinct.'},
{q:'Which record is stronger?',o:['“Unit bad”','“At 2:14 PM, cooling call satisfied; occupied-zone instrument reads 72°F/68% RH”','“Probably low”','“Customer said it always does this”'],a:1,e:'It preserves time, state, location/source and measured conditions.'},
{q:'What should happen to a customer complaint?',o:['Ignore it','Record it as reported and test present reality','Treat it as proven diagnosis','Delete it'],a:1,e:'The complaint matters, but it is the beginning of examination, not the end.'},
{q:'What does “stop where the evidence stops” mean?',o:['Never repair anything','Make only the conclusion the evidence currently supports','Stop working after one reading','Always HOLD'],a:1,e:'Strong technicians distinguish what is known from what is still unknown.'},
{q:'Which can change reality?',o:['Moving a wire','Changing a control setting','Attaching some instruments','All of these'],a:3,e:'Technician actions can alter the condition being examined, which is why sequence and preservation matter.'},
{q:'What makes a measurement more useful?',o:['A bigger number','Known instrument/source, location, time and state','A confident technician','A customer agreement'],a:1,e:'Context makes a measurement attributable and interpretable.'},
{q:'Field readiness is best described as:',o:['Memorizing answers','Using knowledge safely and correctly on a real system with evidence and verification','Owning expensive tools','Working fast'],a:1,e:'The course is about demonstrated field reasoning and performance, not recall alone.'},
{q:'What is the core habit Lesson 1.01 is trying to build?',o:['Repair first, document later','See it, record it, understand what it supports, and do not outrun it','Always attach gauges','Always trust the thermostat'],a:1,e:'Reality first. Record second. Supported reasoning follows.'}
];

const concepts=[
['COMPLAINT','What someone tells you.','“It is not cooling.”','Useful starting information, not proof of cause.'],
['OBSERVATION','Something you directly notice.','The outdoor fan is not turning.','Record exactly what you saw, heard or found.'],
['MEASUREMENT','A number collected from a source.','Indoor RH = 68%.','Record the instrument/source, place, time and operating state.'],
['INFERENCE','A possible explanation.','Airflow may be involved.','A possibility is not yet a diagnosis.'],
['DIAGNOSIS','A supported determination.','Evidence establishes a specific failed condition.','The record must support the conclusion.'],
['CONSEQUENCE','Something you propose to do.','Replace, adjust, repair or recover.','Changing reality requires its own execution basis.']
];

const chain=['REALITY','RECORD','CONTINUITY','ADMISSIBILITY','BINDING','COMMIT','EXECUTION','OUTCOME'];

export default function Lesson101(){
 const [tab,setTab]=useState('start'),[answers,setAnswers]=useState<Record<number,number>>({}),[submitted,setSubmitted]=useState(false),[scenario,setScenario]=useState(0),[sorts,setSorts]=useState<Record<string,string>>({});
 const score=qs.reduce((n,q,i)=>n+(answers[i]===q.a?1:0),0),pct=Math.round(score/qs.length*100),passed=submitted&&pct>=80;
 const card={padding:26,border:'1px solid #245878',borderRadius:18,background:'linear-gradient(145deg,#062945,#041e35)',boxShadow:'0 18px 44px rgba(0,0,0,.22)'};
 const Deep=({title,plain,technical,why,scenarios}:{title:string,plain:string,technical:string,why:string,scenarios:string[]})=><div style={{...card,marginTop:14}}>
   <small style={{color:'#B9D9EB',fontWeight:900}}>GO DEEPER</small><h3 style={{fontFamily:'Georgia,serif',fontSize:27}}>{title}</h3>
   <p style={{color:'#C9E0EF',lineHeight:1.85,fontSize:16}}><b style={{color:'#7BAFD4'}}>PLAIN LANGUAGE — </b>{plain}</p>
   <p style={{color:'#C9E0EF',lineHeight:1.85,fontSize:16}}><b style={{color:'#7BAFD4'}}>TECHNICIAN LANGUAGE — </b>{technical}</p>
   <p style={{color:'#C9E0EF',lineHeight:1.85,fontSize:16}}><b style={{color:'#7BAFD4'}}>WHY IT MATTERS — </b>{why}</p>
   <div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(250px,1fr))',gap:10,marginTop:15}}>{scenarios.map((s,i)=><div key={s} style={{padding:18,border:'1px solid #316987',borderRadius:14,background:'#031a2e'}}><b style={{color:'#B9D9EB'}}>SCENARIO {String.fromCharCode(65+i)}</b><p style={{color:'#C9E0EF',lineHeight:1.7}}>{s}</p></div>)}</div>
 </div>;
 const tabs=[['start','START HERE'],['story','THE BIG IDEA'],['learn','LEARN'],['words','FIELD WORDS'],['chain','TA-14 PATH'],['lab','FIELD LAB'],['play','INTERACT'],['quiz','25-Q EXAM'],['record','RECORD']];
 const choose=(k:string,v:string)=>setSorts({...sorts,[k]:v});
 return <main style={{minHeight:'100vh',background:'radial-gradient(circle at 80% 0%,#0b4163 0%,#001d36 32%,#001326 70%,#000b18 100%)',color:'#f7fbff',fontFamily:'Arial,sans-serif',padding:'0 20px'}}><div style={{maxWidth:1120,margin:'auto'}}>
 <nav style={{padding:'22px 0',display:'flex',justifyContent:'space-between',gap:12,borderBottom:'1px solid #285b78',fontSize:11,fontWeight:900}}><Link href="/eight24-hvacdr/curriculum/01" style={{color:'#7BAFD4',textDecoration:'none'}}>← MODULE 01</Link><span style={{color:'#B9D9EB'}}>1.01 · HVACD/R FIELD READINESS · FOUNDATIONAL ROOM</span></nav>
 <header style={{padding:'65px 0 28px'}}><div style={{display:'inline-block',padding:'8px 12px',border:'1px solid #7BAFD4',borderRadius:999,color:'#B9D9EB',fontSize:10,fontWeight:900}}>READ IT · TOUCH IT · THINK IT · PROVE IT</div><h1 style={{fontFamily:'Georgia,serif',fontSize:'clamp(46px,7vw,80px)',lineHeight:.96,margin:'18px 0'}}>Welcome to HVACD/R.<br/><i>Learn to see first.</i></h1><p style={{maxWidth:880,color:'#C9E0EF',fontSize:19,lineHeight:1.75}}>You do not need to be an HVAC technician to begin this lesson. If you can understand the difference between <b>what someone told you</b>, <b>what you actually saw</b>, and <b>what you can prove</b>, you can begin learning the field correctly.</p></header>
 <div style={{display:'flex',gap:7,flexWrap:'wrap',paddingBottom:28}}>{tabs.map(t=><button key={t[0]} onClick={()=>setTab(t[0])} style={{cursor:'pointer',border:'1px solid #316987',background:tab===t[0]?'#7BAFD4':'#06243B',color:tab===t[0]?'#001426':'#C9E0EF',padding:'10px 14px',borderRadius:999,fontSize:10,fontWeight:900}}>{t[1]}</button>)}</div>

 {tab==='start'&&<section style={{display:'grid',gap:14,paddingBottom:55}}><div style={card}><small style={{color:'#B9D9EB',fontWeight:900}}>WELCOME</small><h2 style={{fontFamily:'Georgia,serif',fontSize:38}}>Think like a detective, not a guesser.</h2><p style={{color:'#C9E0EF',lineHeight:1.85,fontSize:17}}>Imagine someone says, “My bicycle is slow, so the tire must be flat.” The bicycle really might be slow. The tire might even be flat. But the statement did not prove the cause. You would look at the bicycle, check the tires, see whether the brakes are rubbing, and gather information before deciding what is wrong. HVACD/R field work begins with the same habit.</p><p style={{color:'#C9E0EF',lineHeight:1.85,fontSize:17}}>A heating and cooling system can be more complicated than a bicycle, and technician actions can change the system. That makes careful observation even more important.</p></div>
 <div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(210px,1fr))',gap:12}}>{[['1','SEE','What is actually happening right now?'],['2','RECORD','Can another person understand what you saw and measured?'],['3','REASON','What does the evidence support - and what does it not support?'],['4','ACT LATER','Only after the required evidence, authority and standing are established.']].map(x=><div key={x[0]} style={card}><b style={{fontFamily:'Georgia,serif',fontSize:34,color:'#7BAFD4'}}>{x[0]}</b><h3>{x[1]}</h3><p style={{color:'#C9E0EF',lineHeight:1.6}}>{x[2]}</p></div>)}</div>
 <div style={{...card,border:'1px solid #B9D9EB'}}><b style={{color:'#B9D9EB'}}>YOUR GOAL</b><p style={{fontFamily:'Georgia,serif',fontSize:25,lineHeight:1.55}}>By the end, you should be able to hear a complaint, look at a system, collect basic information, and clearly separate <i>known</i> from <i>not yet known</i>.</p></div>
 <Deep title="Complaint is a starting point, not a verdict" plain="If someone tells you their phone will not charge, you would not replace the battery before checking the cable, outlet and charging port. HVACD/R works the same way." technical="The customer complaint is historical or reported information. It establishes the reason for examination, but it does not independently establish present operating state, failure mode or root cause." why="If the technician silently turns a complaint into a diagnosis, every later measurement can become biased toward proving the first guess instead of discovering reality." scenarios={['Customer says: “It needs Freon.” Preserve that exact statement, then establish present system conditions before deciding whether refrigerant evidence is even needed.','Customer says: “It never shuts off.” You arrive and the unit is off with the thermostat satisfied. Both facts belong in the record: the historical complaint and the present state.']} />
 <Deep title="A good beginning record has enough context to survive" plain="Imagine finding a photo labeled only “broken.” You would want to know what object, where, when and what happened. Field measurements need the same kind of label." technical="An orientation record should connect asset identity, complaint, commanded state, observed state, environmental conditions, measurement source/location/time, and known limitations." why="Later decisions depend on knowing that a measurement actually belongs to the system, condition and moment being discussed." scenarios={['Two condensers sit beside each other. A technician records pressure readings but not which condenser was tested. The numbers may be accurate and still be unusable.','A note says “74°F.” A stronger note says “2:14 PM — occupied-zone probe — 74°F dry-bulb — thermostat cooling call active.”']} />
 </section>}

 {tab==='story'&&<section style={{display:'grid',gap:14,paddingBottom:55}}><div style={card}><small style={{color:'#B9D9EB',fontWeight:900}}>THE BIG IDEA</small><h2 style={{fontFamily:'Georgia,serif',fontSize:38}}>A technician can change the thing being examined.</h2><p style={{color:'#C9E0EF',lineHeight:1.85}}>Opening a panel, moving a wire, changing a thermostat setting, attaching an instrument, recovering refrigerant, adjusting airflow, or replacing a part can change the system. Once reality changes, a later reading may no longer describe the condition that existed when you arrived.</p><p style={{color:'#C9E0EF',lineHeight:1.85}}>That is why this program teaches sequence. First establish the starting condition. Preserve it. Then examine. Later, when an intervention is supported and authorized, preserve what you changed and verify what became true afterward.</p></div>
 <div style={{...card,background:'#031a2e'}}><h3 style={{fontFamily:'Georgia,serif',fontSize:28}}>The simple version</h3><div style={{display:'flex',gap:8,flexWrap:'wrap'}}>{['BEFORE','WHAT YOU KNOW','WHAT YOU DECIDE','WHAT YOU DO','AFTER'].map((x,i)=><div key={x} style={{flex:'1 1 160px',padding:18,borderRadius:14,border:'1px solid #285b78',textAlign:'center'}}><b style={{color:i===0||i===4?'#B9D9EB':'#7BAFD4'}}>{x}</b></div>)}</div><p style={{color:'#C9E0EF',lineHeight:1.8}}>If you cannot explain the BEFORE, it becomes much harder to prove whether the AFTER was actually better.</p></div>
 <Deep title="Why BEFORE and AFTER must stay separate" plain="If you change the recipe before tasting the food, you cannot honestly describe what the original recipe tasted like." technical="Pre-intervention evidence establishes Reality₀. An authorized intervention creates a changed condition. Post-intervention evidence establishes Reality₁. Mixing the two weakens causal claims about whether the intervention produced the outcome." why="Technicians often touch controls, reset power or move wiring before preserving the arrival condition. That can erase valuable diagnostic evidence." scenarios={['A breaker is reset before the technician records its tripped state. The system runs afterward, but part of the original condition has been lost.','A thermostat setpoint is changed before recording commanded state. Later readings no longer describe the same operating request that existed at arrival.']} />
 <div style={{...card,marginTop:14}}><small style={{color:'#B9D9EB',fontWeight:900}}>TRY THIS</small><h3 style={{fontFamily:'Georgia,serif',fontSize:26}}>You arrive and immediately cycle power. What did you lose?</h3><p style={{color:'#C9E0EF',lineHeight:1.8}}>Potentially the original control state, fault display, sequence position, component state and evidence of whether the system would have changed without your intervention. Resetting may eventually be appropriate—but first ask whether the starting reality needs to be preserved.</p></div>
 </section>}

 {tab==='learn'&&<section style={{display:'grid',gap:14,paddingBottom:55}}>{[
 ['01','START WITH THE COMPLAINT - BUT DO NOT MARRY IT','Customers give valuable information. “It is hot upstairs.” “The air feels wet.” “The outdoor unit is making a noise.” “The last technician said it needs refrigerant.” Write those statements down as reported information. They tell you where to begin looking. They do not prove the cause.'],
 ['02','IDENTIFY WHAT YOU ARE WORKING ON','Before attaching evidence to a system, know which system it is. A building may have two air conditioners sitting side by side. Record the equipment type, location, indoor/outdoor pairing when applicable, and identifying information available to you. A perfect reading from Unit A cannot prove something about Unit B.'],
 ['03','KNOW WHAT THE SYSTEM IS TRYING TO DO','A reading means more when you know the operating state. Is there a cooling call? Has the thermostat already reached setpoint? Is the blower running? Is the compressor running? Is the unit heating, cooling, dehumidifying, in fan-only mode, in defrost, or off? State gives readings context.'],
 ['04','OBSERVE BEFORE YOU EXPLAIN','“The fan is not turning” is an observation. “The fan motor is bad” is an explanation. Keep those separate. You may eventually prove the motor failed, but the observation comes first. This habit prevents a technician from accidentally turning a first impression into a diagnosis.'],
 ['05','MEASUREMENTS NEED A NAME TAG','Suppose someone writes “74°F.” Where? At the thermostat? Return duct? Supply duct? Outside? Which instrument? At what time? Was the compressor operating? A number without context is like a photograph with no date, place or subject. Preserve the number and its name tag.'],
 ['06','FIVE DISCIPLINES CAN TOUCH THE SAME SERVICE CALL','HVACD/R means Heating, Ventilation, Air Conditioning, Dehumidification and Refrigeration. They interact, but they are not identical. Electrical power at a blower does not prove correct airflow. A cool room does not prove good moisture control. Refrigerant readings do not erase airflow or load conditions.'],
 ['07','THE D IS NOT DECORATION','Dehumidification means moisture control. A room can be 72°F and still feel damp at 68% relative humidity. The temperature condition and moisture condition must be considered separately. Elevated humidity tells you there is a moisture condition to examine; it does not tell you the cause by itself.'],
 ['08','A TOOL DOES NOT THINK FOR YOU','Meters, probes, gauges and sensors provide information. They do not automatically provide a diagnosis. The technician has to know what was measured, whether the measurement is valid, and what conclusions the evidence can support.'],
 ['09','“I DON’T KNOW YET” CAN BE THE RIGHT ANSWER','Good field work does not require instant certainty. If you know the room is humid but do not yet know why, say exactly that. Then gather the next useful evidence. A bounded answer is stronger than a confident guess.'],
 ['10','FIELD READINESS MEANS YOU CAN SHOW YOUR WORK','A ready technician can explain the path: what was reported, what was observed, what was measured, what the evidence supported, what remained unknown, what action was proposed, whether execution was allowed, and what happened afterward. That is much more than memorizing a test answer.']
 ].map(x=><article key={x[0]} style={{...card,display:'grid',gridTemplateColumns:'58px 1fr',gap:16}}><b style={{fontFamily:'Georgia,serif',fontSize:30,color:'#7BAFD4'}}>{x[0]}</b><div><h2 style={{fontFamily:'Georgia,serif',fontSize:25,margin:'2px 0 10px'}}>{x[1]}</h2><p style={{color:'#C9E0EF',lineHeight:1.85,margin:0}}>{x[2]}</p></div></article>)}
 <Deep title="Operating state: what was requested versus what actually happened" plain="If you tell a person to sit down, the request and the result are two different facts. A thermostat can request cooling while some or all equipment fails to respond." technical="Separate commanded state from observed state. Commanded state may include cooling, heating, fan, dehumidification, auxiliary heat or no demand. Observed state includes actual blower, compressor, outdoor fan, valve, heater and control responses." why="Voltage, temperature, pressure and airflow readings can be interpreted incorrectly when the technician assumes the machine is in a state it never actually reached." scenarios={['Setpoint 72°F, room 72°F, cooling call satisfied, compressor off. Compressor-off is expected in that moment and does not establish compressor failure.','Setpoint 70°F, room 76°F, active cooling demand, indoor blower operating, outdoor unit silent. You have established a mismatch between command and observed response—not yet its cause.','Cooling demand active, compressor and fans operating. That establishes operating state, but not correct airflow, charge or capacity.']} />
 <Deep title="Measurement context: every number needs a story" plain="A speed of 60 means something very different for a bicycle, a car and an airplane. The number needs context." technical="Preserve quantity, unit, instrument or data source, measurement point, time/sequence and operating state. Later technical modules will add instrument validity, range, resolution, uncertainty and procedure." why="A technically correct number can support the wrong conclusion if its source, location or state is misunderstood." scenarios={['74°F at the thermostat and 74°F in a supply duct are the same number but represent very different physical conditions.','24 VAC measured across a contactor coil is not the same proposition as 24 VAC measured from one terminal to ground. Measurement points matter.']} />
 <Deep title="Five disciplines, one machine, different questions" plain="A student can have perfect attendance and still fail math. One good result does not prove every other result. HVACD/R systems are similar." technical="Heating, Ventilation, Air Conditioning, Dehumidification and Refrigeration interact through energy, mass flow, controls and equipment operation, but each performance proposition requires appropriate evidence." why="This prevents a technician from using evidence from one domain as automatic proof of another." scenarios={['The blower motor is energized. Electrical state is established; delivered airflow is not.','The room reaches 72°F. Sensible temperature is established at that point; acceptable moisture performance is not automatically established.','Refrigerant pressures are recorded. They must later be interpreted with operating state, airflow, load and measurement context.']} />
 </section>}

 {tab==='words'&&<section style={{paddingBottom:55}}><h2 style={{fontFamily:'Georgia,serif',fontSize:38}}>Six words you must not mix up.</h2><p style={{color:'#C9E0EF',lineHeight:1.8}}>These words look simple. Keeping them separate is one of the most important skills in the course.</p><div style={{display:'grid',gap:10}}>{concepts.map((x,i)=><div key={x[0]} style={{...card,display:'grid',gridTemplateColumns:'150px 1fr 1fr 1fr',gap:15}}><div><b style={{color:'#7BAFD4'}}>{i+1}. {x[0]}</b></div><span style={{color:'#C9E0EF'}}>{x[1]}</span><span style={{color:'#B9D9EB'}}>{x[2]}</span><span style={{color:'#C9E0EF'}}>{x[3]}</span></div>)}</div><div style={{...card,marginTop:14}}><b style={{color:'#B9D9EB'}}>MEMORY TRICK</b><p style={{fontFamily:'Georgia,serif',fontSize:23,lineHeight:1.6}}>Someone <i>says</i> it → you <i>see</i> it → you <i>measure</i> it → you <i>think about</i> it → you <i>establish</i> it → you may eventually <i>change</i> it.</p></div>
 <Deep title="Watch how one sentence can accidentally jump three levels" plain="“The fan is not turning, so the motor is bad, so replace it” sounds efficient—but it combines what you saw, what you think caused it and what you want to do." technical="Observation, inference/diagnosis and proposed consequence are distinct record objects. Each transition requires sufficient support." why="Separating the levels makes reasoning inspectable. Another technician can challenge the diagnosis without disputing the original observation." scenarios={['Observation: condenser fan stationary. Possible causes may include command, power, capacitor, motor, control or mechanical issues. Do not collapse the list prematurely.','Measurement: indoor RH 68%. Inference: moisture removal may be insufficient. Diagnosis and corrective action still require additional evidence.']} />
 <div style={{...card,marginTop:14}}><h3 style={{fontFamily:'Georgia,serif',fontSize:26}}>GOOD RECORD vs. BAD RECORD</h3><p style={{color:'#B9D9EB'}}><b>BAD:</b> “AC bad. Needs fan motor.”</p><p style={{color:'#C9E0EF'}}><b style={{color:'#7BAFD4'}}>BETTER:</b> “Cooling demand active. Indoor blower operating. Outdoor fan observed stationary. Cause not yet established; electrical/control/mechanical examination required.”</p></div>
 </section>}

 {tab==='chain'&&<section style={{paddingBottom:55}}><h2 style={{fontFamily:'Georgia,serif',fontSize:38}}>The path from “something happened” to “something changed.”</h2><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(210px,1fr))',gap:10}}>{chain.map((x,i)=><div key={x} style={card}><b style={{fontFamily:'Georgia,serif',fontSize:30,color:'#7BAFD4'}}>{i+1}</b><h3>{x}</h3><p style={{color:'#C9E0EF',lineHeight:1.6}}>{[
 'What is actually true now.','A preserved representation of what was observed or measured.','Can the record stay connected to its source and context?','Can this evidence be relied on for the proposed purpose?','What does the evidence actually support?','What consequence is being proposed?','The point where an authorized action changes reality.','What became true after the action.'
 ][i]}</p></div>)}</div><div style={{...card,marginTop:14,border:'1px solid #B9D9EB'}}><small style={{color:'#B9D9EB',fontWeight:900}}>THE GOVERNING QUESTION YOU WILL GROW INTO</small><p style={{fontFamily:'Georgia,serif',fontSize:27,lineHeight:1.55}}>Does this proposed consequence have sufficient Admissible Evidence, Applicable Authority, and Established Standing to become reality NOW?</p><p style={{color:'#C9E0EF'}}>You do not need to master that entire question today. Lesson 1.01 teaches you the habit that makes the later question possible: establish reality and preserve a trustworthy record.</p></div>
 <Deep title="The first two anchors deserve patience" plain="Reality is what happened. Record is how you preserve enough of it so someone else can understand what happened." technical="Reality cannot be replaced by the record; the record is a representation of observed/measured reality. Later continuity and admissibility checks ask whether that representation remains attributable and fit for the consequence being considered." why="A weak record forces later reasoning to depend on memory or assumption. A strong record gives later decisions something inspectable to stand on." scenarios={['A technician remembers “humidity was high” but never records the value, instrument, location or time. The later record cannot recover those missing facts.','A technician records 68% RH, instrument ID/source, occupied-zone location, timestamp and system state. Later reviewers can understand exactly what proposition the reading supports.']} />
 </section>}

 {tab==='lab'&&<section style={{paddingBottom:55}}><div style={card}><small style={{color:'#B9D9EB',fontWeight:900}}>FIELD LAB · THE FIRST CALL</small><h2 style={{fontFamily:'Georgia,serif',fontSize:38}}>“It’s not cooling.”</h2><p style={{color:'#C9E0EF',lineHeight:1.85}}>You arrive at a home. The customer says the system is not cooling. The thermostat displays 72°F and the cooling call is satisfied. A separate instrument in the occupied space reads 72°F dry-bulb and 68% RH. The indoor blower and outdoor equipment are operating. You have not yet taken electrical, airflow or refrigerant measurements.</p><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(220px,1fr))',gap:10}}>{[['REPORTED','Customer: “not cooling.”'],['KNOWN','72°F and 68% RH at the stated measurement location.'],['STATE','Cooling call satisfied; equipment observed operating.'],['NOT KNOWN','Why the customer is uncomfortable or why RH is elevated.']].map(x=><div key={x[0]} style={{padding:18,border:'1px solid #316987',borderRadius:14,background:'#031a2e'}}><b style={{color:'#7BAFD4'}}>{x[0]}</b><p style={{color:'#C9E0EF',lineHeight:1.6}}>{x[1]}</p></div>)}</div></div>
 <div style={{...card,marginTop:14}}><h3 style={{fontFamily:'Georgia,serif',fontSize:26}}>What should you say right now?</h3>{['The unit is low on refrigerant.','The complaint is false because the thermostat is at 72°F.','Temperature is presently 72°F, RH is 68%, and the cause of the reported discomfort/moisture condition is not yet established.'].map((x,i)=><button key={x} onClick={()=>setScenario(i+1)} style={{width:'100%',textAlign:'left',padding:15,margin:'7px 0',border:'1px solid #316987',borderRadius:12,background:scenario===i+1?'#104361':'#031a2e',color:'#f7fbff',cursor:'pointer'}}>{x}</button>)}{scenario>0&&<p style={{color:scenario===3?'#7BAFD4':'#B9D9EB',lineHeight:1.75}}><b>{scenario===3?'SUPPORTED':'TOO FAR'}:</b> {scenario===3?'You stated the known conditions and preserved the unknown cause. That is strong field reasoning.':'You jumped from limited information to a conclusion the current record does not establish.'}</p>}</div>
 <Deep title="Three versions of the same service call" plain="The facts can stay the same while the quality of the technician’s reasoning changes." technical="A field-ready learner preserves propositions at their proper evidentiary level and selects the next examination step to reduce uncertainty." why="The goal is not to reward the fastest person to name a component. It is to reward the person who can show why the next step is justified." scenarios={['GUESSER: “68% RH means low refrigerant.” This invents a cause.','RECORDER: “72°F / 68% RH, cooling call satisfied.” Better—the condition is preserved.','EXAMINER: preserves the condition, identifies what remains unknown, and selects the next non-destructive evidence needed to discriminate among plausible causes.']} />
 <div style={{...card,marginTop:14}}><small style={{color:'#B9D9EB',fontWeight:900}}>SCENARIO · THE TEMPTING RESET</small><h3 style={{fontFamily:'Georgia,serif',fontSize:27}}>The thermostat screen looks frozen.</h3><p style={{color:'#C9E0EF',lineHeight:1.8}}>A beginner may immediately pull the thermostat from the wall or cycle power. A stronger first move is to preserve what is displayed, note the commanded state, observe equipment response and consider whether changing power will erase useful information. The lesson is not “never reset.” The lesson is <b>know when your action changes the evidence.</b></p></div>
 </section>}

 {tab==='play'&&<section style={{display:'grid',gap:14,paddingBottom:55}}><div style={card}><small style={{color:'#B9D9EB',fontWeight:900}}>INTERACTION 01 · SORT THE STATEMENT</small><h2 style={{fontFamily:'Georgia,serif',fontSize:28}}>“Indoor RH is 68%.”</h2><div style={{display:'flex',gap:8,flexWrap:'wrap'}}>{['COMPLAINT','OBSERVATION','MEASUREMENT','DIAGNOSIS'].map(x=><button key={x} onClick={()=>choose('s1',x)} style={{padding:'11px 15px',borderRadius:999,border:'1px solid #316987',background:sorts.s1===x?'#7BAFD4':'#031a2e',color:sorts.s1===x?'#001426':'#f7fbff',cursor:'pointer'}}>{x}</button>)}</div>{sorts.s1&&<p style={{color:sorts.s1==='MEASUREMENT'?'#7BAFD4':'#B9D9EB'}}>{sorts.s1==='MEASUREMENT'?'Correct. It is a quantified condition. Now preserve its source, location, time and state.':'Try again. A number collected from a source is a measurement.'}</p>}</div>
 <div style={card}><small style={{color:'#B9D9EB',fontWeight:900}}>INTERACTION 02 · SORT THE STATEMENT</small><h2 style={{fontFamily:'Georgia,serif',fontSize:28}}>“The outdoor fan is not turning.”</h2><div style={{display:'flex',gap:8,flexWrap:'wrap'}}>{['OBSERVATION','DIAGNOSIS','CONSEQUENCE'].map(x=><button key={x} onClick={()=>choose('s2',x)} style={{padding:'11px 15px',borderRadius:999,border:'1px solid #316987',background:sorts.s2===x?'#7BAFD4':'#031a2e',color:sorts.s2===x?'#001426':'#f7fbff',cursor:'pointer'}}>{x}</button>)}</div>{sorts.s2&&<p style={{color:sorts.s2==='OBSERVATION'?'#7BAFD4':'#B9D9EB'}}>{sorts.s2==='OBSERVATION'?'Correct. You saw a condition. You have not yet proven why it exists.':'Not yet. This statement describes what you can see, not why it happened.'}</p>}</div>
 <div style={card}><small style={{color:'#B9D9EB',fontWeight:900}}>INTERACTION 03 · WHAT IS MISSING?</small><h2 style={{fontFamily:'Georgia,serif',fontSize:28}}>Field note: “74°F.”</h2><p style={{color:'#C9E0EF'}}>Choose the best improvement.</p>{['Write it bigger.','Add source/instrument, location, time and operating state.','Call it a diagnosis.'].map((x,i)=><button key={x} onClick={()=>choose('s3',String(i))} style={{display:'block',width:'100%',textAlign:'left',padding:14,margin:'7px 0',border:'1px solid #316987',borderRadius:12,background:sorts.s3===String(i)?'#104361':'#031a2e',color:'#f7fbff',cursor:'pointer'}}>{x}</button>)}{sorts.s3&&<p style={{color:sorts.s3==='1'?'#7BAFD4':'#B9D9EB'}}>{sorts.s3==='1'?'Correct. Now another person can understand what the number represents.':'That does not give the number the context it needs.'}</p>}</div>
 <div style={card}><small style={{color:'#B9D9EB',fontWeight:900}}>INTERACTION 04 · MOISTURE CHECK</small><h2 style={{fontFamily:'Georgia,serif',fontSize:28}}>72°F · 68% RH. Which cause is proven?</h2>{['Low refrigerant','High airflow','Infiltration','None of these yet'].map((x,i)=><button key={x} onClick={()=>choose('s4',String(i))} style={{padding:12,margin:5,border:'1px solid #316987',borderRadius:999,background:sorts.s4===String(i)?'#7BAFD4':'#031a2e',color:sorts.s4===String(i)?'#001426':'#f7fbff',cursor:'pointer'}}>{x}</button>)}{sorts.s4&&<p style={{color:sorts.s4==='3'?'#7BAFD4':'#B9D9EB'}}>{sorts.s4==='3'?'Exactly. The moisture condition is real; its cause still requires examination.':'That may be a hypothesis, but the two readings do not prove it.'}</p>}</div>
 <Deep title="Mini-case: one number, four possible meanings" plain="Numbers do not arrive with explanations attached." technical="Interpretation is conditional on measurement point and system state." why="Learning to ask “where did that number come from?” is a foundational diagnostic reflex." scenarios={['74°F at an occupied-zone sensor may describe space condition.','74°F at return air may describe air entering the equipment.','74°F outdoors describes ambient condition.','74°F at a supply register during an active cooling call would describe a very different proposition and may trigger further examination.']} />
 </section>}

 {tab==='quiz'&&<section style={{paddingBottom:55}}><div style={{display:'flex',justifyContent:'space-between',alignItems:'end',gap:15,flexWrap:'wrap',marginBottom:20}}><div><small style={{color:'#B9D9EB',fontWeight:900}}>FULL LESSON EXAM</small><h2 style={{fontFamily:'Georgia,serif',fontSize:38,margin:'7px 0'}}>25 questions · 80% required</h2><p style={{color:'#C9E0EF'}}>This is not a trick test. Every question checks a habit taught inside this room.</p></div>{submitted&&<b style={{fontFamily:'Georgia,serif',fontSize:32,color:passed?'#7BAFD4':'#B9D9EB'}}>{pct}% · {passed?'PASS':'RE-EXAMINE'}</b>}</div>{qs.map((q,i)=><div key={i} style={{...card,marginBottom:10}}><b style={{color:'#7BAFD4'}}>QUESTION {i+1} / 25</b><h3 style={{fontFamily:'Georgia,serif',fontSize:21,lineHeight:1.45}}>{q.q}</h3>{q.o.map((o,j)=><label key={o} style={{display:'block',padding:'10px 12px',margin:'7px 0',border:'1px solid #316987',borderRadius:10,cursor:'pointer',background:answers[i]===j?'#0d3c59':'transparent'}}><input type="radio" name={'q'+i} checked={answers[i]===j} onChange={()=>{setAnswers({...answers,[i]:j});setSubmitted(false)}}/> <span style={{marginLeft:8}}>{o}</span></label>)}{submitted&&<div style={{padding:12,marginTop:10,borderLeft:'3px solid '+(answers[i]===q.a?'#7BAFD4':'#B9D9EB'),background:'#031a2e'}}><b style={{color:answers[i]===q.a?'#7BAFD4':'#B9D9EB'}}>{answers[i]===q.a?'SUPPORTED':'RE-EXAMINE'}</b><p style={{color:'#C9E0EF',lineHeight:1.6,marginBottom:0}}>{q.e}</p></div>}</div>)}<button disabled={Object.keys(answers).length<25} onClick={()=>setSubmitted(true)} style={{padding:'16px 26px',border:0,borderRadius:999,background:'#7BAFD4',color:'#001426',fontWeight:900,cursor:'pointer',opacity:Object.keys(answers).length<25?.45:1}}>GRADE ALL 25 QUESTIONS →</button>{submitted&&!passed&&<button onClick={()=>{setAnswers({});setSubmitted(false)}} style={{marginLeft:10,padding:'15px 22px',border:'1px solid #B9D9EB',borderRadius:999,background:'transparent',color:'#B9D9EB',fontWeight:900,cursor:'pointer'}}>START RE-EXAMINATION</button>}</section>}

 {tab==='record'&&<section style={{paddingBottom:55}}><div style={card}><small style={{color:'#B9D9EB',fontWeight:900}}>LESSON EVIDENCE OBJECT</small><h2 style={{fontFamily:'Georgia,serif',fontSize:36}}>1.01 Field-Readiness Orientation Record</h2><p style={{color:'#C9E0EF',lineHeight:1.8}}>The browser prototype calculates the assessment state in this session. In the deployed Eight24 learning system, learner identity, timestamps, lesson version, attempts, responses and performance telemetry can be persisted by the LMS/data layer.</p><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(180px,1fr))',gap:10,marginTop:18}}>{[['QUESTIONS','25'],['SCORE',submitted?pct+'%':'NOT SUBMITTED'],['PASS MARK','80%'],['STATE',passed?'COMPLETED':submitted?'RE-EXAMINE':'OPEN']].map(x=><div key={x[0]} style={{padding:18,border:'1px solid #316987',borderRadius:13}}><small style={{color:'#8FB4CC',fontWeight:900}}>{x[0]}</small><p style={{fontFamily:'Georgia,serif',fontSize:21}}>{x[1]}</p></div>)}</div>{passed&&<div style={{marginTop:20,padding:20,border:'1px solid #7BAFD4',borderRadius:14}}><b style={{color:'#7BAFD4'}}>LESSON 1.01 COMPLETE</b><p style={{color:'#C9E0EF'}}>You demonstrated the foundational distinction between what is reported, what is observed, what is measured, and what the evidence actually supports.</p><Link href="/eight24-hvacdr/curriculum/01/lesson/02" style={{display:'inline-block',padding:'13px 18px',borderRadius:999,background:'#7BAFD4',color:'#001426',textDecoration:'none',fontWeight:900}}>CONTINUE WHEN READY →</Link></div>}</div></section>}
 <footer style={{padding:'36px 0 55px',borderTop:'1px solid #285b78',display:'flex',justifyContent:'space-between',gap:15,flexWrap:'wrap'}}><Link href="/eight24-hvacdr/curriculum/01" style={{color:'#B9D9EB',textDecoration:'none',fontSize:10,fontWeight:900}}>MODULE 01 HOME</Link><Link href="/eight24-hvacdr/curriculum/01/lesson/02" style={{color:'#7BAFD4',textDecoration:'none',fontSize:10,fontWeight:900}}>LESSON 1.02 →</Link></footer>
 </div></main>
}