'use client';
import Link from 'next/link';
import {useMemo,useState} from 'react';

const bank=[
 {q:'A customer says the system is “not cooling.” What has been established?',o:['Low refrigerant','Compressor failure','A reported complaint requiring examination','Equipment failure'],a:2,r:'complaint',e:'A complaint belongs in the record, but it is not yet an observation, measurement or diagnosis.'},
 {q:'Which item is an observation rather than a diagnosis?',o:['The compressor is weak','The supply fan is not rotating','The TXV is restricted','The system is undercharged'],a:1,r:'reality',e:'Seeing that the fan is not rotating is an observation. The cause remains unresolved.'},
 {q:'Why must asset identity be preserved?',o:['To make paperwork longer','Because evidence must be attributable to the equipment actually examined','Only for warranty claims','It replaces operating-state documentation'],a:1,r:'record',e:'A measurement without a clear asset relationship can be technically correct yet unusable for the intended conclusion.'},
 {q:'The space is 72°F and 68% RH. What is supported?',o:['Low refrigerant','Insufficient airflow','Temperature and moisture conditions are separately established and moisture requires examination','Compressor underperformance'],a:2,r:'moisture',e:'Temperature and moisture are related but distinct propositions. RH does not identify its cause.'},
 {q:'A thermostat displays 74°F. What additional context strengthens that number as evidence?',o:['Nothing','Source, location, time, operating state and comparison where appropriate','The customer agrees with it','A previous technician saw 74°F'],a:1,r:'measurement',e:'Context establishes where the number came from and what operating reality it represents.'},
 {q:'Which is the strongest definition of field readiness?',o:['Knowing common failures','Passing a written exam','Establishing evidence, making bounded determinations, executing within authority and verifying outcome','Working quickly'],a:2,r:'readiness',e:'Readiness connects knowledge to demonstrated behavior and verified consequences.'},
 {q:'The blower is energized. What does that alone establish?',o:['Correct airflow','Electrical energization/state, not delivered airflow','Correct dehumidification','Correct refrigerant charge'],a:1,r:'boundaries',e:'Evidence from one discipline may inform another, but it does not automatically prove another performance proposition.'},
 {q:'When evidence is insufficient for a diagnosis, the learner should:',o:['Choose the most common fault','Replace the cheapest part','Continue examination or preserve the limitation','Ask the customer to choose a diagnosis'],a:2,r:'limits',e:'The strongest professional conclusion may be that the present record does not yet establish the cause.'},
 {q:'Which statement is a diagnosis rather than a measurement?',o:['Indoor RH is 68%','Contactor coil has 24 VAC across it','The capacitor is the cause of the no-start condition','Outdoor dry-bulb is 91°F'],a:2,r:'classification',e:'The first, second and fourth are measurements. The capacitor statement interprets cause.'},
 {q:'Why does operating state matter?',o:['It does not','A reading can mean different things depending on what the system is commanded and actually doing','Only because of warranty','It replaces instrument identity'],a:1,r:'state',e:'Measurements must be interpreted against commanded and actual system state.'}
];

const technical=[
 ['COMPLAINT','What the customer or prior record reports.','“It is not cooling.”','Preserve it as reported; do not convert it into a cause.'],
 ['OBSERVATION','What is directly perceived or inspected.','Outdoor fan is not rotating.','Record what was observed and under what state.'],
 ['MEASUREMENT','A quantified observation from an identified source.','Indoor RH = 68%.','Preserve instrument/source, location, time and operating state.'],
 ['INFERENCE','A reasoned interpretation supported to some degree by evidence.','Airflow may be affecting coil performance.','Label uncertainty; seek discriminating evidence.'],
 ['DIAGNOSIS','A bounded determination of the condition/cause supported by the record.','A failed component is established by the required evidence.','Do not declare it before the evidence supports it.'],
 ['CONSEQUENCE','A proposed action intended to change reality.','Replace component; adjust airflow; repair leak.','Diagnosis does not itself authorize execution.']
];

export default function Lesson101(){
 const [section,setSection]=useState('brief'); const [answers,setAnswers]=useState<Record<number,number>>({}); const [submitted,setSubmitted]=useState(false); const [checks,setChecks]=useState<Record<string,string>>({});
 const questions=useMemo(()=>bank.slice(0,8),[]); const score=questions.reduce((n,q,i)=>n+(answers[i]===q.a?1:0),0); const pct=Math.round(score/questions.length*100); const passed=submitted&&pct>=80;
 const tabs=[['brief','BRIEFING'],['learn','CORE INSTRUCTION'],['technical','TECHNICAL REFERENCE'],['field','FIELD LAB'],['check','ASSESSMENT'],['record','EVIDENCE RECORD']];
 const card={padding:26,border:'1px solid #214E6D',borderRadius:17,background:'#06243B',boxShadow:'0 16px 40px rgba(0,0,0,.18)'};
 return <main style={{minHeight:'100vh',background:'linear-gradient(180deg,#001426 0%,#001b33 48%,#000f1f 100%)',backgroundAttachment:'fixed',color:'#f4f9fd',fontFamily:'Arial,sans-serif',padding:'0 20px'}}><div style={{maxWidth:1080,margin:'auto'}}>
 <nav style={{padding:'24px 0',display:'flex',justifyContent:'space-between',gap:15,borderBottom:'1px solid #21465f',fontSize:11,fontWeight:900}}><Link href="/eight24-hvacdr/curriculum/01" style={{color:'#7BAFD4',textDecoration:'none'}}>← MODULE 01</Link><span style={{color:'#B9D9EB'}}>LESSON 1.01 · 15 MIN · FOUNDATIONAL INSTRUCTION</span></nav>
 <header style={{padding:'66px 0 32px'}}><p style={{color:'#7BAFD4',fontSize:11,fontWeight:900,letterSpacing:2}}>TA-14 × EIGHT24 · HVACD/R FIELD FOUNDATIONS</p><h1 style={{fontFamily:'Georgia,serif',fontSize:'clamp(44px,7vw,76px)',lineHeight:.98,margin:'14px 0'}}>Welcome to HVACD/R<br/><i>& Field Readiness</i></h1><p style={{maxWidth:880,color:'#C6DCEC',fontSize:18,lineHeight:1.75}}>This lesson establishes the operating discipline for the entire program: begin with present reality, separate what was reported from what was observed and measured, preserve enough context to make evidence usable, and never claim more than the record supports.</p></header>
 <div style={{display:'flex',gap:8,flexWrap:'wrap',paddingBottom:30}}>{tabs.map(t=><button key={t[0]} onClick={()=>setSection(t[0])} style={{cursor:'pointer',border:'1px solid #2C5F7D',background:section===t[0]?'#103B57':'#06243B',color:section===t[0]?'#B9D9EB':'#B8D1E3',padding:'11px 15px',borderRadius:999,fontSize:10,fontWeight:900}}>{t[1]}</button>)}</div>

 {section==='brief'&&<section style={{display:'grid',gap:14,paddingBottom:55}}><div style={card}><small style={{color:'#B9D9EB',fontWeight:900}}>WHY THIS MATTERS</small><h2 style={{fontFamily:'Georgia,serif',fontSize:34}}>A technician changes reality.</h2><p style={{color:'#C6DCEC',lineHeight:1.8}}>Opening equipment, moving a wire, attaching an instrument, changing a control setting, recovering refrigerant or replacing a component can alter the system being examined. Field readiness therefore requires more than knowing facts. The technician must know what is presently true, what evidence supports a conclusion, what remains unresolved, and when an intervention is actually justified.</p></div><div style={{...card,display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(220px,1fr))',gap:14}}>{[['YOU WILL LEARN','Complaint → observation → measurement → inference → diagnosis → consequence'],['YOU WILL PRESERVE','Asset identity, operating state, conditions, source, location and time'],['YOU WILL NOT DO','Diagnose or repair the first “not cooling” condition in this lesson'],['SUCCESS','Stop at the strongest conclusion the available evidence supports']].map(x=><div key={x[0]}><small style={{color:'#7BAFD4',fontWeight:900}}>{x[0]}</small><p style={{color:'#C6DCEC',lineHeight:1.65}}>{x[1]}</p></div>)}</div></section>}

 {section==='learn'&&<section style={{display:'grid',gap:14,paddingBottom:55}}>{[
 ['01','FIELD READINESS IS DIFFERENT FROM KNOWLEDGE','Knowledge answers “what do I know?” Field readiness asks whether you can apply that knowledge to a specific asset, under a specific operating condition, using valid observations and measurements, without outrunning the evidence. A learner can memorize a refrigeration cycle and still be unprepared to decide whether refrigerant-system entry is justified on a particular call.'],
 ['02','START WITH REALITY, NOT THE CUSTOMER’S DIAGNOSIS','The service call often arrives preloaded with conclusions: “needs Freon,” “bad thermostat,” “blower is weak,” or “it just needs a capacitor.” Preserve those statements as complaint/history. Then establish present conditions independently. The report may be useful context, but it does not become true merely because someone said it.'],
 ['03','IDENTIFY THE ASSET BEFORE ATTRIBUTING EVIDENCE','Evidence must belong to something. Establish the equipment or system being examined: equipment type, indoor/outdoor relationship where applicable, manufacturer/model/serial when available, control arrangement, location and any relevant configuration. If two systems serve adjacent spaces, a valid temperature measurement attributed to the wrong asset can corrupt the record.'],
 ['04','ESTABLISH OPERATING STATE','Record what the equipment is commanded to do and what it is actually doing. Cooling call present or satisfied? Heating? Fan only? Dehumidification call? Compressor energized? Indoor blower operating? Outdoor fan operating? Auxiliary heat? Defrost? A pressure, temperature, voltage or current reading without state can be technically accurate yet misleading.'],
 ['05','PRESERVE MEASUREMENT CONTEXT','A number is not self-explanatory. Preserve what was measured, the source/instrument, where it was measured, when it was measured, and the operating state. “74°F” could be a thermostat display, return-air temperature, supply-air temperature, outdoor temperature or an unverified BAS point. Those are not interchangeable evidence.'],
 ['06','HVACD/R HAS MULTIPLE PERFORMANCE PROPOSITIONS','Heating, Ventilation, Air Conditioning, Dehumidification and Refrigeration interact. They do not collapse into one conclusion. A space can reach 72°F while remaining at 68% RH. Electrical energization does not prove airflow. Cooling does not automatically prove acceptable Dehumidification. Refrigeration readings do not erase airflow and load context.'],
 ['07','STOP WHERE THE EVIDENCE STOPS','Professional judgment includes refusing to manufacture certainty. If the evidence establishes a symptom but not its cause, preserve that limitation and continue the examination. A supported HOLD or request for additional evidence is stronger than a lucky repair selected from habit.']
 ].map(x=><article key={x[0]} style={{...card,display:'grid',gridTemplateColumns:'55px 1fr',gap:16}}><b style={{fontFamily:'Georgia,serif',fontSize:28,color:'#7BAFD4'}}>{x[0]}</b><div><h2 style={{fontFamily:'Georgia,serif',fontSize:25,margin:'2px 0 10px'}}>{x[1]}</h2><p style={{color:'#C6DCEC',lineHeight:1.8,margin:0}}>{x[2]}</p></div></article>)}
 <div style={{...card,borderLeft:'4px solid #7BAFD4'}}><small style={{color:'#B9D9EB',fontWeight:900}}>PROGRAM LINE</small><p style={{fontFamily:'Georgia,serif',fontSize:25,lineHeight:1.6}}>Reality → Record → Continuity → Admissibility → Binding → Commit → Execution → Outcome</p><p style={{color:'#C6DCEC',lineHeight:1.7}}>Lesson 1.01 begins with the first two anchors. Later modules establish how records maintain continuity, become admissible, support determinations, cross the execution boundary and are verified against the resulting reality.</p></div></section>}

 {section==='technical'&&<section style={{paddingBottom:55}}><h2 style={{fontFamily:'Georgia,serif',fontSize:38}}>Technical language for the field record.</h2><p style={{color:'#C6DCEC',lineHeight:1.75,maxWidth:850}}>These terms are intentionally separated because collapsing them is one of the fastest ways to turn a service call into unsupported diagnosis.</p><div style={{display:'grid',gap:10}}>{technical.map(x=><div key={x[0]} style={{...card,display:'grid',gridTemplateColumns:'150px 1fr 1fr 1fr',gap:14,alignItems:'start'}}><b style={{color:'#7BAFD4'}}>{x[0]}</b><span style={{color:'#C6DCEC'}}>{x[1]}</span><span style={{color:'#B9D9EB'}}>{x[2]}</span><span style={{color:'#C6DCEC'}}>{x[3]}</span></div>)}</div><div style={{...card,marginTop:14}}><small style={{color:'#B9D9EB',fontWeight:900}}>MINIMUM ORIENTATION RECORD</small><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(200px,1fr))',gap:10,marginTop:12}}>{['Asset / system identity','Complaint as reported','Commanded operating mode','Observed operating state','Indoor temperature + source/location','Indoor RH + source/location','Outdoor condition where relevant','Instrument / data source','Time / sequence','Known limitations'].map(x=><div key={x} style={{padding:13,border:'1px solid #214E6D',borderRadius:10,color:'#C6DCEC'}}>✓ {x}</div>)}</div></div></section>}

 {section==='field'&&<section style={{paddingBottom:55}}><div style={{...card,background:'#031B2F'}}><small style={{color:'#B9D9EB',fontWeight:900}}>FIELD LAB · FIRST SERVICE CALL</small><h2 style={{fontFamily:'Georgia,serif',fontSize:37}}>Complaint: “It’s not cooling.”</h2><p style={{color:'#C6DCEC',lineHeight:1.8}}>You arrive at a residence. The wall thermostat displays 72°F and the cooling call is satisfied. A separate indoor instrument at the occupied zone reports 72°F dry-bulb and 68% RH. The indoor and outdoor equipment are operating. No electrical, airflow or refrigerant measurements have yet been taken.</p><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(210px,1fr))',gap:10,marginTop:18}}>{[['REPORTED','“Not cooling” complaint'],['OBSERVED / MEASURED','72°F · 68% RH'],['OPERATING STATE','Cooling call satisfied; equipment operating'],['UNRESOLVED','Cause of complaint and elevated moisture']].map(x=><div key={x[0]} style={{padding:18,border:'1px solid #214E6D',borderRadius:12,background:'#06243B'}}><small style={{color:'#7BAFD4',fontWeight:900}}>{x[0]}</small><p style={{fontFamily:'Georgia,serif',fontSize:18}}>{x[1]}</p></div>)}</div></div>
 <div style={{...card,marginTop:14}}><small style={{color:'#B9D9EB',fontWeight:900}}>EMBEDDED CHECK</small><h3 style={{fontFamily:'Georgia,serif',fontSize:25}}>Which statement is strongest right now?</h3>{['The system is low on refrigerant.','The complaint is disproven because temperature is 72°F.','Sensible temperature is presently 72°F; moisture is elevated; the cause of the complaint and moisture condition is not yet established.'].map((x,i)=><button key={x} onClick={()=>setChecks({...checks,field:String(i)})} style={{display:'block',width:'100%',textAlign:'left',margin:'8px 0',padding:14,border:'1px solid #214E6D',borderRadius:10,background:checks.field===String(i)?'#103B57':'#031B2F',color:'#f4f9fd',cursor:'pointer'}}>{x}</button>)}{checks.field&&<p style={{color:checks.field==='2'?'#7BAFD4':'#B9D9EB',lineHeight:1.7}}><b>{checks.field==='2'?'SUPPORTED':'RE-EXAMINE'}:</b> {checks.field==='2'?'This preserves the known temperature and moisture conditions while leaving cause unresolved.':'That conclusion goes beyond the evidence currently available.'}</p>}</div></section>}

 {section==='check'&&<section style={{paddingBottom:55}}><div style={{display:'flex',justifyContent:'space-between',alignItems:'end',gap:15,flexWrap:'wrap',marginBottom:20}}><div><small style={{color:'#B9D9EB',fontWeight:900}}>FINAL ASSESSMENT · QUESTION BANK</small><h2 style={{fontFamily:'Georgia,serif',fontSize:36,margin:'7px 0'}}>8 questions · 80% required</h2></div>{submitted&&<b style={{fontFamily:'Georgia,serif',fontSize:32,color:passed?'#7BAFD4':'#B9D9EB'}}>{pct}% · {passed?'PASS':'RE-EXAMINE'}</b>}</div>{questions.map((q,i)=><div key={q.q} style={{...card,marginBottom:12}}><b style={{color:'#7BAFD4'}}>0{i+1}</b><h3 style={{fontFamily:'Georgia,serif',fontSize:21,lineHeight:1.45}}>{q.q}</h3>{q.o.map((o,j)=><label key={o} style={{display:'block',padding:'10px 12px',margin:'7px 0',border:'1px solid #214E6D',borderRadius:10,cursor:'pointer'}}><input type="radio" name={'q'+i} checked={answers[i]===j} onChange={()=>{setAnswers({...answers,[i]:j});setSubmitted(false)}}/> <span style={{marginLeft:8}}>{o}</span></label>)}{submitted&&<div style={{marginTop:12,padding:13,borderLeft:'3px solid '+(answers[i]===q.a?'#7BAFD4':'#B9D9EB'),background:'#031B2F'}}><p style={{color:answers[i]===q.a?'#7BAFD4':'#B9D9EB',margin:'0 0 6px'}}><b>{answers[i]===q.a?'SUPPORTED':'RE-EXAMINE'}</b></p><p style={{color:'#C6DCEC',lineHeight:1.6,margin:0}}>{q.e}</p>{answers[i]!==q.a&&<button onClick={()=>setSection(q.r==='moisture'||q.r==='boundaries'?'learn':q.r==='measurement'||q.r==='classification'?'technical':q.r==='complaint'||q.r==='reality'?'field':'learn')} style={{marginTop:10,border:'1px solid #7BAFD4',borderRadius:999,padding:'8px 12px',background:'transparent',color:'#7BAFD4',fontWeight:900,cursor:'pointer'}}>REVIEW RELEVANT INSTRUCTION →</button>}</div>}</div>)}<button onClick={()=>setSubmitted(true)} disabled={Object.keys(answers).length<questions.length} style={{cursor:'pointer',border:0,borderRadius:999,padding:'15px 24px',fontWeight:900,background:'#7BAFD4',color:'#001426',opacity:Object.keys(answers).length<questions.length?.45:1}}>SUBMIT ASSESSMENT →</button>{submitted&&!passed&&<button onClick={()=>{setAnswers({});setSubmitted(false)}} style={{marginLeft:10,cursor:'pointer',border:'1px solid #B9D9EB',borderRadius:999,padding:'14px 24px',fontWeight:900,background:'transparent',color:'#B9D9EB'}}>RE-EXAMINE</button>}</section>}

 {section==='record'&&<section style={{paddingBottom:55}}><div style={card}><small style={{color:'#B9D9EB',fontWeight:900}}>LESSON EVIDENCE OBJECT</small><h2 style={{fontFamily:'Georgia,serif',fontSize:34}}>1.01 Field-Readiness Orientation Record</h2><p style={{color:'#C6DCEC',lineHeight:1.75}}>The lesson record preserves the lesson/version, assessment result and completion state. In the deployed learner system, identity, timestamps, attempt history and response telemetry can be persisted through the Eight24/LMS layer.</p><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(180px,1fr))',gap:10,marginTop:20}}>{[['LESSON','1.01'],['ASSESSMENT',submitted?pct+'%':'NOT SUBMITTED'],['STATE',passed?'COMPLETED':submitted?'RE-EXAMINE':'OPEN'],['NEXT','1.02']].map(x=><div key={x[0]} style={{padding:18,border:'1px solid #214E6D',borderRadius:12}}><small style={{color:'#8FB4CC',fontWeight:900}}>{x[0]}</small><p style={{fontFamily:'Georgia,serif',fontSize:20,margin:'7px 0'}}>{x[1]}</p></div>)}</div>{passed&&<Link href="/eight24-hvacdr/curriculum/01/lesson/02" style={{display:'inline-block',marginTop:22,padding:'14px 20px',borderRadius:999,background:'#7BAFD4',color:'#001426',textDecoration:'none',fontWeight:900}}>CONTINUE TO LESSON 1.02 →</Link>}</div></section>}
 <footer style={{padding:'35px 0 55px',borderTop:'1px solid #21465f',display:'flex',justifyContent:'space-between',gap:15,flexWrap:'wrap'}}><span style={{color:'#89A9BF',fontSize:10}}>GOLD-STANDARD LIVING LESSON · SELF-GRADING CANDIDATE</span><b style={{color:'#B9D9EB',fontSize:10}}>NO ADMISSIBLE EVIDENCE. NO ADMISSIBLE EXECUTION.</b></footer>
 </div></main>
}