'use client';
import Link from 'next/link';
import {usePathname} from 'next/navigation';
import type {ReactNode} from 'react';
import {useMemo,useState} from 'react';
type NavItem={label:string;href:string;glyph:string;academy:string;group:'Start'|'Operate'|'Requirements'|'Evidence & Review'|'Learn'};
const nav:NavItem[]=[
 {label:'EU AI Act Home',href:'/eu-ai-act',glyph:'EU',academy:'overview',group:'Start'},{label:'Start Here',href:'/eu-ai-act/start',glyph:'01',academy:'start-here',group:'Start'},
 {label:'Command Center',href:'/eu-ai-act/command-center',glyph:'CC',academy:'command-center',group:'Operate'},{label:'System Passport',href:'/eu-ai-act/system-passport',glyph:'SP',academy:'system-passport',group:'Operate'},{label:'Classifier',href:'/eu-ai-act/classifier',glyph:'CL',academy:'classifier',group:'Operate'},
 {label:'Legal Source State',href:'/eu-ai-act/source-state',glyph:'LS',academy:'source-state',group:'Requirements'},{label:'Article 50 Transparency',href:'/eu-ai-act#article-50-workspace',glyph:'50',academy:'article-50',group:'Requirements'},{label:'Requirements Explorer',href:'/eu-ai-act#requirements-explorer',glyph:'RX',academy:'requirements-explorer',group:'Requirements'},{label:'Prohibited Practices',href:'/eu-ai-act#requirements-explorer',glyph:'P5',academy:'prohibited-practices',group:'Requirements'},{label:'High-Risk AI',href:'/eu-ai-act#requirements-explorer',glyph:'HR',academy:'high-risk-ai',group:'Requirements'},{label:'GPAI',href:'/eu-ai-act#requirements-roadmap',glyph:'GP',academy:'gpai',group:'Requirements'},{label:'FRIA',href:'/eu-ai-act#requirements-explorer',glyph:'FR',academy:'fria',group:'Requirements'},
 {label:'Governed Records',href:'/workspace/governed-records/eu-ai-act',glyph:'GR',academy:'governed-records',group:'Evidence & Review'},{label:'Evidence Passport',href:'/eu-ai-act/passport',glyph:'EP',academy:'evidence-passport',group:'Evidence & Review'},{label:'Proof Lab',href:'/eu-ai-act/proof-lab',glyph:'PL',academy:'proof-lab',group:'Evidence & Review'},{label:'Change & Revalidation',href:'/eu-ai-act/source-state#revalidation',glyph:'RV',academy:'revalidation',group:'Evidence & Review'},{label:'Controlled Examination',href:'/eu-ai-act/command-center',glyph:'EX',academy:'controlled-examination',group:'Evidence & Review'},
 {label:'EU AI Act Academy',href:'/academy/eu-ai-act',glyph:'AC',academy:'overview',group:'Learn'},{label:'Access & Plans',href:'/eu-ai-act/commercial',glyph:'$',academy:'access-and-plans',group:'Learn'}];
const routeAcademy:[string,string][]=[['/eu-ai-act/source-state','source-state'],['/eu-ai-act/command-center','command-center'],['/eu-ai-act/system-passport','system-passport'],['/eu-ai-act/classifier','classifier'],['/eu-ai-act/passport','evidence-passport'],['/eu-ai-act/proof-lab','proof-lab'],['/eu-ai-act/commercial','access-and-plans'],['/eu-ai-act/start','start-here'],['/eu-ai-act','overview']];
function active(path:string,item:NavItem){if(item.href.includes('#'))return false;if(item.href==='/eu-ai-act')return path==='/eu-ai-act';return path===item.href||path.startsWith(`${item.href}/`)}
export default function EUAIActWorldLayout({children}:{children:ReactNode}){const pathname=usePathname(),[open,setOpen]=useState(false);const academy=useMemo(()=>routeAcademy.find(([r])=>pathname===r||pathname.startsWith(`${r}/`))?.[1]??'overview',[pathname]);const groups=['Start','Operate','Requirements','Evidence & Review','Learn'] as const;const isHome=pathname==='/eu-ai-act';return <div className="euShell"><style>{`
.euShell{min-height:100vh;background:#02050a;color:#eef7ff}.euSide{position:fixed;inset:0 auto 0 0;z-index:1200;width:276px;overflow:auto;padding:16px 13px 24px;border-right:1px solid #7ee6ff25;background:radial-gradient(circle at 50% 0,#4cc9f021,transparent 24%),#02080ff5;backdrop-filter:blur(24px)}.euBrand{display:grid;grid-template-columns:44px 1fr;gap:10px;align-items:center;padding:8px 8px 15px;color:#fff;text-decoration:none;border-bottom:1px solid #7ee6ff20}.euMark{width:44px;height:44px;display:grid;place-items:center;border:1px solid #7ee6ff61;border-radius:14px;background:#2ab8e240;color:#aef3ff;font-size:11px;font-weight:950;box-shadow:0 0 26px #35d4ff20,inset 0 0 18px #75efff12}.euBrand strong{display:block;font-size:12px}.euBrand small{display:block;margin-top:3px;color:#7f9cb1;font-size:9px}.euBack{display:flex;justify-content:center;margin:13px 7px 17px;padding:11px;border:1px solid #ffffff18;border-radius:11px;color:#bed1df;text-decoration:none;font-size:10px;font-weight:850}.euGroup{margin-top:13px}.euGroup>span{display:block;padding:0 10px 7px;color:#58758c;font-size:8px;font-weight:950;letter-spacing:.17em;text-transform:uppercase}.euNav{display:grid;gap:4px}.euItem{display:grid;grid-template-columns:31px 1fr;gap:9px;align-items:center;min-height:43px;padding:6px 9px;border:1px solid transparent;border-radius:11px;color:#9fb6c8;text-decoration:none;font-size:11px;font-weight:760;transition:.18s ease}.euItem:hover,.euItem.on{color:#fff;border-color:#7ee6ff2e;background:#7ee6ff0e;transform:translateX(2px)}.euItem.on{box-shadow:inset 3px 0 #7ee6ff,0 8px 24px #0005}.euGlyph{width:30px;height:30px;display:grid;place-items:center;border:1px solid #ffffff12;border-radius:9px;color:#7ee6ff;font-size:8px;font-weight:950;background:linear-gradient(145deg,#0b1a29,#051019)}.euHelp{margin:18px 7px 0;padding:14px;border:1px solid #f2c45640;border-radius:14px;background:linear-gradient(145deg,#f2c45614,#f2c45606);box-shadow:0 16px 40px #0004}.euHelp b{color:#f3d889;font-size:9px}.euHelp p{color:#9eb1bf;font-size:10px;line-height:1.5}.euHelp a{display:flex;justify-content:center;padding:9px;border-radius:9px;background:linear-gradient(135deg,#f2c456,#fff0ae);color:#091019;text-decoration:none;font-size:9px;font-weight:950;box-shadow:0 8px 24px #f2c45620}.euMain{margin-left:276px;min-width:0}.euTop{position:relative;z-index:1000;display:flex;justify-content:center;align-items:center;gap:14px;flex-wrap:wrap;padding:9px 18px;background:linear-gradient(90deg,#071a36,#0b315d,#071a36);border-bottom:1px solid #6ad5ff59;font:10px Inter,system-ui,sans-serif;letter-spacing:.08em;box-shadow:0 8px 30px #0007}.euTop strong{color:#7ee6ff}.euTop span{color:#b7cce0}.euTop a{padding:7px 11px;border-radius:999px;color:#071a36;background:#7ee6ff;text-decoration:none;font-weight:900;box-shadow:0 0 22px #7ee6ff2c}.euMenu{display:none}

/* EU AI Act home: layered institutional world rather than a flat dashboard */
.euMain.home .page-shell{position:relative;isolation:isolate;overflow:hidden;background:
radial-gradient(circle at 78% 5%,#1d5ea42f 0,transparent 28%),
radial-gradient(circle at 15% 18%,#16d8ff19 0,transparent 30%),
linear-gradient(180deg,#020812 0%,#02060c 36%,#03070d 100%)}
.euMain.home .page-shell:before{content:"";position:fixed;inset:42px 0 0 276px;pointer-events:none;z-index:-1;opacity:.22;background-image:linear-gradient(#7ee6ff0a 1px,transparent 1px),linear-gradient(90deg,#7ee6ff0a 1px,transparent 1px);background-size:72px 72px;mask-image:linear-gradient(to bottom,#000,transparent 75%)}
.euMain.home .content-shell{position:relative;z-index:2;max-width:1540px;margin:0 auto;padding-left:clamp(22px,4vw,72px);padding-right:clamp(22px,4vw,72px)}
.euMain.home .breadcrumbs{opacity:.82}
.euMain.home .hero{position:relative;margin-top:18px;padding:clamp(34px,5vw,72px);border:1px solid #74e4ff2d;border-radius:30px;background:linear-gradient(135deg,#071421e8 0%,#07101ae8 48%,#091423d9 100%);box-shadow:0 34px 90px #0008,0 0 0 1px #ffffff04 inset,0 0 80px #13b9ff0b;overflow:hidden}
.euMain.home .hero:before{content:"";position:absolute;width:520px;height:520px;right:-190px;top:-210px;border:1px solid #7ee6ff22;border-radius:50%;box-shadow:0 0 0 55px #7ee6ff08,0 0 0 110px #7ee6ff05;animation:euOrbitPulse 10s ease-in-out infinite}
.euMain.home .hero:after{content:"";position:absolute;inset:auto -10% -160px 35%;height:260px;background:radial-gradient(ellipse,#31cfff1e,transparent 65%);filter:blur(12px);pointer-events:none}
.euMain.home .hero>div,.euMain.home .deadline-panel{position:relative;z-index:2}
.euMain.home .hero h1{max-width:900px;font-size:clamp(42px,5.1vw,82px);line-height:.97;letter-spacing:-.045em;text-wrap:balance;text-shadow:0 16px 50px #000}.euMain.home .hero h1 em{font-style:normal;background:linear-gradient(90deg,#fff,#a8efff 55%,#f6d77f);-webkit-background-clip:text;background-clip:text;color:transparent}.euMain.home .hero-copy{max-width:860px;font-size:clamp(15px,1.2vw,19px);line-height:1.75;color:#a9bfd0}
.euMain.home .eyebrow{letter-spacing:.2em;color:#77e5ff;text-shadow:0 0 20px #55dfff44}
.euMain.home .action-row{gap:12px;margin-top:28px}.euMain.home .button{min-height:46px;padding:0 18px;border-radius:13px;transition:transform .18s ease,box-shadow .18s ease,border-color .18s ease}.euMain.home .button:hover{transform:translateY(-2px);box-shadow:0 14px 32px #0007}.euMain.home .primary-button{box-shadow:0 0 28px #38d8ff20}.euMain.home .gold-button{box-shadow:0 0 28px #f2c4561c}
.euMain.home .deadline-panel{gap:14px}.euMain.home .deadline-card{position:relative;border:1px solid #7ee6ff2b;border-radius:20px;background:linear-gradient(145deg,#071a2bdd,#06111ddd);box-shadow:0 22px 50px #0007,inset 0 1px #ffffff08;overflow:hidden}.euMain.home .deadline-card:before{content:"";position:absolute;inset:0 auto 0 0;width:3px;background:linear-gradient(#7ee6ff,#2e83ff00)}.euMain.home .deadline-card.command{border-color:#f2c45645;background:linear-gradient(145deg,#1b1824,#0a1420)}.euMain.home .deadline-card.command:before{background:linear-gradient(#f2c456,#f2c45600)}
.euMain.home .legal-boundary{margin-top:18px;border-radius:18px;border-color:#f2c45630;background:linear-gradient(90deg,#f2c45612,#07111b99);box-shadow:0 16px 40px #0004}
.euMain.home .status-grid{gap:14px;margin-top:18px}.euMain.home .status-grid article{position:relative;min-height:170px;border-radius:20px;border-color:#7ee6ff1f;background:linear-gradient(155deg,#071421d9,#040b12d9);box-shadow:0 18px 44px #0005;transition:.2s ease;overflow:hidden}.euMain.home .status-grid article:hover{transform:translateY(-4px);border-color:#7ee6ff48;box-shadow:0 24px 55px #0008,0 0 35px #37d8ff0d}.euMain.home .status-grid article:after{content:"";position:absolute;right:-30px;bottom:-35px;width:110px;height:110px;border:1px solid #7ee6ff16;border-radius:50%}
.euMain.home .command-teaser{position:relative;margin-top:28px;border:1px solid #7ee6ff2c;border-radius:28px;background:linear-gradient(120deg,#071829e8,#07101be8 58%,#101827e0);box-shadow:0 28px 70px #0007;overflow:hidden}.euMain.home .command-teaser:after{content:"";position:absolute;right:-80px;top:-100px;width:340px;height:340px;background:radial-gradient(circle,#7ee6ff15,transparent 68%);pointer-events:none}.euMain.home .teaser-grid article{border-radius:16px;background:linear-gradient(145deg,#071a27,#050c14);box-shadow:inset 0 1px #ffffff08}.euMain.home .teaser-grid strong{font-size:clamp(26px,2.2vw,40px);text-shadow:0 0 28px #7ee6ff2b}
.euMain.home .page-section{margin-top:clamp(70px,8vw,112px)}.euMain.home .section-heading h2{font-size:clamp(30px,3.2vw,50px);letter-spacing:-.03em}.euMain.home .section-heading p{max-width:760px;color:#8fa8ba;line-height:1.75}
.euMain.home .role-grid,.euMain.home .requirements-grid{gap:14px}.euMain.home .role-card,.euMain.home .requirement-card{position:relative;border-radius:20px;border-color:#7ee6ff1e;background:linear-gradient(155deg,#07131fd9,#040a11e8);box-shadow:0 14px 36px #0004;transition:.2s ease;overflow:hidden}.euMain.home .role-card:hover,.euMain.home .requirement-card:hover{transform:translateY(-5px);border-color:#7ee6ff50;box-shadow:0 22px 54px #0008,0 0 36px #18ccff0d}.euMain.home .role-code{box-shadow:0 0 24px #7ee6ff18}.euMain.home .guided-panel{margin-top:28px;border-radius:24px;background:linear-gradient(120deg,#081a2a,#0a1320);box-shadow:0 22px 55px #0006;border-color:#7ee6ff29}.euMain.home .guided-orb{box-shadow:0 0 0 8px #7ee6ff08,0 0 38px #7ee6ff20}
.euMain.home .progress-grid article,.euMain.home .source-grid article,.euMain.home .record-grid article,.euMain.home .connected-grid article{border-radius:18px;background:linear-gradient(155deg,#07131f,#040a11);box-shadow:0 14px 34px #0004}
.euMain.home .pathway-card{border-radius:24px;background:linear-gradient(150deg,#071521,#050b12);box-shadow:0 20px 50px #0006}.euMain.home .pathway-card:hover{box-shadow:0 28px 70px #0008,0 0 42px #39d8ff0a}
.euMain.home .final-cta{border-radius:30px;background:radial-gradient(circle at 70% 30%,#3bd9ff15,transparent 35%),linear-gradient(125deg,#071a2b,#08101a 60%,#161827);box-shadow:0 34px 80px #0008;border-color:#7ee6ff32}
@keyframes euOrbitPulse{0%,100%{transform:scale(.96) rotate(0);opacity:.5}50%{transform:scale(1.04) rotate(10deg);opacity:.9}}
@media(max-width:900px){.euSide{transform:translateX(-102%);transition:.2s;width:min(86vw,300px)}.euSide.open{transform:none}.euMain{margin-left:0}.euMenu{display:block;position:fixed;right:14px;bottom:14px;z-index:1300;width:52px;height:52px;border:1px solid #7ee6ff73;border-radius:50%;background:#082039;color:#bff5ff;font-weight:950}.euMain.home .page-shell:before{inset:42px 0 0 0}.euMain.home .hero{padding:28px 22px;border-radius:22px}.euMain.home .hero h1{font-size:clamp(38px,12vw,64px)}}
`}</style><aside className={`euSide ${open?'open':''}`}><Link className="euBrand" href="/eu-ai-act"><span className="euMark">EU</span><span><strong>EU AI ACT</strong><small>Governed operating environment</small></span></Link><Link className="euBack" href="/">← TA-14 AI Governance Exchange</Link>{groups.map(g=><div className="euGroup" key={g}><span>{g}</span><nav className="euNav">{nav.filter(x=>x.group===g).map(x=><Link key={x.label} href={x.href} className={`euItem ${active(pathname,x)?'on':''}`} onClick={()=>setOpen(false)}><span className="euGlyph">{x.glyph}</span><span>{x.label}</span></Link>)}</nav></div>)}<div className="euHelp"><b>NEED HELP?</b><p>Learn what this page does, what you need, how to complete it, and what happens next.</p><Link href={`/academy/eu-ai-act/${academy}`}>UNDERSTAND THIS PAGE →</Link></div></aside><button className="euMenu" onClick={()=>setOpen(v=>!v)}>{open?'×':'EU'}</button><div className={`euMain ${isHome?'home':''}`}><div className="euTop"><strong>EU AI ACT · OPERATING ENVIRONMENT</strong><span>Know what applies · prove why · preserve change</span><Link href={`/academy/eu-ai-act/${academy}`}>? LEARN THIS PAGE</Link></div>{children}</div></div>}
