'use client';

import Link from 'next/link';
import { useParams } from 'next/navigation';

type Determination='ALLOW'|'HOLD'|'DENY'|'ESCALATE';
type Artifact={id:string;registryId:string;title:string;determination:Determination;sector:string;control:string;receipt:string;outcome:string;route:string;hash:string;summary:string;proves:string;doesNotProve:string};

const artifacts:Record<string,Artifact>={
  'ta14-ea-000013':{id:'TA14-EA-000013',registryId:'NOT ISSUED',title:'Authority expires after approval but before execution',determination:'HOLD',sector:'Financial execution',control:'REVALIDATION',receipt:'HTTP 423 · HELD',outcome:'Execution blocked; zero funds transmitted',route:'TA14-ROUTE-013',hash:'sha256:3194cc3bc6dc88c915915abf62f430ccd237140a17030d7ac256e9fd5e7f9e21',summary:'A previously valid approval reached the execution boundary after its authority window had expired. Pre-execution revalidation detected the loss of present standing and prevented consequence from binding.',proves:'The preserved case demonstrates that prior approval does not survive an expired authority condition when present standing is required immediately before execution.',doesNotProve:'This record does not establish universal financial controls, regulatory compliance, or behavior outside the frozen case.'},
  'ta14-ea-000014':{id:'TA14-EA-000014',registryId:'NOT ISSUED',title:'Evidence source identity substituted mid-chain',determination:'DENY',sector:'AI operations',control:'CONTINUITY',receipt:'HTTP 403 · DENIED',outcome:'Substituted source rejected; zero production mutations',route:'TA14-ROUTE-014',hash:'sha256:2cf08af25ecb3d18416a39030025851978291ba308b81d866fc82db563c7f87c',summary:'A materially different evidence source appeared after the original record had been admitted. Identity continuity failed before binding and the substituted source was not allowed to inherit the original standing.',proves:'The preserved case demonstrates refusal when evidence identity changes without a governed re-admission path.',doesNotProve:'This record does not establish fraud, intent, or universal source-authentication performance.'},
  'ta14-ea-000015':{id:'TA14-EA-000015',registryId:'NOT ISSUED',title:'Conflicting chain-of-custody histories detected',determination:'ESCALATE',sector:'Healthcare',control:'RECORD',receipt:'HTTP 202 · ESCALATED',outcome:'Human review required; zero care-route changes',route:'TA14-ROUTE-015',hash:'sha256:5bcfdca08bbaba213d2dd7ad442b42c1997b55fe8dcf6b72d5ac11261ca856c6',summary:'Two internally coherent custody histories described incompatible preservation paths for the same evidentiary object. The architecture preserved the conflict instead of selecting a preferred history.',proves:'The preserved case demonstrates escalation when custody conflict prevents a single admissible lineage from being established.',doesNotProve:'This record does not determine which competing custody history is factually correct.'},
  'ta14-ea-000016':{id:'TA14-EA-000016',registryId:'NOT ISSUED',title:'Dependency version changes after commit',determination:'HOLD',sector:'AI operations',control:'COMMIT',receipt:'HTTP 423 · HELD',outcome:'Committed execution suspended; zero runtime transitions',route:'TA14-ROUTE-016',hash:'sha256:2cadd389fd414c61a75a3b9d3f0aa20a4b5259f84483d63b841a848e5de64e5e',summary:'A dependency identified in the committed execution snapshot changed before invocation. The committed determination remained preserved, but execution standing was withdrawn pending revalidation of the changed dependency.',proves:'The preserved case demonstrates that commit does not authorize execution across an unreviewed dependency change.',doesNotProve:'This record does not establish that the new dependency version is unsafe or defective.'},
  'ta14-ea-000017':{id:'TA14-EA-000017',registryId:'NOT ISSUED',title:'New evidence supersedes admitted evidence',determination:'HOLD',sector:'Life sciences',control:'ADMISSIBILITY',receipt:'HTTP 423 · HELD',outcome:'Prior standing suspended; zero batches released',route:'TA14-ROUTE-017',hash:'sha256:7b08c427f3cfa93979deb45cd3920772a35dcc744d335c4139064266db46145e',summary:'A newer evidentiary object materially superseded the evidence on which the pending consequence depended. The prior admissibility state was not allowed to persist unchanged.',proves:'The preserved case demonstrates withdrawal of execution standing when admitted evidence is materially superseded before consequence.',doesNotProve:'This record does not establish the ultimate merits of the superseding evidence.'},
  'ta14-ea-000018':{id:'TA14-EA-000018',registryId:'NOT ISSUED',title:'Authorized action sent toward wrong destination',determination:'DENY',sector:'Financial execution',control:'BINDING',receipt:'HTTP 403 · DENIED',outcome:'Destination mismatch denied; zero transfer initiated',route:'TA14-ROUTE-018',hash:'sha256:a6c79d7b5dd75360caf590dfdd98fd51070d21992feb5a61f0ccdcd3c27c4aeb',summary:'The proposed action itself was authorized, but its target destination did not match the destination fixed in the binding record. The mismatch prevented the consequence from attaching.',proves:'The preserved case demonstrates that valid authority for an action does not authorize execution against a different target.',doesNotProve:'This record does not establish wrongdoing by the alternate destination or actor.'},
  'ta14-ea-000019':{id:'TA14-EA-000019',registryId:'NOT ISSUED',title:'Execution begins but interruption prevents completion',determination:'ESCALATE',sector:'Critical infrastructure',control:'EXECUTION',receipt:'HTTP 202 · ESCALATED',outcome:'Partial execution isolated; outcome unresolved',route:'TA14-ROUTE-019',hash:'sha256:5dce97a30b217597c14864c3760b1695485d4cde298f01b40da7b34c1a172583',summary:'An authorized execution began but a material interruption prevented complete correspondence between the committed action and the observable outcome. The partial state was isolated and escalated.',proves:'The preserved case demonstrates that an interrupted execution cannot be represented as a completed governed outcome.',doesNotProve:'This record does not establish the final operational effect beyond the preserved interruption boundary.'},
  'ta14-ea-000020':{id:'TA14-EA-000020',registryId:'NOT ISSUED',title:'Executed action differs from committed action',determination:'DENY',sector:'AI operations',control:'EXECUTION',receipt:'HTTP 403 · DENIED',outcome:'Correspondence failure denied; divergent action quarantined',route:'TA14-ROUTE-020',hash:'sha256:20449c533ad806f6b1175d66afdfd34ac527cb1dafc2e67071f5164a3e6eefb3',summary:'The runtime invocation materially diverged from the action fixed at commit. Execution correspondence failed and the divergent action was quarantined rather than treated as authorized performance.',proves:'The preserved case demonstrates that execution must correspond to the committed action, not merely originate from an authorized process.',doesNotProve:'This record does not establish why the divergence occurred or assign fault.'},
  'ta14-ea-000021':{id:'TA14-EA-000021',registryId:'NOT ISSUED',title:'Material condition changes during final revalidation',determination:'HOLD',sector:'Environmental systems',control:'CONTINUITY',receipt:'HTTP 423 · HELD',outcome:'Changed-state revalidation required; zero control changes',route:'TA14-ROUTE-021',hash:'sha256:bb77e9a31018bb3e4b004c0dac9e18420a306d764d828ef4d70e5dac4ad13aa6',summary:'A material environmental condition changed during final pre-execution revalidation. The prior chain was closed at the changed state and execution was withheld pending a new admissibility determination.',proves:'The preserved case demonstrates that changed reality can invalidate otherwise complete prior standing before execution.',doesNotProve:'This record does not establish that intervention would have been unsafe under a newly evaluated state.'},
  'ta14-ea-000022':{id:'TA14-EA-000022',registryId:'NOT ISSUED',title:'Two valid obligations produce incompatible consequences',determination:'ESCALATE',sector:'Cross-sector governance',control:'BINDING',receipt:'HTTP 202 · ESCALATED',outcome:'Conflict escalated; no consequence bound',route:'TA14-ROUTE-022',hash:'sha256:ca24dd84ff4974cdfb7fa5f6ee7f9e8ccd8bb65ab7f061286759a8088527b749',summary:'Two independently valid obligations applied to the same governed state but required consequences that could not both be executed. Neither obligation was silently privileged.',proves:'The preserved case demonstrates escalation when valid binding authorities conflict at the consequence layer.',doesNotProve:'This record does not resolve the underlying legal, contractual, or institutional priority between the obligations.'},
  'ta14-ea-000023':{id:'TA14-EA-000023',registryId:'NOT ISSUED',title:'Historical artifact cannot be cryptographically reconstructed',determination:'HOLD',sector:'Research governance',control:'RECORD',receipt:'HTTP 423 · HELD',outcome:'Reliance withheld pending reconstruction',route:'TA14-ROUTE-023',hash:'sha256:57baf6dbb0b7907c1cce37614b3188375c7e6b21fa3cf56a1e9dd6170c65bbb1',summary:'A historical artifact remained human-readable but could not be reproduced to its preserved cryptographic commitment from the admitted package. Reliance was withheld instead of treating readability as integrity proof.',proves:'The preserved case demonstrates that inspectability alone does not establish cryptographic reconstructability or present reliance standing.',doesNotProve:'This record does not establish that the historical artifact is false or malicious.'},
  'ta14-ea-000024':{id:'TA14-EA-000024',registryId:'NOT ISSUED',title:'Changed state revalidated and authorized execution succeeds',determination:'ALLOW',sector:'Cross-sector demonstration',control:'OUTCOME',receipt:'HTTP 202 · RELEASED',outcome:'Revalidated execution completed; verified outcome closed',route:'TA14-ROUTE-024',hash:'sha256:b0f96efd23e29c2d71605389c07d377703511a6d5b4769504d9b3656bd0c7193',summary:'A material state change was detected before execution, the prior standing was withdrawn, the changed state was independently re-recorded and re-admitted, authority was revalidated, a new commit was sealed, and the bounded execution completed with verified correspondence and outcome closure.',proves:'The preserved case demonstrates full-chain recovery after changed conditions: Reality → Record → Continuity → Admissibility → Binding → Commit → Execution → Outcome.',doesNotProve:'This record does not establish universal architecture performance, regulatory certification, or behavior outside the frozen demonstration.'}
};

const chain=['Reality','Record','Continuity','Admissibility','Binding','Commit','Execution','Outcome'];

export default function ArtifactPage(){
  const p=useParams<{slug:string}>();
  const a=artifacts[String(p.slug||'').toLowerCase()];
  if(!a)return <main style={{minHeight:'70vh',padding:'80px 24px',background:'#050b12',color:'#eef6ff',fontFamily:'Inter,system-ui,sans-serif'}}><div style={{maxWidth:900,margin:'0 auto'}}><p style={{color:'#7fdfff',fontWeight:800}}>TA-14 ARTIFACTS</p><h1>Artifact record not found.</h1><Link href='/artifacts' style={{color:'#f2cc68'}}>Return to Artifact Registry →</Link></div></main>;
  return <main style={{minHeight:'100vh',padding:'72px 24px 96px',background:'radial-gradient(circle at 85% 0,rgba(68,161,208,.14),transparent 32%),#050b12',color:'#eef6ff',fontFamily:'Inter,system-ui,sans-serif'}}><div style={{maxWidth:1180,margin:'0 auto'}}>
    <div style={{display:'flex',justifyContent:'space-between',gap:18,flexWrap:'wrap',alignItems:'center'}}><div><div style={{fontSize:11,letterSpacing:2.2,color:'#f2cc68',fontWeight:900}}>TA-14 EXECUTION ARTIFACT · SECOND CORPUS</div><div style={{marginTop:8,color:'#7fdfff',fontWeight:800}}>{a.id} · EAR ID {a.registryId}</div></div><Link href='/artifacts/registry' style={{color:'#dbeaf5',textDecoration:'none',border:'1px solid rgba(127,223,255,.22)',padding:'10px 14px',borderRadius:10}}>Open Artifact Registry</Link></div>
    <section style={{marginTop:22,padding:'16px 18px',border:'1px solid rgba(242,204,104,.28)',borderRadius:14,background:'rgba(242,204,104,.06)'}}><strong style={{color:'#f2cc68'}}>REGISTRY BOUNDARY · UNREGISTERED SECOND-CORPUS RECORD</strong><p style={{margin:'8px 0 0',color:'#9fb1be',lineHeight:1.65}}>This public case has a preserved TA14-EA artifact identity, but no permanent TA14-EAR registry identifier has been issued. Earlier display of EAR-000013 through EAR-000024 on these second-corpus pages was a namespace error and has been withdrawn. TA14-EAR-000013 remains assigned to the published Harmonic external governance artifact.</p></section>
    <h1 style={{fontSize:'clamp(36px,6vw,72px)',lineHeight:1,letterSpacing:'-.045em',margin:'34px 0 18px',maxWidth:980}}>{a.title}</h1>
    <div style={{display:'flex',gap:9,flexWrap:'wrap',marginBottom:28}}><b style={{padding:'8px 11px',borderRadius:999,border:'1px solid rgba(242,204,104,.28)',color:'#f2cc68'}}>{a.determination}</b><span style={{padding:'8px 11px',borderRadius:999,border:'1px solid rgba(127,223,255,.18)',color:'#9fb5c5'}}>{a.sector}</span><span style={{padding:'8px 11px',borderRadius:999,border:'1px solid rgba(127,223,255,.18)',color:'#9fb5c5'}}>Earliest control: {a.control}</span></div>
    <section style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(220px,1fr))',gap:12,margin:'26px 0'}}>{[['Determination',a.determination],['Execution receipt',a.receipt],['Outcome',a.outcome],['Route',a.route]].map(([k,v])=><div key={k} style={{padding:18,border:'1px solid rgba(127,223,255,.13)',borderRadius:14,background:'rgba(7,18,30,.78)'}}><small style={{color:'#71899a',textTransform:'uppercase',letterSpacing:1.2}}>{k}</small><div style={{marginTop:7,fontWeight:800}}>{v}</div></div>)}</section>
    <section style={{padding:'28px 30px',border:'1px solid rgba(242,204,104,.18)',borderRadius:18,background:'linear-gradient(145deg,rgba(242,204,104,.05),rgba(8,19,31,.88))'}}><h2 style={{marginTop:0,fontSize:27}}>Governed finding</h2><p style={{color:'#b1c2cf',lineHeight:1.8,fontSize:16}}>{a.summary}</p></section>
    <h2 style={{fontSize:30,margin:'46px 0 18px'}}>Admissible execution chain</h2><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(130px,1fr))',gap:9}}>{chain.map((x,i)=><div key={x} style={{padding:15,border:'1px solid rgba(127,223,255,.12)',borderRadius:12,background:'rgba(7,18,30,.72)'}}><small style={{color:'#6f8799'}}>0{i+1}</small><div style={{marginTop:6,fontWeight:850}}>{x}</div><div style={{marginTop:5,fontSize:11,color:x.toUpperCase()===a.control?'#f2cc68':'#7890a1'}}>{x.toUpperCase()===a.control?'PRIMARY CONTROL':'PRESERVED'}</div></div>)}</div>
    <section style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(280px,1fr))',gap:14,marginTop:34}}><div style={{padding:24,border:'1px solid rgba(127,223,255,.13)',borderRadius:15}}><strong style={{color:'#7fdfff'}}>WHAT THIS RECORD PROVES</strong><p style={{color:'#a9bac7',lineHeight:1.7}}>{a.proves}</p></div><div style={{padding:24,border:'1px solid rgba(242,204,104,.18)',borderRadius:15}}><strong style={{color:'#f2cc68'}}>CLAIMS BOUNDARY</strong><p style={{color:'#a9bac7',lineHeight:1.7}}>{a.doesNotProve}</p></div></section>
    <section style={{marginTop:26,padding:22,border:'1px solid rgba(127,223,255,.11)',borderRadius:14,background:'rgba(4,12,21,.74)'}}><small style={{color:'#71899a',letterSpacing:1.3}}>CANONICAL CASE DIGEST</small><div style={{marginTop:8,wordBreak:'break-all',fontFamily:'ui-monospace,SFMono-Regular,Menlo,monospace',color:'#c5d4df'}}>{a.hash}</div><p style={{marginBottom:0,color:'#71899a',fontSize:12}}>Digest identifies this frozen public case definition. It does not independently establish the truth of any proposition beyond the preserved record.</p></section>
    <div style={{marginTop:34,display:'flex',gap:10,flexWrap:'wrap'}}><Link href='/artifacts' style={{color:'#f2cc68',textDecoration:'none'}}>← Artifact library</Link><Link href='/artifacts/registry' style={{color:'#7fdfff',textDecoration:'none'}}>Artifact Registry →</Link></div>
  </div></main>;
}
