"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";

type Item={name:string;count:number};
type Trial={status?:string;sourcePage?:string|null;utmSource?:string|null;priority?:string;daysRemaining?:number};
type Data={generatedAt:string;windowDays:number;summary:{pageViews:number;uniqueVisitors:number;clicks:number;commercialIntentEvents:number;commercialIntentVisitors:number;activeTrials?:number;conversionDueTrials?:number;convertedTrials?:number;paidSubscriptions:number;attributedPaidSubscriptions:number;attributedRevenue:number;attributedMrr?:number};pages:Item[];intentPages:Item[];clickTargets:Item[];searchQueries:Item[];sources:Item[];campaigns:Item[];attentionQueue?:Trial[]};

const eu=(s:string)=>/eu[- /]?ai|ai act|european.*ai|compliance/i.test(s||"");

export default function EuAiActCommercialSeo(){
 const[data,setData]=useState<Data|null>(null);const[status,setStatus]=useState("Loading EU AI Act commercial evidence…");
 useEffect(()=>{fetch("/api/admin/seo-intelligence",{cache:"no-store"}).then(async r=>{if(r.status===401)throw new Error("Sign in to view this private engine.");if(r.status===403)throw new Error("This engine is restricted to the TA-14 owner account.");if(!r.ok)throw new Error("Commercial intelligence is unavailable.");return r.json()}).then(x=>{setData(x);setStatus("")}).catch(e=>setStatus(e.message))},[]);
 const signal=useMemo(()=>{if(!data)return null;const pages=data.pages.filter(x=>eu(x.name)),intent=data.intentPages.filter(x=>eu(x.name)),queries=data.searchQueries.filter(x=>eu(x.name)),trials=(data.attentionQueue||[]).filter(x=>eu(x.sourcePage||""));return{pageViews:pages.reduce((s,x)=>s+x.count,0),intentEvents:intent.reduce((s,x)=>s+x.count,0),queries:queries.reduce((s,x)=>s+x.count,0),trials,pages,intent,queries}},[data]);
 const stages=data&&signal?[{name:"Qualified EU AI Act page demand",value:signal.pageViews,rule:"Observed qualified-human page views on EU AI Act / compliance surfaces."},{name:"Commercial intent",value:signal.intentEvents,rule:"Intent events recorded on those surfaces."},{name:"Attributed trial attention",value:signal.trials.length,rule:"External trial records whose preserved source page is EU AI Act related."},{name:"Paid subscriptions",value:data.summary.attributedPaidSubscriptions,rule:"Authoritative paid conversions with acquisition attribution; currently institution-wide, not asserted as EU-only."},{name:"Attributed revenue",value:`$${data.summary.attributedRevenue.toLocaleString()}`,rule:"Authoritative attributed revenue; institution-wide until EU-specific billing attribution is proven."}]:[];
 return <main className="page"><header><div><small>TA-14 · PRIVATE COMMERCIAL INTELLIGENCE</small><h1>EU AI Act Commercial SEO Engine</h1></div><nav><Link href="/workspace/mission-control/seo-intelligence">SEO Intelligence</Link><Link href="/workspace/mission-control/revenue-execution">Revenue Execution</Link><Link href="/eu-ai-act">EU AI Act World</Link></nav></header><section className="hero"><p>COMMERCIAL DOOR · EVIDENCE FUNNEL</p><h2>Find the leak between <em>discovery</em> and <em>revenue.</em></h2><span>This surface isolates EU AI Act demand from the existing qualified-human telemetry. It does not manufacture attribution: institution-wide payment numbers remain explicitly bounded until an EU-specific acquisition chain reaches billing evidence.</span></section>{status?<div className="notice">{status}</div>:null}{data&&signal?<><section className="strip"><b>{data.windowDays}-DAY WINDOW</b><span>Generated {new Date(data.generatedAt).toLocaleString()}</span><span>Internal/operator traffic excluded upstream</span></section><section className="funnel">{stages.map((x,i)=><article key={x.name}><small>STAGE {String(i+1).padStart(2,"0")}</small><strong>{typeof x.value==="number"?x.value.toLocaleString():x.value}</strong><h3>{x.name}</h3><p>{x.rule}</p></article>)}</section><section className="grid"><Panel title="EU AI Act pages" items={signal.pages}/><Panel title="EU AI Act intent pages" items={signal.intent}/><Panel title="Observed EU AI Act queries" items={signal.queries}/><Panel title="All acquisition sources" items={data.sources}/><Panel title="Campaign evidence" items={data.campaigns}/><section className="panel"><small>TRIAL ATTENTION</small><h3>EU-attributed open trials</h3>{signal.trials.length?signal.trials.map((t,i)=><div className="row" key={i}><span>{t.sourcePage||"Unknown source"}</span><b>{t.priority||t.status||"OPEN"}</b></div>):<p className="empty">No EU-attributed trial is currently preserved in the attention queue.</p>}</section></section><section className="decision"><small>NEXT COMMERCIAL DECISION</small><h3>{signal.pageViews===0?"Acquire qualified EU AI Act demand before optimizing conversion.":signal.intentEvents===0?"EU AI Act traffic exists, but the commercial proposition is not yet producing recorded intent.":signal.trials.length===0?"Intent exists. The next leak is diagnostic/trial activation and attribution.":"Trial evidence exists. Work activation, proof of value, and authoritative conversion."}</h3><p>Do not scale traffic merely to improve a vanity metric. Repair the first unsupported transition in the evidence chain.</p></section></>:null}<footer>No admissible evidence. No admissible execution. · Commercial evidence before commercial stories.</footer><style jsx>{`
.page{min-height:100vh;background:radial-gradient(circle at 20% 0,#0d3550 0,#06111d 28%,#02060b 65%);color:#edf8ff;font-family:Inter,system-ui,sans-serif;padding-bottom:60px}.page *{box-sizing:border-box}.page a{color:inherit;text-decoration:none}header{padding:18px 4vw;border-bottom:1px solid #17364b;display:flex;justify-content:space-between;align-items:center;gap:20px;position:sticky;top:0;background:#030910ed;backdrop-filter:blur(18px);z-index:4}header small,.hero>p,.panel>small,.decision>small{color:#64dcff;font-size:9px;font-weight:900;letter-spacing:.15em}header h1{font-size:16px;margin:5px 0 0}nav{display:flex;gap:8px;flex-wrap:wrap}nav a{border:1px solid #214b65;padding:9px 11px;border-radius:8px;font-size:10px;font-weight:800}.hero{max-width:1320px;margin:auto;padding:70px 4vw 35px}.hero h2{font:clamp(44px,6vw,78px)/.95 Georgia,serif;margin:12px 0 20px;max-width:950px}.hero em{font-style:normal;color:#6fe2ff}.hero span{display:block;max-width:950px;color:#a8bdcd;line-height:1.7}.notice,.strip,.funnel,.grid,.decision{max-width:1320px;margin:0 auto 24px}.notice{padding:16px;border:1px solid #604d26;background:#171107}.strip{display:flex;gap:20px;justify-content:space-between;flex-wrap:wrap;padding:15px 20px;border:1px solid #244a60;background:#071521;font-size:10px;color:#9fc9dc}.funnel{display:grid;grid-template-columns:repeat(5,1fr);gap:9px}.funnel article,.panel{border:1px solid #193d55;background:#07131e;padding:20px}.funnel small{color:#6d91a8;font-size:8px;letter-spacing:.12em}.funnel strong{display:block;font:38px Georgia,serif;color:#7de6ff;margin:12px 0 5px}.funnel h3,.panel h3{font:20px Georgia,serif;margin:6px 0 12px}.funnel p,.empty,.decision p{color:#91aabd;font-size:12px;line-height:1.6}.grid{display:grid;grid-template-columns:repeat(2,1fr);gap:10px}.row{display:flex;justify-content:space-between;gap:15px;padding:10px 0;border-top:1px solid #153246;font-size:11px}.row span{overflow-wrap:anywhere;color:#b8cad7}.row b{color:#7de6ff}.decision{padding:25px;border:1px solid #665226;background:#171207}.decision h3{font:30px Georgia,serif;margin:9px 0}footer{max-width:1320px;margin:45px auto 0;padding:20px 4vw;border-top:1px solid #17364b;color:#728c9e;font-size:10px}@media(max-width:900px){.funnel{grid-template-columns:1fr 1fr}.grid{grid-template-columns:1fr}header{align-items:flex-start;flex-direction:column}}@media(max-width:560px){.funnel{grid-template-columns:1fr}}
`}</style></main>
}
function Panel({title,items}:{title:string;items:Item[]}){return <section className="panel"><small>OBSERVED EVIDENCE</small><h3>{title}</h3>{items.length?items.slice(0,12).map((x,i)=><div className="row" key={`${x.name}-${i}`}><span>{x.name}</span><b>{x.count.toLocaleString()}</b></div>):<p className="empty">No qualifying signal recorded in the current window.</p>}</section>}
