"use client";

import { useMemo, useState } from "react";

const sources = [
  ["Daikin — Integrated Report 2026 release (Sep. 28, 2026)", "https://www.daikin.com/press/2026/20260928"],
  ["Daikin — FUSION30 strategic management plan", "https://www.daikin.com/investor/management/strategy"],
  ["Daikin — Message from Management", "https://www.daikin.com/corporate/overview/message"],
  ["Daikin TIC — Technology Strategy", "https://www.daikin.com/about/corporate/tic/technology"],
  ["Daikin TIC — Promotion of Solution Business", "https://www.daikin.com/about/corporate/tic/technology/solution"],
  ["Daikin TIC — Creation of Air Value", "https://www.daikin.com/about/corporate/tic/technology/air"],
  ["Daikin TIC — Open Innovation", "https://www.daikin.com/about/corporate/tic/innovation"],
  ["Daikin — COP31 Japan Pavilion announcement", "https://www.daikin.com/press/2026/20260910"],
  ["Daikin — Sustainability Report 2026", "https://www.daikin.com/sustainability/report"],
];

const chain = ["Reality","Record","Continuity","Admissibility","Binding","Commit","Execution","Outcome"];

const signals = [
  ["01","BUILDING-WIDE","Daikin says FUSION30 is intended to move the company beyond conventional air conditioning toward solutions for building-wide equipment challenges across the entire lifecycle."],
  ["02","AIR QUALITY","Its public strategy describes air-quality management, ventilation, sensing and higher-value IAQ technologies as part of the value it intends to create."],
  ["03","DX + CONTROL","Daikin identifies DX system products, system-level control, BMS, remote monitoring and AI/IoT fault monitoring as active technology and solution directions."],
  ["04","CO-CREATION","Daikin explicitly describes external co-creation with companies, universities, research institutions and startups as a mechanism for accelerating technology development."],
];

const scenarios = [
  {label:"CO₂ RISES", evidence:"A trusted occupied-space CO₂ trend crosses the local threshold.", action:"Increase outdoor-air delivery.", authority:"WHO may authorize the change, under what local rule, and for how long?"},
  {label:"SENSOR DRIFTS", evidence:"A sensor remains connected but its continuity record shows unresolved drift.", action:"Change ventilation based on the reading.", authority:"Does connection plus data availability remain sufficient evidence for this consequence?"},
  {label:"REMOTE OPTIMIZATION", evidence:"A cloud service proposes an energy-saving control change across multiple sites.", action:"Modify setpoints or schedules.", authority:"Does the service have execution authority at this building, for this scope, NOW?"},
  {label:"REFRIGERANT EVENT", evidence:"A leak-related signal is detected and preserved with equipment identity and chronology.", action:"Isolate, recover, service or return equipment to operation.", authority:"What evidence, standing and applicable authority bind each physical consequence?"},
];

export default function DaikinIndustriesShowroom() {
  const [scenario,setScenario] = useState(0);
  const [decision,setDecision] = useState<"ALLOW"|"HOLD"|"DENY"|"ESCALATE"|null>(null);
  const current = useMemo(()=>scenarios[scenario], [scenario]);

  return <main className="page">
    <style>{`
      *{box-sizing:border-box}.page{margin:0;background:#f4f6f7;color:#10242d;font-family:Arial,Helvetica,sans-serif}.shell{width:min(1180px,92vw);margin:auto}
      .nav{position:sticky;top:0;z-index:20;background:rgba(2,21,31,.97);border-bottom:1px solid #17465d;color:#fff}.nav .shell{height:62px;display:flex;align-items:center;justify-content:space-between;gap:18px}.brand{font-size:10px;font-weight:950;letter-spacing:.15em}.links{display:flex}.nav a{color:#b8d8e6;text-decoration:none;font-size:9px;font-weight:900;letter-spacing:.12em;margin-left:18px}.nav a:first-child{color:#5bd4ff}
      .hero{background:radial-gradient(circle at 82% 16%,#07547a 0,transparent 28%),linear-gradient(135deg,#021923,#053247 58%,#06212e);color:#fff;padding:86px 0 72px}.heroGrid{display:grid;grid-template-columns:1.15fr .85fr;gap:54px;align-items:center}.eyebrow{font-size:10px;font-weight:950;letter-spacing:.17em;color:#58d6ff;margin:0 0 17px}.jp{color:#b8d9e5;font-size:11px;font-weight:800;letter-spacing:.12em}.hero h1{font:clamp(58px,8vw,104px)/.88 Georgia,serif;letter-spacing:-.06em;margin:14px 0 27px}.hero h1 em{display:block;color:#91e3ff;font-weight:400}.lede{max-width:760px;font:20px/1.6 Georgia,serif;color:#d7e8ee}.status{display:flex;gap:8px;flex-wrap:wrap;margin-top:26px}.status span{padding:8px 10px;border:1px solid #4f7a8c;font-size:9px;font-weight:900;letter-spacing:.11em;color:#d8edf5}.today{border:1px solid #38718a;background:#061c27;padding:27px;box-shadow:0 20px 60px rgba(0,0,0,.25)}.today small{color:#69d8ff;font-size:9px;font-weight:950;letter-spacing:.15em}.today h2{font:34px/1.05 Georgia,serif;margin:14px 0}.today p{color:#b9d0d9;font-size:13px;line-height:1.7}.today strong{display:block;color:#fff;margin-top:17px;font-size:13px}
      .section{padding:78px 0}.section h2{font:clamp(40px,5vw,68px)/1.02 Georgia,serif;letter-spacing:-.045em;margin:0 0 22px;max-width:960px}.intro{max-width:900px;font:18px/1.7 Georgia,serif;color:#50636b}.signals{display:grid;grid-template-columns:repeat(4,1fr);gap:10px;margin-top:38px}.signal{background:#fff;border:1px solid #d6e1e5;border-top:4px solid #0b769c;padding:25px;min-height:280px}.signal small{color:#0b769c;font-size:9px;font-weight:950;letter-spacing:.13em}.signal h3{font:26px/1.1 Georgia,serif;margin:14px 0}.signal p{color:#586970;font-size:13px;line-height:1.7}
      .dark{background:#071b24;color:#f5fbfd}.dark .intro{color:#b6cbd3}.seam{display:grid;grid-template-columns:1fr 72px 1fr;gap:14px;align-items:stretch;margin-top:38px}.panel{padding:30px;border:1px solid #265063;background:#0b2632}.panel small{font-size:9px;font-weight:950;letter-spacing:.13em;color:#63d8ff}.panel h3{font:30px Georgia,serif;margin:12px 0}.panel p{font-size:13px;line-height:1.7;color:#bfd0d6}.arrow{display:flex;align-items:center;justify-content:center;font-size:34px;color:#71dcff}.rule{margin-top:24px;padding:26px;border-left:5px solid #64d9ff;background:#0f3140;font:18px/1.6 Georgia,serif}.rule strong{color:#fff}
      .chain{display:grid;grid-template-columns:repeat(8,1fr);gap:6px;margin-top:34px}.chain span{padding:15px 8px;text-align:center;background:#fff;border:1px solid #d6e1e5;font-size:10px;font-weight:900}.chain span:nth-child(6){border-color:#0b769c;box-shadow:inset 0 -4px #0b769c}
      .exam{margin-top:36px;border:1px solid #c7d8df;background:#fff;padding:30px}.scenarioTabs{display:flex;flex-wrap:wrap;gap:8px}.scenarioTabs button,.actions button{cursor:pointer;border:1px solid #a8c0ca;background:#fff;color:#17313b;padding:11px 14px;font-size:9px;font-weight:950;letter-spacing:.1em}.scenarioTabs button.on{background:#062837;color:#fff;border-color:#062837}.examGrid{display:grid;grid-template-columns:1fr 1fr;gap:18px;margin-top:24px}.examCard{padding:22px;background:#edf4f6;border-left:4px solid #0b769c}.examCard small{font-size:9px;font-weight:950;letter-spacing:.12em;color:#0b769c}.examCard h3{font:28px Georgia,serif;margin:10px 0}.examCard p{font-size:13px;line-height:1.7;color:#53666d}.actions{display:flex;gap:9px;flex-wrap:wrap;margin-top:19px}.actions button.on{background:#062837;color:#fff;border-color:#062837}.receipt{margin-top:15px;background:#061d28;color:#c7dce4;padding:20px;border-left:5px solid #62d8ff;font-size:13px;line-height:1.65}.receipt strong{color:#fff}
      .todayBand{background:#dff4fb;padding:70px 0}.todayBand h2{max-width:980px}.three{display:grid;grid-template-columns:repeat(3,1fr);gap:14px;margin-top:34px}.three article{background:#fff;border:1px solid #c9dce4;padding:28px}.three small{font-size:9px;font-weight:950;color:#0a759a;letter-spacing:.13em}.three h3{font:27px Georgia,serif}.three p{font-size:13px;line-height:1.7;color:#52666e}
      .langCta{display:inline-block;margin-top:24px;padding:13px 18px;background:#62d8ff;color:#06202c!important;text-decoration:none;font-size:11px;font-weight:950;letter-spacing:.08em;border-radius:3px}.faq{display:grid;grid-template-columns:repeat(2,1fr);gap:12px;margin-top:32px}.faq article{background:#fff;border:1px solid #d5e1e5;padding:25px}.faq h3{font:22px/1.25 Georgia,serif;margin:0 0 10px}.faq p{font-size:13px;line-height:1.7;color:#52666e}.boundary{margin-top:30px;padding:26px;border:1px solid #c7d7dd;background:#fff;color:#42585f;line-height:1.7;font-size:13px}.boundary strong{color:#16303a}
      .sources{display:grid;grid-template-columns:repeat(2,1fr);gap:11px;margin-top:32px}.sources a{display:block;padding:19px;background:#fff;border:1px solid #d3dfe3;text-decoration:none;color:#16313c;font-size:12px;font-weight:850}.sources a:hover{border-color:#0b769c;transform:translateY(-2px)}.footer{background:#03141c;color:#849da7;padding:38px 0;font-size:10px;letter-spacing:.09em;line-height:1.7}
      @media(max-width:900px){.heroGrid,.signals,.three,.examGrid,.seam{grid-template-columns:1fr}.signals{gap:14px}.chain{grid-template-columns:repeat(4,1fr)}.arrow{transform:rotate(90deg);min-height:46px}.links{display:none}}
      @media(max-width:540px){.chain{grid-template-columns:repeat(2,1fr)}.hero{padding:56px 0}.section{padding:58px 0}}
    `}</style>

    <nav className="nav"><div className="shell"><div className="brand">DAIKIN INDUSTRIES · PUBLIC STRATEGY SHOWROOM</div><div className="links"><a href="/">TA-14 EXCHANGE</a><a href="#fusion">FUSION30</a><a href="#seam">BOUNDARY</a><a href="#exam">EXAM</a><a href="#record">RECORD</a></div></div></nav>

    <header className="hero"><div className="shell heroGrid">
      <div><p className="eyebrow">DAIKIN INDUSTRIES · FUSION30 · AIR · BUILDINGS · CONSEQUENCE</p><p className="jp">ダイキン工業 × TA-14 · 公開戦略検討室</p><h1>Perfecting the air.<em>Governing the consequence.</em></h1><p className="lede">Daikin is publicly moving beyond equipment toward building-wide, lifecycle solutions: sensing, controls, energy management, indoor-air value, DX and service. TA-14 examines the boundary that appears when those capabilities can change physical reality.</p><a className="langCta" href="/showrooms/daikin-industries">日本語版を読む →</a><div className="status"><span>INDEPENDENT PUBLIC EXAMINATION</span><span>OPEN FOR CORRECTION</span><span>NO PARTNERSHIP OR ENDORSEMENT IMPLIED</span></div></div>
      <aside className="today"><small>SEPTEMBER 28, 2026 · TODAY</small><h2>Daikin published the record.</h2><p>Daikin Industries released its Integrated Report 2026 and Sustainability Report 2026, placing FUSION30, profitability, sustainability priorities and stakeholder dialogue into the current public record.</p><strong>That makes today's strategy inspectable — not inferred.</strong></aside>
    </div></header>

    <section id="fusion" className="section"><div className="shell"><p className="eyebrow">WHAT DAIKIN IS BUILDING TOWARD</p><h2>FUSION30 pushes the HVAC company toward a building systems company.</h2><p className="intro">The public strategy is not limited to better compressors or higher equipment efficiency. Daikin describes building-wide lifecycle solutions, commercial solutions, system-level control, applied technologies, DX system products, air-quality management, sensing and external co-creation.</p><div className="signals">{signals.map(s=><article className="signal" key={s[0]}><small>{s[0]} · {s[1]}</small><h3>{s[1]}</h3><p>{s[2]}</p></article>)}</div></div></section>

    <section id="seam" className="section dark"><div className="shell"><p className="eyebrow">THE DAIKIN × TA-14 SEAM</p><h2>Capability is growing. Authority still has to be established.</h2><p className="intro">A building can sense more, connect more and optimize more without answering the governance question attached to a specific physical consequence.</p><div className="seam"><article className="panel"><small>DAIKIN · CAPABILITY SURFACE</small><h3>Observe, analyze, optimize, control.</h3><p>Air-quality sensing, BMS integration, remote monitoring, energy management, system-level control, diagnostics, AI/IoT fault monitoring and lifecycle service create increasingly capable building systems.</p></article><div className="arrow">→</div><article className="panel"><small>TA-14 · CONSEQUENCE SURFACE</small><h3>May this become reality NOW?</h3><p>For the proposed consequence, establish sufficient <strong>Admissible Evidence</strong>, <strong>Applicable Authority</strong> and <strong>Established Standing</strong> before Commit and Execution.</p></article></div><div className="rule"><strong>Monitoring is not evidence; evidence is not authority; authority is not execution.</strong><br/>A connected, intelligent building may be technically capable of acting while the consequence remains unauthorized.</div></div></section>

    <section className="section"><div className="shell"><p className="eyebrow">TA-14 CHAIN OF EIGHT</p><h2>Put every Daikin-originated consequence through the same visible route.</h2><p className="intro">The equipment brand does not decide admissibility. The route does.</p><div className="chain">{chain.map(x=><span key={x}>{x}</span>)}</div></div></section>

    <section id="exam" className="section todayBand"><div className="shell"><p className="eyebrow">INTERACTIVE BUILDING CONSEQUENCE EXAM</p><h2>Change the signal. Keep the boundary.</h2><div className="exam"><div className="scenarioTabs">{scenarios.map((s,i)=><button type="button" key={s.label} className={scenario===i?"on":""} onClick={()=>{setScenario(i);setDecision(null)}}>{s.label}</button>)}</div><div className="examGrid"><article className="examCard"><small>OBSERVED / PROPOSED</small><h3>{current.evidence}</h3><p><strong>Proposed consequence:</strong> {current.action}</p></article><article className="examCard"><small>AUTHORITY QUESTION</small><h3>Connection does not answer this.</h3><p>{current.authority}</p></article></div><div className="actions"><button type="button" className={decision==="ALLOW"?"on":""} onClick={()=>setDecision("ALLOW")}>ALLOW</button><button type="button" className={decision==="HOLD"?"on":""} onClick={()=>setDecision("HOLD")}>HOLD</button><button type="button" className={decision==="ESCALATE"?"on":""} onClick={()=>setDecision("ESCALATE")}>ESCALATE</button></div>{decision&&<div className="receipt">{decision==="ALLOW"?<><strong>ALLOW selected.</strong> The route still requires a preserved record showing why evidence, authority and standing were sufficient for this exact consequence at Commit.</>:decision==="HOLD"?<><strong>HOLD selected.</strong> Preserve the observation and proposal, but do not convert capability into execution until the missing condition is established.</>:<><strong>ESCALATE selected.</strong> Route the unresolved authority, evidence or standing question to the responsible local decision-maker without allowing the system to infer permission.</>}</div>}</div></div></section>

    <section className="section"><div className="shell"><p className="eyebrow">WHY THIS MATTERS TO FUSION30</p><h2>The more Daikin becomes a solutions provider, the more the consequence boundary matters.</h2><div className="three"><article><small>01 · LIFECYCLE</small><h3>Commissioned once ≠ authorized forever.</h3><p>Building conditions, sensors, occupants, schedules, equipment and local authority change. A lifecycle service model benefits from explicit revalidation rather than permanent inherited permission.</p></article><article><small>02 · SCALE</small><h3>Remote capability multiplies consequences.</h3><p>Cloud-connected controls can propagate one proposal across many sites. Local authority and standing should remain inspectable at every execution boundary.</p></article><article><small>03 · AIR VALUE</small><h3>Healthy-air goals still need bounded action.</h3><p>Valid IAQ evidence can support a consequence without automatically authorizing one. The value of the evidence increases when the route from observation to outcome is preserved.</p></article></div><div className="boundary"><strong>Independent examination boundary.</strong> This showroom uses Daikin's public corporate materials to examine an architectural seam. It does not state or imply that Daikin Industries, its subsidiaries, executives, engineers, communications staff, partners or customers have adopted, endorsed or formally evaluated TA-14. Corrections to the Daikin representation are invited.</div></div></section>

    <section className="section"><div className="shell"><p className="eyebrow">QUESTIONS DAIKIN MAY ASK</p><h2>Answer the boundary questions before a technical examination begins.</h2><div className="faq">
<article><h3>Is TA-14 asking Daikin to replace its BMS or control logic?</h3><p>No. TA-14 does not replace sensing, BMS, optimization, supervisory control or equipment logic. It examines the governance boundary before a proposed consequence is committed to execution.</p></article>
<article><h3>Where does authority come from?</h3><p>Not from TA-14 by declaration. Applicable Authority must be established from the relevant owner, operator, contract, regulation, safety rule, delegated role or other governing source for that specific consequence.</p></article>
<article><h3>What if the evidence becomes degraded?</h3><p>The observation can remain preserved while the proposed consequence is held, denied or escalated. TA-14 separates preserving evidence from pretending that degraded evidence remains sufficient for execution.</p></article>
<article><h3>Can authority travel through cloud or federated systems?</h3><p>Authority context may cross a connection boundary. Execution authority is not automatically inherited. The receiving domain must establish local authority and standing for the consequence.</p></article>
<article><h3>What does TA-14 record?</h3><p>The objective is an attributable route from Reality through Record, Continuity, Admissibility, Binding and Commit to Execution and Outcome, including why the determination was available at that time.</p></article>
<article><h3>What happens when the answer is not ALLOW?</h3><p>HOLD preserves the proposal without execution. DENY rejects the proposed consequence under the established conditions. ESCALATE routes the unresolved question to an authorized decision-maker.</p></article>
<article><h3>Does TA-14 require Daikin to adopt a proprietary platform?</h3><p>No adoption is assumed by this showroom. The architecture can first be examined as a boundary model against existing Daikin workflows, interfaces, evidence and authority structures.</p></article>
<article><h3>What would a first Daikin × TA-14 examination look like?</h3><p>Choose one bounded consequence, freeze the actors, evidence, connection route and authority conditions, then run controlled changes to determine exactly where ALLOW becomes HOLD, DENY or ESCALATE.</p></article>
</div></div></section><section className="dark"><div className="shell"><p className="eyebrow">NEXT STEP</p><h2>Propose a bounded Daikin × TA-14 technical examination.</h2><p>No product adoption or partnership is assumed. Select one real consequence, freeze the evidence, authority, connection and execution boundaries, and test the seam under Daikin's actual technical conditions.</p><a className="langCta" href="mailto:gregbutlerac@gmail.com?subject=Daikin%20%C3%97%20TA-14%20Bounded%20Technical%20Examination">Propose a bounded examination →</a></div></section><section id="record" className="section dark"><div className="shell"><p className="eyebrow">PUBLIC SOURCE RECORD</p><h2>Follow Daikin's own published strategy.</h2><p className="intro">The examination is intentionally anchored to primary Daikin sources, including material released September 28, 2026.</p><div className="sources">{sources.map(s=><a key={s[1]} href={s[1]} target="_blank" rel="noreferrer">{s[0]} ↗</a>)}</div></div></section>

    <footer className="footer"><div className="shell"><a className="langCta" href="/showrooms/daikin-industries">日本語版を読む →</a><br/><br/>DAIKIN INDUSTRIES · PUBLIC STRATEGY SHOWROOM · PRIMARY-SOURCE EXAMINATION · OPEN FOR CORRECTION · NO ENDORSEMENT IMPLIED · TA-14 EXCHANGE</div></footer>
  </main>;
}