'use client';
import {useEffect,useState} from 'react';

const aaa=[
  ['01','ASSESS','Understand the current environment. Define the occupied spaces, questions, measurement method, equipment condition, timing, uncertainty, and the needs of students, staff, and building occupants.'],
  ['02','ADDRESS','Turn evidence into practical action. Ventilation, filtration, source control, maintenance, moisture management, operational changes, training, and resources each need an owner, scope, and reason.'],
  ['03','ASSURE','Verify what changed. Preserve the before condition, intervention, after condition, method, dates, limitations, and whether the intended result was actually achieved and sustained.']
];

function Samantha({text,label}:{text:string,label:string}){
  const[state,setState]=useState<'idle'|'playing'|'paused'>('idle');
  useEffect(()=>()=>{if(typeof window!=='undefined')window.speechSynthesis?.cancel()},[]);
  const start=()=>{if(typeof window==='undefined'||!('speechSynthesis'in window))return;window.speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);const vs=window.speechSynthesis.getVoices();u.voice=vs.find(v=>/Samantha/i.test(v.name))||vs.find(v=>/Ava|Victoria|Karen|Zira/i.test(v.name))||vs.find(v=>v.lang.startsWith('en-US'))||vs.find(v=>v.lang.startsWith('en'))||null;u.rate=.80;u.pitch=.96;u.onend=()=>setState('idle');u.onerror=()=>setState('idle');window.speechSynthesis.speak(u);setState('playing')};
  const play=()=>{if(state==='paused'){window.speechSynthesis.resume();setState('playing')}else start()};
  const pause=()=>{window.speechSynthesis.pause();setState('paused')};
  const stop=()=>{window.speechSynthesis.cancel();setState('idle')};
  return <div className="sam"><div><b>🎧 SAMANTHA · {label}</b><span>Listen while you study this section · free-scroll remains enabled</span></div><div className="samBtns"><button onClick={play}>{state==='paused'?'▶ RESUME':state==='playing'?'↻ RESTART':'▶ PLAY'}</button>{state==='playing'&&<button onClick={pause}>Ⅱ PAUSE</button>}<button onClick={stop}>■ STOP</button></div></div>
}

export default function LisaGreenfieldShowroom(){
return <main className="page"><style>{`
*{box-sizing:border-box}.page{min-height:100vh;background:#f4f0e7;color:#102734;font-family:Arial,Helvetica,sans-serif}.shell{width:min(1180px,92vw);margin:auto}.nav{position:sticky;top:0;z-index:20;background:#071b28;color:#fff;border-bottom:1px solid #24404e}.nav .shell{display:flex;justify-content:space-between;align-items:center;gap:18px;padding:20px 0}.nav b,.ey{font-size:10px;letter-spacing:.16em;text-transform:uppercase;font-weight:950}.nav a{color:#f1bc4f;text-decoration:none;margin-left:18px;font-size:10px;font-weight:900}
.hero{background:radial-gradient(circle at 82% 20%,#1e536c 0,transparent 31%),linear-gradient(135deg,#0a2230,#0a3142 58%,#071923);color:#f8f4eb;padding:88px 0}.heroGrid{display:grid;grid-template-columns:1.15fr .85fr;gap:62px;align-items:center}.ey{color:#f1bc4f}.hero h1{font:clamp(58px,7.6vw,104px)/.91 Georgia,serif;letter-spacing:-.055em;margin:16px 0 25px}.hero h1 em{display:block;color:#f1bc4f;font-weight:400}.lead{font:20px/1.65 Georgia,serif;color:#d4e0e5;max-width:760px}.portrait{overflow:hidden;border:1px solid #496e7d;background:#0d2d3a;box-shadow:0 24px 70px rgba(0,0,0,.26)}.portrait img{width:100%;aspect-ratio:1/1;object-fit:cover;display:block}.tags{display:flex;flex-wrap:wrap;gap:8px;margin-top:25px}.tags span{border:1px solid #537687;padding:8px 10px;font-size:9px;font-weight:900;letter-spacing:.1em}
.statement{background:#efc869;padding:62px 0}.statement h2,.sec h2{font:clamp(38px,5.1vw,66px)/1.03 Georgia,serif;letter-spacing:-.04em;margin:12px 0 20px}.statement p,.intro{font:18px/1.72 Georgia,serif;max-width:970px}.sec{padding:76px 0}.dark{background:#0d2937;color:#f5f3eb}.dark .intro{color:#c7d6dc}.aaaGrid{display:grid;grid-template-columns:repeat(3,1fr);gap:12px;margin-top:34px}.aaaCard{padding:30px;border:1px solid #c9c4b9;background:#fff;min-height:290px}.dark .aaaCard{background:#123747;border-color:#365c69}.aaaCard .num{font:54px Georgia,serif;color:#d79a20}.aaaCard h3{font:28px Georgia,serif;margin:4px 0 14px}.aaaCard p{line-height:1.7;color:#617076}.dark .aaaCard p{color:#c6d3d8}.visual{margin-top:32px;border:1px solid #cfc8b8;background:#fff;padding:10px}.visual img{display:block;width:100%;height:auto}.caption{font-size:12px;line-height:1.6;color:#68777c;margin-top:10px}.dark .caption{color:#aebfc6}
.journey{display:grid;grid-template-columns:repeat(2,1fr);gap:12px;margin-top:34px}.step{padding:24px;border-left:4px solid #f1bc4f;background:#fff}.step b{display:block;color:#b47a0b;font-size:11px;letter-spacing:.13em}.step h3{font:25px Georgia,serif;margin:8px 0}.step p{margin:0;color:#596a70;line-height:1.67}.question{padding:30px;border:1px solid #d2c59f;background:#fff8e6;margin-top:34px}.question small{color:#aa7200;font-weight:950;letter-spacing:.11em}.question blockquote{font:clamp(24px,3vw,42px)/1.35 Georgia,serif;margin:12px 0 0}.human{background:#e4ecee}.humanGrid{display:grid;grid-template-columns:1fr 1fr;gap:54px;align-items:start}.human p{line-height:1.75;color:#59696e}.quote{font:30px/1.35 Georgia,serif;color:#163847;border-left:4px solid #d99a20;padding-left:24px}.record{background:#102b39;color:#f5f3eb}.record p{color:#c4d2d8;line-height:1.75;max-width:970px}.recordChain{display:flex;gap:8px;flex-wrap:wrap;margin-top:30px}.recordChain span{padding:12px 14px;border:1px solid #426675;background:#0a202b;font-size:10px;font-weight:950;letter-spacing:.08em}.sources{display:grid;grid-template-columns:repeat(2,1fr);gap:12px;margin-top:26px}.sources a{display:block;padding:22px;background:#fff;border:1px solid #d7d1c6;color:#173746;text-decoration:none;font-weight:900;line-height:1.45}.fine{font-size:11px;line-height:1.65;color:#728087;margin-top:25px;max-width:970px}.sam{display:flex;justify-content:space-between;gap:18px;align-items:center;margin-top:20px;padding:18px;border:1px solid #315d6d;border-radius:12px;background:#061923;color:#fff}.sam b{display:block;color:#78e5ff;font-size:11px;letter-spacing:.12em}.sam span{display:block;color:#9fb4be;font-size:11px;margin-top:4px}.samBtns{display:flex;gap:7px;flex-wrap:wrap}.sam button{cursor:pointer;border:1px solid #416977;background:#0b2a36;color:#f8fbfc;padding:10px 13px;font-weight:900;border-radius:7px}.foot{background:#061824;color:#93a8b0;padding:34px 0;font-size:10px;letter-spacing:.09em}
@media(max-width:820px){.heroGrid,.aaaGrid,.journey,.humanGrid,.sources{grid-template-columns:1fr}.portrait{max-width:520px}.nav span{display:none}.sam{align-items:flex-start;flex-direction:column}}
`}</style>
<nav className="nav"><div className="shell"><b>LISA GREENFIELD · PUBLIC PROFILE SHOWROOM</b><span><a href="/showrooms">ALL SHOWROOMS</a><a href="#story">STORY</a><a href="#aaa">AAA</a><a href="#impact">IMPACT</a><a href="#work">WORK</a></span></div></nav>

<header className="hero"><div className="shell heroGrid"><div><p className="ey">LISA GREENFIELD · CENTER FOR GREEN SCHOOLS · U.S. GREEN BUILDING COUNCIL</p><h1>Healthy air.<em>Brighter futures.</em></h1><p className="lead">Lisa Greenfield’s career connects education, advocacy, indoor air quality, facilities practice, and the people who live with the consequences of the indoor environment every day.</p><div className="tags"><span>EDUCATOR</span><span>INDOOR AIR QUALITY</span><span>HEALTHY SCHOOLS</span><span>CHANGE CATALYST</span><span>PUBLIC PROFILE</span></div></div><aside className="portrait"><img src="/Lisa%20Greenfield%203.png" alt="Lisa Greenfield" /></aside></div></header>

<section id="story" className="statement"><div className="shell"><p className="ey" style={{color:'#694600'}}>THE THROUGH-LINE</p><h2>Start with people. Make the invisible environment visible. Then prove what changed.</h2><p>Nearly two decades in public schools and federally funded early-childhood programs gave Lisa a human starting point for indoor air quality: students, teachers, staff, families, and the learning environment itself. Her work has since expanded across education, filtration, indoor air quality, advisory work, and the Center for Green Schools.</p></div></section>

<section id="aaa" className="sec dark"><div className="shell"><p className="ey">LISA GREENFIELD’S AAA METHODOLOGY</p><h2>Assess. Address. Assure.</h2><p className="intro">The framework is intentionally practical: understand the current environment, implement evidence-based solutions, and verify results so healthier conditions are not merely assumed.</p><div className="aaaGrid">{aaa.map(([n,t,d])=><article className="aaaCard" key={n}><div className="num">{n}</div><h3>{t}</h3><p>{d}</p></article>)}</div><div className="visual"><img src="/Clean%20Air%20in%20Schools_%20AAA%20Methodology.png" alt="Clean Air in Schools — Lisa Greenfield AAA methodology teaching visual" /></div><p className="caption">Teaching visual · Lisa’s AAA framework shown as a practical school indoor-air journey.</p><Samantha label="IMAGE 01 · ASSESS → ADDRESS → ASSURE" text={"Lisa Greenfield’s AAA methodology is Assess, Address, Assure. In this first teaching image, begin with Assess. Understand the current environment by evaluating indoor conditions, identifying sources and risks, considering the needs of students, staff, and building occupants, and using data, observation, and evidence. Next is Address. Use what was learned to implement practical, evidence-based solutions. That can include ventilation, filtration, source control, maintenance, energy-efficient strategies, training, and operational improvements. Then Assure. Return to the occupied environment and verify the result. Confirm improvement through measurement, maintain healthy conditions over time, educate and support the people responsible for the space, and track outcomes. The important lesson is that action is not the end of the process. The result must be checked. Assess establishes what is happening. Address responds to what the evidence supports. Assure asks whether the response actually produced and maintained the intended healthier environment."} /></div></section>

<section className="sec"><div className="shell"><p className="ey">THE HUMAN MISSION</p><h2>Healthy schools are not an equipment problem alone.</h2><p className="intro">They are a people, operations, education, evidence, maintenance, and accountability problem. Better ventilation or filtration matters because people occupy the building — and because the result should be demonstrable after the intervention, not simply promised beforehand.</p><div className="visual"><img src="/Healthy%20Schools%20Start%20with%20Healthy%20Air.png" alt="Healthy Schools Start with Healthy Air teaching visual" /></div><p className="caption">Teaching visual · healthier students, supported teachers, safer childcare, stronger communities, and brighter futures.</p><Samantha label="IMAGE 02 · HEALTHY AIR → HUMAN IMPACT" text={"This second teaching image moves from method to human consequence. Healthy schools start with healthy air because the indoor environment is experienced by real people every day. Cleaner air can support healthier students, teachers, and staff. Early-childhood spaces deserve the same attention because younger occupants depend on adults and institutions to protect the environment around them. Stronger school environments also strengthen communities, because schools are public places where health, learning, operations, facilities, and stewardship meet. The image ends with brighter futures. That is the larger purpose of the work: not technology for its own sake, but healthier learning environments and better opportunities for the people who occupy them."} /></div></section>

<section id="impact" className="sec human"><div className="shell humanGrid"><div><p className="ey">THE ADVOCATE</p><h2>Those without a voice are still inside the consequence.</h2><p>Lisa describes herself as an advocate and champion for those without a voice, especially children. That perspective matters because environmental decisions are often made through budgets, work orders, standards, equipment choices, maintenance practices, and institutional processes far removed from the people who experience the result.</p></div><div className="quote">The measure of a healthy-school program is not whether equipment was purchased. It is whether the occupied environment became healthier — and whether that improvement can still be demonstrated.</div></div></section>

<section id="work" className="sec"><div className="shell"><p className="ey">PUBLIC WORK SURFACE</p><h2>A career connecting education, indoor air quality, and healthier learning environments.</h2><div className="sources"><a href="https://www.usgbc.org/center-green-schools" target="_blank" rel="noreferrer">Center for Green Schools · U.S. Green Building Council ↗</a><a href="https://www.usgbc.org/center-green-schools" target="_blank" rel="noreferrer">Healthy schools · education · indoor environmental quality ↗</a></div><p className="fine">Independent public-profile showroom assembled from Lisa Greenfield’s public professional record and public institutional materials to celebrate and teach from her career in education, indoor air quality, healthy schools, and advocacy. Lisa’s AAA methodology — Assess, Address, Assure — remains her work. This page is not an official biography and does not imply endorsement by Lisa Greenfield, the Center for Green Schools, or the U.S. Green Building Council. Open for correction.</p></div></section>

<footer className="foot"><div className="shell">LISA GREENFIELD · HEALTHY AIR · BRIGHTER FUTURES · PUBLIC PROFILE SHOWROOM · OPEN FOR CORRECTION</div></footer>
</main>
}