'use client';
import Link from 'next/link'; import {useState} from 'react';
const concepts=[["Draw the boundary","Know what is inside the problem.","Boundaries can include equipment, controls, ductwork, zones, ventilation, drains and power/control sources.","Too narrow hides conditions; too broad creates noise."],["Context changes meaning","The same machine behaves differently under different conditions.","Weather, load, occupancy, doors, ventilation, setpoints and recent changes affect operation.","Context prevents normal behavior from being mislabeled."],["Command is not response","A request is not proof it happened.","Separate control demand from actual response.","This is foundational to sequence diagnosis."],["Shared systems require care","One component may serve many spaces.","Zoning, shared returns and common ventilation cross apparent boundaries.","Shared effects create attribution risk."],["Bound the claim","Your conclusion needs a boundary too.","State equipment, condition, time and proposition covered.","Bounded conclusions are easier to verify."],["Changed context matters","A conclusion may not transfer unchanged.","Weather, occupancy, mode and configuration can change the proposition.","Later work formalizes revalidation."]]; const scenarios=[["Open patio door","Cooling operates while an exterior door is open.","Preserve changed load/context before declaring capacity failure."],["Warm zone","One room is warm in a multi-zone system.","Establish zone and shared-system context."],["Fan mismatch","Thermostat commands fan ON but blower is stationary.","Mismatch is established; cause is not."],["After-hours","Ventilation is in unoccupied schedule.","Do not compare it to occupied expectations without schedule context."]];
const questions=[
{"q":"What does an examination boundary define?","o":["What is inside the scope being examined","Only equipment brand","The final diagnosis","The invoice amount"],"a":0,"e":"A boundary establishes the scope of the examination."},
{"q":"Which can legitimately be part of a system boundary?","o":["Only the outdoor unit","Equipment, controls, ductwork, zones and relevant sources","Only the thermostat","Only the customer complaint"],"a":1,"e":"The relevant system can extend beyond the box in front of you."},
{"q":"Why can an examination boundary be too narrow?","o":["It always improves accuracy","It proves equipment failure","It may hide conditions that affect the proposition","It changes model numbers"],"a":2,"e":"A narrow boundary can exclude relevant system relationships."},
{"q":"Why can an examination boundary be too broad?","o":["It automatically proves more","It eliminates context","It creates authority","It can add unrelated noise"],"a":3,"e":"Scope should include what matters without absorbing unrelated conditions."},
{"q":"Cooling is operating while a patio door is open. Why preserve that fact?","o":["It changes load and operating context","It proves low charge","It proves a bad compressor","It changes asset identity"],"a":0,"e":"An open exterior door can materially change system load."},
{"q":"A thermostat commands FAN ON but the blower is stationary. What is established?","o":["A bad blower motor","A command-response mismatch","A failed thermostat","Low line voltage"],"a":1,"e":"The mismatch is observable; its cause remains open."},
{"q":"Why is a control command not the same as system response?","o":["Controls never matter","Responses cannot be measured","A request does not prove the requested action occurred","Commands are diagnoses"],"a":2,"e":"Command and actual response are separate propositions."},
{"q":"One room is warm in a multi-zone system. What should happen before declaring equipment capacity failure?","o":["Add refrigerant","Replace the thermostat","Ignore other zones","Establish zone and shared-system context"],"a":3,"e":"A local condition must be interpreted within the serving-system context."},
{"q":"Why do shared returns create attribution risk?","o":["Conditions can reflect multiple served spaces","They prove duct leakage","They eliminate zoning","They identify the compressor"],"a":0,"e":"Shared pathways can make a reading represent more than one apparent boundary."},
{"q":"Ventilation is on an unoccupied schedule after hours. What comparison is inappropriate without more context?","o":["Recording the schedule","Comparing it directly with occupied-operation expectations","Recording fan state","Identifying the unit"],"a":1,"e":"Operating expectations depend on schedule and occupancy context."},
{"q":"Which item is operating context rather than a diagnosis?","o":["Failed compressor","Low refrigerant charge","Outdoor temperature","Bad motor winding"],"a":2,"e":"Weather is context that can change expected system behavior."},
{"q":"Why does occupancy matter to HVACD/R interpretation?","o":["It changes serial numbers","It proves airflow","It authorizes repairs","It can change sensible, moisture and ventilation loads"],"a":3,"e":"Occupancy can materially alter system demand and expectations."},
{"q":"A system was evaluated during mild weather. Can the same conclusion automatically be transferred to peak-load weather?","o":["No","Yes"],"a":0,"e":"Changed context can require revalidation."},
{"q":"Which is the strongest bounded claim?","o":["The AC is bad","At 2:15 PM, AHU-2 was commanded ON and its blower was observed stationary","Building problem","Needs repair"],"a":1,"e":"A bounded claim identifies asset, condition, time and proposition."},
{"q":"Why include time in a bounded conclusion?","o":["Time proves cause","Time replaces equipment identity","Conditions and operating state can change","It establishes authority"],"a":2,"e":"A conclusion belongs to the conditions under which evidence was collected."},
{"q":"A ventilation damper position changes between two visits. Why does that matter?","o":["It proves refrigeration failure","It erases prior evidence","It changes equipment ownership","Configuration/context changed and may affect the proposition"],"a":3,"e":"Changed configuration can change system behavior and interpretation."},
{"q":"A thermostat setpoint was changed minutes before measurements. How should that be treated?","o":["Relevant recent operating context","Proof of a bad thermostat","Irrelevant history","Repair authorization"],"a":0,"e":"Recent control changes can affect current operating state."},
{"q":"Which statement best reflects shared-system reasoning?","o":["Every room condition belongs only to equipment physically nearest it","One component can serve multiple spaces, so relationships must be established","Shared systems eliminate attribution concerns","All zones always behave identically"],"a":1,"e":"Serving relationships can cross apparent physical boundaries."},
{"q":"What does “bound the claim” mean?","o":["Make the broadest possible diagnosis","Avoid recording limitations","State exactly what equipment, condition, time and proposition the conclusion covers","Include every building system"],"a":2,"e":"A conclusion should not claim more than its evidence supports."},
{"q":"A system meets temperature setpoint with unusually low occupancy. Does that alone establish peak occupied performance?","o":["Yes","No"],"a":1,"e":"Performance under one load context does not automatically establish another."},
{"q":"Which change most clearly calls for contextual revalidation?","o":["A major occupancy or operating-mode change","The technician changes pens","The invoice is printed","The model number is copied"],"a":0,"e":"Changes that affect system conditions can alter the proposition."},
{"q":"Why record whether an exterior door was open during testing?","o":["To identify refrigerant","To preserve a load/infiltration condition that can affect readings","To prove ventilation compliance","To establish serial number"],"a":1,"e":"Environmental and building-use conditions can materially affect HVACD/R evidence."},
{"q":"A fan command is present and airflow is measured. Which evidence addresses response more directly?","o":["The command alone","The thermostat brand","The measured airflow","The customer expectation"],"a":2,"e":"Measured response evidence addresses whether the commanded effect occurred."},
{"q":"What is wrong with transferring yesterday's conclusion unchanged after equipment configuration changed overnight?","o":["Nothing ever changes conclusions","Configuration never matters","Prior evidence becomes fabricated","The relevant context changed and the proposition may need revalidation"],"a":3,"e":"Prior evidence remains historical, but changed conditions can require new examination."},
{"q":"What is the central lesson of System Boundaries & Operating Context?","o":["Define what is being examined and preserve the conditions and relationships that give evidence its meaning","Treat the nearest box as the entire system","Ignore occupancy and weather","A command proves a response"],"a":0,"e":"Scope and context keep conclusions attached to the conditions they actually describe."}
];
export default function Lesson(){const [tab,setTab]=useState('learn'),[answers,setAnswers]=useState<Record<number,number>>({}),[submitted,setSubmitted]=useState(false),[picks,setPicks]=useState<Record<number,number>>({});const score=questions.reduce((n,q,i)=>n+(answers[i]===q.a?1:0),0),pct=Math.round(score/25*100),passed=submitted&&pct>=80;const card={padding:26,border:'1px solid #245878',borderRadius:18,background:'linear-gradient(145deg,#062945,#041e35)',boxShadow:'0 18px 44px rgba(0,0,0,.22)'};
return <main style={{minHeight:'100vh',background:'radial-gradient(circle at 80% 0%,#0b4163 0%,#001d36 32%,#001326 70%,#000b18 100%)',color:'#f7fbff',fontFamily:'Arial,sans-serif',padding:'0 20px'}}><div style={{maxWidth:1120,margin:'auto'}}><nav style={{padding:'22px 0',display:'flex',justifyContent:'space-between',borderBottom:'1px solid #285b78',fontSize:11,fontWeight:900}}><Link href="/eight24-hvacdr/curriculum/01" style={{color:'#7BAFD4',textDecoration:'none'}}>← MODULE 01</Link><span style={{color:'#B9D9EB'}}>LESSON 1.05 · 15 MIN</span></nav><header style={{padding:'64px 0 30px'}}><small style={{color:'#7BAFD4',fontWeight:900,letterSpacing:2}}>TA-14 × EIGHT24 · HVACD/R FIELD FOUNDATIONS</small><h1 style={{fontFamily:'Georgia,serif',fontSize:'clamp(44px,7vw,72px)',lineHeight:1,margin:'16px 0'}}>System Boundaries & Operating Context</h1><p style={{maxWidth:900,color:'#C9E0EF',fontSize:19,lineHeight:1.75}}>A system is more than the box in front of you. Learn where the examination begins and ends, what serves what, and which surrounding conditions can change the meaning of your evidence.</p></header><div style={{display:'flex',gap:8,flexWrap:'wrap',paddingBottom:28}}>{[['learn','DEEP LESSON'],['cases','FIELD SCENARIOS'],['interact','INTERACT'],['exam','25-Q EXAM'],['record','RECORD']].map(t=><button key={t[0]} onClick={()=>setTab(t[0])} style={{padding:'10px 15px',borderRadius:999,border:'1px solid #316987',background:tab===t[0]?'#7BAFD4':'#06243B',color:tab===t[0]?'#001426':'#C9E0EF',fontWeight:900,cursor:'pointer'}}>{t[1]}</button>)}</div>
{tab==='learn'&&<section style={{display:'grid',gap:14,paddingBottom:55}}>{concepts.map((x,i)=><article key={x[0]} style={card}><small style={{color:'#B9D9EB',fontWeight:900}}>CONCEPT {i+1}</small><h2 style={{fontFamily:'Georgia,serif',fontSize:30}}>{x[0]}</h2><p style={{color:'#C9E0EF',lineHeight:1.9,fontSize:17}}><b style={{color:'#7BAFD4'}}>SIMPLE — </b>{x[1]}</p><p style={{color:'#C9E0EF',lineHeight:1.9}}><b style={{color:'#7BAFD4'}}>TECHNICIAN LANGUAGE — </b>{x[2]}</p><div style={{padding:17,border:'1px solid #316987',borderRadius:13,background:'#031a2e'}}><b style={{color:'#B9D9EB'}}>WHY IT MATTERS</b><p style={{color:'#C9E0EF',lineHeight:1.75}}>{x[3]}</p></div></article>)}</section>}
{tab==='cases'&&<section style={{display:'grid',gap:14,paddingBottom:55}}>{scenarios.map((s,i)=><article key={s[0]} style={card}><small style={{color:'#B9D9EB',fontWeight:900}}>FIELD SCENARIO {i+1}</small><h2 style={{fontFamily:'Georgia,serif',fontSize:29}}>{s[0]}</h2><p style={{color:'#C9E0EF',lineHeight:1.9}}>{s[1]}</p><div style={{padding:17,borderLeft:'3px solid #7BAFD4',background:'#031a2e'}}><b style={{color:'#7BAFD4'}}>FIELD-READY REASONING</b><p style={{color:'#C9E0EF',lineHeight:1.75}}>{s[2]}</p></div></article>)}</section>}
{tab==='interact'&&<section style={{display:'grid',gap:14,paddingBottom:55}}>{questions.slice(0,5).map((q,i)=><div key={q.q} style={card}><small style={{color:'#B9D9EB',fontWeight:900}}>YOU DECIDE {i+1}</small><h3 style={{fontFamily:'Georgia,serif',fontSize:23}}>{q.q}</h3>{q.o.map((o,j)=><button key={o} onClick={()=>setPicks({...picks,[i]:j})} style={{display:'block',width:'100%',textAlign:'left',padding:13,margin:'7px 0',border:'1px solid #316987',borderRadius:11,background:picks[i]===j?'#104361':'#031a2e',color:'#fff',cursor:'pointer'}}>{o}</button>)}{picks[i]!==undefined&&<p style={{color:picks[i]===q.a?'#7BAFD4':'#B9D9EB'}}><b>{picks[i]===q.a?'SUPPORTED':'RE-EXAMINE'} — </b>{q.e}</p>}</div>)}</section>}
{tab==='exam'&&<section style={{paddingBottom:55}}><h2 style={{fontFamily:'Georgia,serif',fontSize:38}}>25 questions · 80% required</h2>{questions.map((q,i)=><div key={i} style={{...card,marginBottom:10}}><b style={{color:'#7BAFD4'}}>QUESTION {i+1} / 25</b><h3>{q.q}</h3>{q.o.map((o,j)=><label key={o} style={{display:'block',padding:10,margin:'6px 0',border:'1px solid #316987',borderRadius:10}}><input type="radio" name={'q'+i} checked={answers[i]===j} onChange={()=>{setAnswers({...answers,[i]:j});setSubmitted(false)}}/> {o}</label>)}{submitted&&<p style={{color:answers[i]===q.a?'#7BAFD4':'#B9D9EB'}}><b>{answers[i]===q.a?'SUPPORTED':'RE-EXAMINE'} — </b>{q.e}</p>}</div>)}<button disabled={Object.keys(answers).length<25} onClick={()=>setSubmitted(true)} style={{padding:'16px 25px',border:0,borderRadius:999,background:'#7BAFD4',color:'#001426',fontWeight:900,opacity:Object.keys(answers).length<25?.45:1}}>GRADE EXAM →</button>{submitted&&<b style={{marginLeft:18,color:passed?'#7BAFD4':'#B9D9EB',fontSize:25}}>{pct}% · {passed?'PASS':'RE-EXAMINE'}</b>}</section>}
{tab==='record'&&<section style={{paddingBottom:55}}><div style={card}><small style={{color:'#B9D9EB',fontWeight:900}}>LESSON EVIDENCE OBJECT</small><h2 style={{fontFamily:'Georgia,serif',fontSize:34}}>1.05 Completion Record</h2><p style={{color:'#C9E0EF',lineHeight:1.8}}>The deployed Eight24/LMS layer can preserve learner identity, lesson/version, timestamps, attempt history, responses, score, completion state and relevant interaction telemetry.</p><p style={{fontFamily:'Georgia,serif',fontSize:24}}>State: {passed?'COMPLETED':submitted?'RE-EXAMINE':'OPEN'} {submitted?'· '+pct+'%':''}</p></div></section>}<footer style={{padding:'35px 0 55px',borderTop:'1px solid #285b78',display:'flex',justifyContent:'space-between',gap:12,flexWrap:'wrap'}}><Link href="/eight24-hvacdr/curriculum/01/lesson/04" style={{color:'#7BAFD4',textDecoration:'none',fontSize:11,fontWeight:900}}>← LESSON 1.04</Link><Link href="/eight24-hvacdr/curriculum/01" style={{color:'#B9D9EB',textDecoration:'none',fontSize:11,fontWeight:900}}>MODULE 01 HOME</Link><span style={{color:'#607984',fontSize:11,fontWeight:900}}>NEXT · 1.06 IN BUILD</span></footer></div></main>}