"use client";
import {FormEvent,useMemo,useState} from "react";
import Link from "next/link";
import {getDemoFixture} from "../../../../lib/asg/demo-fixtures";

export default function Page(){
 const [q,setQ]=useState("Show me a funny video of kitties");
 const [submitted,setSubmitted]=useState("");
 const [recordId,setRecordId]=useState("");
 const fixture=useMemo(()=>submitted?getDemoFixture(submitted):null,[submitted]);
 const rows=fixture?.candidates.slice(0,10)??[];
 const delivered=rows.filter(r=>r.state==="ALLOW");
 const count=(s:string)=>rows.filter(r=>r.state===s).length;
 function submit(e:FormEvent){e.preventDefault();setSubmitted(q.trim());setRecordId(`ASG-DEMO-${Date.now().toString(36).toUpperCase()}`)}
 function candidateHref(rank:number){return `/ai-governance/admissible-computation/search/candidate?record=${encodeURIComponent(recordId)}&fixture=${encodeURIComponent(fixture?.id??"")}&rank=${rank}`}
 function download(){if(!fixture)return;const data={schema:"ta14.asg.demo-record.v0.1",recordId,request:submitted,provider:"BOUNDED_FIXTURE_NOT_LIVE_GOOGLE",providerWindow:{startRank:1,endRank:10,candidateCount:rows.length},fixtureId:fixture.id,determinations:rows,deliveryCommit:{candidateRanks:delivered.map(r=>r.rank),deliveredCount:delivered.length},notice:"Demonstration fixture only. Not evidence of a live Google query."};const blob=new Blob([JSON.stringify(data,null,2)],{type:"application/json"});const u=URL.createObjectURL(blob);const a=document.createElement("a");a.href=u;a.download=`${recordId}.json`;a.click();URL.revokeObjectURL(u)}
 return <main className="page"><div className="shell"><nav><Link href="/ai-governance/admissible-computation">← ACA Showcase</Link><b>TA-14 · ADMISSIBLE SEARCH GATEWAY v0.1</b></nav>
 <header><p className="eyebrow">POST-PROVIDER · PRE-DELIVERY GOVERNANCE</p><h1>Freeze the first 10.<br/><em>Govern what crosses the boundary.</em></h1><p className="lead">The target architecture takes the provider's first 10 candidates, preserves original rank, evaluates every candidate through TA-14, and delivers only candidates with sufficient standing. Until legitimate Google Web Search Service credentials are configured, this public build uses explicitly query-bound fixtures and never fabricates a live Google result set.</p></header>
 <section className="flow">REQUEST → PROVIDER TOP 10 → TA-14 RECORD / CONTINUITY / ADMISSIBILITY / BINDING → ALLOW · HOLD · DENY · ESCALATE → DELIVERY COMMIT → USER</section>
 <section className="search"><form onSubmit={submit}><label>Run bounded demonstration</label><div><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Try: Cheesecake Factory"/><button>RUN</button></div><p>Fixtures currently support funny kitty video requests and “Cheesecake Factory.” This build does not scrape Google.</p></form></section>
 {submitted&&!fixture&&<section className="hold"><span>HOLD</span><h2>No candidate set is bound to this request.</h2><p>The request <b>{submitted}</b> is preserved, but the live provider is not configured and no matching fixture exists. TA-14 will not inherit another request's candidates or manufacture Google results.</p><small>PROVIDER_CANDIDATE_SET_UNAVAILABLE</small></section>}
 {fixture&&<><section className="receipt"><div><small>SEARCH RECORD</small><strong>{recordId}</strong><p>{submitted}</p><button onClick={download}>DOWNLOAD BOUNDED RECORD (.JSON)</button></div><div><b>PROVIDER WINDOW {rows.length}/10</b><b>ALLOW {count("ALLOW")}</b><b>HOLD {count("HOLD")}</b><b>DENY {count("DENY")}</b><b>ESCALATE {count("ESCALATE")}</b><b>DELIVERED {delivered.length}</b></div></section><p className="notice">BOUNDED FIXTURE · NOT LIVE GOOGLE — {fixture.label}</p>
 <section className="results"><div><p className="eyebrow">DELIVERED RESULT SET</p><h2>What crosses the boundary</h2>{delivered.map(r=><article key={r.rank}><strong className="rank">{r.rank}</strong><span className="allow">ALLOW</span><h3>{r.title}</h3><p>{r.snippet}</p><small>TA-14 REASON · {r.reason}</small><Link href={candidateHref(r.rank)}>View governed candidate record →</Link></article>)}</div><aside><p className="eyebrow">PRESERVED AUDIT SET</p><h2>Nothing disappears silently</h2>{rows.filter(r=>r.state!=="ALLOW").map(r=><article key={r.rank}><span className={r.state.toLowerCase()}>{r.state}</span><h3>Provider rank {r.rank} · {r.title}</h3><p>{r.reason}</p><Link href={candidateHref(r.rank)}>View preserved candidate record →</Link></article>)}</aside></section>
 <section className="rule"><h2>ALLOW is standing for delivery — not a certificate of absolute truth.</h2><p>All ten candidates and their determinations remain in the bounded record. Changed context requires revalidation.</p></section></>}
 </div><style jsx>{`.page{min-height:100vh;background:#02080d;color:#f5fbff;font-family:Arial,sans-serif}.shell{width:min(1180px,calc(100% - 34px));margin:auto;padding:28px 0 90px}nav{display:flex;justify-content:space-between;font-size:11px;color:#91a8b5}nav a,.results a{color:#7ee9ff}.eyebrow,small{color:#6fe7ff;font-size:10px;font-weight:900;letter-spacing:.15em}header{padding:70px 0 38px;max-width:1000px}h1,h2{font-family:Georgia,serif}h1{font-size:clamp(48px,7vw,82px);line-height:1;margin:15px 0}h1 em{color:#a8e4ef}.lead,.search p,.hold p,.results p,.rule p{color:#abc0ca;line-height:1.65}.flow{padding:22px;border:1px solid #6fe7ff55;border-radius:14px;color:#bceef7;font-size:12px;line-height:1.8}.search{margin-top:24px;padding:27px;background:#081a26;border:1px solid #ffffff20;border-radius:18px}.search label{display:block;font:700 25px Georgia,serif;margin-bottom:14px}.search form>div{display:grid;grid-template-columns:1fr auto;gap:10px}.search input{padding:17px;background:#02080d;border:1px solid #ffffff30;border-radius:9px;color:#fff}.search button,.receipt button{padding:14px 20px;border:0;border-radius:9px;background:#9cecff;color:#06202a;font-weight:900}.hold{margin-top:25px;padding:28px;border:1px solid #e5bd6266;border-radius:18px;background:#211b10}.hold>span{color:#f2d37f;font-weight:900}.receipt{display:grid;grid-template-columns:.45fr .55fr;gap:12px;padding:35px 0 12px}.receipt>div{padding:22px;border:1px solid #ffffff1d;border-radius:15px;background:#07131d}.receipt strong{display:block;font-size:20px;margin-top:8px}.receipt div:last-child{display:flex;gap:8px;flex-wrap:wrap;align-content:center}.receipt div:last-child b{padding:10px;border:1px solid #ffffff20;border-radius:8px;font-size:10px}.notice{padding:11px 14px;border:1px solid #e5bd6255;border-radius:9px;color:#d8c991;font-size:11px}.results{display:grid;grid-template-columns:1.1fr .9fr;gap:14px;padding:20px 0 45px}.results>div,.results>aside{padding:25px;border:1px solid #ffffff1b;border-radius:18px;background:#06111a}.results article{padding:18px 0;border-top:1px solid #ffffff14}.results h2{font-size:31px}.results h3{font-family:Georgia,serif;margin:9px 0}.results a{display:block;margin-top:12px;font-size:12px}.rank{font-size:22px;color:#6fe7ff;margin-right:10px}.allow,.hold,.deny,.escalate{display:inline-block;padding:5px 7px;border-radius:6px;font-size:9px;font-weight:900}.allow{background:#123c35;color:#8df2d7}.hold{background:#493c20;color:#f5d886}.deny{background:#4a2529;color:#ff9ca6}.escalate{background:#39294c;color:#d9b0ff}.rule{text-align:center;padding:45px 0;border-top:1px solid #ffffff16}.rule h2{font-size:clamp(30px,4vw,46px)}@media(max-width:760px){.search form>div,.receipt,.results{grid-template-columns:1fr}nav{gap:12px}}`}</style></main>
}