"use client";

import Link from "next/link";
import { useEffect, useState } from "react";

type TrialRecord = {
  userId:string; email:string|null; tier:string; status:string; startedAt:string; endsAt:string; daysRemaining:number;
  sourcePage:string|null; source:string; campaign:string|null; location:string|null; device:string|null;
  registrationOpens:number; governanceSubmissionCount:number; latestSubmissionStatus:string|null;
  governanceName:string|null; organizationName:string|null; claimantName:string|null;
  highestIntent:{type:string;score:number;page:string|null}|null; lastActivityAt:string; friction:string; priority:string;
};

type Payload={generatedAt:string;records:TrialRecord[]};
const fmt=(v:string)=>new Date(v).toLocaleString();
const human=(v:string)=>v.replaceAll("_"," ");

export default function TrialCommandCenter(){
 const[data,setData]=useState<Payload|null>(null);const[status,setStatus]=useState("Loading participant intelligence…");
 useEffect(()=>{fetch("/api/admin/mission-control/trial-command",{cache:"no-store"}).then(async r=>{if(r.status===401)throw new Error("Sign in to Mission Control.");if(r.status===403)throw new Error("TA-14 owner access required.");if(!r.ok)throw new Error("Trial intelligence unavailable.");return r.json()}).then(x=>{setData(x);setStatus("")}).catch(e=>setStatus(e.message))},[]);
 return <main className="page"><header><div><small>TA-14 · PRIVATE OPERATOR INTELLIGENCE</small><h1>Trial Command Center</h1></div><nav><Link href="/workspace/mission-control">Mission Control</Link><Link href="/workspace/mission-control/seo-intelligence">SEO Intelligence</Link><Link href="/workspace/ai-governance/registry">Registry</Link></nav></header>
 <section className="hero"><p>PARTICIPANT ACTIVATION</p><h2>Know who entered. <em>Know what they need.</em></h2><span>A trial is not a counter. This surface binds participant identity, acquisition evidence, observed intent, Registry activity, friction and the next operator action.</span></section>
 {status?<div className="notice">{status}</div>:null}
 {data?<><section className="strip"><b>{data.records.length} OPEN TRIAL{data.records.length===1?"":"S"}</b><span>Generated {fmt(data.generatedAt)}</span></section>{data.records.length?data.records.map(t=><article className="card" key={t.userId}><div className="cardTop"><div><small>{t.priority}</small><h3>{t.email||"Identity unresolved"}</h3><p>{t.organizationName||"Organization not declared"}{t.governanceName?` · ${t.governanceName}`:""}</p></div><strong>{t.tier?.toUpperCase()} · {t.daysRemaining} DAYS LEFT</strong></div><div className="grid"><Metric label="Status" value={t.status}/><Metric label="Observed intent" value={t.highestIntent?`${human(t.highestIntent.type)} · ${t.highestIntent.score}/100`:"No scored intent"}/><Metric label="Registration opens" value={String(t.registrationOpens)}/><Metric label="Governance submissions" value={String(t.governanceSubmissionCount)}/><Metric label="Acquisition" value={t.source}/><Metric label="Location" value={t.location||"Not resolved"}/><Metric label="Trial started" value={fmt(t.startedAt)}/><Metric label="Last activity" value={fmt(t.lastActivityAt)}/></div><section className="decision"><small>OPERATOR CONDITION</small><h4>{human(t.friction)}</h4><p>{t.friction==="REGISTRATION_NOT_COMPLETED"?"Repeated Registry entry is present without a completed governance submission. Offer activation assistance without exposing behavioral surveillance details.":t.friction==="SUBMISSION_PRESENT"?"A governance submission exists. Inspect its current standing and support the participant at the next institutional boundary.":"The trial is active, but the evidence does not yet establish a specific friction point."}</p></section><div className="actions"><Link href="/workspace/ai-governance/registry">Open Registry →</Link><Link href="/workspace/mission-control/seo-intelligence">Inspect Acquisition →</Link>{t.email?<a href={`mailto:${t.email}?subject=${encodeURIComponent("Your TA-14 Exchange trial")}`}>Assist Participant →</a>:null}</div></article>):<div className="notice">No open external trials require operator attention.</div>}</>:null}
 <footer>No admissible evidence. No admissible execution. · Operator evidence before operator action.</footer><style jsx>{`.page{min-height:100vh;background:radial-gradient(circle at 15% 0,#123b55 0,#06111d 30%,#02060b 70%);color:#edf8ff;font-family:Inter,system-ui,sans-serif;padding-bottom:60px}.page *{box-sizing:border-box}.page a{color:inherit;text-decoration:none}header{padding:18px 4vw;border-bottom:1px solid #17364b;display:flex;justify-content:space-between;align-items:center;gap:20px;position:sticky;top:0;background:#030910ed;backdrop-filter:blur(18px);z-index:4}header small,.hero>p,.card small,.decision small{color:#64dcff;font-size:9px;font-weight:900;letter-spacing:.15em}header h1{font-size:16px;margin:5px 0 0}nav,.actions{display:flex;gap:8px;flex-wrap:wrap}nav a,.actions a{border:1px solid #214b65;padding:10px 12px;border-radius:8px;font-size:10px;font-weight:800}.hero,.strip,.card,.notice,footer{max-width:1320px;margin-left:auto;margin-right:auto}.hero{padding:70px 4vw 35px}.hero h2{font:clamp(44px,6vw,78px)/.95 Georgia,serif;margin:12px 0 20px;max-width:1000px}.hero em{font-style:normal;color:#6fe2ff}.hero span{display:block;max-width:950px;color:#a8bdcd;line-height:1.7}.strip{display:flex;justify-content:space-between;gap:20px;padding:15px 20px;border:1px solid #244a60;background:#071521;font-size:10px;color:#9fc9dc;margin-bottom:14px}.notice{padding:18px;border:1px solid #604d26;background:#171107}.card{border:1px solid #1d4962;background:#07131e;margin-bottom:14px;padding:24px;box-shadow:0 20px 60px #0005}.cardTop{display:flex;justify-content:space-between;gap:20px;align-items:flex-start}.cardTop h3{font:30px Georgia,serif;margin:7px 0}.cardTop p{color:#9bb0c0;margin:0}.cardTop>strong{color:#7de6ff;font-size:11px;border:1px solid #24516a;padding:10px;border-radius:8px}.grid{display:grid;grid-template-columns:repeat(4,1fr);gap:8px;margin:22px 0}.decision{border:1px solid #665226;background:#171207;padding:18px;margin-bottom:15px}.decision h4{font:24px Georgia,serif;margin:7px 0}.decision p{color:#b8ad91;line-height:1.6;margin-bottom:0}.actions a:last-child{border-color:#3a8aa8;background:#0b2b3a}footer{margin-top:45px;padding:20px 4vw;border-top:1px solid #17364b;color:#728c9e;font-size:10px}@media(max-width:900px){.grid{grid-template-columns:1fr 1fr}.cardTop,header{flex-direction:column}}@media(max-width:560px){.grid{grid-template-columns:1fr}}`}</style></main>
}
function Metric({label,value}:{label:string;value:string}){return <div className="metric"><small>{label}</small><strong>{value}</strong><style jsx>{`.metric{border:1px solid #17384d;background:#06101a;padding:14px;min-height:76px}.metric small{display:block;color:#6d91a8;font-size:8px;letter-spacing:.1em;text-transform:uppercase}.metric strong{display:block;margin-top:9px;font-size:12px;overflow-wrap:anywhere}`}</style></div>}
