'use client';

import Link from 'next/link';
import Image from 'next/image';
import { useEffect, useMemo, useState } from 'react';

type Disposition='ALLOW'|'HOLD'|'DENY'|'ESCALATE';
const C={cyan:'#70dcff',green:'#71f2b6',gold:'#ffd36f',red:'#ff7885',purple:'#b9a8ff',text:'#eef8fb',muted:'#9bb1bc'};
const btn={cursor:'pointer',padding:'11px 14px',borderRadius:10,border:'1px solid rgba(112,220,255,.3)',background:'rgba(8,37,47,.9)',color:'#eef8fb',fontWeight:950,fontSize:11} as const;
const card={border:'1px solid rgba(112,220,255,.16)',background:'linear-gradient(145deg,rgba(5,24,37,.88),rgba(2,9,15,.97))',borderRadius:22} as const;

function Samantha({text}:{text:string}){
 const [on,setOn]=useState(false),[paused,setPaused]=useState(false);
 useEffect(()=>()=>window.speechSynthesis?.cancel(),[]);
 const start=()=>{window.speechSynthesis?.cancel();const u=new SpeechSynthesisUtterance(text);u.rate=.82;const vs=window.speechSynthesis.getVoices();u.voice=vs.find(v=>v.name==='Samantha')||vs.find(v=>v.lang==='en-US')||vs[0];u.onend=()=>{setOn(false);setPaused(false)};setOn(true);window.speechSynthesis.speak(u)};
 const toggle=()=>{if(!on)return start();if(paused){window.speechSynthesis.resume();setPaused(false)}else{window.speechSynthesis.pause();setPaused(true)}};
 return <div style={{display:'flex',gap:8,flexWrap:'wrap',marginTop:14}}><button onClick={toggle} style={btn}>{!on?'▶ SAMANTHA — EXPLAIN':paused?'▶ RESUME':'Ⅱ PAUSE'}</button>{on&&<button onClick={()=>{window.speechSynthesis.cancel();setOn(false);setPaused(false)}} style={btn}>■ STOP</button>}</div>
}

export default function AaronHastingsBuildingMLShowroom(){
 const [valid,setValid]=useState(true),[admissible,setAdmissible]=useState(true),[authority,setAuthority]=useState(true),[standing,setStanding]=useState(true),[changed,setChanged]=useState(false);
 const result:Disposition=useMemo(()=>!authority?'DENY':!standing?'ESCALATE':(!valid||!admissible||changed)?'HOLD':'ALLOW',[valid,admissible,authority,standing,changed]);
 const color={ALLOW:C.green,HOLD:C.gold,DENY:C.red,ESCALATE:C.purple}[result];
 const toggle=(label:string,value:boolean,setter:(v:boolean)=>void)=><button onClick={()=>setter(!value)} style={{...btn,border:value?'1px solid rgba(113,242,182,.5)':'1px solid rgba(255,120,133,.5)',color:value?C.green:C.red}}>{label}: {value?'YES':'NO'}</button>;
 return <main style={{minHeight:'100vh',padding:'42px 18px 100px',background:'radial-gradient(circle at 80% 0%,rgba(46,195,255,.16),transparent 28%),linear-gradient(180deg,#02060b,#06101a 48%,#02060b)',color:C.text,fontFamily:'Inter,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif'}}>
  <div style={{maxWidth:1260,margin:'0 auto'}}>
   <nav style={{display:'flex',justifyContent:'space-between',gap:12,flexWrap:'wrap',paddingBottom:20,borderBottom:'1px solid rgba(112,220,255,.12)'}}><Link href="/showrooms" style={{color:'#9de8f7',textDecoration:'none',fontWeight:900}}>← TA-14 SHOWROOMS</Link><div style={{fontSize:10,fontWeight:950,letterSpacing:'.17em',color:'#718d9b'}}>PUBLIC TECHNICAL SHOWROOM · BUILDING ML CONSEQUENCE BOUNDARY</div></nav>

   <section style={{marginTop:26,padding:'clamp(38px,7vw,82px)',border:'1px solid rgba(112,220,255,.24)',borderRadius:32,background:'linear-gradient(145deg,rgba(7,38,56,.97),rgba(4,13,22,.99) 58%,rgba(19,28,50,.96))'}}>
    <div style={{fontSize:11,fontWeight:950,letterSpacing:'.22em',color:C.cyan}}>TA-14 · PRACTITIONER TECHNICAL REFERENCE · AARON HASTINGS</div>
    <h1 style={{fontSize:'clamp(50px,8.5vw,108px)',lineHeight:.88,letterSpacing:'-.07em',margin:'18px 0 24px'}}>BUILDING ML<br/><span style={{color:C.green}}>CONSEQUENCE BOUNDARY</span></h1>
    <p style={{fontSize:'clamp(19px,2.5vw,29px)',lineHeight:1.5,maxWidth:1020,color:'#c5d8df'}}>Machine learning may reconstruct missing data, predict future performance, and produce deterministic results. None of those capabilities, by themselves, establish permission for a proposed consequence to become real.</p>
    <div style={{marginTop:28,padding:'clamp(22px,4vw,38px)',borderRadius:20,border:'1px solid rgba(113,242,182,.34)',background:'rgba(2,10,17,.55)',fontSize:'clamp(22px,3.3vw,40px)',fontWeight:1000,lineHeight:1.15}}>Prediction or inference does not create <span style={{color:C.green}}>authority to act.</span></div>
    <Samantha text="Aaron's questions are deceptively simple: admissible to what, and authority to do what? In this showroom, admissibility is not being used as shorthand for courtroom evidence. It is decision-specific. We are asking whether a particular observation, computation, or inference may legitimately support a particular proposed consequence, in this building, under the conditions that exist now. Authority is also consequence-specific. A person, application, analytics platform, machine-learning model, or control system may have technical capability to issue a command without having established authority to cause that command's physical consequence. Imagine a model that predicts an air-handling unit will exceed an operating limit in the next thirty minutes. That prediction may be useful, repeatable, and technically excellent. But the prediction alone does not tell us whether the system may display an advisory, create a work order, change a supply-air setpoint, override an operator, or shut the unit down. Those are different proposed consequences. This showroom examines the boundary between knowing something about a building and being permitted to make something happen in that building. Machine learning can strengthen observation, reconstruction, prediction, and verification. None of those capabilities appoint the model as an authority. Prediction is not permission. Capability is not authority. The question begins again at the consequence."/>
   </section>

   <section style={{marginTop:24,padding:'clamp(28px,5vw,52px)',...card}}>
    <div style={{fontSize:11,fontWeight:950,letterSpacing:'.18em',color:C.green}}>01 · DISAMBIGUATION</div>
    <h2 style={{fontSize:'clamp(35px,5.5vw,68px)',lineHeight:.98,letterSpacing:'-.05em',margin:'12px 0 22px'}}>VALID ≠ ADMISSIBLE ≠ AUTHORIZED</h2>
    <div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(250px,1fr))',gap:12}}>
     {[
      ['VALID','Is the observation technically credible?','A sensor may be calibrated, current, correctly addressed, and functioning.'],
      ['ADMISSIBLE','May this evidence legitimately support this proposed consequence now?','Validity matters, but context, continuity, applicable rules, scope, and other required evidence may still be missing.'],
      ['AUTHORIZED','May this actor or system cause this specific consequence?','Credentials, access, capability, or human approval do not automatically establish authority.']
     ].map(([t,q,d],i)=><article key={t} style={{padding:24,borderRadius:18,border:'1px solid rgba(112,220,255,.15)',background:'rgba(2,10,17,.58)'}}><div style={{fontSize:11,color:[C.cyan,C.green,C.purple][i],fontWeight:1000}}>0{i+1}</div><h3 style={{fontSize:25,margin:'8px 0'}}>{t}</h3><div style={{fontWeight:900,lineHeight:1.45}}>{q}</div><p style={{color:C.muted,lineHeight:1.6,fontSize:14}}>{d}</p></article>)}
    </div>
    <div style={{marginTop:22,marginBottom:10,fontSize:10,fontWeight:950,letterSpacing:".18em",color:C.cyan}}>TEACHING VISUAL 01 / 04</div><Image src="/TA14_Aaron_Hastings_Building_ML_01_Valid_Admissible_Authorized.png" alt="Valid admissible and authorized building ML teaching visual" width={1536} height={1024} style={{display:"block",width:"100%",height:"auto",marginTop:22,borderRadius:20}}/><Samantha text="Start with VALID. Suppose a zone-temperature sensor is calibrated, correctly addressed, current, and behaving within its expected range. Or suppose a machine-learning model receives well-governed inputs and produces a repeatable prediction with strong confidence. That can establish technical credibility. But technical credibility answers only the first question. ADMISSIBLE asks something different: may this evidence legitimately support the consequence being proposed now? Context can matter. Was the model operating inside its trained or validated conditions? Has occupancy changed? Has equipment been placed in hand? Did a technician alter a sequence? Is another sensor contradicting the inference? Is the evidence current enough for this action? A technically valid value can therefore be real and useful while still being insufficient for a particular consequence. Then comes AUTHORIZED. Even when the evidence is admissible, who or what may cause the action? A dashboard account, API token, BACnet write capability, priority-array access, operator credential, or supervisory application proves capability or access. It does not, by itself, establish authority for every consequence reachable through that access. Consider a model recommending that a supply-air setpoint move from fifty-five degrees to fifty-eight. The model may be valid. The evidence may be sufficient to display the recommendation. But permission to recommend is not necessarily permission to write the setpoint. And permission to write within a bounded optimization range is not necessarily permission to disable an air handler. VALID, ADMISSIBLE, and AUTHORIZED are therefore three separate questions. Collapsing them into one is precisely the ambiguity this visual is designed to expose."/>
   </section>

   <section style={{marginTop:24,padding:'clamp(28px,5vw,52px)',...card}}>
    <div style={{fontSize:11,fontWeight:950,letterSpacing:'.18em',color:C.cyan}}>02 · SAME INFERENCE · DIFFERENT CONSEQUENCE</div>
    <h2 style={{fontSize:'clamp(34px,5vw,64px)',lineHeight:1,letterSpacing:'-.05em',margin:'12px 0 22px'}}>The model does not decide the evidence threshold.</h2>
    <p style={{fontSize:18,lineHeight:1.7,color:'#b9ccd5'}}>Assume an ML model predicts that an AHU is likely to exceed an operating limit. The inference may be identical. The proposed consequence is not.</p>
    <div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(220px,1fr))',gap:10,marginTop:18}}>
     {[
      ['01','DISPLAY ADVISORY','Informational consequence. Preserve the prediction, provenance, and uncertainty.'],
      ['02','CREATE WORK ORDER','Operational consequence. Establish routing, scope, and accountable recipient.'],
      ['03','CHANGE SETPOINT','Control consequence. Establish current evidence, applicable authority, standing, bounds, and rollback.'],
      ['04','SHUT DOWN EQUIPMENT','Higher-consequence action. Require the evidence and authority appropriate to that exact shutdown now.']
     ].map(([n,t,d])=><article key={n} style={{padding:22,borderRadius:17,border:'1px solid rgba(112,220,255,.14)',background:'rgba(2,10,17,.55)'}}><div style={{fontSize:10,color:C.cyan,fontWeight:950}}>{n}</div><div style={{marginTop:7,fontSize:17,fontWeight:1000}}>{t}</div><p style={{fontSize:13,lineHeight:1.6,color:C.muted}}>{d}</p></article>)}
    </div>
    <div style={{marginTop:20,padding:22,borderRadius:17,border:'1px solid rgba(255,211,111,.28)',background:'rgba(255,211,111,.05)',fontWeight:1000,fontSize:'clamp(20px,2.7vw,32px)',lineHeight:1.3}}>Same prediction. Different consequence. <span style={{color:C.gold}}>Different proof burden.</span></div>
    <div style={{marginTop:22,marginBottom:10,fontSize:10,fontWeight:950,letterSpacing:".18em",color:C.cyan}}>TEACHING VISUAL 02 / 04</div><Image src="/TA14_Aaron_Hastings_Building_ML_02_Same_Inference_Four_Consequences.png" alt="Same ML inference four different consequences teaching visual" width={1536} height={1024} style={{display:"block",width:"100%",height:"auto",marginTop:22,borderRadius:20}}/><Samantha text="Hold the machine-learning inference constant. Assume the model predicts that an air-handling unit is likely to exceed an operating limit. Nothing about the prediction changes as we move across this visual. What changes is what somebody proposes to do because of it. First, DISPLAY ADVISORY. The system may simply show the prediction, its provenance, confidence, and uncertainty to a human. The consequence is informational. Second, CREATE WORK ORDER. Now the prediction enters an operational workflow. We need to know what asset the work order applies to, what condition is alleged, who receives it, and whether the evidence is sufficient to justify dispatch or investigation. Third, CHANGE SETPOINT. Now information is crossing into physical control. A three-degree setpoint change can affect comfort, energy, humidity, equipment loading, interacting sequences, and downstream control loops. The evidence and authority appropriate for displaying an advisory do not automatically establish permission for that write. Fourth, SHUT DOWN EQUIPMENT. The underlying prediction can still be identical, but the consequence is materially different. Shutdown may affect occupants, process loads, pressure relationships, freeze protection, smoke control interfaces, or other systems. The key lesson is not that every higher consequence must always require more paperwork. The lesson is that the proof burden must fit the exact consequence. A model does not determine that burden merely by becoming more confident. Ninety-nine percent confidence does not transform a recommendation into execution authority. Same inference. Different consequence. Different proof burden."/>
   </section>

   <section style={{marginTop:24,padding:'clamp(28px,5vw,52px)',...card}}>
    <div style={{fontSize:11,fontWeight:950,letterSpacing:'.18em',color:C.green}}>03 · BUILDING ML PROOF PATH</div>
    <h2 style={{fontSize:'clamp(34px,5vw,64px)',lineHeight:1,letterSpacing:'-.05em',margin:'12px 0 22px'}}>OBSERVATION → ML INFERENCE → PROPOSITION → AUTHORITY → EXECUTION → OUTCOME</h2>
    <div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(180px,1fr))',gap:9}}>
     {['OBSERVATION','ML INFERENCE','PROPOSITION','AUTHORITY','EXECUTION','OUTCOME'].map((x,i)=><div key={x} style={{padding:20,borderRadius:15,border:'1px solid rgba(112,220,255,.14)',background:i===3?'rgba(113,242,182,.07)':'rgba(2,10,17,.55)',textAlign:'center'}}><div style={{fontSize:10,color:C.cyan,fontWeight:950}}>0{i+1}</div><div style={{marginTop:7,fontSize:14,fontWeight:1000}}>{x}</div></div>)}
    </div>
    <div style={{marginTop:22,padding:'clamp(24px,4vw,38px)',borderRadius:20,border:'1px solid rgba(113,242,182,.28)',background:'rgba(113,242,182,.04)'}}>
     <div style={{fontSize:11,fontWeight:950,letterSpacing:'.16em',color:C.green}}>COMMIT BOUNDARY</div>
     <div style={{fontSize:'clamp(27px,4vw,48px)',fontWeight:1000,marginTop:10}}>KNOW / INFER / RECOMMEND <span style={{color:C.green}}>│</span> ACT</div>
     <p style={{color:'#b9ccd5',lineHeight:1.65}}>The boundary is not where intelligence ends. It is where a proposition is about to become consequence. At that point, TA-14 resolves the route as ALLOW, HOLD, DENY, or ESCALATE.</p>
    </div>
    <div style={{marginTop:22,marginBottom:10,fontSize:10,fontWeight:950,letterSpacing:".18em",color:C.cyan}}>TEACHING VISUAL 03 / 04</div><Image src="/TA14_Aaron_Hastings_Building_ML_03_Commit_Boundary.png" alt="Building ML commit boundary teaching visual" width={1536} height={1024} style={{display:"block",width:"100%",height:"auto",marginTop:22,borderRadius:20}}/><Samantha text="Follow the route from left to right. OBSERVATION is what the building and its instrumentation tell us about reality. ML INFERENCE is what computation derives, reconstructs, predicts, classifies, or estimates from that evidence. PROPOSITION is where intelligence becomes action-shaped: change this setpoint, dispatch this technician, disable this mode, start this sequence. That proposition approaches the COMMIT BOUNDARY. This is the critical seam. Before commit, the system can know, infer, simulate, rank, recommend, and explain without necessarily causing the proposed physical consequence. At commit, the question changes from what do we know to may this become real now? TA14 resolves that route as ALLOW, HOLD, DENY, or ESCALATE. ALLOW means the required conditions for this bounded consequence are presently established; it permits execution but does not compel it. HOLD means something potentially curable is missing, stale, contradictory, or materially changed, so the state should be preserved and re-examined. DENY means the required authority is absent or prohibitory; technical capability cannot manufacture permission. ESCALATE means the route requires an appropriate human, owner, engineer, authority, or other governed review path. After an allowed action executes, governance does not stop. We verify what command actually crossed the boundary, what the building actually did, and whether the outcome matched the proposition. The outcome returns to reality and becomes part of the next evidentiary record. That is why the commit boundary is not an anti-automation boundary. It is what allows automation to become more consequential without pretending that intelligence and permission are the same thing."/>
   </section>

   <section style={{marginTop:24,padding:'clamp(28px,5vw,52px)',border:'1px solid rgba(255,211,111,.28)',borderRadius:24,background:'linear-gradient(145deg,rgba(56,43,10,.24),rgba(2,10,17,.97))'}}>
    <div style={{fontSize:11,fontWeight:950,letterSpacing:'.18em',color:C.gold}}>04 · THREE NON-EQUIVALENCES</div>
    <h2 style={{fontSize:'clamp(38px,6vw,74px)',lineHeight:.98,letterSpacing:'-.055em',margin:'12px 0 22px'}}>MODEL CONFIDENCE ≠ EVIDENTIARY SUFFICIENCY<br/>DETERMINISM ≠ AUTHORITY<br/>PREDICTION ≠ PERMISSION</h2>
    <p style={{fontSize:18,lineHeight:1.7,color:'#d7d0bd'}}>Deterministic ML can be highly valuable because its results can be repeatable, testable, and verifiable. That strengthens computation. It does not answer the separate execution question: who or what may cause the proposed consequence under the conditions that apply now?</p>
   </section>

   <section style={{marginTop:24,padding:'clamp(28px,5vw,52px)',...card}}>
    <div style={{fontSize:11,fontWeight:950,letterSpacing:'.18em',color:C.cyan}}>05 · AHU WORKED EXAMPLE</div>
    <h2 style={{fontSize:'clamp(34px,5vw,64px)',lineHeight:1,letterSpacing:'-.05em',margin:'12px 0 22px'}}>A correct prediction is still a new proposition.</h2>
    <div style={{display:'grid',gap:10}}>
     {[
      ['REALITY','AHU operating data, sensor observations, occupancy, outdoor conditions, current control state.'],
      ['COMPUTATION','ML reconstructs missing data or predicts future performance from governed inputs.'],
      ['PROPOSITION','Model recommends changing a setpoint to avoid the predicted condition.'],
      ['BOUNDARY','Do current evidence, applicable authority, established standing, scope, timing, and execution constraints support that exact setpoint change NOW?'],
      ['EXECUTION','Only after the route is ALLOW may the bounded action cross commit. ALLOW permits; it does not compel.'],
      ['OUTCOME','Return to reality. Capture what actually happened, whether the action matched the proposition, and whether the expected result occurred.']
     ].map(([t,d],i)=><div key={t} style={{display:'grid',gridTemplateColumns:'minmax(115px,180px) 1fr',gap:14,padding:18,borderRadius:15,border:'1px solid rgba(112,220,255,.12)',background:'rgba(2,10,17,.52)'}}><div style={{fontWeight:1000,color:i===3?C.green:C.cyan}}>{t}</div><div style={{color:'#b9ccd5',lineHeight:1.6}}>{d}</div></div>)}
    </div>
    <Samantha text="Walk through one ordinary air-handler example. REALITY gives us supply-air temperature, return conditions, valve or damper positions, fan status, occupancy, outdoor conditions, schedules, overrides, and the current control state. Those observations become evidence. COMPUTATION may reconstruct a missing point, detect a fault, forecast load, or predict that the current sequence will exceed an operating target. Assume the model is technically sound and recommends changing a setpoint. That recommendation is a new PROPOSITION. The model's correctness does not erase the need to examine the proposed action. At the BOUNDARY we ask: are the observations current? Is there contradictory evidence? Has the equipment state changed since inference? Is the proposed setpoint within the permitted optimization envelope? Does the actor have standing for this asset and this mode? Is there applicable owner, engineering, sequence, safety, contractual, or other authority governing the change? Are rollback and verification conditions established? If those conditions support the exact consequence now, the route may resolve ALLOW. If evidence is stale or a material condition changed, HOLD and re-examine. If authority is absent or prohibits the action, DENY. If standing or required judgment is unresolved, ESCALATE. Then, if execution occurs, record what actually happened. Did fifty-eight degrees get written? At what priority? For how long? Did another sequence overwrite it? Did discharge temperature, humidity, energy, or comfort respond as expected? Outcome is evidence too. A correct prediction was never the end of the route. It was the beginning of a new proposition: new proposition, new consequence, new now."/>
   </section>

   <section style={{marginTop:24,padding:'clamp(28px,5vw,52px)',...card}}>
    <div style={{fontSize:11,fontWeight:950,letterSpacing:'.18em',color:C.green}}>06 · LIVE CONSEQUENCE LAB</div>
    <h2 style={{fontSize:'clamp(34px,5vw,64px)',lineHeight:1,letterSpacing:'-.05em',margin:'12px 0 22px'}}>Change the conditions. Watch the disposition move.</h2>
    <div style={{display:'flex',gap:10,flexWrap:'wrap'}}>{toggle('TECHNICALLY VALID',valid,setValid)}{toggle('ADMISSIBLE EVIDENCE',admissible,setAdmissible)}{toggle('APPLICABLE AUTHORITY',authority,setAuthority)}{toggle('ESTABLISHED STANDING',standing,setStanding)}<button onClick={()=>setChanged(!changed)} style={{...btn,border:changed?'1px solid rgba(255,120,133,.5)':'1px solid rgba(113,242,182,.5)',color:changed?C.red:C.green}}>MATERIAL CHANGE: {changed?'YES':'NO'}</button></div>
    <div style={{marginTop:22,padding:'clamp(30px,5vw,52px)',borderRadius:24,border:`1px solid ${color}66`,background:`linear-gradient(135deg,${color}10,rgba(2,10,17,.96))`,textAlign:'center'}}><div style={{fontSize:10,fontWeight:950,letterSpacing:'.2em',color:'#8099a5'}}>CURRENT GOVERNED DISPOSITION</div><div style={{fontSize:'clamp(66px,11vw,132px)',fontWeight:1000,lineHeight:.9,letterSpacing:'-.07em',margin:'17px 0',color}}>{result}</div><p style={{maxWidth:850,margin:'0 auto',fontSize:18,lineHeight:1.6,color:'#b9ccd5'}}>{result==='ALLOW'?'Required conditions for this bounded consequence are presently established.':result==='HOLD'?'A curable evidence, validity, or changed-condition deficiency blocks action now. Preserve state and re-examine.':result==='DENY'?'Applicable Authority is absent or prohibitory. Capability cannot manufacture permission.':'Standing is unresolved. Route to the appropriate governed authority or review path.'}</p></div>
   </section>

   <section style={{marginTop:24,padding:'clamp(28px,5vw,52px)',...card}}>
    <div style={{fontSize:11,fontWeight:950,letterSpacing:'.18em',color:C.cyan}}>07 · AIR × ACA × AEA</div>
    <h2 style={{fontSize:'clamp(34px,5vw,64px)',lineHeight:1,letterSpacing:'-.05em',margin:'12px 0 22px'}}>Govern both sides of intelligence.</h2>
    <div style={{padding:22,borderRadius:17,border:'1px solid rgba(112,220,255,.14)',background:'rgba(2,10,17,.55)',fontSize:'clamp(18px,2.5vw,30px)',fontWeight:1000,lineHeight:1.6}}>REALITY → <span style={{color:C.cyan}}>AIR</span> → <span style={{color:C.green}}>ACA</span> → INTELLIGENCE → PROPOSED CONSEQUENCE → <span style={{color:C.purple}}>AEA</span> → EXECUTION → OUTCOME → NEW REALITY</div>
    <div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(250px,1fr))',gap:10,marginTop:16}}>
     {[
      ['AIR','Protects the atmospheric integrity record: what was observed, when, where, by what source, with continuity and provenance.'],
      ['ACA','Governs what intelligence may rely upon before computation. Governed input does not guarantee governed output.'],
      ['AEA','Governs what intelligence may cause before execution. The proposed consequence must establish its own route to reality.']
     ].map(([t,d])=><div key={t} style={{padding:22,borderRadius:16,border:'1px solid rgba(112,220,255,.13)',background:'rgba(2,10,17,.52)'}}><div style={{fontSize:22,fontWeight:1000,color:C.green}}>{t}</div><p style={{color:C.muted,lineHeight:1.6}}>{d}</p></div>)}
    </div>
   </section>

   <div style={{marginTop:22}}><div style={{marginTop:22,marginBottom:10,fontSize:10,fontWeight:950,letterSpacing:".18em",color:C.cyan}}>TEACHING VISUAL 04 / 04</div><Image src="/TA14_Aaron_Hastings_Building_ML_04_Governed_Building_ML_Loop.png" alt="Governed Building ML Loop teaching visual" width={1536} height={1024} style={{display:"block",width:"100%",height:"auto",borderRadius:20}}/><Samantha text="This final visual puts the entire building-machine-learning loop together. Begin with REALITY: the building is doing something whether our software understands it or not. AIR protects the record of what was actually observed, including source, time, location, continuity, provenance, and the conditions needed to interpret that observation. ACA governs the computation side: what evidence intelligence may rely upon, what transformations occurred, what model or deterministic process produced the result, and what limitations travel with that result. Then intelligence produces an inference, recommendation, or other PROPOSED CONSEQUENCE. This is where an important reset occurs. Governed input does not automatically create governed output. An admissible observation does not automatically make every downstream action admissible. AEA examines the execution side before the proposition crosses into consequence. Ask the governing question: Does this proposed consequence have sufficient Admissible Evidence, Applicable Authority, and Established Standing to become reality NOW? If the answer is not established, the route does not quietly borrow authority from model confidence, software access, or earlier commissioning. If the route is allowed, only the bounded consequence crosses into execution. Then measure the OUTCOME. Did the physical world change as intended? Were limits respected? Did an unexpected interaction occur? Preserve that result and return it to reality's record. The loop begins again because buildings change, evidence ages, occupants move, weather changes, operators intervene, sequences are revised, and yesterday's permission is not automatically today's permission. Commissioned once does not mean authorized forever. The purpose is not to make machine learning timid. It is to make increasingly capable building intelligence able to show why a consequence was allowed to become real."/></div>
   <section style={{marginTop:24,padding:'clamp(34px,6vw,68px)',border:'1px solid rgba(113,242,182,.3)',borderRadius:28,background:'radial-gradient(circle at 76% 0%,rgba(113,242,182,.11),transparent 28%),linear-gradient(145deg,rgba(8,36,48,.96),rgba(3,11,19,.98))'}}>
    <div style={{fontSize:11,fontWeight:950,letterSpacing:'.18em',color:C.green}}>PRESENTATION-READY DISTINCTION</div>
    <h2 style={{fontSize:'clamp(38px,6vw,76px)',lineHeight:.95,letterSpacing:'-.058em',margin:'14px 0 22px'}}>AN ADMISSIBLE INPUT DOES NOT CREATE AN ADMISSIBLE OUTPUT.</h2>
    <p style={{fontSize:'clamp(19px,2.6vw,30px)',lineHeight:1.55,color:'#c5d8df'}}>A machine-learning model may receive valid, governed evidence and produce a deterministic, repeatable prediction. If that prediction proposes a real-world action, the proposal is a new object of governance. Its evidence, authority, standing, scope, timing, and execution conditions must be established before it becomes consequence.</p>
    <div style={{marginTop:26,padding:24,borderRadius:18,border:'1px solid rgba(113,242,182,.28)',background:'rgba(113,242,182,.05)',fontSize:'clamp(21px,3vw,36px)',fontWeight:1000,lineHeight:1.25}}>Does this proposed consequence have sufficient <span style={{color:C.green}}>Admissible Evidence</span>, <span style={{color:C.cyan}}>Applicable Authority</span>, and <span style={{color:C.purple}}>Established Standing</span> to become reality NOW?</div>
    <div style={{display:'flex',gap:10,flexWrap:'wrap',marginTop:24}}><a href="/TA14_Admissibility_Authority_Building_ML_Technical_Reference_v2.pdf" download style={{...btn,textDecoration:'none'}}>DOWNLOAD TECHNICAL REFERENCE PDF ↓</a><Link href="/admissible-computation-architecture" style={{...btn,textDecoration:'none'}}>ACA →</Link><Link href="/admissible-execution-architecture" style={{...btn,textDecoration:'none'}}>AEA →</Link></div>
   </section>

   <section style={{marginTop:24,padding:24,borderRadius:18,border:'1px solid rgba(112,220,255,.12)',background:'rgba(2,10,17,.55)',fontSize:12,lineHeight:1.7,color:'#78909b'}}><b style={{color:'#a8bdc7'}}>BOUNDARY / NON-CLAIM.</b> This is an explanatory practitioner surface for examining building ML at the consequence boundary. It does not establish legal, regulatory, professional, contractual, or institutional authority; certify a model, sensor, control sequence, building, or practitioner; or claim adoption by Aaron Hastings, SkySpark, SkyPosium, NexusCon, or any other organization. Applicable domain authority remains controlling.</section>
   <footer style={{marginTop:28,paddingTop:20,borderTop:'1px solid rgba(112,220,255,.1)',display:'flex',justifyContent:'space-between',gap:14,flexWrap:'wrap',color:'#66818e',fontSize:11}}><div>TA-14 AUTHORITY · BUILDING ML CONSEQUENCE BOUNDARY</div><div>Capability ≠ Authority · Prediction ≠ Permission</div></footer>
  </div>
 </main>
}