'use client';

import Link from 'next/link';
import {useEffect,useMemo,useState} from 'react';
import {listSystemPassports,type SystemPassport} from '@/lib/eu-ai-act/system-passports';
import {ARTICLE50_SESSION_EVENT,readArticle50Assessment,type Article50AssessmentSession} from '@/lib/eu-ai-act/article-50-session';

type GovernanceState='UNRESOLVED'|'CONDITIONAL'|'EVIDENCE GAP'|'SUPPORTED'|'REVIEW REQUIRED'|'REVALIDATION REQUIRED';

function derive(passport:SystemPassport|undefined,session:Article50AssessmentSession|null):GovernanceState{
 if(!passport||!session||!session.obligationIds.length)return'UNRESOLVED';
 if(passport.article50==='REVALIDATION REQUIRED')return'REVALIDATION REQUIRED';
 if(session.assessmentState==='REVIEW REQUIRED')return'REVIEW REQUIRED';
 if(!session.evidenceRequired.length||session.evidencePercent<100)return'EVIDENCE GAP';
 if(passport.evidenceState!=='ADMISSIBLE')return'CONDITIONAL';
 return'SUPPORTED';
}

export default function Article50GovernanceLayer(){
 const[passports,setPassports]=useState<SystemPassport[]>([]),[selected,setSelected]=useState(''),[status,setStatus]=useState('Loading governed System Passports…'),[basis,setBasis]=useState(''),[session,setSession]=useState<Article50AssessmentSession|null>(null);
 useEffect(()=>{listSystemPassports().then(rows=>{setPassports(rows);setStatus(rows.length?'Select the governed system this Article 50 assessment belongs to.':'No System Passport exists yet. Create one before relying on this assessment.')}).catch(()=>setStatus('System Passport registry unavailable. Assessment may continue as a demonstration, but no governed system is bound.'))},[]);
 useEffect(()=>{setSession(readArticle50Assessment());const handler=(e:Event)=>setSession((e as CustomEvent<Article50AssessmentSession>).detail);window.addEventListener(ARTICLE50_SESSION_EVENT,handler);return()=>window.removeEventListener(ARTICLE50_SESSION_EVENT,handler)},[]);
 const passport=useMemo(()=>passports.find(p=>p.id===selected),[passports,selected]);const determination=useMemo(()=>derive(passport,session),[passport,session]);
 return <section className="govLayer" aria-label="Article 50 governed system and legal source state"><div className="govHead"><div><span>PRODUCTION GOVERNANCE LAYER</span><h2>Bind this assessment to the system, evidence state, source state, and current reliance.</h2><p>The detailed workspace remains intact below. This layer prevents questionnaire completion or declared evidence from becoming an unsupported compliance conclusion.</p></div><Link href="/academy/eu-ai-act/article-50">HOW TO USE ARTICLE 50 →</Link></div>
 <div className="live"><b>LIVE WORKSPACE BINDING</b><span>{session?`${session.actorRole} · ${session.obligationIds.length} pathway(s) · ${session.evidenceDeclared.length}/${session.evidenceRequired.length} evidence declared · ${session.evidencePercent}%`:'Waiting for the Article 50 workspace below…'}</span><strong>{session?.assessmentState??'NOT ASSESSED'}</strong></div>
 <div className="govGrid"><section><span>01 · SYSTEM PASSPORT</span><label><b>Governed system</b><select value={selected} onChange={e=>setSelected(e.target.value)}><option value="">— Select System Passport —</option>{passports.map(p=><option key={p.id} value={p.id}>{p.systemKey} · {p.name} · v{p.version}</option>)}</select></label><p>{status}</p>{passport&&<div className="passport"><b>{passport.systemKey} · {passport.name}</b><small>ROLE · {passport.role}</small><small>VERSION · {passport.version}</small><small>JURISDICTION · {passport.jurisdiction}</small><small>ARTICLE 50 STATE · {passport.article50}</small><small>ADMITTED EVIDENCE STATE · {passport.evidenceState}</small></div>}<Link href="/eu-ai-act/system-passport">OPEN SYSTEM PASSPORT →</Link></section>
 <section><span>02 · LEGAL SOURCE STATE</span><div className="source"><b>Regulation (EU) 2024/1689 · Article 50</b><strong>APPLICABLE · 2 AUGUST 2026</strong><p>Transparency obligations are governed against the current Article 50 source set. Law or guidance changes pressure continuing reliance; they do not rewrite the historical assessment.</p></div><div className="source"><b>Commission Article 50 transparency guidance</b><strong>GUIDANCE CURRENT · 20 JULY 2026</strong></div><Link href="/eu-ai-act/legal-sources">OPEN LEGAL SOURCE STATE →</Link></section>
 <section><span>03 · DERIVED RELIANCE</span><div className={`decision ${determination.toLowerCase().replaceAll(' ','-')}`}><small>GOVERNED DETERMINATION</small><b>{determination}</b></div><p>{determination==='UNRESOLVED'?'Bind a System Passport and select at least one Article 50 pathway.':determination==='EVIDENCE GAP'?'The workspace still has required evidence that has not even been declared available.':determination==='CONDITIONAL'?'Required evidence is declared, but the System Passport does not yet show an ADMISSIBLE evidence state. Declaration is not admission.':determination==='SUPPORTED'?'The current assessment is fully declared and the bound System Passport reports ADMISSIBLE evidence. This is a bounded governance state, not a legal certification.':determination==='REVALIDATION REQUIRED'?'The bound System Passport already carries a revalidation requirement. Prior reliance must not silently continue.':'Independent review or unresolved applicability conditions prevent supported reliance.'}</p><label><b>Reviewer basis / limitations</b><textarea value={basis} onChange={e=>setBasis(e.target.value)} placeholder="Record the bounded reasoning, unresolved exceptions, evidence limitations, and conditions that would invalidate reliance."/></label><div className="receipt"><small>CURRENT GOVERNANCE RECEIPT</small><b>{passport?passport.systemKey:'NO SYSTEM BOUND'} · ARTICLE 50 · {determination}</b><p>{session?`${session.obligationIds.join(', ')} · declared ${session.evidenceDeclared.length}/${session.evidenceRequired.length}`:'No live assessment bound.'}</p><p>{basis||'No reviewer basis has been recorded in this session.'}</p></div><Link href="/eu-ai-act/revalidation-engine">OPEN REVALIDATION →</Link></section></div>
 <div className="rule"><b>TA-14 BOUNDARY</b><span>Questionnaire completion ≠ evidence declaration ≠ evidence admission ≠ governed determination ≠ legal compliance.</span><span>Material system, role, deployment, evidence, law, or guidance change can require revalidation.</span></div>
 <style jsx>{`.govLayer{margin:34px 0 44px;padding:24px;border:1px solid rgba(96,220,245,.26);border-radius:22px;background:linear-gradient(145deg,rgba(7,30,43,.92),rgba(3,11,18,.96));box-shadow:0 25px 80px rgba(0,0,0,.22)}.govHead{display:flex;justify-content:space-between;gap:25px;align-items:end;padding-bottom:18px;border-bottom:1px solid rgba(96,220,245,.14)}.govHead span,.govGrid>section>span,.receipt small,.decision small{font-size:8px;letter-spacing:.17em;color:#70e2f8;font-weight:900}.govHead h2{font:32px Georgia,serif;margin:7px 0}.govHead p{max-width:780px;color:#86a2b1;font-size:11px;line-height:1.65}.govHead :global(a),.govGrid :global(a){display:inline-flex;padding:9px 11px;border:1px solid rgba(112,226,248,.38);color:#9cefff;text-decoration:none;font-size:8px;font-weight:900}.live{display:flex;gap:12px;align-items:center;flex-wrap:wrap;margin:14px 0 0;padding:11px 13px;border:1px solid rgba(112,226,248,.17);background:rgba(112,226,248,.04);font-size:8px}.live b{color:#70e2f8}.live span{color:#a5bac5;flex:1}.live strong{color:#f0d27a}.govGrid{display:grid;grid-template-columns:1fr 1fr 1fr;gap:8px;margin-top:8px}.govGrid>section{padding:17px;border:1px solid rgba(111,194,220,.15);background:rgba(1,8,13,.55)}.govGrid label{display:block;margin:12px 0}.govGrid label>b{display:block;color:#d8edf4;font-size:9px;margin-bottom:6px}.govGrid select,.govGrid textarea{width:100%;border:1px solid #27546a;background:#02080d;color:#eefaff;padding:10px}.govGrid textarea{min-height:95px;resize:vertical}.govGrid p{color:#7896a6;font-size:9px;line-height:1.55}.passport,.source,.receipt,.decision{display:grid;gap:5px;margin:10px 0 13px;padding:12px;border:1px solid rgba(103,224,244,.16);background:rgba(7,26,36,.55)}.passport b,.source b,.receipt b{font-size:10px}.passport small{font-size:7px;color:#7796a6}.source strong{color:#8ee6b8;font-size:8px}.decision b{font:21px Georgia,serif}.decision.supported{border-color:rgba(112,232,172,.35)}.decision.evidence-gap,.decision.review-required,.decision.revalidation-required{border-color:rgba(242,196,86,.38)}.rule{display:flex;gap:12px;flex-wrap:wrap;margin-top:12px;padding:12px;border:1px solid rgba(242,196,86,.22);background:rgba(242,196,86,.05);font-size:8px}.rule b{color:#f2cf72}.rule span{color:#b5a77d}@media(max-width:1000px){.govGrid{grid-template-columns:1fr}.govHead{align-items:flex-start;flex-direction:column}}`}</style></section>
}
