import { NextResponse } from 'next/server';
export const dynamic='force-dynamic'; export const revalidate=0;
type Row={id:string;registry_identifier:string;governance_name:string;short_name?:string|null;version?:string|null;category?:string|null;steward?:string|null;claimed_establishment_date?:string|null;registered_at?:string|null;status:string;summary?:string|null;domains?:string[]|null;evidence_count?:number|string|null;dispute_count?:number|string|null};
type Counts={total_registry_records?:number|string;registered_governance_count?:number|string;public_registered_count?:number|string;non_public_registered_count?:number|string;archived_record_count?:number|string};
const env=()=>{const supabaseUrl=process.env.NEXT_PUBLIC_SUPABASE_URL?.replace(/\/+$/,'');const key=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY??process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY??process.env.SUPABASE_PUBLISHABLE_KEY;return supabaseUrl&&key?{supabaseUrl,key}:null};
const n=(v:number|string|null|undefined)=>typeof v==='number'&&Number.isFinite(v)?v:typeof v==='string'&&Number.isFinite(Number.parseInt(v,10))?Number.parseInt(v,10):0;
const rpc=async(e:{supabaseUrl:string;key:string},name:string)=>{const r=await fetch(`${e.supabaseUrl}/rest/v1/rpc/${name}`,{method:'POST',cache:'no-store',headers:{apikey:e.key,Authorization:`Bearer ${e.key}`,Accept:'application/json','Content-Type':'application/json'},body:'{}'});const text=await r.text();let body:unknown=null;try{body=text?JSON.parse(text):null}catch{body=text}return{r,body}};
const unavailable=(message:string,error:string,status=503)=>NextResponse.json({available:false,error,message,records:null,count:null,registryCounts:null,generatedAt:new Date().toISOString()},{status,headers:{'Cache-Control':'no-store, max-age=0'}});
export async function GET(){const e=env();if(!e)return unavailable('The public Registry is temporarily unavailable because its publication service is not configured.','REGISTRY_CONFIGURATION_MISSING');try{const[directory,counts]=await Promise.all([rpc(e,'ta14_registry_public_directory_v1'),rpc(e,'ta14_registry_public_counts_v1')]);if(!directory.r.ok)return unavailable('The public Registry directory could not be queried.','PUBLIC_REGISTRY_QUERY_FAILED',502);if(!Array.isArray(directory.body))return unavailable('The public Registry returned an invalid response. No zero-value metrics have been inferred.','PUBLIC_REGISTRY_RESPONSE_INVALID',502);const records=(directory.body as Row[]).filter(x=>x&&typeof x.id==='string'&&typeof x.registry_identifier==='string'&&typeof x.governance_name==='string'&&typeof x.status==='string').map(x=>({id:x.id,registryIdentifier:x.registry_identifier,governanceName:x.governance_name,shortName:x.short_name??null,version:x.version??null,category:x.category??null,steward:x.steward??null,claimedEstablishmentDate:x.claimed_establishment_date??null,registeredAt:x.registered_at??null,status:x.status,summary:x.summary??null,domains:Array.isArray(x.domains)?x.domains:[],evidenceCount:n(x.evidence_count),disputeCount:n(x.dispute_count)}));let registryCounts=null;if(counts.r.ok&&Array.isArray(counts.body)&&counts.body[0]){const c=counts.body[0] as Counts;registryCounts={totalRecords:n(c.total_registry_records),registeredGovernances:n(c.registered_governance_count),publicRegistered:n(c.public_registered_count),nonPublicRegistered:n(c.non_public_registered_count),archivedRecords:n(c.archived_record_count)}}return NextResponse.json({available:true,records,count:records.length,registryCounts,generatedAt:new Date().toISOString()},{status:200,headers:{'Cache-Control':'no-store, max-age=0','X-Content-Type-Options':'nosniff'}})}catch{return unavailable('The public Registry service is temporarily unavailable. No zero-value metrics have been inferred.','PUBLIC_REGISTRY_UNAVAILABLE')}}
