'use client';
import Link from 'next/link';
import {useMemo,useState} from 'react';
type Result='ACCEPT_NARROWED'|'HOLD'|'REJECT'|'SUSPEND'|'ESCALATE'|'ALLOW'|'DENY';
const worlds=[
{name:'BUILDING',origin:'Remote optimization domain',target:'AHU-04 / occupied Zone 3',action:'Change live supply-air setpoint'},
{name:'AI AGENT',origin:'Federated agent domain',target:'Protected account / exact request',action:'Release consequential external transaction'},
{name:'INFRASTRUCTURE',origin:'Independent control domain',target:'Bound field endpoint / current version',action:'Issue protected control command'},
{name:'INSTITUTION',origin:'Partner institutional domain',target:'Named governed case',action:'Commit attributable institutional action'}];
const C={line:'#24464d',cyan:'#71e7df',gold:'#e7c76e',text:'#efffff',muted:'#9fb7be',green:'#8de6b0'};
export default function AuthorityJourney(){
 const [world,setWorld]=useState(0);
 const [p,setP]=useState({identity:true,integrity:true,freshness:true,federatedScope:true,revocation:true,localStanding:true,presentState:true,target:true,authority:true,localScope:true,binding:true,evidence:true});
 const [attempts,setAttempts]=useState<{id:number;afa:Result;eaba:Result;effect:string}[]>([]);
 const w=worlds[world];
 const afa=useMemo<Result>(()=>!p.identity||!p.integrity?'REJECT':!p.revocation?'SUSPEND':!p.localStanding?'ESCALATE':!p.freshness||!p.federatedScope?'HOLD':'ACCEPT_NARROWED',[p]);
 const eaba=useMemo<Result>(()=>afa!=='ACCEPT_NARROWED'?'HOLD':!p.authority?'DENY':!p.localStanding?'ESCALATE':!p.presentState||!p.target||!p.localScope||!p.binding||!p.evidence?'HOLD':'ALLOW',[afa,p]);
 const toggle=(k:keyof typeof p)=>setP(v=>({...v,[k]:!v[k]}));
 const run=()=>setAttempts(v=>[{id:v.length+1,afa,eaba,effect:eaba==='ALLOW'?'PROTECTED COMMIT ELIGIBLE':'NO PROTECTED CONSEQUENCE'},...v].slice(0,8));
 const reset=()=>setP({identity:true,integrity:true,freshness:true,federatedScope:true,revocation:true,localStanding:true,presentState:true,target:true,authority:true,localScope:true,binding:true,evidence:true});
 return <main style={{minHeight:'100vh',background:'radial-gradient(circle at 50% 0,#12333a,#031015 36%,#010609 80%)',color:C.text,fontFamily:'Inter,system-ui,sans-serif'}}><div style={{width:'min(1260px,calc(100% - 30px))',margin:'0 auto',padding:'24px 0 100px'}}>
 <nav style={{display:'flex',justifyContent:'space-between',gap:12,flexWrap:'wrap',paddingBottom:20,borderBottom:'1px solid '+C.line}}><Link href="/" style={{color:'#fff',textDecoration:'none',fontWeight:950}}>TA-14 EXCHANGE</Link><span style={{fontSize:10,color:C.cyan,fontWeight:950}}>AFA · TA-14-AIGR-000042 × EABA · TA-14-AIGR-000043</span></nav>
 <section style={{padding:'72px 0 42px',maxWidth:1080}}><small style={{color:C.cyan,fontWeight:950,letterSpacing:'.18em'}}>AUTHORITY JOURNEY · COMPOSITION LAB</small><h1 style={{fontSize:'clamp(48px,8vw,98px)',lineHeight:.91,letterSpacing:'-.055em',margin:'16px 0 24px'}}>CONTEXT MAY CROSS.<br/><span style={{color:C.gold}}>CONSEQUENCE STILL HAS TO EARN ITS WAY THROUGH.</span></h1><p style={{fontSize:19,lineHeight:1.7,color:C.muted,maxWidth:930}}>Operate the complete seam. AFA governs what authority context may cross between independent domains. EABA independently governs whether the exact consequence may proceed locally. A successful crossing is not an execution permit.</p></section>
 <section style={box}><b style={{color:C.gold}}>THE COMPLETE JOURNEY</b><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(125px,1fr))',gap:7,marginTop:16}}>{['ORIGIN','AFA CROSSING','RECEIVE','LOCAL STANDING','EABA','COMMIT','EFFECT','OUTCOME'].map((x,i)=><div key={x} style={{padding:'17px 10px',border:'1px solid '+(i===1?C.cyan:i===4?C.gold:C.line),borderRadius:9,textAlign:'center',fontSize:10,fontWeight:950}}>{x}{i<7?' →':''}</div>)}</div></section>
 <section style={{padding:'52px 0 18px'}}><small style={{color:C.cyan,fontWeight:950}}>CHOOSE A CONSEQUENCE WORLD</small><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(210px,1fr))',gap:8,marginTop:13}}>{worlds.map((x,i)=><button key={x.name} onClick={()=>setWorld(i)} style={worldButton(world===i)}><b>{x.name}</b><small style={{display:'block',marginTop:7,color:C.muted}}>{x.action}</small></button>)}</div><div style={{...box,marginTop:10,display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(220px,1fr))',gap:16}}><Datum k="ORIGIN DOMAIN" v={w.origin}/><Datum k="BOUND TARGET" v={w.target}/><Datum k="PROPOSED CONSEQUENCE" v={w.action}/></div></section>
 <section style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(330px,1fr))',gap:12,marginTop:24}}>
 <div style={{...box,borderColor:'#2b6d70'}}><small style={{color:C.cyan,fontWeight:950}}>STAGE 1 · AFA FEDERATION SEAM</small><h2 style={{fontSize:32}}>May this authority context cross?</h2>{([['identity','ISSUER IDENTITY'],['integrity','PASSPORT INTEGRITY'],['freshness','FRESHNESS'],['federatedScope','FEDERATED SCOPE'],['revocation','REVOCATION STATUS'],['localStanding','RECEIVING STANDING']] as const).map(([k,l])=><Toggle key={k} on={()=>toggle(k)} ok={p[k]} label={l}/>) }<ResultCard name="AFA DETERMINATION" result={afa}/><p style={note}>Even ACCEPT_NARROWED establishes no local commit or execution authority.</p></div>
 <div style={{...box,borderColor:'#6c5b31'}}><small style={{color:C.gold,fontWeight:950}}>STAGE 2 · EABA CONSEQUENCE SEAM</small><h2 style={{fontSize:32}}>May this exact consequence occur now?</h2>{([['presentState','PRESENT STATE'],['target','EXACT TARGET'],['authority','EXECUTION AUTHORITY'],['localScope','LOCAL SCOPE'],['binding','COMMIT BINDING'],['evidence','CURRENT EVIDENCE']] as const).map(([k,l])=><Toggle key={k} on={()=>toggle(k)} ok={p[k]} label={l}/>) }<ResultCard name="EABA DETERMINATION" result={eaba}/><p style={note}>EABA evaluates consequence independently. Federation success cannot manufacture permission.</p></div></section>
 <section style={{...box,marginTop:14}}><small style={{color:C.cyan,fontWeight:950}}>PROTECTED CROSSING</small><h2 style={{fontSize:36,margin:'8px 0'}}>Try to move from context to consequence.</h2><div style={{display:'flex',gap:9,flexWrap:'wrap'}}><button onClick={run} style={primary}>ATTEMPT COMPLETE JOURNEY</button><button onClick={reset} style={secondary}>RESTORE ALL CONDITIONS</button></div><div style={{marginTop:18,padding:18,border:'1px solid '+(eaba==='ALLOW'?C.green:C.gold),borderRadius:10}}><b style={{color:eaba==='ALLOW'?C.green:C.gold}}>CURRENT END STATE · {eaba==='ALLOW'?'COMMIT ELIGIBLE':'CONSEQUENCE BLOCKED'}</b><p style={{color:C.muted,marginBottom:0}}>AFA: {afa} → EABA: {eaba}. {eaba==='ALLOW'?'The route may proceed to protected commit; effect still requires evidence.':'No protected consequence is authorized by this route.'}</p></div></section>
 <section style={{padding:'48px 0 10px'}}><small style={{color:C.cyan,fontWeight:950}}>END-TO-END EVIDENCE LEDGER</small><h2 style={{fontSize:38}}>Changed reality creates a new examination.</h2>{attempts.length===0?<div style={box}>No journey attempted yet. Change any condition, attempt the journey, then change reality and run it again.</div>:<div style={{display:'grid',gap:8}}>{attempts.map(x=><div key={x.id} style={{...box,display:'grid',gridTemplateColumns:'70px 1fr 1fr 1.4fr',gap:12}}><b style={{color:C.cyan}}>#{String(x.id).padStart(2,'0')}</b><span>AFA · <b>{x.afa}</b></span><span>EABA · <b>{x.eaba}</b></span><b style={{color:x.eaba==='ALLOW'?C.green:C.gold}}>{x.effect}</b></div>)}</div>}</section>
 <section style={{...box,marginTop:34,borderStyle:'dashed'}}><b style={{color:C.gold}}>CLAIM BOUNDARY</b><p style={{color:C.muted,lineHeight:1.7}}>This composition lab demonstrates the relationship between registered AFA v1.0-RC1 and registered EABA v1.0-RC1. It does not convert either release candidate into Technical Freeze, certification, legal approval, production authorization, or universal implementation proof.</p><div style={{display:'flex',gap:8,flexWrap:'wrap'}}><Link href="/admissible-federation-architecture" style={secondary}>OPEN AFA →</Link><Link href="/execution-authority-boundary-architecture" style={secondary}>OPEN EABA →</Link><Link href="/afa-eaba-operational-challenge" style={secondary}>OPEN FROZEN CHALLENGE →</Link></div></section>
 </div></main>}
function Toggle({ok,label,on}:{ok:boolean;label:string;on:()=>void}){return <button onClick={on} style={{width:'100%',textAlign:'left',margin:'4px 0',padding:'13px',cursor:'pointer',borderRadius:9,border:'1px solid '+(ok?'#315e61':'#8b4937'),background:ok?'rgba(45,141,143,.10)':'rgba(86,25,13,.22)',color:ok?'#9be7e2':'#ffb29a',fontWeight:900}}>{ok?'●':'×'} {label}<small style={{float:'right',color:'#829da3'}}>{ok?'ESTABLISHED':'BROKEN'}</small></button>}
function ResultCard({name,result}:{name:string;result:Result}){return <div style={{marginTop:13,padding:17,border:'1px solid #3b5960',borderRadius:10,background:'#020b0f'}}><small style={{color:'#8ba5aa'}}>{name}</small><strong style={{display:'block',fontSize:27,marginTop:5,color:result==='ALLOW'||result==='ACCEPT_NARROWED'?'#8de6b0':'#e7c76e'}}>{result}</strong></div>}
function Datum({k,v}:{k:string;v:string}){return <div><small style={{color:'#78969c',fontWeight:900}}>{k}</small><b style={{display:'block',marginTop:6}}>{v}</b></div>}
const box:React.CSSProperties={padding:24,border:'1px solid #24464d',borderRadius:16,background:'rgba(4,21,28,.88)'};
const primary:React.CSSProperties={cursor:'pointer',padding:'13px 16px',border:0,borderRadius:9,background:'#71e7df',color:'#031216',fontWeight:950};
const secondary:React.CSSProperties={cursor:'pointer',padding:'12px 15px',border:'1px solid #31545b',borderRadius:9,background:'transparent',color:'#d7eeee',fontWeight:900,textDecoration:'none',fontSize:11};
const note:React.CSSProperties={fontSize:11,color:'#91aab0',lineHeight:1.6};
const worldButton=(active:boolean):React.CSSProperties=>({cursor:'pointer',padding:18,textAlign:'left',borderRadius:10,border:'1px solid '+(active?'#71e7df':'#24464d'),background:active?'rgba(45,141,143,.16)':'#041318',color:active?'#efffff':'#9fb7be'});
